### ISSUE TITLE
Obtain New Relic licenses

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1008]

**Comment by mogul** [comment]
We [got access to New Relic yesterday](https://gsa-tts.slack.com/archives/CNW3GL70S/p1683034210590769?thread_ts=1682969780.665369&cid=CNW3GL70S) and I've just [granted access to the dev team](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1683155357045669).
