### ISSUE TITLE
Update install methods

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#1011]
We have these errors blocking build and deploys.
```
DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

DEPRECATION: pyjwkest is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```
We do have a 'pyproject.toml' file but we are not using it to keep track of dependences.
Here are our docs on how we are managing dependencies: https://github.com/GSA-TTS/FAC/blob/main/docs/dependency-management.md

We have been getting a notice on this for a while and putting it off.

**Comment by asteel-gsa** [comment]
@LindsayYoung Speaking with @JeanMarie-TTS regarding this, we cannot find references of `setup.py install` 
![image](https://user-images.githubusercontent.com/130377221/232565501-58172076-3039-4636-a5ed-579e704f3038.png)

We do however have the references in `backend/requirements.txt` listed as:
[future](https://github.com/GSA-TTS/FAC/blob/257dd28294681311fa74a6e727f240564f951a68/backend/requirements.txt#L273) and [pyjwkest](https://github.com/GSA-TTS/FAC/blob/257dd28294681311fa74a6e727f240564f951a68/backend/requirements.txt#L591)

Is this recommended to add 
```
--hash=<> \
--use-pep517
```

To those listings in requirements.txt?

**Comment by JeanMarie-TTS** [comment]
@asteel-gsa , we do not edit requirements.txt directly. We update requirements.in and the build process (like `make compile`) update requirements.txt Check the developer docs on this.

**Comment by asteel-gsa** [comment]
> @asteel-gsa , we do not edit requirements.txt directly. We update requirements.in and the build process (like `make compile`) update requirements.txt Check the developer docs on this.

[requirements.in 404](https://github.com/GSA-TTS/FAC/blob/main/backend/requirements.in) if youre referring to `backend/requirements.in` I am unable to access in main branch

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/blob/main/backend/requirements/requirements.in

**Comment by danswick** [comment]
Thanks for the detailed notes, @asteel-gsa! 

> I believe the setup.py install call is happening behind the scenes in the python_buildpack when deploying, as we do not appear to be directly calling pip install -r requirements.txt as part of the workflow.

CF should automatically run `pip install` when it detects the `requirements.txt` file. Looking at the docs, I didn't see an obvious way to pass a pip install flag through to CF. 

Because `pip compile` just generates a dependency lockfile, I don't believe `pip compile --use-pep517` will have any effect on the error message in the OP. I believe the error happens later on, while the above referenced dependencies are being installed automatically as part of CF's whole buildpack workflow. 

Since it's looking tricky to pass the `--use-pip517` flag through, what if you tried adding `wheel` to the `requirements.in`?

**Comment by asteel-gsa** [comment]
> Since it's looking tricky to pass the `--use-pip517` flag through, what if you tried adding `wheel` to the `requirements.in`?

@danswick That is something that @jadudm and I spoke about briefly the other day. I just tested this [here](https://github.com/GSA-TTS/FAC/blob/cba5922cc11377f412495de02dce9737f9a6be3f/backend/requirements/requirements.in#L27) and even [without caching](https://github.com/GSA-TTS/FAC/blob/cba5922cc11377f412495de02dce9737f9a6be3f/.github/workflows/deploy-apps.yml#L33-L44)
```
   Downloading wheel-0.40.0-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.5/64.5 kB 3.7 MB/s eta 0:00:00
```

we are still seeing the warning with [wheel](https://github.com/GSA-TTS/FAC/blob/cba5922cc11377f412495de02dce9737f9a6be3f/backend/requirements.txt#L739-L742)
```
 Running setup.py install for future: started
   DEPRECATION: future is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
   Running setup.py install for future: finished with status 'done'
   Running setup.py install for pyjwkest: started
   DEPRECATION: pyjwkest is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
   Running setup.py install for pyjwkest: finished with status 'done'
```

**Comment by jadudm** [comment]
I think we need to pass this question to the cloud.gov team. At worst, they might say "nope, it's in your stack somewhere."

**Comment by asteel-gsa** [comment]
@jadudm Per CG support on this matter, they are claiming it is application specific.

[Based on this document](https://github.com/pypa/pip/issues/8559#issuecomment-1365250852) I have added wheel to the requirements.txt file per the guidance, re-enabled the caching, and ensuring that wheel is part of the deploy
```
   Collecting wheel==0.40.0
   Using cached wheel-0.40.0-py3-none-any.whl (64 kB)
```

The document does say to remove `setuptools` from the offending environment, and in our `requirements.txt`
# The following packages are considered to be unsafe in a requirements file:
```
setuptools==67.6.0 \
    --hash=sha256:2ee892cd5f29f3373097f5a814697e397cf3ce313616df0af11231e2ad118077 \
    --hash=sha256:b78aaa36f6b90a074c1fa651168723acbf45d14cb1196b6f02c0fd07f17623b2
    # via gunicorn
```

So its coming from [here](https://github.com/GSA-TTS/FAC/blob/364b63993696ad783bdc9e1b6343b85934390c43/backend/requirements/requirements.in#L12) I believe, yet adding wheel does not resolve. Any ideas on how to proceed? I do not see any way to directly pass `--use-pep517` into the deploy when it calls `setup.py install`

**Comment by JeanMarie-TTS** [comment]
We should be using the requirements.txt file in our deploy process. Generation of requirements.txt happens in our local development machibes using `make`. `requirements.txt` is in our GH repo and we need to make sure that we don't regenerate it when we deply on cloud.gov or even in our docker build.

**Comment by asteel-gsa** [comment]
> we need to make sure that we don't regenerate it when we deply on cloud.gov or even in our docker build.

We aren't currently regenerating it. I found that out when I was testing the new relic stuff. Calling `make compile` will remove the current `requirements.txt` file and force update the hashes and version.

Adding `wheel` to `requirements.in` and manually calling `pip-compile --generate-hashes ./requirements/requirements.in -o requirements.txt --allow-unsafe` will only do the diffs on `requirements.txt` and keep versions and hashes as is, only adding in what is needed from the new addition to `requirements.in`. 

As such, the proposed changes in the reference:
```
installing wheel in the environment where you run pip. This means that pip will be able to build wheels using setup.py bdist_wheel.
uninstalling setuptools in the environment where you run pip. This basically means that pip will use the newer build system by default.
pass --use-pep517 to pip, if you're using it as a part of in those environments will suppress the message for end users.
```

do not work. In my branch we have wheel in `requirements.in` and is hashed in `requirements.txt` correctly, with no further changes to version locks or hashes.
```
wheel==0.40.0 \
    --hash=sha256:cd1196f3faee2b31968d626e1731c94f99cbdb67cf5a46e4f5656cbee7738873 \
    --hash=sha256:d236b20e7cb522daf2390fa84c55eea81c5c30190f90f29ae2ca1ad8355bf247
    # via -r ./requirements/requirements.in
```

Because `gunicorn` requires `setuptools` we cannot remove `setuptools` directly, as it is a direct requirement, and because it is handled in the backend package installation of `gunicorn` and CF, I do not believe we can directly add `--use-pep517` in the `setup.py install` call when the package locks are loaded via caching for the app.

**Comment by jadudm** [comment]
We've... addressed these issues. We have semi-automated build/deploy that catches this at this point.
