### ISSUE TITLE
Review GSA IT Security Procedural Guides site for FAC-LATO effort

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#1022]
### Tasks

```[tasklist]
- [x] Review GSA IT Security Procedural Guides portal to gather expected workflow for ATO and post ATO requirements
- [x] Identify any additional IT security requirements needed to comply with ATO
```

**Comment by ChrisB-16** [comment]
GSA Security documentation/procedures under review..

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 , please imclude the SOPs in markdown docs and provide a link to the branch where you are maintaining them.

**Comment by mogul** [comment]
@ChrisB-16 what do we need to do to move this forward?

**Comment by ChrisB-16** [comment]
After passing initial review/LATO assessment phase for FAC LATO documentation there were additional IT security readiness meetings that occurred with GSA ISSO to track IT Security Procedural documents, identify artifacts/SOP documents needed for GSA A&A assessment efforts, and obtain access to necessary GSA SOP templates to help track implementation statements for the maintenance/risk management efforts for the FAC cloud system.
Ticket can be closed actions were completed.
