### ISSUE TITLE
Implement process to scan docker images

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1027]
We are planning to deploy docker images for the following:

1. PostgREST
2. Swagger
3. ClamAV

We need to ensure that these images are scanned for vulnerabilities before they are deployed. An alternative would be to use build packs instead of docker images.

**Comment by JeanMarie-TTS** [comment]
@mogul , can you add your thoughts on how to accomplish this? What tools to do the scan? Where do we store the images? etc.

**Comment by mogul** [comment]
Pulling in [from a Slack thread](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1682703065811389?thread_ts=1682702868.474639&cid=C03QCP4FSN8):
> [Person X] generally is telling people we shouldn't be pulling directly from Docker Hub, because it's not in any recognized boundary, and we therefore need to do our own scans before deploying stuff we pull from there.

> 
> **Note this is not a FAC-specific concern, but rather applies to all GSA systems!**
> 
> When he brought this up I suggested that we could create a GitHub repo solely consisting of a list of images we want scanned, with a GitHub Actions workflow that pulls those images, scans them, and upon "clean enough" scans, pushes them to the GitHub Container Registry ([ghcr.io](http://ghcr.io/)). Then we can set all our apps to pull the images we want from there, rather than Docker Hub. He seemed amenable to that!

As for the actual scanning tool: I think Trivy is a good tool for this, and they have [some pointers for GitHub Actions workflows and a blog post about using Trivy there](https://aquasecurity.github.io/trivy/v0.19.2/advanced/integrations/github-actions/).

As a further iteration once that is working, from a DM:
> Personally, I would have our process include generating security warning info into the GH reporting apparatus when images fail to come up clean, and that's where people would discuss the risk adjustment, based on how that image will be used. If everyone agrees it should be adjusted down, then we flag that somewhere in the repository config for that image, and the image is pushed to proceed to the "trusted" registry at the next scan.
> https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/about-repository-security-advisories

[The archived GitHub Action using Trivy by Microsoft Azure](https://github.com/Azure/container-scan) does some interesting things along those lines which I think are worth learning from.

Note there may be plenty of other GitHub Actions out there that are also options; this is just off the top of my head.

**Comment by mogul** [comment]
Oh wow, yeah, there are [lots of other options](https://github.com/marketplace?category=&query=image+scan+sort%3Apopularity-desc&type=actions&verification=).

**Comment by mogul** [comment]
Note it's already very easy to upload SARIF output from the official Trivy action to GitHub Code Scanning, [per this example](https://github.com/aquasecurity/trivy-action#using-trivy-with-github-code-scanning).

**Comment by JeanMarie-TTS** [comment]
@mogul , can't we just run trivy on our deployed docker images as part of our GH workflow. This would be similar to  what we do with  Zap scan.

**Comment by mogul** [comment]
Reopening as we are now scanning, but not doing anything with the scan results, and not yet having the apps use the scanned images.

**Comment by JeanMarie-TTS** [comment]
@mogul , some thoughts on ontegrating the scan with the deployment process ...
When a new docker image is successfully scanned and uploaded to ghcr, we can trigger a workflow. This workflow will result in the updated docker image being deployed in the `dev` environment. This workflow does not have to use Terraform for this.
