### ISSUE TITLE
Stub in static site information architecture

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1029]
# At a glance

**In order to** author content on the FAC website
**as a** content developer
**I want** the site outline in place, so it is obvious to me where my work will fit into the site.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: A content developer wants to update the resources available to auditees.

**Given**   that I know what content I want to author,
**when**  I'm ready to add it to the site
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the static site information architecture has been laid out and agreed upon
- [ ] the static siet templates/navigation reflect the IA and are implemented
- [ ] the static site skeleton passes usability scans
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: @lauraherring 
* Engineering shepherd: @heymatthenry 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

The site IA is mocked out in mural here:

https://app.mural.co/t/gsa6/m/gsa6/1673043940847/1e6c0ab070d0319de225057c22faae023abf9253?sender=matthewjadud7136

and as of 4/13 looks kinda like:

![Screenshot from 2023-04-20 06-52-05](https://user-images.githubusercontent.com/38290/233344894-9cdcab75-4c8b-4c53-90b9-6d4383a1f04b.png)

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns to this work on the static website.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by heymatthenry** [comment]
The IA in the Mural as pictured here is just the actual FAC app, right? Is the content portion of this ticket about adding the static site IA in as well? Asking because I was about to start making empty pages in the static site according to the IA but I can't tell from this what needs building. Or is there somewhere else I need to look?

**Comment by lauraherring** [comment]
@heymatthenry The static pages are under the Resources section. I've updated the Mural link to make these pages green, let me know if that helps clear things up.

**Comment by jadudm** [comment]
For now, I'd favor "ease of editing."

The validator can be link back to the app. 

This may not make sense a year from now, but I think making it easier to have a place where content lives/is updated over time, and the content team can manage, then that is a win. Putting it in the main repo makes it harder to manage lightly.

**Comment by jadudm** [comment]
Done.
