### ISSUE TITLE
Update copy on FAC app homepage

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1041]
### Tasks

```[tasklist]
- [ ] Change text
```

The existing text is: 

> The Federal Audit Clearinghouse (FAC) is the place to submit and review federal ​single audits. When ​a non-federal entity spends $750,000 or more in federal grant funds in a given year, they are required to submit a ​single audit.

The proposed new text is:

> The Federal Audit Clearinghouse (FAC) is the place to submit and review federal ​single audits. When ​a non-federal entity spends $750,000 or more in federal grant funds in a given year, they are required to submit a ​single audit.

Per https://github.com/GSA-TTS/FAC/issues/534

This simplifies the discussion/task, and we know we need to revisit this as part of (future) workstreams. This allows us to archive 534 and turn this into a simple, actionable task.

**Comment by heymatthenry** [comment]
Is it just me or is the proposed new text identical to the existing text?

**Comment by jadudm** [comment]
Closing as "done." We're doing a lot of work on content in the next week or two, and will likely pick this up in any number of future tickets. (I can imagine a "walk through the entire site as a team" exercise before we go live.") So, I'm going to close this as "done," because enough of us *think* it *might* be done.
