### ISSUE TITLE
"Mark ready for certification" page

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1043]
# At a glance

Auditors and auditees should have a clear checkpoint in their process to demarcate their transition from submitting their audit information to certifying their information.

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** begin certifying an audit
**as a** certifying official
**I want** a point where I will be notified that everything is "done."

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

Editors = auditors and auditees uploading SF-SAC data and the audit package PDF.

### Scenario: The product owner thinks we need a clear point for editors to hand off to certifying officials in the workflow.

**Given**  that the product owner is never arbitrary and capricious
**when**  this ticket lands
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [x] the designer mocks out the "Mark as ready for certification" page
- [ ] content develops explainer text for the "mark as ready" page
- [ ] content suggests text for a "mark as ready for certification button"
```

### Scenario: Editors have uploaded all of the SF-SAC and a PDF package, and all of it passes validation.

**Given**  that the audit is completely uploaded
**when**  everything is validated
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the "Mark audit as ready for certification" page becomes unlocked in the user's audit workflow summary
- [ ] an editor can click "mark as ready" button, which triggers notifications and unlocks certification
- [ ] unit tests confirm the preconditions that must exist for the "mark ready" page to unlock
- [ ] E2E tests confirm that the page only unlocks when a complete, valid package is in place
- [ ] E2E tests confirm that the certification steps unlock after "mark as ready" is indicated
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: @Leighdiddy 
* Engineering shepherd: @tadhg-ohiggins 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

See notes on this mock; it should probably be updated to reflect the design choices/discussion here.

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o?node-id=5157:30226#427362508

It may be that the better place to do the edits is the overall workflow/playground. 

New copy for the "My Audit Submissions Page" below:
In-progress Audit Submissions
The audit submissions below are in progress and assigned to your email address. These audits are for 2022 only. Completed audits from 2021 and earlier can be found on the U.S. Census Bureau's FAC website.

(table of audit submissions and status, per current "Create or modify an audit submission page)

Create a new audit
Before you begin a new audit submission, check the list above to make sure one isn't currently in progress and assigned to your email address.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns exposed as part of this work; this is all part of the normal workflow of the system, no new inputs are proposed.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
See also:

https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o?node-id=5157:30226#427366492

which asks about who can do what?

**Comment by jadudm** [comment]
Also, 

https://github.com/GSA-TTS/FAC/blob/main/backend/audit/models.py#L257

which lays out the roles. Making clear what each role can do, where, might be the easy solution to telling this story.

**Comment by jadudm** [comment]
Consider expanding tuple in above code to indicate whether the role is `ONE` or `MANY`.

Also... can we collapse these roles at all... is there just "contact" or "editor" as a role, and the distinction between auditor/auditee does not matter for general submission/upload. It only matters for certification, of which there can be only one for each of auditor and auditee.

Also, if we move to the "editor" role (collapsing auditor/auditee contacts), this eliminates the creator role, as it becomes an editor.

**Comment by jadudm** [comment]
The story has now been expanded based on conversation with the team and the notes above.

**Comment by lauraherring** [comment]
I've added the new copy for the "My Audit Submissions" page to the Background of this ticket.

**Comment by tadhg-ohiggins** [comment]
The [current Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5031-26947&t=tVXqtPoVtbTcQc7X-0) has:

*   **Create an audit submission**. This maps to `in_progress` and is by default checked by virtue of being able to reach this page.
*   **Complete SF-SAC**. Philosophically, is it possible for the SF-SAC to be “complete” if the PDF has not been uploaded? Is it meaningful to assert that the SF-SAC is “complete” before the user asserts that it’s complete? I think the answer is no, and given that, it doesn’t make sense to allow a user to do some transition other than “ready for certification” at the point where their SF-SAC answers are all valid _and_ they have uploaded a valid PDF.
*   So we have `ready_for_certification` as the internal representation of “valid SF-SAC and uploaded PDF _and_ user has asserted it’s ready”, but the Figma doesn’t quite match this.
*   The later steps (auditor/auditee certification, etc.) are fine, since they match the linear progression.

I think that we should remove the **complete SF-SAC** and **upload PDF** entries and instead have an entry for **Mark as ready for certification** that has sub-items that show whether or not the SF-SAC is currently valid (note that this is conceptually _different_ from “complete”) and whether or not a PDF has been uploaded.

The **Mark as ready for certification** page would just have a button to do that, but users can only do that if the SF-SAC is valid and there’s a valid PDF.

-----

Also, how about we change the name of this issue to ‘“Show submission status and actions to take” page’?

**Comment by jadudm** [comment]
Sounds good. We'll try and update designs tomorrow, perhaps.

**Comment by jadudm** [comment]
I'm flagging @Leighdiddy here...

I think, when I wrote this, I imagined that (somehow) you go from submitting materials to a magical page where you say you're ready for certification.

I _think_ we decided that the "Audit Homepage" (where we see the checkmarks) serves this purpose, because it unlocks the auditor certification when everything is uploaded and ready.

Is this page needed?

**Comment by Leighdiddy** [comment]
@jadudm @tadhg-ohiggins Laura and I mocked this up, what do you think? https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=4954%3A26401&t=cW1TOCHrM4nojabG-1

**Comment by Leighdiddy** [comment]
@jadudm also another thought/question about workflow here- Do we anticipate the Auditee completing this step, or could it be either role?

**Comment by tadhg-ohiggins** [comment]
I had thought anyone involved could do the ready for certification step, since that's really just saying the prior steps are done, and I don't see a good reason to restrict it.

How does one get to that page? The copy that states that the audit and SF-SAC are ready for certification confuses me, in that I thought of this step as the point at which someone involved in the submission asserts that things are ready—not one where we assert that things are ready, since the system can't actually know that.

**Comment by Leighdiddy** [comment]
Definitely still fine tuning the copy, this is a draft. To clarify wording (making sure I follow) - we (the FAC) are not stating that documents are ready, we are asking the user to confirm/certify that they are. 

My bad, I didn't include enough context in that last comment. We've mocked up a new step in the checklist to take you here (needs design tweaks), this is the current draft flow:

1. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=5281%3A31991&t=cW1TOCHrM4nojabG-1
2. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=5596%3A33197&t=cW1TOCHrM4nojabG-1
3. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=4954%3A26401&t=cW1TOCHrM4nojabG-1
4. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=5281%3A32325&t=cW1TOCHrM4nojabG-1
5. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=5281%3A32162&t=cW1TOCHrM4nojabG-1
6. https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=6767%3A33651&t=cW1TOCHrM4nojabG-1

**Comment by Leighdiddy** [comment]
@lauraherring I'm a goof, we already had this ticket for this new page: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1%3A31587&mode=design&t=XYyMsDDBpEGLM50i-1

**Comment by lauraherring** [comment]
@Leighdiddy I've updated the Final Figma page with copy taken from the version you linked above.
