### ISSUE TITLE
Upload Page Timeout

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#1050]
Related to https://github.com/GSA-TTS/FAC/issues/928

# At a glance

The user is notified if their file upload was unsuccessful due to a timeout. 

# Acceptance Criteria

In the event of a server timeout for whatever reason (long processing time, crash, etc.), the frontend should timeout the response and let the user know. 

# Background

The relevant HTTP request is made in  `/backend/static/js/upload-page.js`. Some sort of timeout function should be written that aborts this request and updates the `info_box` on the frontend.

**Comment by jadudm** [comment]
This was previously implemented, then commented out. We need, as a team, to decide what the timeout should be, and why. Then, we'll bring it back.

**Comment by jadudm** [comment]
Lets choose 30 seconds. :gavel: Arbitrary. To be revisited based on testing.

**Comment by mogul** [comment]
Note the lack of a timeout limit came up explicitly in our assessment. I'm leaving this a `SHOULD` for now, but it _may_ need to move up to a `MUST` if it's determined to be a big risk blocking our ATO (seems doubtful, but...).
