### ISSUE TITLE
E2E passing tests exist for federal awards page

### ISSUE THREAD

**Issue by eazapata23** [GSA-TTS/FAC#1055]

**Comment by eazapata23** [comment]
This still a work in progress but something quick and straightforward

Given user is on the federal awards upload page
When the user clicks on the xlsx link
And the user grabs the xlsx file 
And xlsx file gets validated successfully
And user clicks on save and continue button
Then user should be taken to the next page 

this works in the normal flow with DISABLE_AUTH = True , your able to successfully be taken to the next page but not when set to False. Error Forbidden (403) 
<img width="1311" alt="Forbidden -403-file-upload-false- 2023-04-27 at 3 31 20 PM" src="https://user-images.githubusercontent.com/99770283/234972047-4f9bb89f-3a57-4508-ae2d-4ba44fba1f4c.png">

**Comment by eazapata23** [comment]
Update: I written tests in file upload test suite for both upload success and upload failed. Tests for successful upload pass but for failed upload they are inconsistent, likely related to wait process. These same tests that fail do pass in their own corresponding test for that upload page. Still learning about cypress and best practices. 

https://user-images.githubusercontent.com/99770283/236514962-41545faa-425e-4b1c-bb58-7a75a0d7b421.mov

**Comment by jadudm** [comment]
@eazapata23 , is this done? If so, we can close it out. ✅

**Comment by eazapata23** [comment]
These currently aren't working due to they need to be updated due to all the recent changes.
