### ISSUE TITLE
Configure apps to use HTTPS egress-proxy

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#1064]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** ensure apps can make outbound HTTPS requests to necessary services even after their space is egress-restricted
**as a** system architect
**I want** all apps to make use of bound HTTPS egress-proxy credentials

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given** I have configured the [`gsa-fac`|`clamav`] app to use the proxy credentials provided in the `egress-creds` UPSI
**when** the [`gsa-fac`|`clamav`] app makes an outbound connection
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [x] I see an entry in the `egress` app logs documenting the request being allowed/denied.
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: N/A
* Engineering shepherd: @mogul

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

We deployed an egress proxy service in #1015. This issue is about ensuring the apps pay attention to the proxy settings.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

This change will cause apps to funnel all outbound requests through a controlled interface, which meets the intent of NIST control SC-7. A further change to block all outbound requests that are not going through the proxy, at the space level, is out of scope but coming as soon as we can also proxy SMTP requests.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by mogul** [comment]
@asteel-gsa and I were having trouble confirming whether `fac-av-dev` was using the `https_proxy` environment variable or not, since we saw it was successfully updating the virus definitions database but there were no logs on the proxy. It turns out that...
> [The freshclam program is not designed to recognize standard Linux environmental variables used by Security Analytics which define the web proxy](https://knowledge.broadcom.com/external/article/168849/clamav-not-updating-virus-definitions-vi.html#:~:text=The%20freshclam%20program%20is%20not%20designed%20to%20recognize%20standard%20Linux%20environmental%20variables%20used%20by%20Security%20Analytics%20which%20define%20the%20web%20proxy.).
So we might need to make a custom ClamAV image or else deploy ClamAV with a buildpack to make the necessary changes to the config file at app startup.

**Comment by mogul** [comment]
> So we might need to make a custom ClamAV image or else deploy ClamAV with a buildpack to make the necessary changes to the config file at app startup.

We resolved a previous problem by [making an upstream PR that was accepted within one day](https://github.com/ajilach/clamav-rest/pull/14); I'm going to try the same thing here.

**Comment by mogul** [comment]
Summary of the approach: In [the `entrypoint.sh` script that runs at container startup](https://github.com/ajilach/clamav-rest/blob/master/entrypoint.sh), if the `https_proxy` environment variable is set, [use a regexp to extract the protocol, username, password, host, and port elements from the `https_proxy` URL](https://stackoverflow.com/a/63993578), and then use sed to make edits to the `freshclam.conf` file (similar to the existing lines that make edits to the `clamd.conf` file).

**Comment by mogul** [comment]
For the `swagger` application: If the `https_proxy` variable is set while staging (pushing) the application, the docker process attempts to use it to reach Docker Hub and fails:
```
mogul@rocinante-w11:~/Documents/Code$ cf set-env swagger https_proxy [REDACTED]
Setting env variable https_proxy for app swagger in org gsa-tts-oros-fac / space dev as bret.mogilefsky@gsa.gov...
OK

TIP: Use 'cf restage swagger' to ensure your env variable changes take effect.

mogul@rocinante-w11:~/Documents/Code$ cf restage swagger
This action will cause app downtime.

Restaging app swagger in org gsa-tts-oros-fac / space dev as bret.mogilefsky@gsa.gov...

Staging app and tracing logs...
   Cell fca078c1-c655-4d4e-8dde-001c634c490b creating container for instance 7a241e19-487b-4c8c-98e3-0291490c9109
   Security group rules were updated
   Cell fca078c1-c655-4d4e-8dde-001c634c490b successfully created container for instance 7a241e19-487b-4c8c-98e3-0291490c9109
   Staging...
   Staging process started ...
   Failed getting docker image manifest by tag: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": Forbidden  Going to retry attempt: 1
   Failed getting docker image manifest by tag: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": Forbidden  Going to retry attempt: 2
   Failed getting docker image manifest by tag: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": Forbidden  Going to retry attempt: 3
   Failed getting docker image manifest by tag: pinging docker registry returned: Get "https://registry-1.docker.io/v2/": Forbidden
   Staging process failed: Exit trace for group:
   builder exited with error: failed to fetch metadata from [swaggerapi/swagger-ui] with tag [latest] and insecure registries [] due to pinging docker registry returned: Get "https://registry-1.docker.io/v2/": Forbidden
   Exit status 2
   Staging Failed: STG: Exited with status 2
   Cell fca078c1-c655-4d4e-8dde-001c634c490b stopping instance 7a241e19-487b-4c8c-98e3-0291490c9109
   Cell fca078c1-c655-4d4e-8dde-001c634c490b destroying container for instance 7a241e19-487b-4c8c-98e3-0291490c9109
Error staging application: StagingError - Staging error: staging failed
FAILED
```

So we need to set the value for the `https_proxy` variable under another name, then set it under the right name at app startup. This is probably doable with a `start-command`, but I haven't done that with Docker much in the past.

**Comment by mogul** [comment]
> For the `swagger` application: If the `https_proxy` variable is set while staging (pushing) the application, the docker process attempts to use it to reach Docker Hub and fails:
> 
> [...]
> 
> So we need to set the value for the `https_proxy` variable under another name prior to staging, then set it again based on that value under the right name at app startup. This is probably doable with a `start-command`, but I haven't done that with Docker much in the past.

This was looking iffy, so we [sidestepped the need for swagger to use the egress-proxy](https://github.com/GSA-TTS/FAC/pull/1098) by having it point to a private route on the `apps.internal` domain instead.

**Comment by mogul** [comment]
From DMs with Alex today:

> Hey based on [this](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1683587084418779?thread_ts=1683566830.036099&cid=C03QCP4FSN8) I think we need have our PR to `clamav-rest` to get the values from some variable name other than `https_proxy`.
> Maybe just have it accept the variables for the settings just as it does the others:
> https://github.com/ajilach/clamav-rest#environment-variables
> And then we can change the egress-proxy module to output exactly the values we need rather than round-tripping through the URL.

**Comment by mogul** [comment]
Summary of where we are here:

- [x] `gsa-fac` is properly accessing login.gov and api.sam.gov via the proxy, and sending data to New Relic
- [ ] Alex [made a PR for `clamav-rest`](https://github.com/ajilach/clamav-rest/pull/20) that is still pending.
  - If we don't see movement on this by the middle of next week we'll start building/maintaining our own image.
- [x] `postgrest` does not need to use the proxy because it only accesses the bound DB services
- [x] `swagger` does not need to use the proxy because it operates in the user's browser and only accesses the public postgrest API endpoint

**Comment by mogul** [comment]
@asteel-gsa Given no response from the upstream I guess we will need to start maintaining your fork. Want to move `asteel-gsa/clamav-rest` into `GSA-TTS` and set up a GitHub action to build, scan, and push it to GHCR?

**Comment by asteel-gsa** [comment]
> Summary of where we are here:
> 
> * [x]  `gsa-fac` is properly accessing login.gov and api.sam.gov via the proxy, and sending data to New Relic
> * [x]  Alex [made a PR for `clamav-rest`](https://github.com/ajilach/clamav-rest/pull/20) that is still pending.
>   
>   * If we don't see movement on this by the middle of next week we'll start building/maintaining our own image.
> * [x]  `postgrest` does not need to use the proxy because it only accesses the bound DB services
> * [x]  `swagger` does not need to use the proxy because it operates in the user's browser and only accesses the public postgrest API endpoint

`docker pull ghcr.io/gsa-tts/clamav-rest/clamav:20230530` [TTS ClamAV](https://github.com/GSA-TTS/clamav-rest/pkgs/container/clamav-rest%2Fclamav)

**Comment by mogul** [comment]
Still to do: 

- [ ] Replace the existing image from Docker Hub with the new upstream clamav image we maintain in our scan-images workflow @JeanMarie-TTS 
- [ ] [Update our Terraform to inject the credentials for our proxy into the clamav-rest environment](https://github.com/GSA-TTS/FAC/blob/main/terraform/shared/modules/env/clamav.tf#LL19C3-L19C51) @asteel-gsa

**Comment by mogul** [comment]
As of this week's prod deploy, we believe this is done.

**Comment by mogul** [comment]
We still need to configure ClamAV to use the proxy.
