### ISSUE TITLE
Resubmission of audits

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1067]
# At a glance

submitter = auditor/auditee

**In order to** to correct errors
**as a** submitter
**I want** to be able to resubmit a completed audit. 

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

SA = Single Audit

### Scenario: An auditee needs to upload a new PDF package for a previously submitted SA.

**Given**   that I have a new PDF
**when**  I'm ready to resubmit
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] a migration is added to extend the SingleAudit model with the appropriate versioning fields
- [ ] the auditee can find the completed audit on the "My Audits" page
- [ ] the auditee can chose to resubmit a completed audit
- [ ] the auditee is presented with the Report Home page for that audit, with all form data cleared *except* for the Pre-SAC (?)
- [ ] the auditee can begin the General Info workflow to enter background info
- [ ] the auditee can upload XLSX documents
- [ ] the auditee can upload the PDF package
- [ ] the auditee/auditor can reach the certification workflow
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

When a resubmission starts, we will take an "APPEND ONLY" worldview. Therefore, a new report with a new UID is created. It should have three fields that don't exist currently (subject to renaming):

* `originating_report` : This is the UID of the original submission in a resubmission chain. 
* `parent_report` : this is the report which we are revising.
* `version`: an integer field that we increment with each revision.

Eg:

The original report would look like

| uid  | originating | parent | version |
| ---- | ----------- | ------ | ------- |
| 0    | ROOT        | ROOT   | 0       |
| 34   | 0           | 0      | 1       |
| 283  | 0           | 34     | 2       |
| 3934 | 0           | 283    | 3       |

This lets us do a query on the `originating` field and version field to find the most recent submission in a chain without having to walk the chain.

Users should only be able to create a revision off the most recent revision.

We need to discuss what is public and what is not. Is the complete revision chain public? (If it is, it is easier for us.)

![Screenshot from 2023-05-02 12-56-30](https://user-images.githubusercontent.com/38290/235733762-13d4026a-afb4-46e2-94cc-f59a7331b745.png)

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns in report resubmission; it is the same as report submission.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
How do we reduce friction so as to encourage resubmissions to the FAC. (May require more convo w/ agencies, etc.)

**Comment by jadudm** [comment]
Should there be a ... feed... for revisions? (We don't have a way for people to subscribe to a revision chain. May never have that feature.)

**Comment by danswick** [comment]
Consolidating under https://github.com/GSA-TTS/FAC/issues/2301
