### ISSUE TITLE
Configure egress proxy to allow ClamAV to update scan packages (freshclam)

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1083]

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 needs to update SSPP on how this affects data flow through the boundaries

**Comment by asteel-gsa** [comment]
@JeanMarie-TTS Please update the description of this ticket with what needs to be done. Thank you.

**Comment by mogul** [comment]
The egress proxy is already configured to allow egress traffic to database.clamav.net, and Alex is already making [these other changes](https://github.com/GSA-TTS/FAC/issues/1064#issuecomment-1536820002) to make ClamAV use it. So maybe this issue can be closed, or else limited just to documentation updates?

**Comment by asteel-gsa** [comment]
@JeanMarie-TTS https://github.com/GSA-TTS/FAC/issues/1064#issuecomment-1540676175

**Comment by mogul** [comment]
Closing as a dupe of work happening in #1064
