### ISSUE TITLE
add /vw_structured_data, /vw_crosswalk (?), /vw_pdf_audit endpoints

### ISSUE THREAD

**Issue by jpmorris** [GSA-TTS/FAC#1103]
Feature Request:

At HHS-OIG we used the old FAC site HEAVILY.  We used a RPA bot (UIPath) to scrape all single-audits for a given time period. The workflow was the following:

1. Go to FAC site
2. Enter arbitrary dates for 'FAC Release Date'
3. Download each of the provided 100 audit batches which includes all audit PDFs and corresponding crosswalk files (the crosswalk files link the filename to the corresponding entry in the structured data)
4. Download all structured data (the backend data tables in csv format) for the year on the main FAC file

This would give us everything we needed (structured data. crosswalk, all pdf audits) to be able to perform advanced NLP and store in our DB.   

So we don't use any of the current exposed endpoints, we pull all the data to run analysis in aggregate.  I don't see any endpoints exposed that allows us to get this information, so we would like to request these endpoints:
 
   * /vw_structured_data(year) - gets all structured data for the year
   * /vw_pdf_audit(date range) - gets all audits for a given date range
   * /vw_crosswalk(date range) - gets all crosswalk entries for a date range (in the old FAC site this was bundled with the audit PDFs)

Thanks for this API! Can't wait to get access to this, it's going to help out an automated pipeline we are working on tremendously.

**Comment by jadudm** [comment]
@jpmorris, I've moved this over to the GH Discussions space:

https://github.com/GSA-TTS/FAC/discussions/1147

It is my hope you'll join us there and expand a bit on this. I'm going to close this particular ticket, and continue the conversation there. Depending on where it leads us, we'll possibly come back around to stories for implementation.
