### ISSUE TITLE
ZenDesk needs a .gov alias

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1109]
See the top.

**Comment by jadudm** [comment]
This is complete, but only works for administrative views, because we don't (yet) have any services live at ZenDesk. All seems to be good.

**Comment by mogul** [comment]
Still seeing this at support.fac.gov... Are we really done here?


![Image](https://github.com/GSA-TTS/FAC/assets/47762/853f369f-510f-4895-afcf-89a2ef1e5436)
