### ISSUE TITLE
Research on content management workflows

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#112]
**Background**
We need a better understanding of how, who, and when content on the FAC front end will change. 

**We'll know we're done when...**
- [ ] 
- [ ] 

**Tasks**
- [ ] 
- [ ]

**Comment by ryanwoldatwork** [comment]
Happy to support with service design pertaining to data flow.

**Comment by jadudm** [comment]
We have lots of content management questions, but we also have a content team, so... we'll get there. Closing this ticket as not necessary.
