### ISSUE TITLE
Improve deployment frequency & environment configuration

### ISSUE THREAD

**Issue by eazapata23** [GSA-TTS/FAC#1137]
### Overview:

 Based on previous discussions this ticket proposes a shift in our deployment strategy, suggesting that we push changes to the staging and production environments on a daily basis rather than weekly. The consensus reached among the team was that pushing to staging daily was the preferred approach. By leveraging, more frequent deployments:

-May help identify potential issues 
-Reduce the chance of bugs in production 
-Encourages us to optimize the deployment process
-Overall help improve software quality

Additionally, it raises the need for clarifying the purpose of staging and opens the discussion of possibility for introducing additional environments?

Things to consider:
-Evaluating risks & feasibility 
-Streamline deployment process
-Define a test strategy(smoke, regression, etc.)
-Revisit environment configuration

Of course, further discussion/collaboration to be had.

  
### Tasks

```[tasklist]
- [ ] A thing
- [ ] Antoher thing
```

**Comment by asteel-gsa** [comment]
Closing this PR, as the MVP AC for this solution has been resolved with the merge of #1135 and nightly PRs from main to staging are occuring. A subsequent ticket will be created for debt and improving this.
