### ISSUE TITLE
Should we call out tribal audit access needing a login on homepage, under "search older audits" button?

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1142]

**Comment by Leighdiddy** [comment]
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?type=design&node-id=4954%3A24052&t=0yBKrQyiXsJJcHcy-1

**Comment by jadudm** [comment]
Closing as the world will likely have changed underneath us by the time this ticket comes around. Will be picked up in research and design around both `search` and `certification`.
