### ISSUE TITLE
Refactor github workflows - DRY

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1157]
Looking pretty good... In addition to the cleanup and bugfix here, I'd like to see the `fetch-versions` job factored back out!

_Originally posted by @mogul in https://github.com/GSA-TTS/FAC/pull/1151#pullrequestreview-1440922145_
            
Eliminate duplication wherever it exists.

**Comment by danswick** [comment]
Let's close this for now. We can reopen or create a new issue with more detail later if needed.
