### ISSUE TITLE
Address Ryan's SSPP comments

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1161]
- [x] Update architecture diagram - external service, agenct user, ports, cloud.gov access, etc Review narrative.
- [x] Revisit other diagrams in SSPP
- [x] Systems in diagram should match the narrative in the SSPP
- [ ] Revisit system environment narrative about AWS
- [ ] Asset inventory vs Software inventory
- [ ] Table 9.4 and associated narrative
- [x] Review ports in Table 10.3

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 Here's the output from OWASP scan. See https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120

docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap-baseline.py -t https://fac-dev.app.cloud.gov/ -c zap.conf -I
  shell: /usr/bin/bash -e {0}
  env:
    url: https://fac-prod.app.cloud.gov/
Using the Automation Framework
202[3](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:3)-05-2[4](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:4) 17:42:11,782 Unable to copy yaml file to /zap/wrk/zap.yaml [Errno 13] Permission denied: '/zap/wrk/zap.yaml'
Total of 7 URLs
PASS: Vulnerable JS Library (Powered by Retire.js) [10003]
PASS: In Page Banner Information Leak [10009]
PASS: Cookie No HttpOnly Flag [10010]
PASS: Cookie Without Secure Flag [10011]
PASS: Content-Type Header Missing [10019]
PASS: Anti-clickjacking Header [10020]
PASS: X-Content-Type-Options Header Missing [10021]
PASS: Information Disclosure - Debug Error Messages [10023]
PASS: Information Disclosure - Sensitive Information in URL [10024]
PASS: Information Disclosure - Sensitive Information in HTTP Referrer Header [1002[5](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:5)]
PASS: HTTP Parameter Override [1002[6](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:7)]
PASS: Open Redirect [10028]
PASS: Cookie Poisoning [10029]
PASS: User Controllable Charset [10030]
PASS: User Controllable HTML Element Attribute (Potential XSS) [10031]
PASS: Viewstate [10032]
PASS: Directory Browsing [10033]
PASS: Heartbleed OpenSSL Vulnerability (Indicative) [10034]
PASS: Strict-Transport-Security Header [10035]
PASS: HTTP Server Response Header [10036]
PASS: Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s) [1003[7](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:8)]
PASS: Content Security Policy (CSP) Header Not Set [1003[8](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:9)]
PASS: X-Backend-Server Header Information Leak [1003[9](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:10)]
PASS: Secure Pages Include Mixed Content [[10](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:11)040]
PASS: HTTP to HTTPS Insecure Transition in Form Post [10041]
PASS: HTTPS to HTTP Insecure Transition in Form Post [10042]
PASS: User Controllable JavaScript Event (XSS) [10043]
PASS: Big Redirect Detected (Potential Sensitive Information Leak) [10044]
PASS: Retrieved from Cache [10050]
PASS: X-ChromeLogger-Data (XCOLD) Header Information Leak [10052]
PASS: Cookie without SameSite Attribute [10054]
PASS: X-Debug-Token Information Leak [10056]
PASS: Username Hash Found [10057]
PASS: X-AspNet-Version Response Header [10061]
PASS: PII Disclosure [10062]
PASS: Timestamp Disclosure [10096]
PASS: Hash Disclosure [10097]
PASS: Cross-Domain Misconfiguration [10098]
PASS: Weak Authentication Method [10105]
PASS: Reverse Tabnabbing [10108]
PASS: Dangerous JS Functions [10[11](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:12)0]
PASS: Absence of Anti-CSRF Tokens [10202]
PASS: Private IP Disclosure [2]
PASS: Session ID in URL Rewrite [3]
PASS: Script Passive Scan Rules [50001]
PASS: Stats Passive Scan Rule [50003]
PASS: Insecure JSF ViewState [90001]
PASS: Java Serialization Object [90002]
PASS: Charset Mismatch [90011]
PASS: Application Error Disclosure [90022]
PASS: WSDL File Detection [90030]
PASS: Loosely Scoped Cookie [90033]
WARN-NEW: Re-examine Cache-control Directives [100[15](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:16)] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/robots.txt (200 OK)
WARN-NEW: Cross-Domain JavaScript Source File Inclusion [100[17](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:18)] x 2 
	https://fac-dev.app.cloud.gov/ ([20](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:21)0 OK)
	https://fac-dev.app.cloud.gov/ (200 OK)
WARN-NEW: Information Disclosure - Suspicious Comments [100[27](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:28)] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: Non-Storable Content [10049] x 4 
	https://fac-dev.app.cloud.gov/openid/login/ ([30](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:31)2 Found)
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/robots.txt (200 OK)
	https://fac-dev.app.cloud.gov/sitemap.xml ([40](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:41)4 Not Found)
WARN-NEW: CSP: Wildcard Directive [10055] x 6 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/openid/login/ (302 Found)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/openid/login/ (302 Found)
WARN-NEW: Permissions Policy Header Not Set [10063] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: Modern Web Application [10109] x 1 
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: Sub Resource Integrity Attribute Missing [90003] x 3 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/ (200 OK)
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 8	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: [52](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108594120#step:4:53)

**Comment by JeanMarie-TTS** [comment]
@jadudm , there was a request to include the static transition site in the scope of our ATO.  Can you either update the SSPP directly or give us some detail so @ChrisB-16 or I can update it. In particular I don't know what the branching and CI/CD pipeline is. If the status site is going to link to the app, we will have to update our diagram as well.

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 , can you update the diagrams to include port numbers as discussed at the status call today? Please ask someone for help with PUML at the standup if you need.

**Comment by ChrisB-16** [comment]
@jadudm @mogul @heymatthenry - I wanted follow up on this request from the ISSM for our FAC SSPP to include the static transition site in the scope of our ATO. Pls feel free to provide updates to the SSPP directly or give us some technical details for usages of Pages so @ChrisB-16 or @JeanMarie-TTS we can perform updates..

**Comment by mogul** [comment]
I'll be working on adding the static site info today.

**Comment by mogul** [comment]
I think we can close this again, yeah...?
