### ISSUE TITLE
Dependabot warnings

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1171]
### Tasks

```[tasklist]
- [ ] Go to https://github.com/GSA-TTS/FAC/security/dependabot
- [ ] Fix the things
```

We might want a dependabot template.

**Comment by asteel-gsa** [comment]
based on the draft pr #1173 

`windows-curses` comes from ` localstack-ext` which comes from **dev-requirements.in** `localstack`

re-compiling requirements and dev-requirements via
`pip-compile --generate-hashes ./requirements/requirements.in -o requirements.txt --allow-unsafe` & `pip-compile --generate-hashes ./requirements/dev-requirements.in -o dev-requirements.txt --allow-unsafe` is causing a break in our requirements

**Comment by asteel-gsa** [comment]
From the dev-huddle discussion, proposal to remove localstack, thus getting rid of windows-curses and replacing it with minio(?) may be the next action item for this, which should allow us to recompile dev-requirements with latest versions for Django, Sqlparse and Requests.

**Comment by jadudm** [comment]
Does replacing localstack with Minio feel like the path of least resistance at this point? Just confirming; I think we left it as not-fully-decided, but if that feels right, it probably isn't a difficult change. 

It turns out when I was investigating this, I did it in a separate repository. It was a docker container and example workflow. 

https://github.com/jadudm/test-minio-gh-action

So, this is not (I don't think) "drop-in" ready, but given that this is for local dev and testing via actions, it might be close. (There's a `test.bash` that essentially does an insert, which mirrors the kinds of things we're doing in Django.) Point being... I'm not sure who might want to take this on right now, or what the prioritization is for it in terms of stack/deploy/etc.

@mogul, thoughts?

**Comment by asteel-gsa** [comment]
> Does replacing localstack with Minio feel like the path of least resistance at this point? Just confirming; I think we left it as not-fully-decided, but if that feels right, it probably isn't a difficult change.
> 
> It turns out when I was investigating this, I did it in a separate repository. It was a docker container and example workflow.
> 
> https://github.com/jadudm/test-minio-gh-action
> 
> So, this is not (I don't think) "drop-in" ready, but given that this is for local dev and testing via actions, it might be close. (There's a `test.bash` that essentially does an insert, which mirrors the kinds of things we're doing in Django.) Point being... I'm not sure who might want to take this on right now, or what the prioritization is for it in terms of stack/deploy/etc.
> 
> @mogul, thoughts?

Another question which @tadhg-ohiggins brought up via slack:
`Are dev-requirements security alerts something we actually need to worry about, since they're not used in any production environment?`

**Comment by mogul** [comment]
That said I'd say addressing findings in dev tools is low priority right now... but localstack setup also adds five minutes to our test running time. So replacing localstack with minio might be worth prioritizing now for the time benefit rather than the risk!

**Comment by asteel-gsa** [comment]
with #1196 all dependabot vulnerabilities are gone

![image](https://github.com/GSA-TTS/FAC/assets/130377221/9e6db6d1-2e19-4afa-92ec-c2248c3c0fed)

**Comment by jadudm** [comment]
@asteel-gsa , I missed the move to done. I'm going to go ahead and close this ticket.
