### ISSUE TITLE
Make JSON Schema validation more standards-based.

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1180]
Breakout issue of #1140

We want our JSON Schema validation to be based on standards where feasible.

```[tasklist]
### Possible standards
- [ ] Move phone numbers to E.164/E.123 standards in JSON Schema. E.164 essentially means all-digits, 11–15 digits in length. E.123 means a leading `+`, and only digits and spaces.
- [ ] Move zip codes to some standard. Our current regex doesn’t allow the hyphen, and I think that updating it might be a matter of allowing both five digits alone and five digits plus a hyphen plus four digits.
- [x] Determine whether or not to update the list of US state two-character codes to include DC, territories, and so on. I do not know if there’s some policy issue here about what addresses the FAC should be accepting audits from, but I doubt it, and this should probably be a matter of finding a good source for that list and switching to it.
-  [ ] Check all other lists in our validation and verify that they have the correct contents.
```

Re E164: There doesn’t appear to be an international standard on exactly what spacing should be used, which may mean that we shouldn’t impose any requirements about those spaces (and, potentially, should discard that information and treat the spaces as irrelevant). This standardization move should be considered carefully to determine that it would be worth the effort.

**Comment by jadudm** [comment]
#1091 is where the phone number tracking came from, and there's a few links there that may be of use. I closed #1091 as not being relevant in light of this better-structured ticket.

**Comment by neilmb** [comment]
Ran into this today:

```Traceback (most recent call last):
  File "/src/audit/validators.py", line 170, in validate_general_information_json
    validate(value, schema, format_checker=FormatChecker())
  File "/usr/local/lib/python3.10/site-packages/jsonschema/validators.py", line 1121, in validate
    raise error
jsonschema.exceptions.ValidationError: '+1-578-863-8980' does not match '^^(\\+0?1\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$'

Failed validating 'pattern' in schema['properties']['auditee_phone']:
    {'pattern': '^^(\\+0?1\\s)?\\(?\\d{3}\\)?[\\s.-]?\\d{3}[\\s.-]?\\d{4}$',
     'type': 'string'}

On instance['auditee_phone']:
    '+1-578-863-8980'
```

That was the Python library `faker` generating an E.123 format phone number with the leading `+`.

**Comment by neilmb** [comment]
https://pe.usps.com/text/pub28/28apb.htm is a list of the allowable two-letter state abbreviations for US-based addresses, including DC, AS, FM, GU, MH, MP, PW, PR, VI.

**Comment by jadudm** [comment]
Not in the 3-month lookahead. Labling REVISIT, and closing.
