### ISSUE TITLE
Inventory `null` fields in validation

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1182]
Breakout issue of #1140

Go through all of the fields where we’re allowing `null` as an answer and determine if we should actually do so, and if not, make the appropriate schema/code changes.

```[tasklist]
- [ ]   Inventory all of the current fields where `null` is allowed by the validation.
- [ ]   Determine what the policy for each of those fields should be.
- [ ]   Write tests based on that.
- [ ]   Update the schemas (and code if necessary) based on that.
```

Relevant note from @jadudm on #1140:

> I would like to move to a world where every field always has an input. There may be exceptions... for example, the second address line in a two-line address. However, at that point, we should probably assert that at least one of the two address fields must have a string value. Further, do address fields have a minimum length? What is the shortest valid entry in an address field? (How many angels can dance on the head of a pin, while we're at it.) Although pedantic, I think I would rather people submit helpdesk tickets where we discover, in practice, that our typing is too robust, and we have to relax it, than to have typing that is too lax, and we end up (quietly) with data that we validate, but wish we hadn't.

**Comment by jadudm** [comment]
PR #971 had additional conversation that may be relevant.

**Comment by jadudm** [comment]
Not in the 3-month lookahead. Labling REVISIT, and closing.
