### ISSUE TITLE
FAC - Bug: [Address Zap Scan Warnings]

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1186]
### Describe the bug

OWASP Scan run on  #1131 identified eight warnings.
WARN-NEW: Re-examine Cache-control Directives [10015] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/robots.txt (200 OK)
WARN-NEW: Cross-Domain JavaScript Source File Inclusion [10017] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/ (200 OK)
WARN-NEW: Information Disclosure - Suspicious Comments [10027] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: Non-Storable Content [10049] x 4 
	https://fac-dev.app.cloud.gov/openid/login/ (302 Found)
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/robots.txt (200 OK)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: CSP: Wildcard Directive [10055] x 6 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/openid/login/ (302 Found)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/openid/login/ (302 Found)
WARN-NEW: Permissions Policy Header Not Set [100[63](https://github.com/GSA-TTS/FAC/actions/runs/5071591115/jobs/9108172666#step:4:64)] x 2 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: Modern Web Application [10109] x 1 
	https://fac-dev.app.cloud.gov/sitemap.xml (404 Not Found)
WARN-NEW: Sub Resource Integrity Attribute Missing [90003] x 3 
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/ (200 OK)
	https://fac-dev.app.cloud.gov/ (200 OK)

### Steps to reproduce the bug

1.  Happens whenever we deploy to staging or production/

### Expected Behavior

Current result summary is:
FAIL-NEW: 0	FAIL-INPROG: 0	WARN-NEW: 8	WARN-INPROG: 0	INFO: 0	IGNORE: 0	PASS: 52

We need to get numbers to zero except for PASS

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mogul** [comment]
@asteel-gsa and @JeanMarie-TTS: Let's close this one once we get ZAP results reporting into the Security panel.

**Comment by jadudm** [comment]
This is an ancient ticket, and we're picking up this kind of work as part of normal work now.
