### ISSUE TITLE
Get cypress specs running in CI

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#1207]
The FAC app uses Cypress to automate testing of the UI and end-to-end testing. The specs all run successfully against the app running locally, but currently fail when running in CI. At some point after the specs were ported over from the old FAC-Frontend app and added to the CI pipeline, some of the specs began failing intermittently and a bit unpredictably. Eventually most or possibly all of them began failing, despite no changes to the specs or the code under test. 

Prior art: the implementation of this that worked all the way up until it didn't is in #862

## Acceptance Criteria

- [ ] All cypress specs run successfully in Github Actions

**Comment by jadudm** [comment]
Leaving open for reference; moving to the E2E regression test milestone.

**Comment by jadudm** [comment]
Tracking in another epic.
