### ISSUE TITLE
Multiple attempts to submit for the same entity and year

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1213]
This is not about historical data deduplication, but only about new submissions, and is about what happens when a submission is started, not when it is finalized.

This is also not about resubmissions, which are somewhat related but not the same thing.

The assumption is that currently Census FAC doesn’t allow a second submission for the same entity as an existing submission to be started; in effect, this means that once a submission for the current fiscal year has been started, no other submission for that year with the same UEI can be started. This is a first-mover-wins scenario.

We’d like to verify that this is current Census practice.

If we don’t do it this way, we instead would have to deduplicate later (presumably at finalization) or simply ignore the conflict. I _think_ that we probably have to identify the canonical submission for a given year by a given entity, but that is also ultimately a policy question.

So, initial non-technical questions to answer here:

1.  Does Census currently reject submissions if a submission for that entity is already in progress (or has been submitted) for that year?
2.  Is it a customer support function to delete stray submissions that get in the way due to #1? (My understanding is that this is very rare, but we might want to get citations for that.)
3.  For MVP, can we go forward with a policy of just rejecting submissions for a given UEI and year if a submission with that UEI/year combination is already present in our app? (And, by implication, leaving any practical issues caused by this first-mover-wins policy as something that has to be handled manually via support.)

**Comment by JeanMarie-TTS** [comment]
Should we use UEI + AuditPeriodEndDate to uniquely identify a submission rather than UEI + AuditYear?

**Comment by jadudm** [comment]
*This ticket is early days, and has not yet moved past triage. it requires conversation and research with a number of parties before action is taken or decisions made.* 

That said, I'm tempted to handle this by having it be a validation rule in the final cross-check. 

If one already exists, then it reports it as an error, and encourages them to reach out to the help desk.

That's a "first thought, not thought out fully" thought, but I wanted to record it here for the moment.

**Comment by tadhg-ohiggins** [comment]
We also have an implicit notion of an audit year; it’s just that right now it’s always 2023, because that’s the year we have to handle for MVP.

My initial thought was “one already exists” if a submission for a given audit year—in other words, for 2023—were already in our system.

I don't think we yet fully understand what it means for an entity to submit multiple audits for the same audit year when changing fiscal calendar, and we probably need some details on that.

**Comment by danswick** [comment]
Bundling this under https://github.com/GSA-TTS/FAC/issues/2301.
