### ISSUE TITLE
Create a checklist for new repositories

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1216]
### Tasks

```[tasklist]
- [ ] Create the checklist
```

https://github.com/GSA/data.gov/wiki/Checklist-for-new-repositories

We should have a doc/checklist like that.

**Comment by jadudm** [comment]
Per @mogul , "It seems like it belongs in the developer docs in GitHub, alongside other information about how we manage code."

**Comment by asteel-gsa** [comment]
https://github.com/GSA-TTS/FAC/wiki/Checklist-for-new-repositories

or should it be in [docs](https://github.com/GSA-TTS/FAC/tree/main/docs)
