### ISSUE TITLE
FAC - Feature: Use postgres roles appropriate to function

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1224]
### Is your feature request related to a problem? Please describe.

Currently, the FAC app uses a single role to access the postgres database. 
The database is used by PostgREST to serve read-only requests. PostgREST should connect to the database using credentials that do not support DDLs and updates.
The FAC web app accesses the database at run rime to insert, update, delete, modify and view data. This use has no need to perform DDL operations like CREATE /ALTER table.  The app should therefore use credentials that do not support DDL.
The app start-up process performs database migrations i.e. DDL operations. The startup process therefore needs to have these enhanced privileges.

### Describe the solution you'd like

- [ ] Implement a read-only role in the database. Ensure that this role only has SELECT privileges on views.
- [ ] Implement a CRUD role in the database that can perform SELECT, INSERT, UPDATE and DELETE on any tables but cannot CREATE or ALTER tables.
- [ ] Configure PostgREST to connect to the database using the read=only role
- [ ] Configure django to use the CRUD role at run time and the privileged role at start up.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by jadudm** [comment]
We can/should revisit this. I'm moving it to MVP. If we can move it left on the timeline, we can/should.

**Comment by jadudm** [comment]
I think our Postgrest role only has select privs. Closing this as not planned at this time, as we're operating as securely as we know how with the tools we're using.
