### ISSUE TITLE
Content inaccuracies on GSAs walkthrough page

### ISSUE THREAD

**Issue by Carley-Sullivan** [GSA-TTS/FAC#1226]
### Tasks

```[tasklist]
- [x] Fix the Pre-SAC screener section of static site
- [x] Fix Beginning New Audit section of static site
```

**Comment by Carley-Sullivan** [comment]
Pre-SAC screener section mentions:

The single audit submission process is for non-profit entities who spend $750,000 or more in Federal grant awards in a fiscal year.

This is not fully capturing who the submission process is for.  It should include:

-Non-Profits
-State and Local Governments
-Institutions of Higher Education
-Indian Tribes or Tribal Organizations

Beginning New Audit section needs correction.  The current language is:

The UEI is replacing the Employer Identification Number (EIN) in the single audit process. Every field that took the EIN in the past will now need the UEI.

This is not true.  UEI is not replacing (EIN).  EIN will still be a part of GSA's collection.  However, DUNS is going away... perhaps that is where the confusion started...

**Comment by lauraherring** [comment]
@Carley-Sullivan I've updated the copy in [those two sections](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/updating-walkthrough/walkthrough/). Please take a look and let me know if these are accurate before I push them to Main.

**Comment by Carley-Sullivan** [comment]
Very close.  

Pre SAC screener section has "institution of higher education" > I think we want "institutions of higher education" to match the other bulleted items in that section.

Beginning New Audit section - I wouldn't say that DUNS is replacing UEI in all instances of the form.  That could mislead members of single audit community as they have never needed a DUNS number to start a submission.  Would rather  have- DUNS is no longer being collected.  

On second thought, I would take out that entire second piece:

_The UEI is replacing the Data Universal Numbering System (DUNS) number in the single audit process. Every field that took the DUNS number in the past will now need the UEI._

**Comment by lauraherring** [comment]
Thanks for the feedback, @Carley-Sullivan. I've removed that paragraph entirely and made "institutions" plural. If you want to take a second look and confirm it all looks good, I can push the changes to main later today.

**Comment by Carley-Sullivan** [comment]
Looks good.

**Comment by lauraherring** [comment]
Thanks! I've submitted the pull request for this.

**Comment by lauraherring** [comment]
Changes merged with main on 6/16.
