### ISSUE TITLE
Push to prod for UAT 1

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1284]
### Tasks

```[tasklist]
- [ ] Locally tested for UAT path
- [ ] Pushed and tested on live site
```

**Comment by asteel-gsa** [comment]
Adding @eazapata23 as a collaborator on this ticket for support with UAT path.

@jadudm Do you mind determining the "release window" for the UAT testing in prod on `https://app.fac.gov`? More specifically, what day is UAT beginning and what is the deployment date that we are determining to "lock" the environment.

**Comment by asteel-gsa** [comment]
[this release](https://github.com/GSA-TTS/FAC/releases/tag/v1.20230628) fixes excel upload in staging and prod
