### ISSUE TITLE
FAC - Bug: Image broken on app.fac.gov 

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1290]
### Describe the bug

When dragging a doc in for upload, the icon that appears next to the file is broken.

### Steps to reproduce the bug

1. Select a file.
2. Image shows up broken.

### Expected Behavior

Image is not broken.

### Screenshots

![Screenshot from 2023-06-20 07-05-43](https://github.com/GSA-TTS/FAC/assets/38290/81c6351f-4667-4d08-975c-3baae1fbb9ef)

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by tadhg-ohiggins** [comment]
This may be fixed by https://github.com/GSA-TTS/FAC/pull/1344

**Comment by danswick** [comment]
Following up here after some more troubleshooting last week: I think we might want to use `img-src blob:` instead of `data:`. 

For possible future posterity, the source from USWDS is here-ish: https://github.com/uswds/uswds/blob/develop/packages/usa-file-input/src/index.js#L372

**Comment by jadudm** [comment]
We just hid the image with CSS. We also raised some flags with USWDS. Closing as "done," but we might be able to later fix this.
