### ISSUE TITLE
Add management of Django admin interface access

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1309]
### Background

We will need to look at the Django admin interface in our `dev`, `staging`, and `prod` environments in order to support various kinds of testing and troubleshooting. We currently do not have a deployment chain set up to create, grant access to, or manage access to those Djano admin interfaces, so we should build that.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We have a managed way of handling Django admin access on `dev`.
- [ ]   We have a managed way of handling Django admin access on `staging`.
- [ ]   We have a managed way of handling Django admin access on `prod`.

**Comment by tadhg-ohiggins** [comment]
@jadudm assigning to you for prioritization/triage. This was prompted by the [Slack thread](https://app.slack.com/client/T025AQGAN/C03QCP4FSN8) about upload problems and logs on staging.

**Comment by tadhg-ohiggins** [comment]
Somewhat easy approach: store email address of admins in comma-separate GitHub secret, add script to grab them from the secret and for each one create a Django admin user. Probably have a common password for now, also stored in a GitHub secret.

**Comment by jadudm** [comment]
Closing and flagging as `revisit` until we can schedule in this work.
