### ISSUE TITLE
Change process/documentation for workbook updates

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1314]
### Tasks

This may want to be system-wide. Curate/revise.

```[tasklist]
- [ ] Discuss/design workflow
- [ ] Document
- [ ] Test workflow, validate with partners, etc...
```

**Comment by jadudm** [comment]
We need a way to communicate changes to workbooks. This may matter most in the first three months (in a way), because we may discover bugs that require workbook changes. How do we document this for users? How/where do we communicate it?

**Comment by danswick** [comment]
Another note from discussion: if we link to workbooks on GitHub, will those be out of sync with the ones available via the static site? For example, if `main` hasn't been deployed yet, etc.

**Comment by jadudm** [comment]
Still needed, but it needs a better epic/ticket. And, it isn't clear it is on the near horizon. Leaving the `revisit` label, closing.
