### ISSUE TITLE
Update lorem ipsum for Submission Checklist page.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1326]
### Tasks

```[tasklist]
- [x] Multiple workbooks want improved text.
- [x] Might already be in Figma.
```

**Comment by jperson1** [comment]
Lorem ipsum removed as a first step, text can be added/improved.

**Comment by lauraherring** [comment]
I've updated this text, both in Figma and in a branch of the app that has been merged into main. I think we can close this ticket, @jadudm

**Comment by jadudm** [comment]
@jperson1 , if this ticket is done, go ahead and close it. I think it is.
