### ISSUE TITLE
BUG - Unclear error with file mismatch

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1341]
When I go to upload a federal awards sheet, but choose the CAP text instead, I get the following error:

```
Field Error: undefined
```

![Screenshot from 2023-06-27 08-52-01](https://github.com/GSA-TTS/FAC/assets/38290/3c088cc2-e23b-4227-a97c-a636da693edb)

We should handle this better...

We may want to add a sheet to every workbook where we have some metadata:

1. filename
2. version
3. date rendered
4. ...

which we could add to the validation. Or, we could check before we apply the validation... like, do we have a JSON document? How we check this, I'm not positive... but, somewhere in our mapping or validation, we need to make sure that we catch this error. (I suspect this is an error in the mapping... but, that's just :spider: sense.)

**Comment by sambodeme** [comment]
For unknown workbook
![image](https://github.com/GSA-TTS/FAC/assets/26260777/559d9543-96b8-4d3f-a8c6-a93f4fd73b76)

For wrong workbook
![image](https://github.com/GSA-TTS/FAC/assets/26260777/8ef1ed94-94e7-4db1-a7d0-6f09c282eaa6)
