### ISSUE TITLE
Fix New Relic's CSP-unsafe inline script usage pattern

### ISSUE THREAD

**Issue by neilmb** [GSA-TTS/FAC#1348]
Running on fac-dev.app.cloud.gov/audit we see an error that inline scripts are not allowed. It appears that NewRelic is putting its tracking code onto our pages by writing an inline Javascript onto the page using something like a Django middleware (?) https://github.com/newrelic/newrelic-python-agent/blob/ab590a2074c3e3e148ca077bf1ec24d6a09b2d89/newrelic/hooks/framework_django.py

<img width="474" alt="Screenshot 2023-06-27 at 10 35 58 AM" src="https://github.com/GSA-TTS/FAC/assets/443389/42f2bc4a-fe0a-4206-b6aa-1f1a4c16405e">

This inline script approach cannot work with our strict CSP that does not allow inline scripts that don't have a nonce. 

We should try to fix how NewRelic does this, either to add our nonce to their script so that it can be accepted by our policy, or setting NewRelic up to use a different approach.

**Comment by danswick** [comment]
I believe this is fixed now.
