### ISSUE TITLE
Manage S3 CORS headers in Terraform and add them for production

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1352]
### Background

We manually added the required CORS headers to the S3 buckets for fac-dev.app.cloud.gov and fac-staging.app.cloud.gov but should manage this with Terraform.

WE DID NOT DO THIS FOR THE PRODUCTION ENVIRONMENT. So that still needs to be set up, preferably by the Terraform process that will cover all of the environments.

We used this command to set the CORS headers:
```sh
aws s3api put-bucket-cors --bucket [BUCKET_NAME] --cors-configuration file://cors.json
```

where `[BUCKET_NAME]` is the name of the bucket for that environment. The contents of `cors.json` were:

```json
{
   "CORSRules": [
      {
         "AllowedHeaders": [
            "Authorization"
         ],
         "AllowedMethods": [
            "HEAD",
            "GET"
         ],
         "AllowedOrigins": [
            "https://[ENV_DOMAIN]"
         ],
         "ExposeHeaders": [
            "ETag"
         ]
      }
   ]
}
```

where [ENV_DOMAIN] was `fac-dev.app.cloud.gov` for `dev` and `fac-staging.app.cloud.gov` for `staging`.

For reference, the commands for this are included below:

```sh
SERVICE_INSTANCE_NAME=fac-public-s3;
KEY_NAME=fac-public-s3-key;
cf create-service-key "${SERVICE_INSTANCE_NAME}" "${KEY_NAME}";
S3_CREDENTIALS=`cf service-key "${SERVICE_INSTANCE_NAME}" "${KEY_NAME}" | tail -n +2`;
export AWS_ACCESS_KEY_ID=`echo "${S3_CREDENTIALS}" | jq -r .access_key_id`;
export AWS_SECRET_ACCESS_KEY=`echo "${S3_CREDENTIALS}" | jq -r .secret_access_key`;
export BUCKET_NAME=`echo "${S3_CREDENTIALS}" | jq -r .bucket`;
export AWS_DEFAULT_REGION=`echo "${S3_CREDENTIALS}" | jq -r '.region'`;
echo $BUCKET_NAME;
aws s3api put-bucket-cors --bucket $BUCKET_NAME --cors-configuration file://cors.json;
aws s3api get-bucket-cors --bucket $BUCKET_NAME;
cf delete-service-key "${SERVICE_INSTANCE_NAME}" "${KEY_NAME}";
```

### Acceptance Criteria (We'll know we're done when...)

- [ ]   Setting the CORS headers for the S3 buckets for each environment is handled by Terraform.
- [ ]   The CORS headers have been set for the S3 bucket for the production environment.

**Comment by mogul** [comment]
> Also, we had to manually run `cf bind-service` for the private S3 bucket for both `dev` and `staging`, that should also probably be handled by terraform? Do we need a separate ticket for that?

We should specify that in the application manifest, as [we do for the public bucket](https://github.com/GSA-TTS/FAC/blob/bee1b65b5444b60014b3b491c7ef173bd3eb2f3f/backend/manifests/manifest-fac.yml#L21).

**Comment by tadhg-ohiggins** [comment]
> > Also, we had to manually run `cf bind-service` for the private S3 bucket for both `dev` and `staging`, that should also probably be handled by terraform? Do we need a separate ticket for that?
> 
> We should specify that in the application manifest, as [we do for the public bucket](https://github.com/GSA-TTS/FAC/blob/bee1b65b5444b60014b3b491c7ef173bd3eb2f3f/backend/manifests/manifest-fac.yml#L21).

@mogul added that here: https://github.com/GSA-TTS/FAC/pull/1374

**Comment by mogul** [comment]
Noting for later: We would do this by having [a resource `provisioner`](https://developer.hashicorp.com/terraform/language/resources/provisioners/syntax#how-to-use-provisioners) call a local script that basically performs the commands Tadhg listed.

**Comment by jadudm** [comment]
@tadhg-ohiggins , is this... debt? Something we should flag as `revisit` and come back to?

**Comment by tadhg-ohiggins** [comment]
@jadudm No, this is something that appears to still be causing problems in production, or at least there are images failing to load that report CORS errors in the browser console, so I strongly suspect those are due to this not having been done.

**Comment by jadudm** [comment]
I have not yet been able to prioritize this, given many other needs.

It should remain in the pile for @Dan Swick - Q2ABD ***@***.***> and
I to map in as part of our continued board cleanup.
