### ISSUE TITLE
Github Branch Cleanup

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#1356]
Based on the current branches, this ticket will track the removal of current branches that are out of date in an effort to clean up the fac repository. Only considering [stale branches](https://github.com/GSA-TTS/FAC/branches/stale), please review these branches if they are no longer in use.

##############
@tadhg-ohiggins 
##############

```[tasklist]
- [x] https://github.com/GSA-TTS/FAC/tree/tadhg/linkml
- [x] https://github.com/GSA-TTS/FAC/tree/static-assets
- [x] https://github.com/GSA-TTS/FAC/tree/adding-static-assets
- [x] https://github.com/GSA-TTS/FAC/tree/tadhg/hotfix-whitenoise
- [x] https://github.com/GSA-TTS/FAC/tree/revert-676-ly/deploy-update
- [x] https://github.com/GSA-TTS/FAC/tree/revert-677-tadhg/deploy-tweak-procfile
- [x] https://github.com/GSA-TTS/FAC/tree/tadhg/deploy-without-collectstatic
- [x] https://github.com/GSA-TTS/FAC/tree/tadhg/switch-deploy-action
- [x] https://github.com/GSA-TTS/FAC/tree/tadhg/deploy-debug20230330b
- [x] https://github.com/GSA-TTS/FAC/compare/main...tadhg/deploy-debug20230330
- [x] https://github.com/GSA-TTS/FAC/tree/tadhg/hotfix-tags-trigger
- [x] https://github.com/GSA-TTS/FAC/tree/revert-1176-prod
- [x] Stale Branches Deleted
```

#############
@heymatthenry 
#############
https://github.com/GSA-TTS/FAC/tree/migrate-templates-564
```[tasklist]
- [x] Stale Branches Deleted
```

#######
@jadudm 
#######
https://github.com/GSA-TTS/FAC/tree/ly/data-exploration - @LindsayYoung 
https://github.com/GSA-TTS/FAC/tree/sarah/excel-generator-prototype - @geekygirlsarah 
https://github.com/GSA-TTS/FAC/tree/Add-design-research-docs - @MelissaBraxton 
https://github.com/GSA-TTS/FAC/tree/391-endpoint - @rachelschneiderman 
```[tasklist]
- [x] Stale Branches Deleted
```

**Comment by tadhg-ohiggins** [comment]
@asteel-gsa cleared out all mine and found a few other strays, thanks for compiling them!

**Comment by mogul** [comment]
> https://github.com/GSA-TTS/FAC/tree/bret/refactor-terraform-bootstrap

I brought this one up to date recently and I'm working on it intermittently, so I won't be deleting it.

That leaves just @heymatthenry to remove one branch before we can close this.

**Comment by heymatthenry** [comment]
I just deleted my branches. Do I need to do anything else?

**Comment by jadudm** [comment]
I think everyone has done their part for cleanup. Closing.
