### ISSUE TITLE
Model the dissemination API after Census-provided CSVs

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1359]
Per conversation with @JeanMarie-TTS and @jadudm, capturing here that our dissemination API should provide data that tracks Census-provided CSVs as closely as possible. We might do this with views or with the underlying data model or some combination. 

[This Google Drive folder](https://drive.google.com/drive/folders/1S5oTyFYfWxsEriiQfio1BfhrHuvohztq?usp=drive_link) is a good place to find reference data, including some SQL that @jadudm created from Census-provided CSVs.

**Comment by jadudm** [comment]
Added to the Census-inspired dissemination milestone for visibility.

**Comment by jadudm** [comment]
This work is well underway, and ticketed.
