### ISSUE TITLE
Sign and validate Docker images

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#1371]
Placeholder ticket to enable [DCT](https://docs.docker.com/engine/security/trust/) 
https://github.com/GSA-TTS/FAC/pull/1365#issuecomment-1614141101

Alternatively use SigStore/CoSign:
https://github.com/marketplace/actions/cosign-installer

**Comment by mogul** [comment]
We changed the verbage in the SSPP to not say we're doing this. If it comes up again as a poam, we can revisit.

**Comment by jadudm** [comment]
Closing as not planned as it was documented, and has not come up.
