### ISSUE TITLE
Make Census data available for API views

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1379]

**Comment by JeanMarie-TTS** [comment]
Pasting comment from @jadudm  on Slack related to this:
I have an initial scrub and dump of the Census data.
https://drive.google.com/drive/folders/1AwKP1P-TOjtEEdjx1PBuJrY9iCf8yAKn
In that folder, you'll find Postgres dumps of the Census data.
To be clear: this is the data we have recently been provided. Do not, under any circumstances, find a way to 1) commit this to GH or 2) load it into a DB that might have public access. This is for local development only at this time.
The awful code that takes their CSV dumps and notionally cleans them up, loads them locally, and dumps them is here:
https://github.com/GSA-TTS/FAC/tree/jadudm/scrub-census-data
The purpose of this is to make it possible to begin exploring the historic ETL process, which will necessarily have to work from these dumps. It should not derail or otherwise slow down our work in standing up the dissemination tables, which are based on the CSV exports that Census makes publicly available.

**Comment by jadudm** [comment]
Now tracking in Epic #1405.
