### ISSUE TITLE
FAC - Bug: Copying and Pasting into Excel Worksheet with Merged Cells Causes Breakage

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#1383]
### Describe the bug

When attempting to copy content from another Excel document and paste it into a worksheet that contains merged cells, the destination worksheet becomes corrupted. It appears that the copy operation, which involves selecting multiple cells, and pasting them into multiple cells, encounters issues when encountering merged cells. This results in unexpected behavior and breaks the layout of the worksheet.

### Steps to reproduce the bug

1. Open an xlsxl worksheet with merged cells (e.g. CAP xlsx or FindingsText xlsx or ...).
2. Open another Excel document containing data to be copied.
3. Select multiple cells in the second document.
4. Copy the selected cells.
5. Switch to the worksheet with merged cells.
6. Attempt to paste the copied content into the merged cells area.

### Expected Behavior

The copied content should be pasted smoothly into the merged cells area without any issues. The layout and structure of the worksheet should remain intact after the paste operation.

FYI,  this bug occurs specifically when copying and pasting content from multiple cells into merged cells. It does not affect regular copying and pasting within the same worksheet or between worksheets without merged cells.

### Screenshots

![image](https://github.com/GSA-TTS/FAC/assets/26260777/3f27ffa6-3936-4d2b-a0be-1adfaaf36efd)
![image](https://github.com/GSA-TTS/FAC/assets/26260777/b5a48967-14e1-4cf1-95dc-ce11b408b238)

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Putting a thought or two here for visibility.

1. We could use something [like this](https://stackoverflow.com/questions/26671581/horizontal-text-alignment-in-openpyxl) to avoid merging for aesthetic reasons.
2. If we have to, I'm prepared to suggest that we put single-cell values on the first sheet of the workbook, and column values on the second sheet of the workbook. This way, we don't have this kind of merge game going on for aesthetics.

Other thoughts/suggestions?
