### ISSUE TITLE
FAC PenTest

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#1394]
FAC PenTest Actions: Prep

```[tasklist]
### Pre pentest
- [x] Freeze all app/infra source code updates (Lock GitHub prod branch settings )
- [x] Disable GitHub Actions (AutoDeploy) automatic push to prod feature,
- [x] Create Login.gov accounts for PentTest
- [x] Review FAC PenTest Rules of engagement/sign
- [x] Track PenTest efforts for 10-14days -Tentative dates 7/6 to 7/20
```

```[tasklist]
### Readiness Checklist (POST actions)
- [x] Attend Pen Test Assessment review/summary
- [x] Post PenTest address findings with Severity levels (Critical & Highs) or Showstopper
- [x] Draft POAMS or RBD if needed
- [x] Perform verification scans if needed
```

**Comment by mogul** [comment]
@ChrisB-16 what is the next step to closing this one?

**Comment by ChrisB-16** [comment]
FAC PenTest status as of 8/2/2023:

1.  PenTest was conducted on targets: the Federal Audit Clearinghouse (FAC) sites

https://fac.gov/
https://fac-staging-postgrest.app.cloud.gov/
https://fac-production-postgrest.app.cloud.gov/
https://fac-staging.app.cloud.gov/
[app.fac.gov](http://app.fac.gov/)
https://fac-prod.app.cloud.gov/
https://gsa-tts-oros-fac-staging-egress-https-proxy.apps.internal/
https://gsa-tts-oros-fac-production-egress-https-proxy.apps.internal/
https://gsa-tts-oros-fac-staging-egress-smtp-proxy.apps.internal/
https://gsa-tts-oros-fac-production-egress-smtp-proxy.apps.internal/
https://fac-av-staging.apps.internal/
https://fac-av-production.apps.internal/

2. FAC Pentest results
A total of 0 critical, 0 high, 1 medium and 2 low findings were discovered during the testing window.
FAC Pentest results indicate team can move forward with FAC LATO effort no critical/Highs were discovered.

3. FAC POST PenTest Task
Once each finding has been remediated, please utilize the GSA Penetration Test Remediation and Validation Request form to submit for validation.

https://drive.google.com/file/d/1bDyAPBQMpfQuBqt3NN0TwaEVEclkQbwm/view?usp=drive_link
4. FAC POST PenTest Additional tasks
- Scan results identified 3 findings that may be tracked within POAMS if can not be remediated
