### ISSUE TITLE
FAC - Bug: EINs might have dashes

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1396]
### Describe the bug

When entering an EIN, users might enter

```
##-#######
```

because that is how IRS officially presents them (?).

Our frontend should accept that or 

```
########
```

(That's 9 digits.)

But, pass to the backend a value that is nine digits.

### Steps to reproduce the bug

This is on the general info page.

### Expected Behavior

See above.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by danswick** [comment]
This is validated on the frontend and in the jsonschema.
