### ISSUE TITLE
FAC ATO Artifact Request: FAC Code Scan Results #1

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#1397]
ISSO & Assessment team will need new FAC code scan results. The last submission was May 31,2023
Generate from OWASP Bandit

old scan results: https://docs.google.com/document/d/1RYcRMLmOoR3JejMZhxEi-_rJTm6DhBqT/edit?usp=drive_link

Scan results will be uploaded:
https://drive.google.com/drive/folders/1Zj92Fz2ux-y0zb3TGRKq47aVLM200eqK
 @JeanMarie-TTS  @asteel-gsa @mogul 
```

**Comment by mogul** [comment]
Who should own this?

**Comment by ChrisB-16** [comment]
@JeanMarie-TTS @mogul @asteel-gsa , the expected FAC LATO artifact due date is 7/20/23, Do we have any status updates for *providing Trivy Container,  Zap Web App  and compliance Scan Results?

**Comment by asteel-gsa** [comment]
@ChrisB-16 
Trivy scans are located [here](https://github.com/GSA-TTS/FAC/actions/runs/5590270224/jobs/10219773252#step:5:28) [here](https://github.com/GSA-TTS/FAC/actions/runs/5590270224/jobs/10219773385#step:5:34) and [here](https://github.com/GSA-TTS/FAC/security/code-scanning)

Zap scan is [here](https://github.com/GSA-TTS/FAC/actions/runs/5587846567/jobs/10214469947#step:4:76)

**Comment by ChrisB-16** [comment]
@asteel-gsa  Thanks I will forward back to ISSO

**Comment by ChrisB-16** [comment]
@mogul @asteel-gsa @JeanMarie-TTS , quick FAC LATO update as of 7/26 the ISSO just notified me the FAC vulnerability scans should be exported in CSV format. I wanted to ask status of this request in attempts to close out assessment Artifact Request List? Thanks

**Comment by mogul** [comment]
You have access to [the Trivy scans I exported into Google Sheets](https://docs.google.com/spreadsheets/d/16WqEu8fDh0aic-VBvWXBKB7gAfJ726loclBPZyGnNeE/edit?usp=sharing). We'll work on exporting the ZAP scans.

**Comment by mogul** [comment]
@ChrisB-16: It'll take some work to export ZAP results to CSV, since it only exports to XML and JSON natively. GSA IS does their own ZAP scanning and reports to us; do they actually need our ZAP scan results in CSV too, or are we done here?

**Comment by mogul** [comment]
>  Do we still need to export to csv or are those good and we can close this?

☝ @ChrisB-16 _ping_?

**Comment by mogul** [comment]
Chris reports that these are no longer listed as missing artifacts, so we believe what we submitted was sufficient.
