### ISSUE TITLE
Epic: Email notifications

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1401]
## Description

[//]: # ( A plain language description of the epic. Who, what, why. )

**Who**: Auditors, auditees
**What**: Users should get notifications at key points in the workflow.
**Why**: It helps them coordinate their submission and have confidence that the system is performing as expected.

```[tasklist]
### Stories
- [ ] #335
- [ ] https://github.com/GSA-TTS/FAC/issues/572
- [ ] Add support email address to error messages
```

**Comment by danswick** [comment]
Collecting references to some prior tickets here:

* https://github.com/GSA-TTS/FAC/issues/335
* https://github.com/GSA-TTS/FAC/issues/319
* https://github.com/GSA-TTS/FAC/issues/386
