### ISSUE TITLE
General table has ETL from collection to dissemination

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1415]

**Comment by jadudm** [comment]
Closed via #1384.

**Comment by pluribus-tony** [comment]
Some revisions to the general table need to be made.

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1507

**Comment by JeanMarie-TTS** [comment]
@pluribus-tony  
For G-FAC ETL, we only need to have date fields corresponding to the transitions we support. Use `sac.get_transition_date(stats)` where status is as defined in audit/models.py
        READY_FOR_CERTIFICATION = "ready_for_certification"
        AUDITOR_CERTIFIED = "auditor_certified"
        AUDITEE_CERTIFIED = "auditee_certified"
        CERTIFIED = "certified"
        SUBMITTED = "submitted"
In addition, initial_date_received = sac.date_created 

We can remove the other dates for now and add them as required when we implement ETL for historical data.

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1536

**Comment by pluribus-tony** [comment]
https://github.com/GSA-TTS/FAC/pull/1590
