### ISSUE TITLE
FAC - Bug: Consolidate Lookup and Validation Lists

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#1435]
### Describe the bug

Currently, there are duplicate instances of lookup lists and validation lists in the application. For example, there are separate instances of the list of cluster names in two different locations: [schemas>source>base>Base.libsonnet](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/base/Base.libsonnet#L386) and [schemas>source>data>cluster-names-20230626.csv](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/data/cluster-names-20230626.csv). This duplication of lists can lead to errors and inconsistencies. The purpose of this ticket is to consolidate all the lists (including the list of agencies, the list of federal programs, the list of cluster names, and others) so that each specific list has only one instance across the application.

### Steps to reproduce the bug

1. Open the code in github.
2. Navigate to the locations provided in the description sections.
3. Observe that there are multiple instances of the same list available.
4. Attempt to use different instances of the same list for lookup or validation.
5. Note the inconsistencies or errors that may occur due to the multiple sources of the lists.

### Expected Behavior

When filling out the xlsx sheets or performing any operations that require selecting items from lists, there should be only one instance of each list across the application. This single instance should serve as the authoritative source for data lookup and validation.

### Additional context

Impact:
This bug affects the data lookup and validation functionality of the application. It is important to consolidate the lists to ensure consistency and eliminate potential errors.

Workaround:
Currently, there is no workaround available for this issue. It is necessary to consolidate the lists to resolve the problem.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
I think the Makefile generates the sonnet from the CSV. In that regard, I think we only have one document. We just don't read the CSV directly into the Jsonnet specs.

Check me if I'm wrong, though...

https://github.com/GSA-TTS/FAC/blob/722e8cc3a3535d024babfa4e54e1505fa3b315cf/backend/schemas/Makefile#L28C13-L28C13

?

**Comment by jadudm** [comment]
There is a longer-term question of how we will be storing this data as a project (will it be a table in our DB? A file in this GH?), and therefore, it is not clear that the makefile process/script of CSV->JSON will be needed. We might, for example, just maintain a JSON or Jsonnet document.

But, that's a "future" question. For now, this is a recent, authoritative dump of those names/fields from Census, and it is transformed programmatically from CSV to JSON, which lets us include it in our specs. 

Thoughts?

**Comment by sambodeme** [comment]
> I think the Makefile generates the sonnet from the CSV. In that regard, I think we only have one document. We just don't read the CSV directly into the Jsonnet specs.
> 
> Check me if I'm wrong, though...
> 
> https://github.com/GSA-TTS/FAC/blob/722e8cc3a3535d024babfa4e54e1505fa3b315cf/backend/schemas/Makefile#L28C13-L28C13
> 
> ?
@jadudm I might be missing something here, but for instance, the cluster names used in the JSON schema validation for federal awards are not derived from the CSV file. Based on the code, the cluster names generated from the CSV file are used in the XLSX templates, but the schema validation have it owns cluster name source which I mentioned in the description of the ticket.

**Comment by jadudm** [comment]
Per this and Slack conversation: @sambodeme is correct; I was confusing myself by not looking carefully enough.

We'll want to use the CSVs as "source of truth" and fix anywhere that we aren't using them.
