### ISSUE TITLE
FAC - Bug: Icons on file upload

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1461]
### Describe the bug

Images/busy indicator don't behave correctly on form upload.

### Steps to reproduce the bug

When someone first uploads a file on the Findings Text page, a little progress wheel appears over the (broken) icon to the left of the file name. Once the file has been validated, the wheel remains on screen and keeps turning (ie looks like it's still thinking.) I tried to recreate it but I think it only happens for the first upload, not a replacement

### Expected Behavior

The busy indicator should stop when it should stop. 

The image shouldn't be broken.

### Screenshots

![Screenshot 2023-07-10 at 4 14 38 PM](https://github.com/GSA-TTS/FAC/assets/38290/68ec0b37-6a82-4102-ade6-05455a5b5f23)

### Additional context

https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1689020296236719

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
It might be a dupe. Feel free to close one of them as you see fit (close as not planned).

**Comment by danswick** [comment]
Closing here in favor of #1290.
