### ISSUE TITLE
FAC - Bug: Warn if a UEI has already been used to start an audit?

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1467]
### Describe the bug

It is possible that more than one audit might be submitted for a given UEI. However, users expect to be warned that another submission is already underway for a given UEI if that is the case. 

Unfortunately, this might leak information.

This ticket is a placeholder for discussion and conversation about what we will do:

1. For Launch.
2. Post-launch/MVP.

The solution at launch might be to document that not special checks are in place. To be discussed.

### Steps to reproduce the bug

No particular steps.

### Expected Behavior

Census had a process, but it may have been manual. Also, this involves subyears.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by danswick** [comment]
After discussing with @jadudm, all of these questions will be answered as part of the resubmission work planned in #2301.
