### ISSUE TITLE
Add coversheet to all workbooks

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1473]
```[tasklist]
### Workbooks
- [x] Federal awards
- [x] Audit findings
- [x] Corrective action plan
- [x] Audit findings text
- [x] Secondary auditors
- [x] Notes to SEFA
- [x] Additional UEIs
```

The coversheet is the first tab the user sees. It should include 

1. Auditee UEI
2. Any auto-computed fields that are single cells (varies by workbook)
3. `version`

The sheet should be called "Coversheet." 

It might have a look roughly like:

| Federal Audit Clearinghouse | fac.gov | Version X.Y.Z |
|---|---|---|
| Auditee UEI: | ... | |
| Total Expenditures: | 123,456 | | 

where perhaps the header row is blue. 

However, these could also all be cells with no header row.

| | |
|---|---|
| Federal Audit Clearinghouse | fac.gov | 
| Version | 1.2.3 |
| Auditee UEI | ... |
| Total Expenditures | ... |

Simple is good. 

We do not *yet* know how we will version the workbooks. this work should set all of them to `1.0.0`. 

Note a leading `v` is not technically valid semver.

**Comment by danswick** [comment]
Testing this out in [a branch](https://github.com/GSA-TTS/FAC/tree/ds-auditors-coversheet) and thinking it might be worth adding a new cells/range type to handle both text-only content (title, website, version) and vertically-oriented input cells. We could merge these heading cells, but 1) I think merged cells might be more trouble than they're worth and 2) the resulting sheet could still be awkward and confusing. Open to other ideas using the current parse/render workflow for generating workbooks. 

<img width="541" alt="image" src="https://github.com/GSA-TTS/FAC/assets/2365503/ef139e29-f67b-4ce2-86d2-840f58da7653">

**Comment by jadudm** [comment]
1. Agree we want to avoid merges at this point.
2. The option-two visualization above might keep things simpler with side-by-sides. :shrug:

Certainly, for the data inputs, we already have the `single_cell`, which might make things easier?
