### ISSUE TITLE
Permissive dissemination tables

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1509]
In migrating from Census, we inherited a lot of things... including types/limits on fields.

For example, we have fields that claim to be `varchar(2)` (modulo Oracle/Postgres syntax/notation). Reading the Postgres documentation:

https://www.postgresql.org/docs/current/datatype-character.html

> If one explicitly casts a value to character varying(n) or character(n), then an over-length value will be truncated to n characters without raising an error. (This too is required by the SQL standard.)

This sounds bad. Our pipeline does not (yet) check intake lengths. We have no validations/errors on the spreadsheets that limit the character length.

We need to fix a few things before we call it an MVP.

```[tasklist]
### Stories
- [ ] https://github.com/GSA-TTS/FAC/issues/1510
- [ ] https://github.com/GSA-TTS/FAC/issues/1511
```

**Comment by danswick** [comment]
Is this tracking ticket still relevant, @jadudm?

**Comment by jadudm** [comment]
We did the second, but haven't yet done the first. 

If we're going to do the first item, we should put it in the Backlog, and decide if we're going to pay that debt soon. 

If not, we should archive this.

I'm going to go ahead and do the close and archive.

**Comment by jadudm** [comment]
We'll revisit as needed in the future. Pulling this from the board for now.
