### ISSUE TITLE
Override `save` methods to check certification state

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1516]
We need to check in multiple models:

```[tasklist]
### Override save for...
- [x] `SingleAuditChecklist`
- [x] `ExcelFile`
- [x] `SingleAuditReportFile`
```

This is per #1495; we don't want users uploading once we have locked for submission.

**Note**: We may need to introspect a bit here, as `save` is used for updating the submission status. So, we do need to still be able to update the submission status once we override/lock save...

**Comment by tadhg-ohiggins** [comment]
We don't technically need to do `ExcelFile` separately, since the data ends up getting saved to `SingleAuditChecklist` and the exception is raised there, but I'll leave this open as a stand-in for making the error for the upload at least vaguely useful.

**Comment by timoballard** [comment]
@tadhg-ohiggins @jadudm - I believe that now that #1589 is merged, the `ExcelFile` task, and thus this ticket as a whole is done. Yes?

**Comment by tadhg-ohiggins** [comment]
I can't verify that it works correctly on `dev` because of the issue described [here](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1690867866348659). I’d like to fix that and verify it on `dev` before closing this.

**Comment by tadhg-ohiggins** [comment]
![image](https://github.com/GSA-TTS/FAC/assets/2626258/ca51b1d0-317c-48f4-9df4-78df133a6fe2)
