### ISSUE TITLE
Improve test suite robustness with slow-starting services

### ISSUE THREAD

**Issue by neilmb** [GSA-TTS/FAC#1523]
# Description

Some of our new tests depend on the full stack of services in our Docker Compose setup in order to run successfully. For example, `audit.test_commands:TestLoadFixturesCommand` actually uploads Excel files into our application and so it needs `minio` and `clamav-rest` to be up and running. But those two services can take time to be completely available after their containers are started. If the unit tests are run before the services are fully running, tests can fail or even hang indefinitely.

# Resolution

Our current best recommendation for local development is to make sure that `docker compose up` is run in a separate shell and that the logs there indicate that `clamd` is actually up and running. We should

- [ ] Document the recommendation around `docker compose up` for local devs

For the future, we could 

- [ ] consider using tools like [wait-for-it](https://github.com/vishnubob/wait-for-it) or [dockerize](https://github.com/jwilder/dockerize) to wait for Clamd and Minio to be up and responsive before allowing the `backend-web` container to move on and run itself.

**Comment by jadudm** [comment]
We added some explicit sequencing in the docker stack. This addressed some/most of this.
