### ISSUE TITLE
Is there any timeline for the urls to the pdf reports to be integrated into the api?

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1528]
Thank you for the very helpful documentation!  Is there any timeline for the urls to the pdf reports to be integrated into the api?

_Originally posted by @wcsherb in https://github.com/GSA-TTS/FAC/discussions/1465#discussioncomment-6489111_

**Comment by JeanMarie-TTS** [comment]
@jadudm Can we have the spec for this reqt worked on and finalized? Here's my first take to get the ball rolling.:

1. Add a column in api_v1_0_0_beta.general view to include a URL - something like <fac-base-url>/pdf/<report_id> where fac-base-url will be something like https://fac-dev.app.cloud.gov/  
2. Create a django view in the search app to process the request when the above url is called.
3. The view should, for now, throw an error if the report_id is for a SAC where is_publc is not True.
4. If this is a valid request, the view should initiate a download of the pdf from S3. The location of the file should be available in the SAC. pdf_url field.

Questions:
1. In order that the URL not be easily guessable, should we create a difficult to guess identifier and store this in both dissemination_General and in audit_SAC? 
2. Should access to the pdf  be restricted to users who login through login.gov? Or should we restrict access only via api.data.gov? What's the simplest solution that does not create DOS concerns?

**Comment by jadudm** [comment]
PDFs are arguably post collection, so we can story this out, but not today/possibly not in the next two weeks.

I think we can assume that all PDF urls will be of the form

`app.fac.gov/pdf/<report-id>`

and that everything will go through the app. The app will dynamically do one of the following two things:

1. Open the file from the private S3 bucket, and stream the data to the user, or 
2. Set a timeout on the S3 object and provide a time-limited S3 URL

https://stackoverflow.com/questions/2636783/django-as-s3-proxy

I'm concerned about #2. It means that someone with privileges could request a file, share it with someone else, and then download it. However, we could set the time window to a few seconds. 

#1, though, has other issues. We are then a streaming data app, and as people hammer the PDFs, we could end up with a lot of long-lived sockets open.

Once we have parts of the app outside of the login.gov boundary, anonymous access (non-authenticated) to public PDFs should be possible. However, we will always have to work our way through the app.

All of the questions/concerns you have, and others, are  why I want to focus on getting collection done before we dive into this. When I feel we're in a position to devote time to working through this story, we will. Right now, my concern is that we're too deep in to getting ready for beta testing to tackle this.

**Comment by jadudm** [comment]
All public PDFs are available at the URL

https://app.fac.gov/dissemination/report/pdf/[report-id]

This needs/wants to be documented elsewhere, but closing this ticket.
