### ISSUE TITLE
Use SAM Entity Data to Clean Entity Types in FAC's General Info

### ISSUE THREAD

**Issue by joffemd** [GSA-TTS/FAC#153]
When users download GENyy.zip or Summary Reports associated with individual audits, one of the output fields they see is "Type of Entity".  Unfortunately, the data in this field is often incorrect.  

For example, in 2021, Gem County (Idaho) has an entity type of 888 (Unknown), but it should be 100 (County).  The Employer ID for this entity is 826000299.

But it is correctly classified in the SAM Entity Registration data set at https://sam.gov/data-services/Entity%20Registration/Public%20V2?privacy=Public. In this data set, "GEM, COUNTY OF" (UEI DKD8J6XYYZF1) has a Business Type Structure string of "12\~C7\~HQ" which means includes the code for County (C7).

So once Single Audit records are matched up against UEIs it should be possible to check and clean up the Type of Entity field.

**Comment by danswick** [comment]
We've heard from SAM.gov that this use case is likely not supported. We may want to reopen this issue and investigate more at a future date, but it's not on our roadmap right now.
