### ISSUE TITLE
Single Audit Database Download Formats

### ISSUE THREAD

**Issue by joffemd** [GSA-TTS/FAC#154]
On the existing FAC, when a user Downloads the Complete Single Audit Database at https://facdissem.census.gov/PublicDataDownloads.aspx, the downloaded files are pipe delimited.

This delimiter is not directly supported by Excel and so the files are somewhat more difficult to import than they could be.

I recommend supporting comma separated values (csv) and tab separated values (tsv) as alternatives.  I recognize that csv poses some challenges because grantee names may include commas.

**Comment by jadudm** [comment]
We've picked this up partially.

1. The API provides far more utility than raw downloads, including search and filtering tools. The API can also provide CSV natively, along with other formats.
2. We will revisit this post-MVP to see whether there will be any "bulk download" formats.

**Comment by joffemd** [comment]
Thank you!
