### ISSUE TITLE
The submission checklist is a source of truth.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1560]
```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [x] Product signoff
- [x] Content signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy Content on this one is done. You were going to clean up the final steps to turn them green, add the timestamp of who submitted when, etc.

**Comment by lauraherring** [comment]
@thebestsophist @jadudm @Carley-Sullivan Content and design are done, this is ready for your review. Page can be found [here in Figma](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=197-6148&mode=design&t=S2WsY76ymUneqU4t-4).

**Comment by thebestsophist** [comment]
looks great!

**Comment by lauraherring** [comment]
After talking with Carley, looks like this page needs some copy updates so I'm unchecking the content sign-off.

**Comment by James-Paul-Mason** [comment]
@lauraherring I provided some comments regarding passive voice, clarity, and correctness. Let me know what you think! Other than those items I commented upon, this looks good to go!

**Comment by lauraherring** [comment]
@Leighdiddy and I re-named some of the steps of the pre-screener questions (before workbooks) so I'm going to re-write the copy for the first two steps and she's going to add in a step to the checklist.

@James-Paul-Mason When I have this copy done, I'll ping you to take a look.

@jadudm We'll ping you as well when this is all ready.

**Comment by James-Paul-Mason** [comment]
@lauraherring The copy is looking very **tidy**! Just two additional comments/suggestions for the tricky text with Workbook 5.

**Comment by lauraherring** [comment]
Update: new checklist items need to be written and added. I'll ping @Leighdiddy when it's ready to be dropped into design.

**Comment by lauraherring** [comment]
@Leighdiddy I've written the new copy for the new checklist items and tagged you in Figma as well. Once those are added and the page length is adjusted to fit, I think this one will be good to go.

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/issues/1899 will close this.

**Comment by jperson1** [comment]
A new competitor enters the arena:

https://github.com/GSA-TTS/FAC/issues/1910

**Comment by jadudm** [comment]
I'm closing out the "source of truth" workstream. We have come well within 97%, and should now step back and decide what our process will be going forward. And, any remaining edits are that: refinements and edits to what is.
