### ISSUE TITLE
The general info form is a source of truth.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1561]
```[tasklist]
### Tasks
- [ ] #1728
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy Content is good on this one, it just needs the breadcrumbs removed.

**Comment by lauraherring** [comment]
@thebestsophist @jadudm @Carley-Sullivan Leigh and I are good on content and design on this [page](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1-20696&mode=design&t=S2WsY76ymUneqU4t-4), ready for review.

**Comment by Carley-Sullivan** [comment]
I believe this questions are out of order and not matching PRA.  First question should be: Fiscal Period End dates, Type of Uniform Guidance Audit, Audit Period Covered, Auditee Identification Numbers, Auditee Information, Auditor Information (I don't see a place to indicate secondary auditors were used, either).

**Comment by jadudm** [comment]
Assigning back to @Leighdiddy and @lauraherring based on comments from @Carley-Sullivan .

**Comment by lauraherring** [comment]
@jadudm Surprise! We're changing the title of this page to be "Audit info".

**Comment by lauraherring** [comment]
@Leighdiddy this is back with you, see comment in Figma

**Comment by jadudm** [comment]
See also https://github.com/GSA-TTS/FAC/issues/1728 from @LeoFotovich 's walkthrough.
