### ISSUE TITLE
The audit info form is a source of truth.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1562]
```[tasklist]
### Tasks
- [ ] #1678
- [x] Design complete
- [x] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
```

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/issues/1678

**Comment by lauraherring** [comment]
I discussed the content question with Carley and re-wrote one of the questions. 

@jadudm Is Carley looking into 1678 to see if those fields are required to add? Or what's happening with that ticket?

**Comment by lauraherring** [comment]
@Leighdiddy is making slight alignment changes, content is good.

@jadudm we still have the outstanding dev question on this page re. the agency selector, see Figma for specifics
