### ISSUE TITLE
The PDF upload is a source of truth

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1565]
```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
- [x] Content signoff
```

**Comment by lauraherring** [comment]
@Carley-Sullivan [This checklist](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1-22279&mode=design&t=4c3NDSdHM7fkhv7s-4) calls out removing all PII. Should it also include removing all BII?

**Comment by James-Paul-Mason** [comment]
@lauraherring I added a few comments here. Overall, this is looking strong and clear. I had similar concerns about the confirmation pop-up (buttons and text).

**Comment by lauraherring** [comment]
@Leighdiddy is going to shift all content to the left a bit.
