### ISSUE TITLE
Pre-certification validation is a source of truth

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1566]
```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , @Carley-Sullivan and @james mason to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy I'm good with the content on [this page](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1-22391&mode=design&t=4c3NDSdHM7fkhv7s-4). Once you're good with design we can pass it along to the others.

**Comment by lauraherring** [comment]
@jadudm @Carley-Sullivan @thebestsophist @James-Paul-Mason @Leighdiddy and I are done with this page, passing to you all for review.
