### ISSUE TITLE
Auditor certification is a source of truth

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1567]
```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
- [x] Content signoff
```

**Comment by lauraherring** [comment]
@Leighdiddy Based on feedback from Carley, Matt J, et al in Figma, I've taken a crack at combining the Auditor Certification screens into one screen. Would love to chat/cowork on this with you next week.

**Comment by lauraherring** [comment]
@jadudm @thebestsophist @Carley-Sullivan @James-Paul-Mason 

@Leighdiddy and I have finished with the certification mock. We prefer the combined version but understand the devs may not be able to re-combine the pages at this point, we're good with the content and design of both options.

**Comment by James-Paul-Mason** [comment]
Content and design look great. I also prefer the combined version, but if that's not possible, the two-step option is totally fine.
