### ISSUE TITLE
Implement API authentication and rate limiting

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#157]
**Background**: API rate limiting is a best practice in APIs. 

**Requirements**:
* Use api.data.gov as our framework
* Provide:  classes of API users: government users with high limits and public users with more modest limits. 

**Open questions**:
* How will our authentication scheme relate to rate limiting?
* What is the onboarding to using a new key? 
* Where do we store regular API user versus power user? Flag on user?

**Comment by geekygirlsarah** [comment]
After discussing with @Jkrzy and @NicholasKramer, we decided this might still be a valid issue but not really feasible to work on at this time, so I'm unassigning and moving back to the backlog for the future.

**Comment by danswick** [comment]
This is lightly documented on the developers page https://www.fac.gov/developers/.
