### ISSUE TITLE
Map data available from sam.gov API to Auditee Info mocks

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#160]
**Background**
For #126 we are validating UEIs and returning data from the sam.gov API. 

Engineering will collaborate here with content and design to understand and document the endpoints/data available from SAM.gov and how they can be best leveraged for the `Auditee Info` step towards creating a SIngleAuditChecklist.

References: [SAM.gov API documentation](https://open.gsa.gov/api/entity-api/)

**We'll know we're done when...**
- [x] We've mapped attributes available from SAM.gov to the current mock-ups for for Auditee info step.
- [x] Given the data we need, we know if we'll to use the Public, FOUO, or Sensitive API endpoint.

**Comment by Jkrzy** [comment]
Picking this up and translating the SAM.gov docs, data dictionary, and API responses to a google sheet for us to collaborate with

**Comment by Jkrzy** [comment]
Proposal for mapping after reviewing data dictionary and FIGMA mock-up. 

I only see two fields we need immediately.

SAM.gov field | FAC field
---| ---
legalBusinessName| Auditee name
ueiSAM| UEI


Other fields considered:

**Field Name:** Fiscal Year End Close Date
**Definition:** The date the entity's accounting period closes. When entering the information on the
web site, you must enter as MM/DD.

My understanding of the `Auditee fiscal period end date for this submission` field is that it's a user-provided data point describing the date range which is covered by the audit they are submitted.

**Comment by Jkrzy** [comment]
We'll need to use the `FOUO` API endpoint to support validation of entities which have opted out of inclusion in the public dataset.

**Field Name:** No Public Display Flag
**Definition:** The field indicates whether an entity has chosen to opt-out of their registration being
displayed in SAM public search results. Opting out may result in a reduction in Federal
Government business opportunities, and subcontractors who choose this option will not be visible
to prime contractors. Entities that have opted out will be removed only from the SAM public
search but will still be visible to users with For Official Use Only (FOUO) data access and will be
provided in accordance with Freedom of Information Act (FOIA) requests.

**Comment by Jkrzy** [comment]
@NicholasKramer, @geekygirlsarah, does this look right to you given what you've seen implementing #148?

@sreuber, does only pulling `Auditee Legal Name` from SAM feel right to you given the current mock-ups and research?

**Comment by sreuber** [comment]
> 

Yes, auditee legal name should be sufficient.

**Comment by Jkrzy** [comment]
Thanks @sreuber! We'll use this as input for #148
