### ISSUE TITLE
General form should handle international addresses for auditors

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1603]
## Description

SF-SAC includes a provision for listing international primary auditors (`ELECAUDITHEADER.CPAFOREIGN`), which we haven't yet implemented in our intake form or data model. Note that there is no provision for international addresses for secondary auditors.

Here is a screenshot of the relevant section from the IDES manual: 
<img width="667" alt="screenshot of IDES manual section describing how to submit address information for international auditors" src="https://github.com/GSA-TTS/FAC/assets/2365503/8abeb236-ed4e-4b58-b837-3941234c0700">

## Next steps

In IDES, this functionality is built on a conditional UI. There are two UI's: one for US-based auditors (this is what we have now and is the default in IDES) and one for non-US-based auditors. UIs are conditionally shown based on which dropdown item a user selects. 

A rough outline of what implementation might look like:

- [ ] Update Figma designs to add a conditional "international audit firm/organization address" field. As far as I can tell, this should be a large, single text box, not a multi-field address form with fine-grained field validation. 
- [ ] Change the General form's auditor "country" field to a dropdown with two options: `US` and `non-US`. This is in the current Figma designs, but the web form is a text box right now.
- [ ] Update data model and validations to treat auditor country as a dropdown
- [ ] Update data model and validations to include an optional international address field (assuming this will just be a large string)
- [ ] Handle conditional country field in web form: if `US` is selected, the remaining address fields are required (this is the current state). If `non-US` is selected, only the "international address" text field is required.
- [ ] Handle conditional country field in intake validation: if `US`, the default address fields are required and validated as they are today. If `non-US`,  default address fields should be empty and there should be a long string for "international address". 
- [ ] Update ETL to handle the new international address field. 

cc @Leighdiddy for possible figma things, @jperson1 for frontend work, @Carley-Sullivan for truthiness, and @JeanMarie-TTS for eventual ETL connection.

**Comment by timoballard** [comment]
Some initial work on this here https://github.com/GSA-TTS/FAC/pull/1646

**Comment by JeanMarie-TTS** [comment]
PR ready for review
