### ISSUE TITLE
Add history tables for C-FAC columns

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1619]
```[tasklist]
### Tasks
- [ ] https://github.com/GSA-TTS/FAC/issues/1620
```

**Comment by JeanMarie-TTS** [comment]
Continuation of #1460 
Let's take another look as there have been changes to the dissemination model.
Let us also create history tables in the dissemination model to disseminate field that are not in G-FAC but did exist in C-FAC from AY16 onwards. We need to create views corresponding to these history tables as well.

We can start with Hist_General, which is required, and add tasks for other tables if required.

**Comment by gsa-suk** [comment]
For AY16 through AY22, the following are the extra fields that need to be added on top of GFAC dissemination:
DBKEY
STREET2
CPASTREET2
CPAFAX in Multiple CPAS info

**Comment by JeanMarie-TTS** [comment]
Added the above.
Added duns, add_duns and add_ein as well.
