### ISSUE TITLE
Remove manage access button until implemented

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1636]
This will be picked up in #1446. For now, we need to remove the button, as it will confuse users/break.

**Comment by danswick** [comment]
![Image](https://github.com/GSA-TTS/FAC/assets/2365503/9c204d3d-e4aa-4b2a-86e7-a9057a70f09e)

Does this exist anywhere other than in the above? We should also remove the "Account tools" link.

**Comment by jadudm** [comment]
Might only be there. And, yes, the "account tools" should also go for now.
