### ISSUE TITLE
Configure New Relic High Security Mode

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#1649]
see https://github.com/GSA-TTS/FAC/pull/1077#issuecomment-1534713161

**Comment by danswick** [comment]
@timoballard will follow up and report out next steps here.

**Comment by asteel-gsa** [comment]
`export NEW_RELIC_HIGH_SECURITY=true` in [setup_cgov_env.sh](https://github.com/GSA-TTS/FAC/blob/main/backend/tools/setup_cgov_env.sh)

Reference: https://docs.newrelic.com/docs/apm/agents/python-agent/configuration/python-agent-configuration/#high_security

**Comment by asteel-gsa** [comment]
Based on discussions in slack, this is not an ATO requirement, and, with the functionality of NR High Security, it seems unnecessary for our system, however, we can easily enable it if we deem it necessary. As of this time, we are leaning towards this being unnecessary.

**Comment by danswick** [comment]
Agreed. Let's close this as unplanned. If we need to come to it later, the record is still here.
