### ISSUE TITLE
Design failure state if SAM.gov API is unreachable

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#165]
**Background**: There may be cases where SAM.gov's API fails and we are unable to match UEI's. If we're unable to reach SAM.gov, what do we tell the user? 

**We'll know we're done when:** 

- [x] We have a design and copy for this failure state documented somewhere and linked in #126 and/or #180

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Is any other refinement needed for this task? Seems like a pretty narrow one.

**Comment by petermarks-gsa** [comment]
Flagging this as needs refinement as we need to know what the user's options are here. @MelissaBraxton am I correct to assume that the user cannot move forward in the flow with an unverified UEI?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Thanks for this explanation. 

@brentryanjohnson Please let us know if you need further information.

**Comment by brentryanjohnson** [comment]
Does the UEI have a specific, predictable format? Is it alphanumeric? Numeric only? A specific number of characters?

Ideally, I'd like to write conditional copy based on error type (e.g., format vs. api).

**Comment by MelissaBraxton** [comment]
The Unique Entity ID is a 12-character, alphanumeric value that adheres to the following rules:
- The letters “O” and “I” are not used to avoid confusion with zero and one.
- The first character is not zero to avoid cutting off digits that can occur during data imports, for example, when importing data into spreadsheet programs.
- Nine-digit sequences are not used in the identifier to avoid collision with the nine-digit DUNS Number or Taxpayer Identification Number (TIN).

**Comment by brentryanjohnson** [comment]
Will we be able to detect on user interaction if the API isn't working?

**Comment by petermarks-gsa** [comment]
@brentryanjohnson Yes, ye'll know from the response code or lack of the response if the API is unreachable.

**Comment by brentryanjohnson** [comment]
I've written some draft error copy. I tried to keep the messages as simple as possible; we can add more detail later if needed. I don't know if it's realistic to use conditionals to generate different copy, but ideally we'd help the user narrow down the source of the error as much as we can. Let me know your thoughts!

## If format error:
We don’t recognize the UEI you entered. The UEI should be 12 characters and a combination of letters and numbers.

## If API is working, but UEI isn’t recognized:
We don’t recognize this UEI. You can continue for now, but you’ll need to come back to this. [Find out how to get a UEI](#).

## If API isn’t working:
We can’t connect to SAM.gov to confirm your UEI. We’re sorry for the inconvenience, and we’re working on it.

**Comment by petermarks-gsa** [comment]
@brentryanjohnson Sounds like this is ready for review? Suggesting @MelissaBraxton or @austinhernandez as a reviewer. Moving this to "ready for review" and removing "refinement needed". CC @jhansen-flexion

**Comment by MelissaBraxton** [comment]
LGTM, with one small tweak to this one (revision in bold): 

_## If API isn’t working:
We can’t connect to SAM.gov to confirm your UEI. We're sorry for the delay. You can continue, but we'll need to confirm your UEI before **your audit can be certified.**_

I know I've made it passive voice, but the FAC isn't the one certifying the audit--it's certifying auditee and auditor certifying officials who do that.

@heymatthenry  - I think the next step is for you to pick this up and implement it now?
