### ISSUE TITLE
Confirm with SAM.gov folks that the data we auto-populate are public data

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#167]
**We'll know we're done when:** 
We understand what, if any, special handling needs to take place for Entities which have opted out of public display.

Tasks
- [x]  Connect with someone at SAM.gov to understand this.

**Comment by Jkrzy** [comment]
From #160 we know we're only bringing in an Auditee's Legal name which is available via the public API. 

I propose that we use this issue to better understand entities what, if any, special handling needs to take place for Entities which have opted out of public display.

 
<img width="784" alt="Screen Shot 2022-04-29 at 9 48 30 AM" src="https://user-images.githubusercontent.com/3485564/165957614-b710fa52-e2d2-4cc9-82ee-cd6e0dd61a41.png">

**Comment by petermarks-gsa** [comment]
@jadudm A next step for this that we've discussed is finding a contact at SAM.gov to talk to about this issue. Do you have one?

**Comment by petermarks-gsa** [comment]
I have asked the following to meredith.whitehead@gsa.gov (Mimi):

We're pulling over entity information to show to the user when they give us an EIN. We're wondering what, if any, special handling needs to take place for Entities which have opted out of public display (noPublicDisplayFlag is set). Are we allowed to show information for an entity flagged tayt way? Do we need to provide some sort of disclaimer?

**Comment by petermarks-gsa** [comment]
@Jkrzy Does the below response from Mimi answer your question? 

Good afternoon, Peter. Thanks for reaching out. Let me share a few things which might help. The Taxpayer Identification Number (TIN) can be either an Employer Identification Number (EIN) or a Social Security Number (SSN) in SAM.gov depending on the entity type (e.g. sole proprietors and single member LLCs taxed as disregarded entities can both use their SSN as their TIN if they choose not to get an EIN). TINs are discretely identified as one of those two TIN Types (EIN or SSN). TINs in SAM.gov are considered sensitive financial information (therefore Controlled Unclassified Information) because the entity registration is a pre-award condition. We do not display or make an entity's TIN available to the public. Entity registrations are unique based on legal business name and physical location. You can't just pull a SAM.gov entity registration data based on the EIN. Multiple entities may share the same EIN, i.e. different locations of a single organization all directly doing business with the government would be individually registered, with different Unique Entity IDs, but may share the same EIN as their TIN. Even if you are only displaying data on entities that received a federal award subject to single audit requirements, you would likely need to query based on Unique Entity ID and TIN (must be EIN) combination. **The "no public display flag" means the entity did not authorize their non-sensitive registration information (e.g. legal business name and physical address) to be returned in a SAM.gov public search. It applies to searching at SAM.gov only. Again, SAM.gov has entity registration records on hundreds of thousands of entities that never received a federal award. If the entity has a federal award with terms and conditions which require certain data to be made public, the awardee must adhere to those terms.**

**Comment by Jkrzy** [comment]
Thanks @petermarks-gsa!  Since we learned that the `noPublicDisplay` flag applies **only** to searching at SAM.gov, we don't need any special handling here.
