### ISSUE TITLE
Import fixture data from Django app into jsonnet processing pipeline (or vice-versa)

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1673]
It would be helpful to import some fixture data or other constants from the Django app into the jsonnet processing pipeline so we can be DRYer. Jsonnet cannot import Python code directly. Thus far the workaround has been to pre-process data (usually CSV) into JSON as a pre-build step, but that's not as straightforward for Python code that isn't designed to be standalone modules. 

We might approach this problem in the same way we have so far: pre-processing and munging before building out schemas. Though it might be better to go the other direction: refactor certain constants as part of our schemas and import them into the Django app instead.

This issue was prompted by my attempts to import excel fixtures into our jsonnet templates as part of https://github.com/GSA-TTS/FAC/issues/1472. 

# Security Considerations

None. This would likely just involve moving some of the schema generation code to another part of the codebase. 

# Definition of Done

We've established a process for importing fixture data (or other constants) into jsonnet and have removed any legacy copypasta currently being used as a workaround.

**Comment by jadudm** [comment]
As part of a spike (not yet ready for consideration), I was looking at how we generate workbooks.

https://github.com/jadudm/workbook-compiler

Part of this suggests being able to run arbitrary Python code at time of workbook generation.

It is possible to pass a Python file or module to another Python program, and then "hook into" that code at runtime. So, in theory, it is possible to have Jsonnet-driven workbook generation that includes a "[foreign function calls](https://en.wikipedia.org/wiki/Foreign_function_interface)" to let us "call out" from a Jsonnet spec into Python code while we are generating a workbook.

I'm moving this to `revisit`.  I'll... leave it open for now.

**Comment by jadudm** [comment]
I have spikes/branches floating for both new workbook generation approaches as well as how to import data into the app. Closing  this as not targeted enough/wanting for better storytelling.
