### ISSUE TITLE
Break apart the block in .profile

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1675]
https://github.com/GSA-TTS/FAC/blob/ad0667394861dd993c66ebb7c6b6b8ece3780a84/backend/.profile#L39-L54

We could do

1. API things
2. Migrate
3. More API things

separate from a block that does

1. Migrate
2. Collect static

**Comment by tadhg-ohiggins** [comment]
@jadudm I think we decided it's not worth it to do this right now; I can't remember the details.

**Comment by jadudm** [comment]
Bumping it back to backlog.

**Comment by jadudm** [comment]
Actually, I'm removing it. We can dig it up later if we want.
