### ISSUE TITLE
Draft FAC Account Management SOP

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#1676]
In order to meet FAC ATO A&A security control requirements
as a FAC system owner I should document the workflow steps needed to gain access to the FAC system, track all details within FAC Account Management SOP plan.

**Comment by ChrisB-16** [comment]
The latest FAC Account Management SOP is ready for review: 

https://drive.google.com/drive/u/0/folders/1IZN3KNjaDRlbblhdvxGjpnjyxhUgvwX_

Waiting for POST GSA LATO comments from assessment team to perform additional updates to FAC Account management SOP

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 , the link does not work. Can you check please?

**Comment by danswick** [comment]
@ChrisB-16 it looks like folks will need permission to access that document. Could you update?

**Comment by danswick** [comment]
Is this done? I'm able to find a [document](https://docs.google.com/document/d/13j5Dh-nvPF7S42OYxy0MwTdNxIwcFRui/edit) from August in our "Working Documents" directory, but it's not clear whether that is the final document. @ChrisB-16, can you confirm?

**Comment by danswick** [comment]
Sounds like this is done. During FAC assessment, the onboarding and offboarding processes were deemed acceptable and the Account Management SOP is no longer necessary.
