### ISSUE TITLE
[Revisit 08/16] SSPP Updates incorporating FAC Info Exchange Agreement-S3

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#1679]
- Update current FAC SSPP with FAC Info Exchange Agreement-AWS S3 bucket landing zone
- Gain new FAC diagram
- Submit FAC SSPP draft updates for review within internal FAC management team prior to ISSM
- 

```

**Comment by ChrisB-16** [comment]
Just gained access to FAC IEA doc-extracting AWS S3 technical  details
Identifying areas within FAC SSPP that will require implementation updates (System description, controls, diagram)

**Comment by ChrisB-16** [comment]
@jadudm @mogul @JeanMarie-TTS 

Please review the updated FAC SSPP within section 10.5 (overall Database Nature explanation-now includes Census data migration effort with FAC), and technical sections describing FAC database & S3 bucket usage such as  section 10.10.6, 10.10.7, 10.10.8

https://docs.google.com/document/d/1bcSJTHb92jt2ESfYj7R9g0-IA_1MXd-43Tq_nKcLPHE/edit#heading=h.q98pckusgt5g

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 , I nade a small change in 10.10.5. Both the app and postGREST can access postgreSQL, only the app can access S3.
I will have to defer to @mogul on 10.10.6, 10.10.7 and 10.10.8 as Idon't know which specific encryotion mechansms are used. If you got your facts from a cloud.gov document, we should be good.

**Comment by mogul** [comment]
Noting for posterity: The link above is to a _copy_ of the SSPP that incorporates info from the info exchange agreement. JM, Chris, and I just reviewed the content together and are fine with the changes in the sections noted. Once our assessment is complete, we should probably note these changes on the actual SSPP in "suggest" mode, so that they're ready to go for the next assessment.

**Comment by danswick** [comment]
@ChrisB-16 is this done? The sections referenced above (10.10.5/6/7/8) look complete.

**Comment by danswick** [comment]
This is done.
