### ISSUE TITLE
Uniform guidance

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1692]
```[tasklist]
### Initial review
- [x] Design complete
- [x] Content complete
- [ ] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [ ] SME signoff
- [x] Design lead signoff
- [ ] Product signoff
- [ ] Content signoff
```

**Comment by lauraherring** [comment]
[This page](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/ia-updates/resources/guidance/) can be reviewed on my branch of the static site. I got the link to the UG from Carley.

**Comment by lauraherring** [comment]
Note to self: remove "2023" per Carley's instructions.

**Comment by lauraherring** [comment]
Removed the year.

**Comment by Leighdiddy** [comment]
@jadudm looks good to me, passing off!
