### ISSUE TITLE
Create workbook instructions data file

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1697]
We want to create a set of pages or a single data dictionary for all of the instructions.

For example, we might have a folder called `workbook_instructions` in the site.

In that folder, there could be a folder for each workbook. E.g. `federal_awards`. 

In that folder, we could have one file per instruction, **named the same as the workbook named range**. E.g. `auditee_uei.md`

In the file, it might look like

```
---
field: auditee_uei
ug: 2CFR200...
---

Put the info in this field.
```

We would also add files like `blurb.md`, perhaps.

Then, we can create a template for all of the workbook pages, and just walk through this data, creating the instruction pages. The win is that we could conceivably use the same data within the workbooks, if we want to. Or, it will make linking to the instructions easier, because we can auto-generate anchors in the webpage, and when we have error content that wants to link to instructions, the app can easily point directly to the right thing in the instructions.

So: organizing the instructions *as data* is a huge potential win. And, it really isn't "more" work.

We need to design this a bit more; the above design may be no gooood. But, it demonstrates the idea.

**Comment by jadudm** [comment]
This is happening in the branch `lh/ia-updates`.

https://github.com/GSA-TTS/FAC-transition-site/tree/lh/ia-updates

**Comment by lauraherring** [comment]
Instructions for Workbooks 1-6 have been written and created. Workbook 7: Additional EINs will need one after that workbook is created.
