### ISSUE TITLE
Cross-validation: auditee UEI cross-check only checks top-level fields

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#1726]
Relates to #1382 

`auditee_ueis_match`, which ensures that the auditee UEI is the same in all workbooks currently only checks top level JSON fields in each SF-SAC section.

To reproduce: upload a Federal Awards workbook with a different `auditee_uei` from that provided in the `General Information` form, then perform cross-validation. The cross-validation will (erroneously) succeed because the `auditee_uei` field in the Federal Awards section is nested beneath a top-level `FederalAwards` field.

`auditee_ueis_match` should be updated to check for nested `auditee_uei` entries, which likely necessitates a recursive scan of each SF-SAC section.

**Comment by timoballard** [comment]
FYSA @jadudm

**Comment by tadhg-ohiggins** [comment]
We should fix this by adding the “the name of this workbook is this” keys [here](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/cross_validation/sac_validation_shape.py#L11-L16).

**Comment by tadhg-ohiggins** [comment]
Addressed in https://github.com/GSA-TTS/FAC/pull/1737
