### ISSUE TITLE
FAC - Feature: Single Audits From Before FY 2023

### ISSUE THREAD

**Issue by joffemd** [GSA-TTS/FAC#1794]
### Is your feature request related to a problem? Please describe.

I understand that sometime after fac.gov goes live, the legacy Census Bureau site will be taken down. At that time, I am concerned that researchers like myself will no longer have access to Single Audits for FY 2016-2022 and grants data going back over 20 years.

### Describe the solution you'd like

I hope that the files and data on the Census Bureau site can be ported over to the new fac.gov.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by jadudm** [comment]
We will be transitioning the UG audit data to GSA. We will soon be updating fac.gov, and details will appear there. I think the short answer is "yes, we are bringing data forward."
