### ISSUE TITLE
Lock for certification screen

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#1808]
```[tasklist]
### Tasks
- [x] Design complete
- [x] Content complete
- [x] Assign @thebestsophist , @jadudm , and @Carley-Sullivan to this ticket
```

### then...

```[tasklist]
### Signoffs
- [x] SME signoff
- [x] Design lead signoff
- [x] Product signoff
- [x] Content signoff
```

**Comment by Leighdiddy** [comment]
@lauraherring I'm sorry, I found an older ticket that I believe covers this? Let me know what you think: https://github.com/GSA-TTS/FAC/issues/1043

**Comment by lauraherring** [comment]
@jadudm @thebestsophist @Carley-Sullivan @James-Paul-Mason I've updated the copy on this new page and it's ready for review.

**Comment by Carley-Sullivan** [comment]
Reviewed this with @lauraherring and made minor updates.  Latest screens look good to me. Going to sign off.

**Comment by James-Paul-Mason** [comment]
I had one suggestion for the microcopy. Please let me know if it helps with clarity or if I'm missing something about how the "lock for certification" process works. My understanding is that the user locks the submission, and this step notifies/allows for final review/certification.

**Comment by jadudm** [comment]
I'm closing out the "source of truth" workstream. We have come well within 97%, and should now step back and decide what our process will be going forward. And, any remaining edits are that: refinements and edits to what is.
