### ISSUE TITLE
Create and populate one-time table for Cognizant agency assignment with 2019 data.

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#1813]
Breaking this out from its parent epic. See https://github.com/GSA-TTS/FAC/issues/1218 for more discussion and history.

This covers the implementation for one-time table creation and population of cognizant agency assignments with 2019 baseline data.

**Comment by JeanMarie-TTS** [comment]
This was completed, but needs to be revisited as there are cases where there are multiple submissions for an EIN in 2019.
@Carley-Sullivan recommends that we consider all submissions for an EIN and derive the cog_agency from the aggregates.
