### ISSUE TITLE
Make app template match static template

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1823]
For going to beta, it would be nice to now sync the static template back to the app template.

@lauraherring / @Leighdiddy may have input. Whomever picks this up should get their signoff.

**Comment by heymatthenry** [comment]
Are we going to remove the `sign in` card from the static site homepage or is that just going to link back to the app?

**Comment by lauraherring** [comment]
@heymatthenry That is going to link back to the app. We do need to remove the "Search older audit reports" box though. @Leighdiddy has mocked that up[ in Figma](https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-final?type=design&node-id=1-20234&mode=design&t=6yxiY5SPXEffCLSy-4).

**Comment by jadudm** [comment]
@heymatthenry , if this is done, free to close it! :ty:
