### ISSUE TITLE
Date validation needs to be significantly improved

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1840]
I'm not 100% sure what I meant when I wrote this.

Ah. 

1. Our schemas need to validate what format date(s) we're accepting. 
2. We need to make sure that is then acceptable as it goes back through the pipeline.

Right now, from front-end to validation, I think we have differences (the default format from Django views might not be what we were expecting in the validation...) Then, is that what we want as we head back to the DB?

I'm not proposing an answer, and I believe we have something in place. However, I would appreciate a set of eyes from one or two engineers pairing to make sure that whatever we're doing is consistent and sensible/obvious to people who follow behind. (Which might be us in 6 months.)

**Comment by jadudm** [comment]
The fields that tell us what these should be are also confusing -- everything needs to align.

**Comment by sambodeme** [comment]
https://www.iso.org/iso-8601-date-and-time-format.html
YYYY-MM-DD
