### ISSUE TITLE
Upload not working on `preview`: troubleshooting log

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#1865]
We haven't been able to determine why file uploads work on `dev` and not on `preview`. This tracks efforts to pin down whether or not it's a credentials problem, a proxy problem, an application problem, or other. Currently it's inconclusive as far as I can tell.

However, the credentials from `preview` appear to work when used locally, suggesting that it's not a credentials problem.

I can't seem to get past proxy problems when trying to run the AWS CLI on the `dev` instance, which is where I stopped for now.

Below are logs trying to work first against dev and then against preview.

### Verify that uploads on dev are working in the application.

12:05:50 Thursday 2023-08-17: verified.

### Verify that uploads on dev are working via Django shell.
    
```sh
cf target -s dev
cf ssh gsa-fac
/tmp/lifecycle/shell
source .profile
python manage.py shell
```

```python
import boto3
from django.conf import settings
session = boto3.session.Session(aws_access_key_id=settings.AWS_PRIVATE_ACCESS_KEY_ID, aws_secret_access_key=settings.AWS_PRIVATE_SECRET_ACCESS_KEY, region_name=settings.AWS_S3_PRIVATE_REGION_NAME)
s3 = session.resource("s3", endpoint_url=settings.AWS_S3_ENDPOINT_URL)  # No, this does not have _PRIVATE in the variable name.
bucketname = settings.AWS_PRIVATE_STORAGE_BUCKET_NAME
bucket = s3.Bucket(bucketname)
from os import environ  # Paranoia: just make sure we’re on dev
environ
environ["no_proxy"]

from audit.models import SingleAuditReportFile
from audit.models import SingleAuditChecklist
from django.core.files.base import File
somefile = open('/app/manage.py', "rb")
djangofile = File(file=somefile)
print(settings.AWS_PRIVATE_ACCESS_KEY_ID)  # Capture this for comparison with creds from local step below.
sac = SingleAuditChecklist.objects.all()[0]
sar = SingleAuditReportFile.objects.create(file=djangofile,filename='whatever',sac=sac,component_page_numbers=[1,1,1,1,1,1,1])
```

We expect that last command to complete with no error on dev.

12:20:38 Thursday 2023-08-17: verified.

### Verify that we can run `aws s3 ls` using our dev credentials locally

This script gets the credentials from the current target space and puts them in environment variables; we can then run the AWS CLI locally and should be able to see the results:

```sh
export S3CREDS="$(cf env gsa-fac|tail -n +3|sed -n '1,/VCAP_APPLICATION:/p'|sed '0d;$d'|sed -e 's/VCAP_SERVICES: //'|jq -r '.s3')"
export FACPRIVS3="$(echo $S3CREDS|jq '.[]|select(.name=="fac-private-s3")'|jq '.credentials')"
export AWS_ACCESS_KEY_ID="$(echo "$FACPRIVS3"|jq -r '.access_key_id')"
export AWS_SECRET_ACCESS_KEY="$(echo "$FACPRIVS3"|jq -r '.secret_access_key')"
export BUCKET_NAME="$(echo "$FACPRIVS3"|jq -r '.bucket')"
export URI="$(echo "$FACPRIVS3"|jq -r '.uri')"
export AWS_DEFAULT_REGION='us-gov-west-1'
```

We expect this to succeed:

```sh
cf target -s dev
source ../.local/shell/getenvcreds.sh  # The above grab-credentials-from-cf-env commands in a script
aws s3 ls "s3://${BUCKET_NAME}"
```

12:11:37 Thursday 2023-08-17: verified.

Output:

``` 
                           PRE census_public_csv/
                           PRE excel/
                           PRE singleauditreport/
```

### Verify that the access key is the same

```sh
echo "${AWS_ACCESS_KEY_ID}"
```

12:22:45 Thursday 2023-08-17: verified that this matches what we saw in the Django settings above.

### Get the AWS CLI onto the dev cloud.gov instance and run it

```sh
cd .local
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
cat ./awscliv2.zip | cf ssh gsa-fac -c "cat > ./awscliv2.zip"
cf ssh gsa-fac
/tmp/lifecycle/shell
cd ..
unzip awscliv2.zip
./aws/install -i ~/usr -b ~/bin
source .profile
export S3CREDS="$(echo $VCAP_SERVICES|jq -r '.s3')"
export FACPRIVS3="$(echo $S3CREDS|jq '.[]|select(.name=="fac-private-s3")'|jq '.credentials')"
export AWS_ACCESS_KEY_ID="$(echo "$FACPRIVS3"|jq -r '.access_key_id')"
export AWS_SECRET_ACCESS_KEY="$(echo "$FACPRIVS3"|jq -r '.secret_access_key')"
export BUCKET_NAME="$(echo "$FACPRIVS3"|jq -r '.bucket')"
export URI="$(echo "$FACPRIVS3"|jq -r '.uri')"
export AWS_DEFAULT_REGION='us-gov-west-1'
export NO_PROXY=$no_proxy
echo $NO_PROXY  # this shows that the same domain as the URI is using _is_ present in the NO_PROXY env var, which the AWS CLI should respect
~/bin/aws --version
~/bin/aws s3 ls
```

13:52:35 Thursday 2023-08-17: that last command is giving this error and kicking us out of the `/tmp/lifecycle/shell` shell:

``` 
Failed to connect to proxy URL: "https://***:***@gsa-tts-oros-fac-dev-egress-https-proxy.apps.internal:61443"
```

14:06:54 Thursday 2023-08-17: I don’t understand why this is happening, and am stopping this current effort here. Some prior efforts looking at what’s going on in the `preview` instance are below for comparison.

11:05 Monday 2023-09-11: It looks like the above error was due to the AWS CLI requiring _IP addresses_, not hostnames, in `no_proxy`.

### Verify that uploads on preview are failing in the application.

12:25:05 Thursday 2023-08-17: verified.

In the browser: `Bad Request (400)`

```sh
cf target -s preview
cf logs --recent gsa-fac
```

In the logs:

``` 
2023-08-17T12:24:56.98-0700 [APP/PROC/WEB/0] ERR Arguments: (ClientError('An error occurred (AccessDenied) when calling the PutObject operation: Access Denied'),)
```

### Verify that uploads on preview are failing via Django shell.

```sh
cf target -s preview
cf ssh gsa-fac
/tmp/lifecycle/shell
source .profile
python manage.py shell
```

```python
import boto3
from django.conf import settings
session = boto3.session.Session(aws_access_key_id=settings.AWS_PRIVATE_ACCESS_KEY_ID, aws_secret_access_key=settings.AWS_PRIVATE_SECRET_ACCESS_KEY, region_name=settings.AWS_S3_PRIVATE_REGION_NAME)
s3 = session.resource("s3", endpoint_url=settings.AWS_S3_ENDPOINT_URL)  # No, this does not have _PRIVATE in the variable name.
bucketname = settings.AWS_PRIVATE_STORAGE_BUCKET_NAME
bucket = s3.Bucket(bucketname)
from os import environ  # Paranoia: just make sure we’re on preview
environ
environ["no_proxy"]

from audit.models import SingleAuditReportFile
from audit.models import SingleAuditChecklist
from django.core.files.base import File
somefile = open('/app/manage.py', "rb")
djangofile = File(file=somefile)
print(settings.AWS_PRIVATE_ACCESS_KEY_ID)  # Capture this for comparison with creds from local step below.
sac = SingleAuditChecklist.objects.all()[0]
sar = SingleAuditReportFile.objects.create(file=djangofile,filename='whatever',sac=sac,component_page_numbers=[1,1,1,1,1,1,1])
```

We expect that last command to fail on preview.

12:31:26 Thursday 2023-08-17: verified.

Error message:

``` 
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

### Determine whether we can run `aws s3 ls` using our preview credentials locally

```sh
cf target -s preview
source ../.local/shell/getenvcreds.sh  # The above grab-credentials-from-cf-env commands in a script
aws s3 ls "s3://${BUCKET_NAME}"
```

12:33:39 Thursday 2023-08-17: this command succeeds.

### Verify that the access key is the same

```sh
echo "${AWS_ACCESS_KEY_ID}"
```

12:34:33 Thursday 2023-08-17: verified that this matches what we saw in the Django settings above.

The credentials work locally but the command fails in Django with an access error. Can we run them from the CLI in our instances? We expect this to succeed in dev (but they turn out not to due to proxy errors, see [above](#get-the-aws-cli-onto-the-dev-cloud.gov-instance-and-run-it) ) but with preview it’s unclear.

**Comment by jadudm** [comment]
Preview seems to be taking deploys. Closing as done.

**Comment by tadhg-ohiggins** [comment]
Uploads still not working on `preview`; re-opening.

**Comment by mogul** [comment]
Fixed by https://github.com/GSA-TTS/FAC/pull/2663 !
