### ISSUE TITLE
FAC - Bug: Confusing error after certification lock

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1873]
### Describe the bug

If you submit a complete audit, and lock for certification, further uploads should be blocked.

It seems like they are.

However, if you go back to a workbook, and upload again, you get an error that says that 

```
The workbook you tried to upload is for a different section
```

So, it seems like... well, it seems like this is the error we're getting. I would *guess*  that it is because the upload fails, and then, we try and validate a failed upload, which means that we don't find the workbook ID. 

### Steps to reproduce the bug

See above.

### Expected Behavior

Provide an error that says "we're locked for certification."

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by timoballard** [comment]
Addressed in #2013 - turns out we weren't doing our late change check at all for Excel uploads 😬
