### ISSUE TITLE
FAC - Bug: Final certification does not route back to audit home

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1874]
### Describe the bug

After the very final button click, where ETL is triggered, we are routed back to the checklist.

We should be routed back to the audit home, and ideally, see the audit in a table of completed audits.

### Steps to reproduce the bug

See above

### Expected Behavior

See above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by tadhg-ohiggins** [comment]
Fixed in https://github.com/GSA-TTS/FAC/pull/1881
