### ISSUE TITLE
Test cog / over assignment with 2022 public data.

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#1887]
Breaking this out from its parent epic. See https://github.com/GSA-TTS/FAC/issues/1218 for more discussion and history.

This covers the testing of cog / over assignment with 2022 public data.

**Comment by JeanMarie-TTS** [comment]
@gsa-suk please include a link to the google doc in this ticket.

**Comment by gsa-suk** [comment]
Details are in:
https://docs.google.com/document/d/1SaBRMdr7HsHqHuDZ98oxsJOvQGQPlYjEmk7Zhky8mXM/edit
