### ISSUE TITLE
Storyboard federal access to the database

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#189]
Some work in progress here: https://app.mural.co/t/gsa6/m/gsa6/1651144252291/7d8687fa6bc82d090cb227ad3b87d0d8f22a3358?sender=ua4d37dfba3f1e69e09078790

We'll know we're done when

- [ ] There are stories on the main story mural board, ready to be translated into github.

**Comment by MelissaBraxton** [comment]
@petermarks-gsa  - This is likely something design can help with. If that sounds good, feel free to add the design label and put in on an agenda for discussion at an upcoming co-working mtg.
