### ISSUE TITLE
Refactoring Considerations for Test Scenarios

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#1898]
## Description:
This ticket identifies areas of potential improvement and clarification regarding the existing test scenarios :

1. Overlapping Scenarios between test_schema and test_validator: there is no clear cut  between the tests in test_schema and those in test_validator.
2. Schema Validation in test_excel: Some tests within test_excel also perform schema validation tasks, which might not align with the intended separation of concerns.
3. Redundant test_schema: Given the current structure where each code file maps directly to a test file (e.g., excel/test_excel or validator/test_validator), moving all tests from test_schema to test_validator could be considered since there is no corresponding `schema` Python file in the codebase. 
4. Clear Definition of Testing Purposes: For the sake of clarity and maintainability, it might be beneficial to distinctly define the role of each test location. For instance excel/test_excel should focuse on tasks like mapping worksheet cells to the appropriate JSON object paths while validator/test_validator should focuse on schema validation tasks.

**Comment by jadudm** [comment]
Possible "yes, and." 

We might create a test harness file for each schema. That file would be a list of test objects. This would let us walk the objects, running a test over each.

We could also say whether it is a pass/fail test.

```
tests: [
  test: 
    pass: false,
    obj: { ...}
]
```

(Or, something.)

Point is, this would let us as developers see our pass/fail tests, and more easily test conditionals (as opposed to patching data in the test functions themselves).

**Comment by jadudm** [comment]
Partially/mostly completed as we moved to new validations, and added "should pass" and "should fail" workbooks and tests. Still not table-driven, but it is fairly automated.
