### ISSUE TITLE
Disable lock for certification after it's been completed

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#1903]
Cross-validation is always able to the user, so that they can check for errors even if they have not yet completed every form or uploaded every document. After completing cross-validation and locking their submission for certification, this page is still available. Attempting to lock for submission a _second_ time throws errors, which is good, but we should prevent the user from attempting to lock twice.

We should either disable the entire cross validation flow after they've locked, or disable only the lock step.

**Comment by jadudm** [comment]
Done.
