### ISSUE TITLE
It should not be possible to submit a *second* SA for any given UEI.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1922]

**Comment by jadudm** [comment]
We might not be able to tackle this until we implement resubmission.

**Comment by tadhg-ohiggins** [comment]
Note: if we implement this, then it will no longer be possible for users to start over with their submission in cases where, for example, they need to change their [organization type](https://github.com/GSA-TTS/FAC/issues/949).

**Comment by tadhg-ohiggins** [comment]
Clarification: we intend to prevent submission if a UEI for the same year is already in the dissemination table, probably by putting a check for that in the cross-validation functions.

**Comment by jadudm** [comment]
Until we have resubmission handled properly, we cannot address these kinds of issues. Closing as "not planned," as resubmission infrastructure is the only way to handle this.
