### ISSUE TITLE
Is "Y" the same as `True`?

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#1927]
Does our ETL rewrite values like `"Y"` to `True`? If so... *is that the same*?

We need to revisit ETL, and ask some semantic questions.

**Comment by danswick** [comment]
Could be part of walking/comparing the named ranges and dissemination fields. We'll likely want to document decisions for any discrepancies and probably create a public documentation page for "migrating to the new API" or similar. 

- Are names consistent? If not, note it.
- Are values/types consistent? If not, note why.

**Comment by jadudm** [comment]
This was done. We walked the entire dissemination, and mapped all values back to their input values.

If the user entered `Y`, we disseminate `Y`.
