### ISSUE TITLE
FAC - Bug: Correct name field 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1932]
### Describe the bug

-revert name field from “first,last” back to “full name” in audit submission access (on staging) 

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Done.
