### ISSUE TITLE
FAC - Bug: City field on gen info accepting zipcode

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1933]
### Describe the bug

<img width="480" alt="Screenshot 2023-08-24 at 2 34 06 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/ea7e5075-87c2-4ade-a0b0-50d8a8803a28">

### Steps to reproduce the bug

enter numbers into the city field 

### Expected Behavior

city names should only be alpha

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
For anyone picking this up:

Let's set the validation to only accept alpha characters on this. We don't believe that any city has numbers in it.

What I'm not clear on is how back-end validations affect the forms. But, either way, we can limit the city fields to prevent this kind of basic error/mistake pretty easily.

**Comment by jadudm** [comment]
Done.
