### ISSUE TITLE
FAC - Bug: Staging site missing download for workbook 2 SEFA

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1935]
### Describe the bug

Note - Please work with @lauraherring directly on this, it's her branch! 

The staging site is currently only showing workbooks 1-4 for download, but the submission checklist shows an additional workbook (Notes to SEFA)
<img width="1157" alt="Screenshot 2023-08-24 at 4 28 01 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/702eef06-f26f-4f8a-b9d8-6bd03084ee3c">
<img width="916" alt="Screenshot 2023-08-24 at 4 28 53 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/4e566a36-1589-4de7-9826-6c03235cf021">

### Steps to reproduce the bug

see above

### Expected Behavior

Please add workbook 2 Notes to SEFA into list of downloads from top nav, and renumber workbooks on the page to reflect inserting the new one :)

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by lauraherring** [comment]
The [beta-testing branch](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/beta-testing/resources/workbooks/) has been updated to include Notes to SEFA and all the numbers have been fixed as well.
