### ISSUE TITLE
FAC - Bug: Error message showing before step is completed (staging)

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1936]
### Describe the bug

Error stating complete all fields is showing up after entering first field only on submission access form:

<img width="1040" alt="Screenshot 2023-08-24 at 2 31 53 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/69fe88c5-c74d-4966-ad9f-4b179ac72532">

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Done.
