### ISSUE TITLE
FAC - Bug: suggested improvements + validation to federal award workbook 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1938]
### Describe the bug

Sorry, I know this isn't the right template but wanted to capture things quickly. This is open test feedback from a user on the federal awards workbook: 
![Screenshot 2023-08-21 at 4 53 47 PM](https://github.com/GSA-TTS/FAC/assets/119363060/f271e0a5-30a9-46df-8e77-22b64118fb44)

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
These are possible improvements; they don't hinder data entry, and don't prevent users from completing their audits. I'm ticketing it as a "COULD" under bugs for us to address, and shifting it down in priority below other work that is more pressing at this time.

**Comment by jadudm** [comment]
Done.
