### ISSUE TITLE
FAC - Bug: workbooks do not allow filtering columns

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1943]
### Describe the bug

I believe this is intentional, but passing along this open test feedback in case it's an oversight: 
<img width="712" alt="Screenshot 2023-08-24 at 5 13 20 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/0463de9b-4d2a-445d-88ad-749f5c7be675">

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
No, it doesn't. I don't know if that feature will be available anytime soon. They can use CTRL-F, which may not be as ideal. 

We cannot enable filters and keep the columns locked.

There... might be solutions/workarounds. They could do their work in another workbook, and paste their final work into the workbook for submission. Or, we provide unlocked workbooks... and refuse to accept unlocked workbooks.

Either way, we can't enable the creation of filters on columns that are locked. Closing as not planned.
