### ISSUE TITLE
FAC - Bug: Field for passthroughs in federal award worksheet not validating correctly 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1951]
### Describe the bug

Open test feedback, see note: 
<img width="718" alt="Screenshot 2023-08-25 at 1 26 13 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/4da181e0-adaf-451b-8a13-35ecd88652f3">

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Moving over to available; this sounds like a validation logic bug, possibly. I wish they could attach the workbook in question when submitting a bug.

**Comment by sambodeme** [comment]
@jadudm, yes this looks similar to what we captured in #2036

**Comment by jadudm** [comment]
Closed via #2036.
