### ISSUE TITLE
Add Burden Statement to static site

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#1953]
### Tasks

```[tasklist]
- [x] create page with PRA-approved copy
- [x] add to site navigation
```

**Comment by lauraherring** [comment]
Page has been built and added to the nav on the `lh/ia-updates` branch of the static site. Copy currently has placeholders for OMB operating number that will need to be updated once we have that.

**Comment by jadudm** [comment]
Done.
