### ISSUE TITLE
FAC - Bug: Error validation not working for fed awards workbook 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1960]
### Describe the bug

Open test user feedback, user attempting to submit their own data: "In scenario 3, I got all the way to the pre-submission validation.  The system gave me numerous errors saying that the award workbook said I had X findings for AWARD-X, but there were Y findings on the findings workbook.  I checked the first 2 and the errors were not correct as the number of findings on the awards workbook agreed with the number of findings on the finding workbook."

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Without a copy of the workbooks, it's almost impossible to debug this kind of report. @Leighdiddy , is there any way to follow up and get a copy of what they were doing?

**Comment by jadudm** [comment]
We've done a lot of work here in the past two weeks re: workbooks and validations. Without the workbooks, we can't test/address this further.
