### ISSUE TITLE
Validate dissemination objects against model before calls to save

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#1971]
Per discussion with @jadudm and @sambodeme, the intake-to-dissemination flow currently steps through all of the dissemination objects and saves them one by one. This could be a problem if an object in the middle of the list is missing a field, causing a crash while some items are saved and some others are not.

To safeguard against this, we should validate **all** of a report's dissemination objects against the dissemination model and only trigger a save action **if they all pass**. There are a number of ways to accomplish this, but Django's [`full_clean()`](https://docs.djangoproject.com/en/4.2/ref/models/instances/#validating-objects) method is a good place to start. When saving data that doesn't come from a form, the method needs to be invoked manually and we'd need to handle any exceptions accordingly.

**Comment by jadudm** [comment]
Done.
