### ISSUE TITLE
FAC - Bug: Submission step giving 500 error on staging 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#1977]
### Describe the bug

user test feedback:
 _If you answered "No," can you describe at what point in the submission workflow you stopped and why? You can reference the steps of your submission checklist to better identify the stopping point._
After certifying and submitting to the FAC, I received an error message “500 error: internal server error”.

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
This is likely a dissemination error.

We have plans to catch this, and it might be done before go-live. Just leaving a comment here for myself that this would be handled by the transaction wrapped around save in `IntakeToDissemination`.

Assuming it was a dissemination error.

**Comment by jadudm** [comment]
We've brought in the ETL branch as well as fixes that wrap some protection around the save. Closing this as done.
