### ISSUE TITLE
Define override proces for cog assignment

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#1986]

**Comment by JeanMarie-TTS** [comment]
@Carley-Sullivan please add your thoughts on how we should implement this process . The implementation will be in two phases. In the first phase, we will have a bare bones process that experts like @Carley-Sullivan  will follow to allow cog agency assignment to be changed. A later phase will involve building a full-blown UI for a larger support team or perhaps with the ability of agency users to propose and approve these changes. For now, let's define the bare minimum that we need.

1.  A privileged user will be able to access a special page, either via a menu option on the FAC app or via a special URL.. In either case, they will have to login using their federal email address at login.gov. Privileged users will be pre-configured in the system by the FAC app admin team.
2. The page will have an option to select a finalized AY23 submission. What would be the fields to search on: report_id, currently assigned cog agency, anything else?
3. The user will be able to view some details about the submission - which fields to be determined. The user will be able to pick a new cog agency for the submission and add some comments on why the change is being made.
4. Does the app need to make any validations about the  new cog agency? Should you only be allowed to pick an agency listed in the federal awards? Can a cog agency be assigned instead of an oversight agency or vice versa?
5. The system will log the requested changes and update the dissemination tables immediately.
6. Is there a need to view the history of these changes? If so, should this be in the publicly visible dissemination tables, or only for privileged users.

**Comment by gsa-suk** [comment]
@Carley-Sullivan  Is the current override list maintained in a separate table by Census?

**Comment by Carley-Sullivan** [comment]
Comments/thoughts on the following:

2. Search by report ID should suffice.
4. Privileged user should be able to choose from any federal agency - not just the ones listed on the auditee's SEFA. This allows OMB to contact the FAC and make changes to Cog as they (OMB) deem necessary.  The assignment type (Cog v Over) should never change. If an auditee is assigned a Cog, they should not be reassigned an Oversight and vice versa.
6. Yes, we will need to keep record of any reassignments, as well as, why the reassignment occurred. For greater transparency, this listing of reassignments should be made public

**Comment by JeanMarie-TTS** [comment]
- [ ] Search by report_id or UEI in a single search box
- [ ] Filter by cog_agency, computed vs manual
- [ ] Only allow cog overrides to submissions with existing cog assignments
- [ ] Screen to browse baseline table that will be used for 2021 to 2025

**Comment by jadudm** [comment]
@JeanMarie-TTS , I've moved this back to Backlog. 

I'm happy to work with you, Carley, and Sudha to work out what we want to do here. Then, it wants to become one or more increments that we work into our feature delivery pipeline.

**Comment by jadudm** [comment]
Closing this, as we will want to pick up the policy work and process given where we are at now.
