### ISSUE TITLE
FAC - Bug: General Information Doesn't Have to be Completed

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#1991]
### Describe the bug

There is a path to skip the general information form. When a user completed the access form, they have created a SingleAuditChecklist object in the database, but they haven't completed the general information form. If they leave and come back to FAC.gov and then access that report, it shows general information as being complete. But, all that's in there is the pre-populated information that comes from the previous steps. 

### Steps to reproduce the bug

1. Begin an audit.
2. Fill out "step three" by entering user access information. Do _not_ fill out the general information page
3. Leave and come back to your submission homepage
4. The new audit was created and is accessible. Access it.
5. Verify that the general information forms shows as complete, even though it is not.

### Expected Behavior

For sure:
1. General information should not be showing as complete when it isn't. Validation should run in the checklist view that ensures the correct view.
2. General information should be editable without completing all the fields. There are cases where several individuals fill out different parts of the form, and they shouldn't have to fill out everything to continue.
3. There should be two schemas for general information, to ensure both data validity and completeness in two steps:
    * One checks all fields for the correct data, but doesn't require anything. This is used when saving the form. 
    * One type-checks everything in the object, and requires all fields. This is used to determine completeness. 

Possibly:
1. Completing the access step should send a user to the checklist, bypassing general info. They then complete general info (or a portion of it). 
2. The Django form should handle some validation (like EIN length) to help prevent 400 errors. 

### System setup

All of them! Noticed in a substantial way in the staging environment by colleagues from the state of Virginia. 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
This was picked up as #1992 . We'll close the bug ticket, and think about how to move bug tickets across the board in the future. For now, closing this, but anyone watching it should watch #1992 and associated PRs instead.
