### ISSUE TITLE
FAC - Bug: General Info Skip

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#1995]
### Describe the bug

By exiting, going back a page or submitting incorrect info, it is possible to skip the general info section of the audit and still get a green checkmark or sign of completion when on the main page

### Steps to reproduce the bug

1. Submit Audit submission access data
2. Close out of your tab or hit the back button
3. Re log in and open FAC
4. It should say that general info is completed despite not being completed

### Expected Behavior

For general info to know whether or not all fields have been completed to show the completion checkmark.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Closed via #2085 .
