### ISSUE TITLE
FAC - Bug: Error 400: Bad Request on General Info

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#1996]
```[tasklist]
### This is done when
- [ ] Each bug below is verified
- [ ] New tickets to fix any remaining bugs are created.
``` 

Original bug below

--------------------------

### Describe the bug

There are multiple instances of Error 400 appearing on general info when inputting incorrect data (and sometimes correct yet improperly formatted data) in text boxes.

### Steps to reproduce the bug

Here are some examples of where Error 400 appears
1. Incorrect date formatting (adding more characters than required, also following a formatting that doesn't use dashes in the date)
2. Inputting more than 9 characters for EIN's
3. Inputting more than 100 characters for contact addresses
4. Submitting more than 5 characters for zip code
5. Not following the exact 10 digit formatting for phone numbers (##########) instead of something like (###) ###-#### or ### ### #### Etc. 
6.  Submitting an email without an @gmail or something similar at the end of it.

### Expected Behavior

Similar to other parts of the website, I expected an error message or something that might point out what I did wrong when submitting this info. As is, it is difficult to tell what is incorrect when submitting the general info form

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Each of Leo's findings should be double-checked, and see if we've picked these up/fixed them.

**Comment by jadudm** [comment]
This was caught with a number of other GI fixes.
