### ISSUE TITLE
Front end "audit submission access" UI

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#200]
**Background**: The third step of the create new audit flow is "audit submission access" where auditee / auditor contacts are entered. 

**Acceptance criteria**:

- [x] #204
- [x] "Add another contact" creates a new row
- [x] There is a way to delete a row of bypass validation if you leave a new row blank
- [x] Email fields have client-side validation for valid email format

**Design**: ([current design](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=1906%3A8483))
![Audit submittion access](https://user-images.githubusercontent.com/100610443/168103938-3025ac36-57d0-4eea-9f2f-a16fd1c490b0.png)

**Comment by petermarks-gsa** [comment]
@heymatthenry Just took a look at the federalist preview of this. It meets the current acceptance criteria, but I noticed an issue that I think needs addressing:

There is not currently a way to delete a row or bypass client side validation if you leave a new row blank. This means if you fill out 12 inputs, but create a new row perhaps by accident, you are stuck and must refresh the page to fill out the form again without the extra row. My suggestion is to keep the validation on the new row, but add some sort of delete button on the end of each extra row.

**Comment by heymatthenry** [comment]
@petermarks-gsa I implemented this in GSA-TTS/FAC-Frontend#18

**Comment by petermarks-gsa** [comment]
@heymatthenry Acceptance criteria on this looks good to me. I did notice that you don't see the immediate validation if you leave a field blank on the "add additional contact form", but see that it validates upon trying to submit the form which I personally feel is sufficient. Marking as done.
![Screen Shot 2022-06-09 at 10 44 33 AM](https://user-images.githubusercontent.com/100610443/172875795-7e95e336-3cbe-4694-9ba5-043e255a2fb7.png)
