### ISSUE TITLE
FAC - Bug: multiple field validations not working

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2001]
### Describe the bug

Open test user feedback:
_For Scenario 2, I had problems where I intentionally put in information that should have given an error, but instead, it let me continue. I intentionally put a typo in one of the boxes to confirm an auditee email. The box was white instead of blue/gray like the ones that matched, but when I clicked save and continue to the next section, it let me continue. Then I left the box for Auditee EIN not being a SSN unchecked and when I clicked save and continue, it let me continue and gave me a green checkmark that the information step was complete. When inputting page numbers for required elements of the report I left the page number blank for the Corrective Action Plan. Since I had marked that there was a material weakness and non-compliance in the report, it should not have let me continue without marking that._

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
#1992 will address these bugs on the general info form.
