### ISSUE TITLE
FAC - Bug: update copy for CFDA to Assistance Listing Number

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2005]
### Describe the bug

open test user feedback:
_There are references to CFDA in various places (including instructions).  These should be updated to Assistance Listing Number._

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by Leighdiddy** [comment]
@lauraherring FYI I haven't checked this against the figma doc yet, may be a non-issue of old copy in the staging site.

**Comment by lauraherring** [comment]
@Leighdiddy Do we have any more specifics on where this is an issue? And I thought we were keeping CFDA and ALNs? That it's just DUNS that are obsolete?

**Comment by Leighdiddy** [comment]
Closing, outdated feedback from initial UAT/beta testing
