### ISSUE TITLE
FAC - Bug: Unable to view/print summary before submission 

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2006]
### Describe the bug

open test user feedback (sorry this is probably a feature request!):
_Will there be an ability to print to a draft to an Excel file to review all inputs prior to submission?  This is critical for higher level reviews._

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
At time of cert, we should allow the certifying official to download all of the PDF and XLSX documents; essentially, we want to give them the search result page for the audit. 

* Dump general info
* Dump audit info
* Link to each of the submitted files

so they can review the whole audit.

**Comment by jadudm** [comment]
This has become an epic, as it is feature level. Closing this ticket.
