### ISSUE TITLE
FAC - Bug: Auditor Certification Error 500

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2028]
### Describe the bug

It is possible to cause the webpage to send back an error or outright crash if you submit your Auditor Certification and then use the history function on your browser or the back button to go back to a previous page and try to submit. 

### Steps to reproduce the bug

Described above

### Expected Behavior

Using the back button shouldn't cause a webpage crash.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
I think we've addressed a number of things in this space? Yes. We've done a lot of state machine work since this was written, and it is effectively handled.
