### ISSUE TITLE
Overall site copy-edit.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2031]
A close, final read of every page, and any reasonable edits.

*Be very careful of editing anything that smells of policy.*

Target: 9/15

**Comment by James-Paul-Mason** [comment]
I just finished giving the static site a close, final read of every page. I sent my comments to @lauraherring, and here is the link to the Figma file for viewing/documentation: https://www.figma.com/file/hlctsACKW4XPVyvLDQz6Dt/FAC-Static-Site%3A-Content-Launch-Final-Notes?type=design&mode=design&t=Ff4G2l3xkRHf0H97-1

**Comment by jadudm** [comment]
We've done this at various points, and it was done at the time. This is closed.
