### ISSUE TITLE
FAC - Bug: Possible to complete pre-submission validation without doing general info

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2044]
### Describe the bug

This problem is piggybacking off of the ability to skip "general info" as noted in previous bug tickets. Currently, if you are able to skip general info via going back to the FAC landing page or using the back button, the pre submission validation doesn't see anything wrong with this, and lets you proceed. 

### Steps to reproduce the bug

1. Skip general info by going back to the FAC landing page while in the form submission
2. Upload all other workbooks and requirements for pre submission validation
3. Validate without issue despite missing crucial information

### Expected Behavior

Considering the general info skip I assume this is just an extension of that problem. However, even if you aren't able to skip general info, the pre submission validation should still be able to pick up on errors with general info submission like it does with the other forms.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by LeoFotovich** [comment]
Won't submit another ticket for this problem to not be redundant, however if you go through with pre submission validation, it is entirely possible to permanently lock yourself out of completing your audit. Because there is no auditor listed (no general info), moving onto auditor certification after validating will give you an error. Because you've already certified you can't go back and make changes to your audit, which include general info. This makes the entire audit non completable.

**Comment by jadudm** [comment]
Fixed long ago.
