### ISSUE TITLE
FAC - Bug: Biennial and Low Risk Auditee Issue

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2046]
### Describe the bug

Not exactly a "bug", but a missing feature. According to Carley, selecting Biennial under "general info", and then saying yes for a low risk auditee under "Audit info" should return with an error under validation, as you cannot be a biennial auditee and also low risk.

### Steps to reproduce the bug

Described above

### Expected Behavior

Selecting both of these should have an error message when validating 

### Screenshots

<img width="388" alt="Bug 5" src="https://github.com/GSA-TTS/FAC/assets/139488747/b16d894f-f725-4eb2-9731-9ec10c49c6f6">

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
We didn't triage this in. I'm placing it in backlog, as it is pretty clear what we need to do, and it is a validation/cross-validation action we should take.
