### ISSUE TITLE
Refactor Cypress tests to complete multiple submissions

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2048]
Loopify the full-submission test so that we can perform multiple submissions, using different workbooks for each.

More workbooks can be found [here](https://drive.google.com/drive/u/3/folders/13Xtuz6ab0dpz1fpQLjYhcahWrfhvdY-y).
```[tasklist]
### Tasks
```

**Comment by jadudm** [comment]
This has been done. It may not loop over many workbooks, but we now have 3 submissions on every regression test, covering critical paths. Closing.
