### ISSUE TITLE
FAC - Bug: No Error Message to Indicate 

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2055]
### Describe the bug

When creating an audit report, users need to validate the auditee's UEI (Unique Entity Identifier) by clicking the "Validate" button before proceeding to the next step by clicking "Continue." However, the form does not clearly indicate that this field is mandatory or that the "Validate" button needs to be clicked separately before hitting "Continue." Additionally, if users neglect to validate the UEI and click "Continue," the application resets the form and returns them to the same page without displaying an error message to guide them on what needs to be done to proceed to the next steps.

### Steps to reproduce the bug

1. Go to [FAC-DEV](https://fac-dev.app.cloud.gov/audit/) and initiate an audit report.
2. When you reach the Auditee information form displayed below, filled the form, do not click the `Validate UEI` and click `Continue` 
![image](https://github.com/GSA-TTS/FAC/assets/26260777/96470213-c6bd-4c8d-adeb-38ff461da428)
3. Note that the application resets the form and returns you to the same form without warning or error message. 

### Expected Behavior

When creating an audit report, the form should clearly indicate that validating the auditee's UEI is a required step. This could be accomplished through the visual cue `*` (see the other fields on the form for example).
Also, it should be made clear to users that the "Validate UEI" button must be clicked before clicking "Continue."
If the user fails to validate the UEI and clicks "Continue," the application should display an error message that informs the user they must first validate the UEI in order to proceed to the next steps.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Resovled long ago.
