### ISSUE TITLE
Update workbooks in static site for go-live

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2057]

**Comment by jadudm** [comment]
To be done on Friday the 15th.

**Comment by lauraherring** [comment]
@jadudm Does this mean update the static site repo to have the latest versions of each workbook and merge a new branch?

**Comment by jperson1** [comment]
We also want to make sure updated instructions from the libsonnet are going through. Double check that bolding is correct (markdown double asterisk).
