### ISSUE TITLE
Wrap the dissemination save / protect against 500 errors in write to DB

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2060]

**Comment by danswick** [comment]
@sambodeme made a first crack at this here: https://github.com/GSA-TTS/FAC/pull/2084/files#diff-6e5e23e622de844b8095e89f6e8b4aaedfb2e926e2f8d5770c500fabd2feaa6bR60. With this change, we should be protected on a section-by-section level, but a user could still theoretically upload a report where broken sections don't make it through to dissemination (though it's not entirely clear that a broken section could make it this far). The open questions I can think of:

1. Should we validate the presence of _the entire report_ first before attempting to run through ETL as a sort of "dry run?"
2. If/when an error occurs, how do we capture the error, communicate it to the user, or handle it on our end? A "dry run" approach might address this.

**Comment by jadudm** [comment]
Lets make sure the user gets a good error message.

Watch for #2142 to merge first.

**Comment by jadudm** [comment]
We can't get to dissemination without making it through cross-val. Cross-val won't pass unless everything is present. Although (in theory) something could fail on the general form, this is not a high priority at this point, as we have enough validations/protections earlier in the submission chain. Closing this for now as not planned.
