### ISSUE TITLE
FAC - Bug: Beta Test scenarios on home page after clicking Contact Us

### ISSUE THREAD

**Issue by eazapata23** [GSA-TTS/FAC#2073]
### Describe the bug

When logging into the FAC.gov app and clicking on Contact Us then clicking FAC.gov you are taken back to the homepage that is populated with the beta-testing app which requires you to sign in again (sometimes) taking you to login.gov, which then will see that you are logged in already or require to sign again or take you back to Single audit submissions.

side note: You are able to click on Contact Us and then clicking on the back arrow to return to Single audit submissions avoiding resigning in.

side note: The URL also changes after clicking on Contact Us

### Steps to reproduce the bug

1. Sign in into the FAC.gov 
2. Click on Contact Us
3. Click on FAC.gov
4. Click on Sign in
5. By clicking sign in, you will either be prompted to sign in again or taken to single audit submissions

### Expected Behavior

By clicking on Contact us then clicking on Fac.gov you should be taken back to Single audit submissions page.

### Screenshots

https://github.com/GSA-TTS/FAC/assets/99770283/d055a8bb-05b5-466c-b4de-65bfba1c0d70

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by danswick** [comment]
This was fixed at some point in the last couple of months.
