### ISSUE TITLE
Possibly remove "certified" state

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2074]
Per discussion with @jadudm and @sambodeme, the "certified" state may be redundant. It has the same meaning (I think) as the combination of "auditee certified" and "auditor certified" and its timestamp is exactly the same as the "submitted" state.

* If we remove "certified" state, then the "submitted" timestamp should be what we disseminate. 
* Are there tests/other parts of the state machine that rely on "certified" that will also need to change?

**Comment by jadudm** [comment]
Just checking... did we remove this as part of the `etl` merge? I thought we did. (We may have ticketed this minutes before removing it.)

**Comment by sambodeme** [comment]
Yes, we did remove `certified` before merging to main

**Comment by jadudm** [comment]
Closing this then because we picked it up.
