### ISSUE TITLE
Disseminate `submitted_date` in UTC-12

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2075]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** know my submission was "on time"
**as a** submitter
**I want** my submission date disseminated in UTC-12, or the [Anywhere on Earth](https://www.timeanddate.com/time/zones/aoe) timezone.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I complete a submission.

**Given**   that I have pressed the final submit button
**when**  our intake-to-dissemination process runs
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the `disseminated` timestamp should be used for the `submitted_date` in the dissemination tables
- [ ] the `disseminated` timestamp should not be altered in the intake database
- [ ] the dissemination process should convert the `submitted_date` from `UTC` to `UTC-12`
- [ ] the dissemination table should only contain `YYYY-MM-DD` (iso8601), not a full timestamp.
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Engineering shepherd: @danswick 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

In the past, the FAC required submissions to arrive by midnight in the Eastern Standard Timezone. 

This means that submitters in (say) California need to submit by 9PM.

In Hawaii, they need to submit by 2PM.

This is a complex thing for users to understand, first and foremost. There is no reason that EST is a "special" timezone. Further, it is very difficult to tell what timezone a user is in; if they are using a VPN (for example), a user in Hawaii may appear (to the FAC) as being a user in Washington, D.C.

Our server records time in UTC, which is otherwise known as GMT. 

What would be easiest to do would be the following:

1. Communicate to users that their submissions are due by midnight wherever they live. 
2. We record the time of their submission in UTC. This is the "real" and accurate time of their submission.
    1. The time we record will appear to be "in the future" of all users. For example, EST is UTC-5. That means a submission at 11PM EST will be recorded as 4AM UTC.
3. When we disseminate the package, we convert the time of acceptance to UTC-12. Put another way: we subtract 12 hours from the submitted timestamp in our system. 
4. We record the year, month, and day of submission, not the full timestamp.

There are some side-effects to this choice.

1. Users who submit in EST at (say) 9AM on Thursday the 22nd will see their submission appear as being disseminated on Wednesday the 21st.
2. Users who submit in HST (Hawaii standard time) at 1AM on the 22nd will see their submission appear as being disseminated on the 21st.
3. No user who submits before midnight in their local timezone will ever be marked as "late."

This sounds like the FAC is "changing the time of submission." This is not the case. The FAC is *choosing to record the time of dissemination in the last timezone that a submission could possibly be made*. In this way:

1. We can communicate to users that their deadline is midnight.
2. If a user submits a few minutes late (in any timezone except UTC-12), they will still be recorded as "on time."
3. Only users in UTC-12 have a **hard** deadline of midnight, because there are no timezones further west of UTC-12.

We do not believe there are any submissions from UTC-12. American Samoa is in UTC-11, which we suspect (but are not 100% certain) is the westernmost point from which a submission to the FAC might be made.

This will be recorded in a PDR.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns in this ticket.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details> 

Original bug ticket below.

----------------------------------------

### Describe the bug

When we move data into `dissemination`, we are migrating timestamps in UTC.

We should disseminate our times in AoE.

These timestamps are used to determine whether or not a submission is "on time." UTC is essentially GMT. This is EST+4/5, depending on daylight savings time. (EST vs EDT). Likewise, different parts of the US vary (e.g. Indiana has no daylight savings.)

There are territories out near the dateline. If they are submitting by midnight on a given day (to be "on time,") it is actually "tomorrow" from the point-of-view of EST. 

Therefore, to be consistent and fair to all states and territories that might submit an audit, I think we should record times in UTC (which we are), but disseminate all times in AoE (12 hours behind UTC): https://www.timeanddate.com/time/zones/aoe

We may go another way, but I think we want to do this. TBD.

### Steps to reproduce the bug

Run a submission.

### Expected Behavior

Have a time that is fair to all submitters.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by tadhg-ohiggins** [comment]
Following up on my [earlier comment](https://github.com/GSA-TTS/FAC/pull/2232#issuecomment-1734214060)

The code I just merged to fix the test failures has us apply the date as if the timestamp were UTC−11. This ticket specifies UTC−11, so we’ll need to fix that.

The current code converts the internal timestamp, which is UTC, to the `US/Samoa` timezone, which is not quite what we want. I think that the next iteration should not do anything with timezone conversion as such, but rather just subtract 12 hours from the UTC timestamp. This is very similar to what timezone conversion does, but is simpler and completely avoids any complications such as daylight savings, making sure that the timezone we choose doesn’t have any odd issues, and so on.

@jadudm leaving it up to you whether to create a new ticket or just re-open this one.

**Comment by jadudm** [comment]
It feels like we can safely reopen this one; I think the change scope is
small enough?
