### ISSUE TITLE
FAC - Bug: Workbook Timeout

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2076]
### Describe the bug

Submitting a non workbook excel spreadsheet with a lot of filled in cells causes the validation process to timeout. This is likely intended, however could potentially be confusing if somebody submitting an audit doesn't fully understand what counts as a workbook or not.

### Steps to reproduce the bug

1. Submit a workbook with a lot of data or an excel spreadsheet with lots of filled in cells
2. Workbook timeout error occurs

### Expected Behavior

The workbook validation process should be able to tell if a spreadsheet submitted is not a workbook.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
We've addressed this in various ways. Closing until we observe it again.
