### ISSUE TITLE
FAC - Bug: Zendesk ticketing, confusion

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2083]
### Describe the bug

When you select "support" from the static site it takes you to [zendesk](https://support.fac.gov/hc/en-us), where you have two options in the upper right hand corner of the home page:
![Screenshot 2023-09-12 at 1 14 12 PM](https://github.com/GSA-TTS/FAC/assets/119363060/ed2ca46a-c835-4d99-b785-12ab25f745cb)
A user may not understand that "Submit a request" means "ask for help," so they select "sign in" and are taken here. This wording  implies that I need a password (and an account) even if I've already emailed my request. I don't have an account, so I select the New "sign up" option from the bottom:
<img width="465" alt="Screenshot 2023-09-12 at 12 47 22 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/c9792a00-2fca-4e00-a5a2-2b40d5bf1a46">
That takes me here. I filled this out and sent the request earlier today, nothing ever came back to my email:
<img width="443" alt="Screenshot 2023-09-12 at 12 26 05 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/f44c4d59-bbd6-4f76-aeac-1671de030c88">

After discussion with @Carley-Sullivan , we've determined that both the "sign in" and "submit a request" buttons on the homepage, and the "submit a request" option at the bottom of each published article are all not working. I (Leigh) have tried submitting requests from various points throughout the site, nothing is coming through on the admin side. 

### Steps to reproduce the bug

see above

### Expected Behavior

see above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by Carley-Sullivan** [comment]
Agree with above. The only way to generate a Zdesk ticket is to email support@fac-gov.zendesk.com.

**Comment by jadudm** [comment]
We seem to have found a way forward with submitting tickets beyond email, but that does not change some of the fundamental questions here.

**Comment by danswick** [comment]
It seems that folks haven't been encountering this issue since Sept.
