### ISSUE TITLE
Do a copy-edit/proofing of content in the Helpcenter (ZD)

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2092]
What it says on the tin. This was, apparently, discussed at end-of-day on 9/12. Talk to @thebestsophist for more information if needed, and expand this ticket as needed.

**Comment by James-Paul-Mason** [comment]
Just a quick note to report that this is in progress.

**Comment by James-Paul-Mason** [comment]
Complete. However, I going to coordinate with Carley about creating a how-to resource for creating new FAQs and editing existing ones in Zendesk. Also, I want to make sure that we begin ticketing any new FAQs for content review before publication. I know this has been discussed, but I am not sure if it is in place.
