### ISSUE TITLE
Verify these fields are in dissemination or not needed

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2093]
```[tasklist]
### Where are these fields?
- [x] `fac_accepted_date`
- [x] `questioned_costs`
- [x] `material_weakness_major_program`
- [x] `type_report_financial_statement`
- [ ] `prior_year_schedule`
```

**Comment by jadudm** [comment]
I believe the following is true:

* `gen.submitted_date` is the date everything is complete. So, `fac_accepted_date` becomes `submitted_date` in dissemination. Should we rename this to `fac_accepted_date` for more clarity for users? https://github.com/GSA-TTS/FAC/blob/b2cb3d4b750417e50b955c186a45f3fa534a8cee/backend/dissemination/api/api_v1_0_0/create_views.sql#L234C13-L234C27
* `questioned_costs` is `finding.is_questioned_costs`. https://github.com/GSA-TTS/FAC/blob/b2cb3d4b750417e50b955c186a45f3fa534a8cee/backend/dissemination/api/api_v1_0_0/create_views.sql#L62
* `material_weakness_major_program` is `gen.is_internal_control_material_weakness_disclosed`. https://github.com/GSA-TTS/FAC/blob/b2cb3d4b750417e50b955c186a45f3fa534a8cee/backend/dissemination/api/api_v1_0_0/create_views.sql#L244C9-L244C60
* `type_report_financial_statement` is `finding.type_requirement`. https://github.com/GSA-TTS/FAC/blob/b2cb3d4b750417e50b955c186a45f3fa534a8cee/backend/dissemination/api/api_v1_0_0/create_views.sql#L65
* `prior_year_schedule` .. I am not certain. `finding.prior_finding_ref_numbers` seems close, but we need to double-check this.  https://github.com/GSA-TTS/FAC/blob/b2cb3d4b750417e50b955c186a45f3fa534a8cee/backend/dissemination/api/api_v1_0_0/create_views.sql#L61

**Comment by MstrDan** [comment]
Thanks, Matt. Ideally, these fields would be available in general api than having to cross walk to Findings. That was the case earlier but apparently got moved to Findings. A mapping document would be of great help so there's no confusion. We'll review the online documents and proceed as advised.

**Comment by jadudm** [comment]
We've decided that everything that can be derived will be something that, in the first instance of the API, users can do. We're documenting rollup fields as examples, and will bring those live as part of the API documentation. Closing this ticket for now.
