### ISSUE TITLE
Generate new workbooks for Cypress tests

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2098]
### Tasks

Now that Cypress tests are passing again in main thanks to Hassan's [PR](https://github.com/GSA-TTS/FAC/pull/2086), new workbooks need to be generated to be used in [multi-submit Cypress testing](https://github.com/GSA-TTS/FAC/issues/2048).

```[tasklist]
- [ ] Generate new workbooks
- [ ] Ensure they work for current Cypress tests
```

**Comment by jadudm** [comment]
Done.
