### ISSUE TITLE
Update submission progress/checklist logic to handle the new form

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2102]
The checklist wants to make this form conditionally available. 

IF they say it is a tribal audit, THEN this form should appear right before cross-val.

OTHERWISE, this form does not appear.

**Comment by jadudm** [comment]
Note: we need to determine if this is only doable/visible by the auditor certifying official.

**Comment by danswick** [comment]
@jadudm sounds like this should be the audit**ee** certifying official.

**Comment by jadudm** [comment]
FYI, Figma mocks are up to date for the checklist: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?type=design&node-id=1%3A31587&mode=design&t=aSsuCZi6cLL3XXif-1

**Comment by danswick** [comment]
This is in our feature branch!
