### ISSUE TITLE
Cypress testing for tribal audit submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2105]
A complete happy path involves two submissions:

1. Does a submission, selecting as a tribal org, asking to keep data Fed-only.
2. Does a submission, selecting as a tribal org, asking to make data public.

In both cases, the API needs to be hit at `api-staging.fac.gov` *after* the submission is complete.

For each of the above:

1. [ Some data should NOT be present. Update this ticket when we know exactly what that is.  We can look for something that should be suppressed. If we DO NOT find it, that is good. ]
2. [ All data should be present. We can look for something that would otherwise be suppressed. If we find it, good. ]

This suggests we need to add an API key for the Cypress tests. Which suggests a new `CYPRESS_` variable. Those keys should be created against our test user account (`test.user+public-key@...`, `test.user+fed-key@...`), be added to the appropriate key storage location, and be rotated on a schedule.

We could use two keys. One with privs, and one without. This would suggest two keys. Then, we would test each in both cases.

**Comment by eazapata23** [comment]
When tribal is public: 

![Image](https://github.com/GSA-TTS/FAC/assets/99770283/61adfd30-9bb4-45c3-b073-2ca6cc31207e)



![Image](https://github.com/GSA-TTS/FAC/assets/99770283/8fef3500-1f1d-4eca-9e35-1215bc1d9915)

When tribal is private:



![Image](https://github.com/GSA-TTS/FAC/assets/99770283/f76411ad-4057-4738-aea5-0dc2fb79ecc9)



![Image](https://github.com/GSA-TTS/FAC/assets/99770283/1f05651a-ae94-4558-81fb-22c65d670330)

When tribal is public, response is populated vs private. 
@jadudm @timoballard 
These test are just using the JWT Token created from the api dissemination test. When it comes to creating two new API keys? Is it the same process as previously?

**Comment by jadudm** [comment]
We can use the existing key from prior work as a public key. A "privileged" key is just a second key that we (I) will attach some permissions to behind the scenes. The key request/use process would be no different from your point of view, though.

**Comment by danswick** [comment]
This is merged.
