### ISSUE TITLE
Alter audit.models.sfsac.is_public method

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2106]
Possibly remove

https://github.com/GSA-TTS/FAC/blob/eeb31ae55db049460e7870718bba62c4a2ef229a/backend/audit/models.py#L491

because we believe that `is_public` is a distributed property, and not a property of the input. See ticket about dissemination for notes on how we could do this calculation at time of dissemination vs. as part of the model.

**Comment by JeanMarie-TTS** [comment]
@jadudm , @danswick Just noticed the PR related to this. Making sure you considered why this field may have been in SingleAuditChecklist in the first place.
As far as I remember, it had something to do with exposing a URL to download the pdf.

**Comment by jadudm** [comment]
@timoballard , if we were to remove `is_public` from the `sac` object, and instead ask that the value be checked in the dissemination tables, would that break anything from your POV w.r.t. file download? 

Because this is essentially a value that cannot be computed until the user has completed the audit submission process (or, at least, completed the intake and tribal data cert), we thought perhaps it should be computed at dissemination time instead of being stored in the `sac` object.

Thoughts?

**Comment by timoballard** [comment]
The [spike branch](https://github.com/GSA-TTS/FAC/pull/2284) does contain a reference to `is_public`, but that's not a big deal to rework. 

Are we planning to support file downloads for in-progress submissions at all, or only after submission? Mostly wondering because that might influence where we put the download code (i.e. `audit` vs `dissemination` app).

**Comment by danswick** [comment]
Updating from discussion: we don't have any plans to use the audit model's `is_public` property for anything. In-progess file access will be handled via app access/authentication.
