### ISSUE TITLE
Decide what we're going to name the fields involved

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2107]
This form collects three pieces of information:

* A radio button that we will call `is_tribal_information_authorized_to_be_public`
* A text field `tribal_authorization_certifying_official_name`
* A text field `tribal_authorization_certifying_official_date`

**Comment by danswick** [comment]
Moved these field names over to https://github.com/GSA-TTS/FAC/issues/2185. We're good to close here.
