### ISSUE TITLE
Remove `api` from codebase.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2116]
The `api` app is legacy. It represents a time when the FAC team thought that there would be a complete separation between the FE and BE. 

That changed at some point. But, the code lingered.

The `api` directory should go away, and it should not impair our application. Or, that is true *in theory*. 

This will clean up the codebase and get rid of the possibility that anything in that part of the app 1) will trigger security scans, or 2) be a point of weakness, or 3) just confuse things.

**Comment by JeanMarie-TTS** [comment]
@jadudm I suggest we also move report_submission to audit. This was a decision made many months ago (see dev huddle notes) but we never got down to doing it.

**Comment by jadudm** [comment]
I think that is #1847. Note these are backlog, and will get storied further before moving to "available."

**Comment by jadudm** [comment]
I'm closing debt tickets so we can tackle debt payment systematically in a sequence of epics. Or, get debt actions on the board in a manner that anyone can pick them up -- but I also want us to have a way of knowing (testing, process, review) that tells us we're not doing harm in the process.
