### ISSUE TITLE
Remove `data_distro` from codebase

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2117]
The `data_distro` directory is from a time long past when we were attempting to build a robust data intake/distribution framework around the public CSVs. 

These CSVs turned out to be messy and problematic. We will be getting authoritative data from Census.

So, we should instead remove this code completely. It should be the case this does not impact the app at all. It will make code searches easier, eliminate unused Django commands, etc.

**Comment by JeanMarie-TTS** [comment]
Will implement in two phases. The first phase is to drop the objects from the databse - for which we need to include the app in INSTALLED_APPS. This phase is covered in the current PR.
The second phase will be the removal of the app from the codebase. This should be done after the first PR has been deployed in all environments where data_distro was previously deployed.

**Comment by jadudm** [comment]
Moving this back to backlog. This was not work I planned for the week we go live, and it wasn't storied out fully for moving to `available`.

**Comment by jadudm** [comment]
There's a lot of debt to pay, the the team should pay it. Closing as not planned. I would rather the team develops a coherent plan for ongoing maintenance and debt payment, and the tickets come through small and actionable on a day-to-day basis. (And, they'll need tests for regression coverage before being implemented.)
