### ISSUE TITLE
It's possible to skip steps in the pre screener

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2118]
### Describe the bug

Getting a link to any point in the pre screener form after submission eligibility starts an uncompletable form that would make it confusing to a user as to why they can't proceed. 

### Steps to reproduce the bug

1. Go to https://fac-staging.app.cloud.gov/report_submission/auditeeinfo/
2. try to submit valid info 
3. page refreshes 

### Expected Behavior

You shouldn't be able to link directly to parts of the pre screener form, and if you do have a link it should automatically put you in the "submission eligibility" form or just give an error.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
Is this still true? Needs to be triaged.

**Comment by danswick** [comment]
Just tested this and it _is_ still possible to start partway through the pre-screener, which puts the audit into a state where it's impossible to pass validation, but also impossible to fix. 

![Image](https://github.com/GSA-TTS/FAC/assets/2365503/e04a6125-8250-4d87-b327-1196d3993215)
