### ISSUE TITLE
Data integrity for pre-deploy DB exports

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2119]
We are now dumping data before deploy.

1. Did we export all the data?
2. When we need to restore... how? Wipe-and-load? 
3. What is `django db restore` doing?

dbbackup dumps the entire database. Defaults to a `bin` file. (Called `.dump` in our code.)

dbrestore looks at that dump file. Does some magic and puts things back.

Table integrity is not something we can see yet. Are tables overwritten? Duplicated? Is the data there that we want? (How does this play with the Django app w.r.t. migration state, etc.?)

Should we dump the entire DB before restoring? Should we go table-by-table? We'll want to test.

`preview` is a good environment for testing this kind of thing.

A more thorough investigation will be necessary for us to ticket out some stories about what we want to do.

**Comment by JeanMarie-TTS** [comment]
@jadudm , @mogul Is there a reason we want to use django to perform database backups and restores? Why can we not not use the native options provided by cloud.gov - see https://cloud.gov/docs/management/database-backup-restore/ ?

To get migrations right, it may be useful, and perhaps necessary, to know the last git commit that was applied to the environment where we are doing the backup. Is this stored somewhere, like in the Terradorm state?

If the space into which we are doing the restore has a more recen commit deployed, we need to run  `migrate` to sync the databse with the latest model definitions in the codebase.. We should typically avoid restoring into a space where an older commit is deployed.

If our database backup is somehow tagged with the corresponding commit id, we can ensure that any space that we want to restore to is first updated up to this commit.

I am concerned that using django commands for backups and restores will have challenges when the deployed commit in source and target spaces are not the same.

We need a similar process for our S3 buckets that host the pdf and xlsx files. I don't think we have any meta data bout these objects in our codebase - so, we don't have to worry about having to do anything similar to `makemirations`.

**Comment by jadudm** [comment]
So we're all clear:

This is a triage ticket.

My next step is to ticket out the work, which I want to involve creating one or more Google Docs that we can use to 1) collect questions, 2) answer them, and 3) then ticket out more work around this in an organized manner.

Please, lets not start a conversation thread on a triage ticket that was created yesterday to just *start* identifying the work. 

I'll capture these questions for you in a GDoc, and try and ticket out some of the steps around research, discussion, and decision making today.

**Comment by mogul** [comment]
> @jadudm , @mogul Is there a reason we want to use django to perform database backups and restores? 

The module we're using understands S3 and various other read/write locations, and will operate consistently without us writing any new tooling. It's well-tested and also uses the native `pg_dump`/`pg_restore` tooling internally. It can be configured to mail us if there are problems, handle rotations, encrypt backups, and so on. It can also handle backup/restore of media, including things we put in our private S3 bucket, which are as much a part of our application state as the DB content.

> Why can we not not use the native options provided by cloud.gov - see https://cloud.gov/docs/management/database-backup-restore/ ?

The process described there works from a local workstation, outside of cloud.gov. We do not want to include local workstations in the transport of data involved in our backups, particularly when it includes large amounts of file data, particularly when the intended destination is an S3 bucket. Also, this process is impossible to automate in CI/CD; we must not allow Moderate government data to transit GitHub's LiSaaS application runners. The process we're implementing now (running the backup/restore process with `cf run-task`) happens completely within cloud.gov.

> To get migrations right, it may be useful, and perhaps necessary, to know the last git commit that was applied to the environment where we are doing the backup. Is this stored somewhere, like in the Terradorm state?

We do the backup as a step just prior to deploying new application code in the GitHub Action workflow. By looking at the history of production deploys, we know exactly which code was deployed at the time of each backup; it's the code from the production deploy prior.

> If the space into which we are doing the restore has a more recen commit deployed, we need to run `migrate` to sync the databse with the latest model definitions in the codebase. 

Migrations run automatically on application instance 0 in the `.profile`, so making migrations happen post-restore is just a matter of running `cf restart-app-instance gsa-fac 0`. We can make that step part of the restore workflow so no one misses it.

> We should typically avoid restoring into a space where an older commit is deployed.

I think we all agree here; are you suggesting a problem to be resolved? (I'm presuming that our application code will balk if it sees a schema version in the DB newer than it is equipped to work with.)
 
> If our database backup is somehow tagged with the corresponding commit id, we can ensure that any space that we want to restore to is first updated up to this commit.

(See above; we can always get that info.)

> I am concerned that using django commands for backups and restores will have challenges when the deployed commit in source and target spaces are not the same.

Why, if we're just using the stock commands like `python manage.py dbbackup`? The process does not involve much if any of our own custom code. (Note also that the backups S3 bucket will be shared between the spaces that need access to it.)

> We need a similar process for our S3 buckets that host the pdf and xlsx files. I don't think we have any meta data bout these objects in our codebase - so, we don't have to worry about having to do anything similar to `makemirations`.

I _think_ this is all covered by the `mediabackup`/`mediarestore` commands that I mentioned above, though I would like someone who knows Django better than me to confirm that.

**Comment by mogul** [comment]
> Please, lets not start a conversation thread on a triage ticket that was created yesterday to just _start_ identifying the work.

Oops, sorry, I just saw this. 😳 I think you take from above my feelings here, which is that we're already in pretty good shape on all of these points.

**Comment by JeanMarie-TTS** [comment]
@mogul , your responses address most of my concerns. Relieved that we are using PG native commands for backup/restore rather than django commands.
Do we already have a check to ensure that the space where we are restoring to does not have an outdated codebase?

**Comment by jadudm** [comment]
I'm reasonably confident we don't yet have a restore.

This is why I wrote #2145. "...in order to move from a single script that dumps our database as a result of a cf task call to a reliable and robust process for dumping, verifying, and restoring our production data..."

We need to actually design those things. That may involve proposing a series of spike explorations that test what the features of this module do. But I also want us to have a way of verifying that the steps (dump, restore, etc.) did what we expected.

**Comment by JeanMarie-TTS** [comment]
@jadudm , if you've created a GDoc for this, can you include the link here please?

**Comment by jadudm** [comment]
I don't think I have. I ticketed this so that I wouldn't be doing the work, as there's a bunch of stuff on my plate already. Feel free to create whatever docs you need to collaborate on planning.
