### ISSUE TITLE
Document and practice incident response procedures

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2121]
Some people have fire drills. 

And, there are exit maps, and plans for how to do headcounts, etc.

We have no drills, no maps, and no way to do headcounts. 

What are our failure modes, how do we recover from them, and can we build some code to also check for things in terms of a "healthcheck." (Check tables exist, check services exist, etc.)

Do we have documented ways to recover from failures, and do multiple members of the team who can support debugging and recovery? (We do not want to have a lottery problem on failure recovery.)

**Comment by danswick** [comment]
This ticket needs some more detail before it can go into `Available`. 

cc @jadudm @Carley-Jackson

**Comment by jadudm** [comment]
We did this when we tackled bucket configuration with GSA IT.
