### ISSUE TITLE
Create a single intake form with all desired form elements

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2129]
Develop a Zendesk form that matches a Github ticket.

**Comment by Carley-Sullivan** [comment]
@LeoFotovich I've updated the ZD form to house all necessary data elements to kick off the ZD > GH workflow.

**Comment by Carley-Sullivan** [comment]
ZD form is ready for review.

**Comment by Carley-Sullivan** [comment]
@lauraherring here ya go: https://support.fac.gov/hc/en-us
