### ISSUE TITLE
Migrate relevant FAC wiki info, then close the wiki down

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2139]
We advertise

https://github.com/GSA-TTS/FAC/wiki

as part of our communications. It is painfully out of date.

1. Should we get rid of the wiki? 
2. If not, what do we use it for? Why?
3. If we keep it, it needs gardening. Badly.
4. If we keep it, we need process around it.

**Comment by danswick** [comment]
We should gather any relevant info that doesn't exist elsewhere, then shut the Wiki down and remove references from public docs.

**Comment by lauraherring** [comment]
I'll begin reviewing these documents and making recommendations on keep/trash.

**Comment by lauraherring** [comment]
Confirming that everything of use/relevancy to the team is stored elsewhere (either [the FAC Google Drive](https://drive.google.com/drive/folders/1fccgEQoY81Ms9_C0k7A-2TQvpjV7sYhd) or [FAC Mural room](https://app.mural.co/t/gsa6/r/1550267447734)).

I think we're good to shut down the wiki and move forward with deleting it.

**Comment by lauraherring** [comment]
Realizing I should have tagged @danswick and @jadudm in my previous comment...

**Comment by danswick** [comment]
I went ahead and deprecation message to the main wiki page and deleted all of the other pages. Wikis get their own separate git repos, so we can just clone the Wiki's git repo and revert to an earlier commit if we ever need to restore something.

**Comment by jadudm** [comment]
SGTM, and TY! And, yes, I knew they were repositories at some point, so that makes total sense.
