### ISSUE TITLE
Remove transition_to_in_progress

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2141]

**Comment by jadudm** [comment]
@tadhg-ohiggins knows what this means. He will add any additional notes to bring it into `available` or `in progress`.

**Comment by tadhg-ohiggins** [comment]
I'm fairly certain that related to [Add barebones feature allowing users to send submissions back to in progress from ready for certification](https://github.com/GSA-TTS/FAC/pull/2572) we actually need to support transitions to `in_progress` and thus should not remove it after all.
