### ISSUE TITLE
Update dates re: tribal submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2147]
Now that we are moving tribal audits forward, we should update the site content to reflect that.

```[tasklist]
### Tasks
- [x] Remove the March date, if/where it exists.
```

**Comment by lauraherring** [comment]
Confirmed March date isn't listed anywhere on static site.

**Comment by lauraherring** [comment]
@James-Paul-Mason You can leave a comment here on this ticket for any places you find a March date listed in the app

**Comment by James-Paul-Mason** [comment]
@jadudm Yesterday in Sinister Side Sync, I believe you were able to determine that the app does not have text regarding tribal and March. Just wanted to double check. I am happy to check via a test submission in the app.

**Comment by jadudm** [comment]
I did check. I think it would be good to do a test submission against `staging` regardless, and use that as an opportunity to walk through the submission/app. :thank-you:

**Comment by James-Paul-Mason** [comment]
Will do! @Leighdiddy can you send me the updated testing workbooks when you can (or direct me to their location)?

**Comment by jadudm** [comment]
"Notes to SEFA" saw an update last night. It should be our last workbook update before we go live (and, therefore, our last workbook update barring any significant finds). @Leighdiddy , happy to help update the test version so that it is ready for use.

**Comment by James-Paul-Mason** [comment]
Can confirm that there is no mention of March date.

**Comment by James-Paul-Mason** [comment]
Moving to "Done" on the board unless there are any objections.
