### ISSUE TITLE
TTS Launch Checklist

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2159]
What it says.

**Comment by thebestsophist** [comment]
[Done](https://docs.google.com/spreadsheets/d/1IP2NLQchFQJi8eoI1V9RdWbOZq44tt_VB5Rd8nu45mo/edit#gid=1232597517)

**Comment by thebestsophist** [comment]
(will need to tackle some things around standard practices for testing against browsers and devices, but otherwise we look good)
