### ISSUE TITLE
Back End - SingleAuditChecklist model updates to store SF-SAC General Information section data

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#216]
Breakout task for https://github.com/GSA-TTS/FAC/issues/185

**Background**
The current `SingleAuditChecklist` model contains fields covering Auditee and Auditor Information. We need to review the current implementation to ensure we're able to receive and store all fields present in the SF-SAC form and our current mock-ups.

- [ ] Enumerate form fields present on our [current mock-up of the General Info page](https://www.figma.com/file/ty7iZnrnpBO5OlhRoDQd4m/FAC-Playground?node-id=1899%3A8010)
- [ ] Review existing, update where necessary, and create new [field definitions](https://docs.djangoproject.com/en/4.0/ref/models/fields/) within  the `SingleAuditChecklist` model so that we can store all data for each of the fields identified above

**Comment by Jkrzy** [comment]
Once we tackle this slice, we can use this issue as a template to complete model updates for the remaining SF-SAC Sections.

**Comment by Jkrzy** [comment]
@MelissaBraxton, In reviewing the SF-SAC form and instructions I noticed the "Secondary Auditors" question and addendum on the bottom of the General Info section. 

I don't see this reflected in the current mock-up and wanted to confirm if we needed to implement that functionality or not.
<img width="343" alt="Screen Shot 2022-05-17 at 4 44 37 PM" src="https://user-images.githubusercontent.com/3485564/168906909-9a71dc0d-a70a-4034-b946-d5ea6c4379c5.png">

**Comment by MelissaBraxton** [comment]
Tagging @sreuber as you work on #185 - We do need this. I think it was an oversight and needs to be added. 

We will also need to build logic in here to toggle lock/unlock of the **secondary auditors** page of the SF-SAC.
