### ISSUE TITLE
FAC - Bug: sac is not being updated with cognizant / oversight in run_2022 support command

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#2162]
### Describe the bug

Running the 'run_2022' command with the latest jmm/cog_using_history code, the end result is
"Processed all 36966 rows.
Found 1703 cog and 1 over mismatches."

But, the expected cog mismatches is < 20.

post_save for sac is not working. 

### Steps to reproduce the bug

Run 'run_2022' command. 

### Expected Behavior

Expected cog mismatches is < 20.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by gsa-suk** [comment]
Found issue with signals in post_cog_assignment.  This runs asynchronous with the calling function.  sac.cognizant_agency is not getting updated before it is being checked in run_2022 function.  Saving sac.cognizant_agency in assign_cog_over instead of the post_cog_assignment signal method.  Tadhg and I have tested and updated the tadhg/cognizant_oversight branch with this change.

**Comment by tadhg-ohiggins** [comment]
Note: the actual PRs that brought the fix into main were https://github.com/GSA-TTS/FAC/pull/2156 and then https://github.com/GSA-TTS/FAC/pull/2065
