### ISSUE TITLE
Update app nav to match static site

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2169]
We want the app nav to match the nav on the static site. 

We will not, for the moment, add site search to the app. This searches the static site, and does not search audit data... hence could be confusing to users in the app.

We will ticket design work around that question, however.

**Comment by jperson1** [comment]
1. Resources & policy links should be updated to match the static site (a few are missing)
2. Banish the FAQs and Contact Us sections in favor of the Zendesk TWO Support link

**Comment by Leighdiddy** [comment]
Here is a mockup: 

![Certification step 3480w](https://github.com/GSA-TTS/FAC/assets/119363060/18229866-83b2-4175-a608-90a58f09b75d)

**Comment by Leighdiddy** [comment]
You can ignore that this is a page from the app side, just follow the top nav layout: https://www.figma.com/file/lnkXJTfKzD3YBhiJZ2QFEv/FAC-Source-of-Truth?type=design&node-id=1%3A31587&mode=design&t=aEYotWGg1tzxHEQQ-1

**Comment by jadudm** [comment]
This is completed and pushed through to prod.
