### ISSUE TITLE
Revisit sequence numbers

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2174]
Per discussion with @jadudm, we should be preserving item order when loading from workbooks, so sequence _should_ be preserved. However, there are still some `seq_number` properties in workbook templates and schemas. Should those be removed? Or should we make it standard across workbooks? Either way, `seq_number` should be consistent.

**Comment by jadudm** [comment]
This is desired by users, as it brings clarity to API work. However, we should discuss further. Leaving open, and moving to Triage for discussion.

**Comment by danswick** [comment]
I think this is covered better in other places.
