### ISSUE TITLE
Come up with an approach for progress and form page saving

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#218]
Background
We need a mechanism to manage page state of form progress

<img width="254" alt="Screen Shot 2022-05-17 at 2 01 46 PM" src="https://user-images.githubusercontent.com/100610443/168879891-9912d5ca-494d-4c1c-a45f-6ea78503365b.png">

Acceptance criteria
- [ ] We've come up with a model (or extension of the SAC model) to manage state
- [ ] We've found a way to surface that via the API to show what steps are available to a user
- [ ] Nail down the urls for the steps we have implemented so far (and maybe a naming scheme for future steps). Currently they’re /audit/new/step-{1,2,3,…} .

**Comment by petermarks-gsa** [comment]
@heymatthenry Flagging this for your awareness and general clarification.

**Comment by geekygirlsarah** [comment]
For the record, @NicholasKramer and I looked into this, and heard that @tadhg-ohiggins determined there shouldn't be a way of saving state, it's generated from the data that is completed. (i.e. we don't save they're on page 3, we look at the data to see they've completed data for page 2 so they're on page 3.) But this might require more conversations from past thoughts from Tadhg/Joe, so it's blocked for now.

**Comment by jadudm** [comment]
I think I've had conversations with Joe and Tadhg about this.

If we maintain an actual tracker of where they are (a row or other space in the store that says "Matt has completed the following fields," or "Matt is on Page 3"), then we need to make sure that *never* gets out of sync with the data in the DB. It is, fundamentally, state derived from my actual (not-necessarily-stepwise) completion of the form.

Put another way, in terms of code, the function `getCurrentUserForm` (pretend with me on that existing for a moment...) should return enough information that we can compute where they are. If we later decide that we are going to store this somewhere in the data model, then queries like `getCurrentUserForm` will get refactored to return the cached state. 

In short, my 2p would be to proceed as if we can determine the state (current page, etc.) from a query. If we need to optimize that away at some point, we can.

Knowing the state of the form doesn't necessarily determine what action we should take, however. It would be good to have a/some storie(s) for this. Given that users can skip around the form (I think that's true), we're essentially going to have to *choose* and document a behavior. That behavior could be:

1. Always starting on the first page.
3. Always start on the first page they completed in part.
4. Always start on the last page they completed in part.
5. Always start on the first page they completed in whole.
6. Always start on the last page they completed in whole.

(Some of those might be the same...)

So, really... the question of where they should start is arguably arbitrary, without a user story or decision as to what behavior we're going to support. Something consistent would be good, and I'd be fine with something simple and arbitrary (e.g. start on the first page they completed in part) until such time as we can address it with research, so we can communicate that to the user. @MelissaBraxton... ?

**Comment by MelissaBraxton** [comment]
If we are talking about happens when they log back in to pick up working on an unsubmitted form, it's safe to assume #1 above (Always starting on the first page) is the behavior we should build in to start. 

Multiple people could be working on these and will have entered bits of data on any number of pages...

**Comment by geekygirlsarah** [comment]
I can look this back over and let you all know.
