### ISSUE TITLE
FAC - Bug: Corrections to static site header UI

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#2189]
### Describe the bug

The static site is currently displaying the wrong logo in the header, and the top nav options are the wrong color. Please update the logo with the attached svg, and update the hex on "News Resources&Policy Support" to 171717. 
![full_logo](https://github.com/GSA-TTS/FAC/assets/119363060/adb6362b-301a-4f14-ad69-bb7bf57ca327)

### Steps to reproduce the bug

see above

### Expected Behavior

see above

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jperson1** [comment]
Closed as completed by https://github.com/GSA-TTS/FAC/pull/2256
