### ISSUE TITLE
Decide how we handle submission processing 

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#219]
**Background**
We talked with Census processors and learned about their work and role in processing FAC submissions. GSA will need to determine how we handle processing as we go forward. Considerations and recommendations are[ here](https://docs.google.com/document/d/1ApHaC5_daADSJzrUnWk4P6Oe-OYmJd6570ZmBiJWCk4/edit#).

**Comment by petermarks-gsa** [comment]
@MelissaBraxton I copied this context over to the new issue. Going to close this and go with new issue as I'm linking to it in a few places.
