### ISSUE TITLE
replace USWDS favicon

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#2190]
Currently, fac.gov uses the USWDS favicon and app.fac.gov doesn't have one. They should both use the favicon for fac.gov

- [ ] replace favicon on fac.gov
- [x] add favicon to app.fac.gov

[Logos available in slack](https://gsa-tts.slack.com/archives/C03QGB056KB/p1695245684932969?thread_ts=1695240003.607049&cid=C03QGB056KB)
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by heymatthenry** [comment]
Favicon is [up on dev](https://fac-dev.app.cloud.gov/). Will be live on the next prod deploy.
