### ISSUE TITLE
[HD]: Notes to SEFA workbook indicates a field is missing when it is filled out

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2198]
### Scenario

A user might have a workbook that is "out of date." Currently, some "Notes to SEFA" workbooks are in circulation that lack a Y/N column. We should have a FAC entry that says "if you get an error about your workbook missing a column, or being the wrong version, download the newest template [link], copy your data into that workbook, and try to upload the workbook again."

```[tasklist]
- [x] Write FAQ entry
- [x] Product "LGTM" signoff
- [x] Plain language review
- [x] Transfer into ZD
- [ ] Reply to user w/ pointer to ZD entry
- [ ] Close ZD ticket
- [ ] Close this ticket
```

### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/34

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

I am unable to upload the notes to the SEFA workbook. It says  A field is missing in the uploaded file. Ensure you have uploaded the correct workbook, or contact an administrator. Field error: 'contains_chart_or_table'

I’ve tried everything. Please advise.

This is for Gooding Senior Housing Association Inc FYE 5/31/2023. UEI = RBDDGXEAKZN3

**Comment by Carley-Sullivan** [comment]
From convos w/ MJ, it sounds like this user is using an outdated WB.  They will need to download the latest WB.

We should add a new FAQ in re: workbooks -> "If you have issues uploading your WB, please download the latest version of the WB and copy and paste your info into it."  Something like that...

**Comment by jadudm** [comment]
That's a good idea on the FAQ entry. I'll update this ticket to reflect that, and move it into the "Available" column for content...

**Comment by jadudm** [comment]
Draft content

https://docs.google.com/document/d/15aYxM7pVAaCbpOuWQwLoeiCuOrsxQSueOnaJ8myFp0k/edit

**Comment by Carley-Sullivan** [comment]
@lauraherring @James-Paul-Mason Please review this FAQ.

**Comment by James-Paul-Mason** [comment]
Just one comment about paragraph breaks. Looks good otherwise.

**Comment by lauraherring** [comment]
Made one small change, looks good to me.

**Comment by James-Paul-Mason** [comment]
@lauraherring Nice fix! Good to go

**Comment by lauraherring** [comment]
@James-Paul-Mason Great! Then this is ready for ZD imo.

**Comment by James-Paul-Mason** [comment]
@lauraherring This FAQ did not have a full question listed in the title. Could you make sure that the question I wrote for this FAQ is good to go? If so, I will publish to Zendesk. 

https://docs.google.com/document/d/15aYxM7pVAaCbpOuWQwLoeiCuOrsxQSueOnaJ8myFp0k/edit

**Comment by lauraherring** [comment]
@James-Paul-Mason Yep, this one is good to go. It's broad enough to cover errors for any workbook, not just Notes to SEFA.

**Comment by James-Paul-Mason** [comment]
@LeoFotovich @alyssamwong I have created and published an FAQ for this issue. 
https://fac-gov.zendesk.com/knowledge/editor/01HBRTZM6SQMZ1QC40CFM2HZ9E/en-us?brand_id=7095561790861
