### ISSUE TITLE
Spike: File downloads

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#2202]
We need to frame up a general approach for supporting the downloading of files from the app. This includes audit report PDFs and, later on,  Excel workbooks.

Because some submissions are not disseminated publicly, we also need a mechanism for conditionally restricting download access. For web users, this means restricting downloads to those with `Access` to the submission. For API users, we'll need a way for postgrest to perform some kind of authorization handshake with the app (because API calls are authenticated via api.data.gov keys and not Login.gov).

**Comment by tadhg-ohiggins** [comment]
## Feature sketch

Primarily pulled from discussion on j2023-09-20.

Note that while we may re-use some of the code to handle downloading PDF and Excel files on the submission side, this feature is focused on downloads for the dissemination side.

-   One endpoint for both public and private PDFs.
-   The endpoint is handled by Django.
-   The URL path includes the ``report_id`` for its audit.
    *   Initial idea for the path: `/files/reports/〈report_id〉/`.
    *   The filename when downloaded should be this (which may mean we should change what we’re currently saving to S3): `〈report_id〉--〈lowercase UEI〉--audit-report.pdf`
-   The first thing the view does is check for the existence of a PDF matching the URL path. Which raises another point:
    -   Do we report non-existence of audits versus privacy of audits, or is that some kind of security issue?
-   Once we know whether or not the PDF exists and has been disseminated, check the privacy status of its audit.
-   If it’s public, get a quick-expiry S3 link and either forward the client to it (my preference) or pull it and then pass the contents to the client.
-   If it’s private, check to see if we have a login.gov user in session. If we don’t, inform the user that it’s private and prompt for login.
-   If we do, check the accesses for that audit to see if the user is associated with it (any role).
-   If they do, get them the file by the same process as above.
-   If they don’t, inform them that they don’t have access to that file.

**Comment by jadudm** [comment]
So, we have established that the *only* thing we hold back in the case of Fed-only audits is the PDF.

So, there is no security issue in saying "you do not have permission to view this file." That the audit report exists is *not* a secret. 

I agree with everything there (until I panic and come up with something), and we can also decline to show a link to the PDF on search results if someone doesn't have perms? But, we should do as you describe regardless, obviously.

**Comment by jadudm** [comment]
Use cases we want to capture...

## For the web access

* Public user, from the public web (not logged in) accessing public data (PDF, files)
* Logged in user accessing public data
* Logged in user accessing tribal data
* Have a list of users who should have that access

## For the API

* Public API key. Hits the endpoint to ask for access, denied.
* Federal API key. Hits the endpoint, gets a token. Then hits view with token.

**Comment by jadudm** [comment]
Further to this:

1. For the first increment, it is safe to assume everyone will have to log in. We can do the work to move the search outside the login boundary as part of a future ticket/future work.
2. We are interested in supporting the auth question for PDFs and XLSX docs. We know we need to be able to download those as part of search results, and we know we need to suppress the PDF and some of the XLSX docs. 
3. We assume some additional data work will be needed. While we could probably do this all through the auth objects, it might be easiest to have a table where we maintain email addresses for the people who have permission to access tribal audit data. 
4. It feels unlikely that we will have other kinds of privs. Right now, it is either tribal or public. That feels like it will not change under us in the near future.
5. The API is different enough that we will not worry about it in the spike. That is, the ability to generate a pre-signed S3 URL may be something we reuse, but most everything about the API is different from the web-based download pathway.


We expect to want to be able to generate and download database dumps at some point. Those will be either public or containing tribal data. However, they are *different*. That is, an XLSX or PDF document is attached to a record row in our database that tells us if the data is public or private. The dumps will be independent, and therefore are different enough that we will ignore their possibility for the moment as well.

**Comment by timoballard** [comment]
@jadudm @tadhg-ohiggins 

[Sketched some things out in a branch](https://github.com/GSA-TTS/FAC/pull/2284/files) to demo one approach to separating the access control from the file download machinery. The `FileDownloadView` is meant to capture the web entrypoint, while the `ApiFileDownloadView` is meant to capture the API entrypoint -- the `ApiFileDownloadView` in particular isn't "real", but is just stubbed in to get a feel for what the code reuse would look like

**Comment by timoballard** [comment]
Note that the `FileDownloadView` does work if you manually hit the URL in a browser, e.g.

http://localhost:8000/audit/files/report/2023SEP0001000001
