### ISSUE TITLE
Test tabular data backup integrity

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2215]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** ensure our data is correct and valid (i.e. not malformed or corrupted)
**as a** product owner or anyone paranoid about data
**I want** to validate in a repeatable that we can access and test data before and after a backup/restore.

We'll do this work in `dev` to start, and then `staging`. 

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: We have run a database dump.

**Given**  that we want a repeatable validation on export 
**when**  the DB is dumped to an S3 bucket

```[tasklist]
### We'll know we're done when
- [x] We know the state of the DB before export
- [x] We do the export
- [ ] Restore tables as temporary/virtual for comparison
- [ ] We validate the captured "before" state with the re-imported state
- [ ] We remove the temporary tables
- [ ] BONUS: Dump the data as CSV alongside binary formats *just in case*.
```

Note: By "know the state of the DB before export" we mean that we have a way of generating some state we can compare "before" and "after." The hard way would be to checksum every row in every table. `psql` may have tooling to support us here.

Note: If we restore tables to a live context, we can then (possibly) do validation table-to-table. Implementation TBD by the team doing the work.

Note: We could also achieve this (not ideal) by dumping data to CSV, and then doing a value-by-value comparison. Could be expensive in time.

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Engineering shepherd: @danswick 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

While it is true that media backup and restoration is linked to database backup and restoration, it involves a separate set of concerns and considerations for validation that we do not yet understand. 

The purpose of  this work is to first get the *tables* backed up. It is understood and media is intimately linked to the tables. But, in terms of agile increments, we need to get something working, with confidence, and backing up and restoring our tables is the first step.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

None. All work happens within our SSPP/security boudaries.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by danswick** [comment]
Rolled into #3595
