### ISSUE TITLE
Implement on-demand restore (db) tooling in the codebase

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2217]

**Comment by JeanMarie-TTS** [comment]
@asteel-gsa What's the design for this? A simple solution is to have a GH workflow for each space that we need to do a restore, have this workflow be run manyally and only by a FAC Admin.

**Comment by asteel-gsa** [comment]
> @asteel-gsa What's the design for this? A simple solution is to have a GH workflow for each space that we need to do a restore, have this workflow be run manyally and only by a FAC Admin.

Any workflow is accessible by anyone, i don't know if there is an easy solution to restrict it. And this is already ready with #2246

**Comment by JeanMarie-TTS** [comment]
@asteel-gsa 
We definitely need to restrict who can do a restore.
We should research how best to enforce this. We can, for example, determine who triggerred the workflow and blt run it if the actor is not part of a list of users.
As far as I see, the PR has the plumbing to do the restore. But we still need to invoke it without having to ssh to the box.

**Comment by asteel-gsa** [comment]
> @asteel-gsa We definitely need to restrict who can do a restore. We should research how best to enforce this. We can, for example, determine who triggerred the workflow and blt run it if the actor is not part of a list of users. As far as I see, the PR has the plumbing to do the restore. But we still need to invoke it without having to ssh to the box.

We will be, when we are ready for it. Until this morning, we were not ready to have restores as part of workflows. `if: contains('["person1","person2"]', github.actor)`

**Comment by danswick** [comment]
Rolled into #3595
