### ISSUE TITLE
Test tabular data restore integrity in `dev`

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2218]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** ensure our data is correct and valid (i.e. not malformed or corrupted)
**as a** product owner or anyone paranoid about data
**I want** to validate in a repeatable that we can access and test data before and after a backup/restore.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: We want to run a DB restore.

**Given** that we want repeatable validation on import
**when**  we trigger a restore

```[tasklist]
### we'll know we're done when
- [ ] Manually run/test `dbrestore` and `mediarestore` with manual inspection to understand what these tools do and how they work.
- [ ] Run `dbrestore`
- [ ] Using the same/reverse process as above, validate the state between the dump and the now-restored tables
```

Note: We do not currently know what `dbrestore` or `mediarestore` do. Therefore, it is not enough to "just run dbrestore." We need to know if these tools drop the existing tables, append, etc. Therefore, we need to test this more/research it more in order to implement a restore that has integrity. Document findings as part of the comments in this ticket to start. 

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Engineering shepherd: @danswick 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

While it is true that media backup and restoration is linked to database backup and restoration, it involves a separate set of concerns and considerations for validation that we do not yet understand. 

The purpose of  this work is to first get the *tables* backed up. It is understood and media is intimately linked to the tables. But, in terms of agile increments, we need to get something working, with confidence, and backing up and restoring our tables is the first step.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

None. All work happens within our SSPP/security boudaries.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by JeanMarie-TTS** [comment]
@jadudm We can test after every restore if the database metrics natch what was collected prior to the backup. In addition, it would be nice to have a FAC-specific smoke test to confirm that nothing is corrupted. Perhaps, you can try to do an automated end to end submission and then delete and data created by the smoke test. Please scope out and prioritize this. We should get a few more people to brainstorm on this.

**Comment by danswick** [comment]
Rolled into #3595
