### ISSUE TITLE
Implement mechanism to collect and store metrics about restore operations

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2219]

**Comment by JeanMarie-TTS** [comment]
- [ ] We have a django command to collect basic metrics about fac data. 
 `python manage.py collect_metrics > metrics.out `
- [ ] The plan is to store these metrics in a log folder in the `backup` s3 bucket along with some info about the backup itself. This metrics will be collected prior to a backup.
- [ ] The netrics will also be collected and stored after every restore.
- [ ] We need to get AWS CLI installed in all our environments

**Comment by danswick** [comment]
Rolled into #3595
