### ISSUE TITLE
Mock remaining SF-SAC form sections

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#222]
**Background**
This iss covers the design work to mock up the remaining sections of the form SF-SAC. We don't yet have issues that cover the implementation of these pages, so I've added the creation of new front/back end engineering issues that should follow this work as a task below. 

**We'll know we're done when...**
We have initial design mocks that depict how users will enter data into the following form pages:
- [x] Findings text 
- [x] CAP text
- [x] Additional EINs
- [x] Additional DUNS
- [x] Secondary auditors

**Tasks**
Mock pages
- [x] Findings text 
- [x] CAP text
- [x] Additional EINs
- [x] Additional DUNS
- [x] Secondary auditors
- [x] Design Lead reviews 
- [ ] Collaborate with PM and at least one engineer to write new issues that cover the front and back end implementation of these pages.

**Comment by MelissaBraxton** [comment]
Recommend deleting the last task from this issue and added a task for PO review. We are going to want to test these with users before we create any new engineering issues here. We will further specify expected behaviors as a part of writing up engineering issues.

Links to form section mocks:

[Award findings](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2837%3A13976)
[Findings text ](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2837%3A14290)
[CAP text](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2837%3A14482)
[Additional EINs](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2618%3A12074)
[Additional UEIs](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2618%3A12313)
[Secondary auditors](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=2618%3A12552)

Heads up, @petermarks-gsa

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Sounds good on scratching "Collaborate with PM and at least one engineer to write new issues that cover the front and back end implementation of these pages."

**Comment by MelissaBraxton** [comment]
With removing the last acceptance criteria here and the creation of #255, Can we call this done?

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Yep, let's call this done.
