### ISSUE TITLE
Only accept "Active" UEIs at validation time

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2228]
Per convo w/ @timoballard . 

> SAM returns two fields ueiStatus (in this case "Active"), and `registrationStatus` (in this case "Inactive"). I'm not sure how those two fields relate, but we're currently only looking at `ueiStatus` in our UEI validation check

We want to 

```[tasklist]
### We'll know we're done when....
- [ ] We have tightened the validation at the start of submission to accept UEIs that are active.
- [ ] A sensible error message is presented to the user if an inactive UEI is retrieved.
- [ ] SHOULD A pointer to sam.gov docs about renewing/refreshing a UEI is presented
- [ ] Content reviews the error message for plain language.
- [ ] A unit test is added for a currently inactive UEI.
- [ ] An ADR is written about this decision.
```

The unit test is tricky; a UEI might be inactive now, but become active later. For now, we can incorporate the test, and decide what to do later if the UEI becomes active and our test begins... _failing_?

**Comment by timoballard** [comment]
Per discussion on 9/26 w/ @jadudm, @tadhg-ohiggins, @danswick @JeanMarie-TTS, next steps here pending clarification on:
- what exactly `registrationStatus` means
- whether or not the FAC needs to be concerned about `registrationStatus`

**Comment by jadudm** [comment]
We addressed this, and an ADR will be written about it. Closing this ticket.
