### ISSUE TITLE
fac.gov / app.fac.gov do not appear in the DAP data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2229]
It appears that

* `fac-dev.app.cloud.gov`
* `fac-staging.app.cloud.gov` 

appear at 

https://analytics.usa.gov/general-services-administration/data/

but 

* fac.gov
* app.fac.gov

do not. 

We should see what needs to be done for the DAP code to log visits to our production sites.

**Comment by danswick** [comment]
Replaced by #2813
