### ISSUE TITLE
Back end - Date picker

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#223]
Breakout of https://github.com/GSA-TTS/FAC/issues/127

We'll know we're done when 
Date picker validates that given dates are in the appropriate year. For MVP, we only care about FY22.

**Comment by petermarks-gsa** [comment]
@NicholasKramer Can you please link your PR to this when you get a chance?

**Comment by NicholasKramer** [comment]
https://github.com/GSA-TTS/FAC/pull/206

**Comment by petermarks-gsa** [comment]
@NicholasKramer Saw this got merged. Good to close this issue out?

**Comment by NicholasKramer** [comment]
Yes, closing issue!  We can look at this again if the fiscal year end date doesn't cover it.
