### ISSUE TITLE
[HD]: User is looking for search capability

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2239]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/33

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [X] other

### What browser did the user report as using?

None

### What happened?

If you are one of the Federal Programs listed when a Contracting Entity & CPA submit an audit to FAC for 2023, do have to a sign-in set-up or is there a place on the website to view a single audit?

**Comment by jadudm** [comment]
Draft response

https://docs.google.com/document/d/1WdgcZQwOm1egmj2dirNXeKQXGK7o_qa_P8gKuDv_o4k/edit

**Comment by Carley-Sullivan** [comment]
LGTM. @lauraherring @James-Paul-Mason this is ready for review.

**Comment by lauraherring** [comment]
I updated the copy in the doc, looks good to me now.
