### ISSUE TITLE
[HD]: User wants search training 

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2240]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/38

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [X] other

### What browser did the user report as using?

None

### What happened?

I am looking at the website and do not see links for Federal employee training. I download reports for resolution and do not see how to do it with the GSA database.  I am hoping that it will be comparable with the Census DB.

**Comment by danswick** [comment]
Should be well covered by documentation now.
