### ISSUE TITLE
[HD]: Federal Award Findings Text WB results in error 404

### ISSUE THREAD

**Issue by Carley-Sullivan** [GSA-TTS/FAC#2242]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/39

https://fac-gov.zendesk.com/agent/tickets/56

https://fac-gov.zendesk.com/agent/tickets/60

https://fac-gov.zendesk.com/agent/tickets/62

https://fac-gov.zendesk.com/agent/tickets/65

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Microsoft Edge

### What happened?

First Ticket:

The link for workbook 4 is not working and I keep getting message below. 

404 / Page not found

You might want to double-check your link and try again, or return to the [homepage](https://www.fac.gov/).

This is a default 404 page for [Pages](https://cloud.gov/pages), a hosting service for federal websites.
-----
Second Ticket:

Reoccuring issue - User cannot download workbooks 3 and 4 links from home page. “404/Page not found. You might want to double-check your link and try again, or return to the homepage.”  All other workbooks download aside from 3 and 4.

**Comment by jadudm** [comment]
Seems to be working? Suggest they reload?

**Comment by alyssamwong** [comment]
@jadudm It seems users are having trouble downloading workbooks 3 and 4. I added another 2 tickets that are experiencing these issues today. It's odd because I was able to download them from the site without problems

**Comment by jadudm** [comment]
Ah. We determined this is in the application itself, not the static site.

We have moved a ticket through that fixes it. I'll comment here when it is pushed to production, which will probably be tomorrow (Friday).

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/pull/2289

**Comment by jadudm** [comment]
These are all fixed. We need to reply to the users as part of our update to the website fixes on Tuesday.
