### ISSUE TITLE
[HD]: Delete a Duplicate Report / FAQ

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2251]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/42

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

Ticket: We had a slight hiccup with a client where they entered in a duplicate FAC submission instead of certifying the submission that we had already created. Can you please delete Report ID 2022FEB0001000042? Or is there another way that we should be deleting invalid submissions?

**Comment by Carley-Sullivan** [comment]
I'll write an FAQ for this.

**Comment by Carley-Sullivan** [comment]
FAQ is drafted here: https://docs.google.com/document/d/1WxnGx3f_RydzFooV8u52fmxQaFtWeBori_EsYOASCC0/edit

Ready for review.

**Comment by Carley-Sullivan** [comment]
@lauraherring @James-Paul-Mason Can either of you review the FAQ? Once it has your blessing I will publish to ZD. Thanks!

**Comment by James-Paul-Mason** [comment]
Can do for both! I should be able to do this tonight.

**Comment by James-Paul-Mason** [comment]
@Carley-Sullivan please see the Google doc for a couple of quick comments.

**Comment by jadudm** [comment]
Made an edit or two based on @James-Paul-Mason 's comments.

**Comment by lauraherring** [comment]
I took a pass at writing a simpler version this morning and added it to the Google doc.

**Comment by Carley-Sullivan** [comment]
Changes look good. Publishing to ZD and closing ticket
