### ISSUE TITLE
[HD]: Lock for certification / FAQ

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2252]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/43

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

User cannot return to edit their submission form after checkmarking certification.

**Comment by Carley-Sullivan** [comment]
I'll write an FAQ for this

**Comment by Carley-Sullivan** [comment]
FAQ is ready for content review here:
https://docs.google.com/document/d/1rEhVmZYx7khcYNAmcAFh9h23KpsRDrx93TqOVpXt8oE/edit

**Comment by Carley-Sullivan** [comment]
@lauraherring @James-Paul-Mason Can either of you review the FAQ? Once it has your blessing I will publish to ZD. Thanks!

**Comment by James-Paul-Mason** [comment]
This FAQ is good to go.

**Comment by Carley-Sullivan** [comment]
Thank you for the review. Publishing FAQ to ZD and closing ticket
