### ISSUE TITLE
[HD]: ALN invalid error message

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2258]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/50

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/folders/1JFywl9FYvhNChNnhu2sKyrRNq1sJE-ih?usp=drive_link

### What happened?

User experiencing a validation error when using a ALN number referenced from the excel workbook.

**Comment by jadudm** [comment]
Do we know what ALN, and did they provide a workbook?

**Comment by alyssamwong** [comment]
They stated ALN 27.011. Workbook is linked to google drive folder above.

**Comment by jadudm** [comment]
This is addressed by #2440.
