### ISSUE TITLE
Update language in fac.gov re: tribal data collection

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2268]
Still says we are not collecting data. Need to update the announcements section to reflect readiness the week of October 2nd.

https://www.fac.gov/info/updates/

**Comment by James-Paul-Mason** [comment]
Section: "For grantees and auditors" (final bullet point in that section)
Revision: "The FAC will be ready to accept submissions for Indian tribes and tribal organizations the week of October 2nd."
Note: Along with tribal organizations, the original sentence in the Updates section also states that the FAC won't be accepting submissions for Alternative Compliance Examination Engagements (ACEE). I want to make sure that ACEE in covered in the Updates section, but I am not sure if we are accepting their submissions the week of October 2nd as with tribal. 
@lauraherring Would you be able to help clarify the ACEE issue? Also, if desired, perhaps I could train on how to make updates to the static page.

**Comment by lauraherring** [comment]
@James-Paul-Mason From my understanding, ACEE is still not on the roadmap and will not be part of the Oct. 2nd update.

I think we should remove the Tribal part from that last bullet, like you've mentioned, and also add a new bullet to the General updates section that says "The FAC is now accepting single audit submissions for Indian tribes and tribal organizations."

**Comment by James-Paul-Mason** [comment]
@lauraherring Thank you! Your solution sounds perfect to me.

**Comment by jadudm** [comment]
That sounds like a good idea. Go for it.
