### ISSUE TITLE
UEI bug banner

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#2269]
# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: We have a bunch of UEI problems, and want to alert the users.

**Given**   that we have a bug that is not in our control
**when**  users hit the app
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] a banner with the following language is part of the app
- [ ] it should have a color that stands out (pale yellow or similar?)
``` 

The language should be

> We are aware some users may not be able to validate their UEIs. We have traced the issue and are working with sam.gov to implement a fix as soon as possible.

This does **not** need to be added to the static site at this time.

Original ticket follows

----

add banner text to site that explains that there is a known issue with some UEIs

[draft](https://docs.google.com/document/d/167GDX2MQJWYjeSAHwiNkfOD9x1yU36Qb6WcxmHC1fZU/edit)

- [ ] add banner to static site
- [ ] add banner to app

**Comment by thebestsophist** [comment]
@lauraherring @jadudm wanna take a look? at the draft text?

**Comment by lauraherring** [comment]
@thebestsophist I took a look and made some suggestions in the doc.

**Comment by jadudm** [comment]
Added my `LGTM` in the doc.

**Comment by jadudm** [comment]
No longer needed.
