### ISSUE TITLE
[HD]: Changing user form data / FAQ

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2272]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/49

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

User input incorrect email address when creating new audit. Changes/updates to the form cannot be made after creation. Add FAQ that a new submission is required to correct the issue

**Comment by James-Paul-Mason** [comment]
@lauraherring Would you mind taking a look at this FAQ draft? Any suggestions/comments welcome.https://docs.google.com/document/d/1Fe7JO8QiX1cZwYvwmpddHRZU3OtRJ_z6CSJl-m1rXVk/edit

**Comment by lauraherring** [comment]
Hey @James-Paul-Mason, I took a look and re-drafted it based on my understanding of the question. Right now, users can't update email addresses at any point once they've started a single audit, not just after they've hit submit. Let me know if you have any questions.

**Comment by Carley-Sullivan** [comment]
@lauraherring @James-Paul-Mason draft looks good to me.

**Comment by James-Paul-Mason** [comment]
@LeoFotovich @alyssamwong Please note a new FAQ has been published for this issue. 
https://fac-gov.zendesk.com/knowledge/editor/01HBRTHFQVTM6XABE4EAZHDBA2/en-us?brand_id=7095561790861
