### ISSUE TITLE
[HD]: When is search and training available FAQ

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2273]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/38

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [X] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

We will need an FAQ on when search will be available and a redirect to a 'How to Search' page on static site.

**Comment by Carley-Sullivan** [comment]
FAQ is drafted and ready for review. @James-Paul-Mason @lauraherring 

https://docs.google.com/document/d/1WdgcZQwOm1egmj2dirNXeKQXGK7o_qa_P8gKuDv_o4k/edit

**Comment by lauraherring** [comment]
@Carley-Sullivan I re-wrote the answer in the doc.

**Comment by James-Paul-Mason** [comment]
@Carley-Sullivan @lauraherring Just one minor suggestion in the doc.

**Comment by lauraherring** [comment]
Works for me, I'm good with this going live on ZD.

**Comment by James-Paul-Mason** [comment]
This has been posted as a FAQ on ZD.
