### ISSUE TITLE
[HD]: FAC inquiry on submitting audits / FAQ

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2276]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/55

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [X] other

### What browser did the user report as using?

Firefox

### What happened?

User inquiry on submitting an audit if they no longer have any grants with a specific agency.

**Comment by Carley-Sullivan** [comment]
@alyssamwong This is already on our FAQs here: https://support.fac.gov/hc/en-us/articles/18792665392141-Is-my-organization-required-to-conduct-a-Single-Audit-

I already responded to this user and closed the ZD ticket. Moving this GH ticket to Closed.
