### ISSUE TITLE
A user can progress to the Audit Submission Access Page

### ISSUE THREAD

**Issue by Jkrzy** [GSA-TTS/FAC#228]
## Background

As an auditee, I want to be able to access the ` Audit Submission Access` page  so that I can provide the information necessary for collaborators to access my SF-SAC once it is in-progress. 

## Accept Criteria: 

**Given** that I entered a known UEI and valid date range on  information on [the Auditee Info page](https://federalist-9a617ff8-042d-4076-9581-bb999f9c6639.app.cloud.gov/site/gsa-tts/fac-frontend/audit/new/step-2/)
**When** I click Continue
**Then** I’m taken to the final step in the submission process, the [Audit Submission Access page](https://www.figma.com/file/ty7iZnrnpBO5OlhRoDQd4m/FAC-Playground?node-id=1801%3A9179), where I can information for certifying officials and contacts.

## Not in scope
* We don't need to provide a direct link to the Audit Submission Access page, it should only be accessible by completing the previous step.
* Implementation of the `Audit Submission Access page` is being tackled here: https://github.com/GSA-TTS/FAC-Frontend/pull/13

## Remaining tasks
- https://github.com/GSA-TTS/FAC/issues/322

**Comment by petermarks-gsa** [comment]
Verified end to end by @timoballard and @jasnakai via django admin (see screen). That info gets stored on the user in the backend until the 3rd form is submitted at which point the info gets written to the database.

![image](https://user-images.githubusercontent.com/100610443/178057742-171387f8-3783-452b-aadd-f5e31ab43121.png)
