### ISSUE TITLE
Document and implement backup retention policy

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2281]

**Comment by JeanMarie-TTS** [comment]
@jadudm  Policy questions.
How long should we retain our backups?
We will be backing up `prduction` before every deployment as well as every night. This will add up very qiockly. So, we need to decide how many PR backups and daily backups to retain.
I am inclined to say that we retain one instance of the most recent daily backup and one instance of a backup taken at the end of the week. This seems reasonable as cloud.gov too takes a daily backup.
As for PR backups, should we retain just the last two?
I recommend keeping only one daily backup of `dev`.

**Comment by jadudm** [comment]
1. I'm actually not "worried" about backups in dev/staging from a retention standpoint. I assume those are for test and development purposes, not "we need to restore dev" purposes.
2. Are we able to easily determine which backup came from a `prod` push and what came from a nightly? 
3. Keeping the last two PR backups seems reasonable. It sounds like I should write a scenario or two to make clear why. My primary use-case for PR backups is the "OH NO, THAT WENT SIDEWAYS" case, and we restore immediately. If we're going backwards in time, we're potentially losing a random/arbitrary amount of data. But, if we do multiple PR pushes in short order, having more than one feels good. Two sounds reasonable, given no motivating scenario for a different number.
4. I'd be inclined to keep dailies for 7 days (rolling) and weeklies for 4 weeks (rolling). But... really, I don't know what weeklies do for us? That is, if we're restoring to a weekly... we're again losing a lot of data, and cloud.gov keeps things for 14 days if we need it. So, in that regard, perhaps just keeping a daily on a rolling basis for 7 days is enough, without weekly snapshots? (Feedback/thoughts there welcome.)

If we only keep one daily of `dev` and/or `staging`, that feels fine. 

Thoughts? When we feel good about this, I'll document it in an ADR.

**Comment by JeanMarie-TTS** [comment]
We are not planning to back up `staging`. But we will be restoring  daily backups from `prodiction` to `staging` everyday.
We will backup `dev` and restore to `dev` everyday. This is just to make sure that a new software version has not messed up anything. Someone will have to actually monitor this, but this is a separate issue.
We will implement the following retention policy:
Production PR push: At the end of every day, we will delete all PR backups except the two most recent ones.
Production Daily: We will retain the last seven.
Dev Daily: We will retain only the most recent one.

@asteel-gsa  Can you confirm if this sounds reasonable?

**Comment by asteel-gsa** [comment]
> We are not planning to back up `staging`. But we will be restoring daily backups from `prodiction` to `staging` everyday. We will backup `dev` and restore to `dev` everyday. This is just to make sure that a new software version has not messed up anything. Someone will have to actually monitor this, but this is a separate issue. We will implement the following retention policy: Production PR push: At the end of every day, we will delete all PR backups except the two most recent ones. Production Daily: We will retain the last seven. Dev Daily: We will retain only the most recent one.
> 
> @asteel-gsa Can you confirm if this sounds reasonable?

i.. am not sure we do production pushes daily, and even will be. I mean, theoretically we can, but thats the only major issue i see.

It will effectively have the following
prod:
```
# releases, so names stay the same, but times differ
production-db-backup-2023-XX-YY-ZZZZ.psql.bin
production-media-backup-2023-XX-YY-ZZZZ.tar

# Scheduled, so names stay the same and times stay the same, just with different days
production-db-backup-2023-10-01-0013.psql.bin
production-db-backup-2023-10-02-0013.psql.bin
production-media-backup-2023-10-01-0013.tar
production-media-backup-2023-10-02-0013.tar
```

So.. im not sure how we want to do the removal of the backups, but we need some check to get the latest based on the day, and then drop everything != that backup `.psql.bin and .tar`
