### ISSUE TITLE
[HD]: A federal awards workbook that fails validation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2282]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/58

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/folders/1e2scaQY4TQ3Uye6tDzrAUf3vSt8O5sJN

### What happened?

The user is attempting to upload a federal awards workbook. It has three rows.
 
They say that they get the error 
 
`R2 needs to be $0 or greater`
 
when they upload. 
 
However, I cannot reproduce the error in `staging` or in `production`. What happens, instead, is that the error table comes back, and no errors are reported at all. 
 
Or, it is an empty error table. Screenshot from `production` below.
 
![Screenshot from 2023-09-27 18-11-36](https://github.com/GSA-TTS/FAC/assets/38290/d22f3f63-cb91-450c-a330-8d060960b97a)

**Comment by danswick** [comment]
@jadudm I tested this locally and got the same result as you: empty error table. A wrinkle I've noticed: if I try to upload it again, the upload page hangs and doesn't display any errors. 

I also tried transferring the data from this test workbook into a fresh copy of the workbook template and got the same errors.   Trying a couple other things to try triangulating the issue and will report back.
