### ISSUE TITLE
Add questioned costs rollup to `/general` endpoint in API

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2305]
Census in the `gen` table provided a rollup for whether or not there were findings. This was essentially a way of saying "there were questioned costs."

We could provide `does_report_contained_questioned_costs` (or a simpler/shorter name?). It would behave as follows:

```
IF the audit has any findings AND one of the questioned cost fields are `true`
THEN this is true
ELSE false
```

**Comment by phildominguez-gsa** [comment]
Now tracked here: https://github.com/GSA-TTS/FAC/issues/2473
