### ISSUE TITLE
Add `typereport_mp` rollup to `general` endpoint in API

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2307]
IF there is a major program
THEN rollup all the MPs
ELSE leave it blank

For example, if the type reports `U`, `A`, and `D` all appeared in the awards expended, then we would have a rollup variable of `ADU`. (Assume we alphabetize the rollup.)

**Comment by phildominguez-gsa** [comment]
Now tracked by: https://github.com/GSA-TTS/FAC/issues/2474
