### ISSUE TITLE
[HD]: Unable to upload workbooks 

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2315]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/60 

https://fac-gov.zendesk.com/agent/tickets/65

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

Multiple users can't upload their workbooks despite downloading the latest version from the site. In this case, it's issues with workbooks 3-7, where there's no feature to upload the workbooks. (separate ticket issue from downloading the form)

**Comment by jadudm** [comment]
Ticket 60 requires more response, but it is a user who has not read the directions. 

Ticket 65 was handled by schema work.
