### ISSUE TITLE
Change code to generate submission-side `report_id` to also use end date

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2326]
Notes from 2023-09-29 discussion were to change `report_id` to follow these rules:

*   Four-digit year based on submission fiscal _end date_.
*   Two-digit month based on submission fiscal _end date_.
*   Audit source: either `GSA` or `CENSUS`.
*   Zero-padded 10-digit count.
*   Separated by hyphens.

For example: `2023-09-GSA-0000000001`, `2020-09-CENSUS-0000000001`.

**Comment by danswick** [comment]
This is done.
