### ISSUE TITLE
No linting of tools

### ISSUE THREAD

**Issue by stucka** [GSA-TTS/FAC#2332]
### Describe the bug

`black` is now set up to run only on the `backend` directory, but turns up problems in the unchecked `/tools` directory. `flake8` and `mypy` also find some problems in `/tools`.

I flagged three files within `tools` in Issue #704 that black finds some problems, extensive in number but not in substance.

Problem can be fixed within `https://github.com/GSA-TTS/FAC/blob/main/.github/workflows/linting.yml`.

`black` is not running on`tools` -- the backend linting seems explicitly for `/backend` and nothing at all is set up for `/tools/`.

```
      - name: Check formatting with black
        working-directory: ./backend
        run: black --check .
```

### Steps to reproduce the bug

Verify in .github/workflows/linting.yml

or from the command line, simply run:
pip install black mypy flake8
flake8 tools
mypy tools
black tools

### Expected Behavior

The nice thing about standards is there's so many to choose from.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
I'll triage this, but my suspicion is that the `tools` directory is going to go away as a short-lived experiment, to be replaced by evolutions of those tools that are now integrated more fully into the stack (and, therefore, covered by linting, for example).

Thank you for the bug report!
