### ISSUE TITLE
[HD]: Workbook validation: Possible error around cluster names?

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2338]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/77

### FAC components involved

- [ ] submission system (app.fac.gov)
- [x] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

The user has a workbook that won't validate regarding cluster names. We should check both the workbook and the validation.

> getting an error regarding not using the correct Cluster Name, it is related to 20.205 Highway Planning and Construction Cluster. I have tried to check it multiple times and even selected N/A or Other Cluster Not Listed Above and still getting the error

![error](https://github.com/GSA-TTS/FAC/assets/38290/9652882a-89f3-4f70-9643-1c9255f6036a)

**Comment by Carley-Sullivan** [comment]
Columns H and I should be NULL.  Error message should've covered H2:H6 and I2:I6

**Comment by James-Paul-Mason** [comment]
Seems like this may be the same issue as ticket 2417: https://github.com/GSA-TTS/FAC/issues/2417

**Comment by jadudm** [comment]
Closed by #2441.
