### ISSUE TITLE
Epic: Admin / CX API and tools

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2344]
Collecting some backlog items related to Admin and CX.

```[tasklist]
- [ ] https://github.com/GSA-TTS/FAC/issues/2827
- [ ] https://github.com/GSA-TTS/FAC/issues/2826
```

**Comment by danswick** [comment]
It might make sense to combine several related efforts under an admin API and related tools:

* Cog/over admin tool
* CX in-flight data API
* Tribal audit access admin tool
