### ISSUE TITLE
[HD]: Federal Awards Workbook Cell Error

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2357]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/84

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/folders/1gRS7ny9zMwHjAsrERaxq8kojk-r9iUoi?usp=drive_link

### What happened?

I am attempting to upload the Federal Awards workbook, but I am getting an error (see attached PDF “Error DCF”). Apparently there is an error with Cell L2. But that cell is formatted exactly in line with the instructions (I entered “N”). I don't know how to fix the error or how to proceed with the submission. 

You will see that the error does not apply to my workbook, so far as I can tell (cell L2 is formatted correctly).

Report ID: #2022JUL0001000331

**Comment by jadudm** [comment]
Addressed by #2440 .
