### ISSUE TITLE
[HD]: SEFA worksheet validation error

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2358]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/93

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Microsoft Edge

### Gdrive link

https://drive.google.com/drive/folders/1SyOjk8CHgxqPfdIdjpBR5m5I-Yv6yDDy?usp=drive_link

### What happened?

I have used the SEFA workbook template to enter the SEFA details for YE 2022. All data entered and I have tried diligently to “not override” the pre-existing cell formulas or rules when updating with my 2022 information and saving file to upload.  When I select the saved file to download it seems to just sit and show “Validating your file..”

**Comment by jadudm** [comment]
I cannot currently recreate this with #2440. I believe we have fixed this problem.
