### ISSUE TITLE
[HD]: Invalid agency ALN [CFDA] prefix

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2359]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/81

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/folders/1DXLN2gJySgckM_NB5-mCusGZ2_rCSJ02?usp=drive_link

### What happened?

I am getting an “Invalid agency ALN [CFDA] prefix” error code for cell B3 when trying to input the attached federal award workbook. The agency is in the SAM.gov site, so I am not sure why it is not being accepted. It still gives me the same error even if row 3 is blank.

**Comment by jadudm** [comment]
Addressed by #2440 .
