### ISSUE TITLE
Review design onboarding documentation and make tickets for gaps

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#236]

**Comment by MelissaBraxton** [comment]
Drafting [here.](https://docs.google.com/document/d/1EILl0nZr59T4PFJJMtFbmnQDJPksgzIFPuoFDN0bk0g/edit#)

**Comment by petermarks-gsa** [comment]
@MelissaBraxton This seems duplicative to #231. Closing as "not planned".
