### ISSUE TITLE
[HD]: Add additional users after the pre screener feature request

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2367]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/86

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

"At this time the FAC does not allow additional users to be added to a report once a submission has been created. I am requesting that you add this functionality as soon as possible. Also, users should be able to be removed from a report. What if there are personnel changes? It is not secure/smart to not be able to remove access."

This one seems pretty important and a very useful feature both ways.

**Comment by jadudm** [comment]
We'll reply after posting an update on Tuesday. We'll have a list of "coming soon" type things.
