### ISSUE TITLE
[HD]: Workbook issue: blank cell causing validation errors 

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2368]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/90

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

Take a look at the zendesk link for more info and the workbook!

**Comment by jadudm** [comment]
@LeoFotovich , just a small reminder that not everyone has access to ZD. When we pull tickets from ZD, we need to copy files to the GDrive so devs can access them.

**Comment by jadudm** [comment]
This is addressed by #2440.
