### ISSUE TITLE
Review engineering onboarding documentation and make tickets for gaps

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#237]

**Comment by petermarks-gsa** [comment]
@geekygirlsarah Next step reach out to someone at TTS not on this project (18F?) and ask them if it seems easy to get going on? 

Note: Let's focus on backend here as front end recently went through this process.

**Comment by petermarks-gsa** [comment]
@timoballard @jasnakai Looks like you guys are getting close to wrapping up your dev onboarding tickets. Find anything that needs changing with our onboarding docs?

**Comment by petermarks-gsa** [comment]
per discussion, @jasnakai will follow up with meeting or pr

**Comment by jadudm** [comment]
We have been iterating the onboard docs as we go. They're living materials, and we're comfortable with them/have a way to pick up improvements on an ongoing basis.
