### ISSUE TITLE
[HD]: Still receiving UEI validation bugs after fix 

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2371]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/122

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

This zendesk request was done 6 minutes ago and is still claiming to have UEI validation errors

**Comment by James-Paul-Mason** [comment]
Same issue for this user: https://fac-gov.zendesk.com/agent/tickets/114

**Comment by jadudm** [comment]
Closed 122. 114 may require a response still, so moving this ticket to Review for CX to pick up.

**Comment by jadudm** [comment]
The Federal Awards workbook passed by 114 had many, many errors; so many that I do not believe they attempted to read the instructions. However, we now have errors for everything they did. #2440 should fix this when it lands.

**Comment by jadudm** [comment]
#2440 now fixes 114.
