### ISSUE TITLE
[HD]: Entering expenditures workbook error

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2372]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/97

https://fac-gov.zendesk.com/agent/tickets/104

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

Ticket 97: https://drive.google.com/drive/folders/1DYOr2jBROaPfYXIaeJV2GN96D1UJ7zF2?usp=drive_link

Ticket: 104: https://drive.google.com/drive/folders/1xSwtDhdo7mhRFztvSAb_hYOejgUcipOn?usp=drive_link

### What happened?

Users has negative numbers in their expenditures. The workbook draws an error when negative numbers are entered, allowing only positive numbers on their end.

**Comment by jadudm** [comment]
97 now passes via schema improvements.

104 (negative values) also was fixed.
