### ISSUE TITLE
[HD]: Fed Awards Workbook Error: cell L2 must be “Y” or “N”. 

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2373]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/84

### FAC components involved

- [X] submission system (app.fac.gov)
- [x] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

User is attempting to upload the Federal Awards workbook. He is receiving “Error DCF”. Indicates that error is with Cell L2. But user states that cell is formatted exactly in line with the instructions (he entered “N”).

**Comment by jadudm** [comment]
The workbook issues are handled by #2440. User will need a reply.
