### ISSUE TITLE
[HD]: Workbook submission error in cell O2 

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2374]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/126

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/folders/1kkroW-0VAELrJUFZq5VtkBygbL6ETMid?usp=drive_link

### What happened?

I am getting this error message upon submission of the SEFA. Clearly, cell O2 contains text and this error is not valid.

**Comment by jadudm** [comment]
#2440 now handles this. Tighter checking around the passthrough numbers. Also, better checking for the correct workbook at the start now.
