### ISSUE TITLE
[HD]: SEFA workbooks out of order?

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2378]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/103

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

Before I noted required sequence. I entered / uploaded, and the system validated, the SEFA footnote workbook 2. It was the smaller of the two. Then I entered data for SEFA in workbook 1 template and tried to upload and validate it. It just hangs in a loop, it appears, and does not validate or give an error message in response. I tried several edits to workbook 1 and still would not validate. I finally figured out it was because I validated workbook 2 first, inadvertently.

I then tried to remove workbook 2 and start workbook 1 upload process, but system would not let me remove the already validated workbook 2 for SEFA footnotes. It would only let me upload “another file” over it. I also tried to start a “new submission” and let the draft started die on the vine. However, when I tried to start a new submission to overcome the hang up mentioned in first paragraph, the “system” would not validate my UEI number and let me move forward with a new submission with the same UEI as the one “in-progress” with the same number. The note in the support screen read “drafts could not be deleted at this time but would not hurt any new submissions”? 

So, I'm stuck. I Cann,ot do new submission. I Cannot delete workbook 2 inadvertently uploaded and validated before workbook 1, and therefore workbook 1 will not upload / validate.

Obviously I need some help and guidance.

**Comment by jadudm** [comment]
Replied. Closed.
