### ISSUE TITLE
[HD]: D3 Sequence number please contact support SEFA workbook

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2379]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/113

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

"receiving error “D3 Sequence number please contact support” Workbook is attached below for your reference."

Checkout the zendesk link for the workbook in question

**Comment by jadudm** [comment]
Not everyone has ZD access. We need to copy these into GDrive.

File copied. Somehow, column D was corrupted? We need to check this.

A stopgap solution was given to the user, but this still represents a problem for the user.

**Comment by jadudm** [comment]
https://fac-gov.zendesk.com/agent/tickets/113

**Comment by jadudm** [comment]
In GDrive:

https://drive.google.com/drive/folders/1axJl7PjT9fXspDYFTxq_q8g8XoooDInK

**Comment by jadudm** [comment]
Addressed by prior work and/or #2440.
