### ISSUE TITLE
A plan for how to integrate audit search and site search

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2382]

**Comment by Carley-Jackson** [comment]
This is blocked by top-nav card sort

**Comment by Leighdiddy** [comment]
Resolved by new top nav redesign: https://www.figma.com/file/dIpUx2YV9yMYqrxpJ5949a/FAC-Search?type=design&node-id=0-1&mode=design&t=t8UvOYhPoEeNVujR-0
