### ISSUE TITLE
Update sitemap to include search, search resources, updates, etc.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2384]
# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: A user hits the site, and wants to search for documentation and "how to" content

**Given**   that we have two kinds of search
**when**  they want to search the site
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the site nav makes obvious how to search for *content* on the fac.gov site
``` 

### Scenario: A user hits the site, and wants to search for audits

**Given**   that we have two kinds of search
**when**  they want to search the site
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] the site nav makes obvious how to search for audits
```

**Comment by Carley-Jackson** [comment]
This is blocked by top-nav card sort
