### ISSUE TITLE
FAC - Bug: Infinite Loop When Validating Workbook

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2387]
### Describe the bug

The application enters an infinite loop whenever a user attempts to upload the attached federalAwards workbook.
[federal-awards-workbook_plus.xlsx](https://github.com/GSA-TTS/FAC/files/12805782/federal-awards-workbook_plus.xlsx)

### Steps to reproduce the bug

1. Launch the application locally.
2. Create an audit report.
3. Upload the attached workbook through the FederalAwards section.
4. Check your IDE console and take note that the application enters an infinite loop.

### Expected Behavior

The application should return an error report indicating the invalid cells instead of going into an infinite loop.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by sambodeme** [comment]
I created this ticket to investigate an issue resembling an infinite loop that I encountered while working on #2331. For context, I inserted a single record into the federal awards workbook and then deleted the data in cell B1 (Federal Agency Prefix). I tried to upload the file with the expectation that it would fail validation, and the application would indicate the invalid cell.

During the upload, I noticed that the validation process was taking an unusually long time for a file with only one record. This led me to suspect the presence of an infinite loop. However, upon closer examination, I realized that due to the formulas in the workbook, when I deleted data from cell B1, the workbook matched that cell with all the blank cells in the named range. This caused the federal program total to be duplicated in all 5000 rows of column J. Now, when the application read the file, it saw 5000 non-empty rows, and the validation had to process them all and report thousands of errors. This was because all these rows, except the first, were effectively empty, with only the federal program total set to a non-zero value. Therefore, I am going to close this ticket.

**Comment by jadudm** [comment]
Apologies; I thought the workbook contained user data.

The workbook referenced in the ticket is this one:

[federal-awards-workbook_plus.xlsx](https://github.com/GSA-TTS/FAC/files/12811201/federal-awards-workbook_plus.xlsx)

**Comment by sambodeme** [comment]
@jadudm Oh I see, my bad. I should have mentioned in the ticket that I created these fabricated data to test a specific condition (infinite loop) :)

**Comment by jadudm** [comment]
No worries.
