### ISSUE TITLE
[HD]: Workbook still not validating / email confirmation question

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2388]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/73

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

User has tried several times with support from us, but workbook is still not validating. User also has question about email notifications/confirmations:

"On another client I was able to get everything uploaded and worked perfectly. However, when I hit the button to submit to my client for their certification and then eventually mine, it did not send an e-mail, or at least I did not get one, I’m not sure if he got one yet. Is it supposed to send the e-mails like it used to?"

**Comment by jadudm** [comment]
Handled by schema work and/or #2440.
