### ISSUE TITLE
[HD]: Validation issue

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2389]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/90

https://fac-gov.zendesk.com/agent/tickets/159

https://fac-gov.zendesk.com/agent/tickets/132

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Microsoft Edge

Chrome

### Gdrive link

Ticket 90: https://drive.google.com/drive/folders/1Eh5eS3xo_UCfWGlwl-PkMa2-rVBnoJui?usp=drive_link

Ticket 159: https://drive.google.com/drive/folders/1tJkJ14F_gJ_lOxqPc18TivKn25Pcdd0g?usp=drive_link

Ticket 132: https://drive.google.com/drive/folders/1SivMVGAZ2lgDP8CI7P5pUIiBo0pGWg_b?usp=drive_link

### What happened?

User reports the following:

Users are experiencing a validation error when they upload using cluster names from the drop down.

Ticket 90: "I have completed the federal-awards-workbook but when i upload it I get and error on validation. It just says cell 15, If Other Cluster, Enter Other Cluster Name, Name must be 75 characters or less. All the cells in this column are blank so I do not know how to resolve the error."

Ticket 159: "I used the cluster names from the drop down as well as the cluster tab but I'm getting a validation error on this."
Google Drive file attachment linked above.

Ticket 132: "I used the cluster names from the drop down as well as the cluster tab but I'm getting a validation error on this."

**Comment by jadudm** [comment]
All three of these are handled by #2440.
