### ISSUE TITLE
[HD]: Workbook issue for specific client

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2390]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/105

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/u/2/folders/1Dc_pJVWkLsYYcxmsUcrOjf8tWJ_q3wLr

### What happened?

User has successfully uploaded several other clients – however the two that are attached just will not upload.  She tried in Chrome as well as Edge.

**Comment by jadudm** [comment]
The first workbook seems to now pass; fixes put in on Friday, Oct 6 may have addressed this.

**Comment by jadudm** [comment]
The second workbook is passing, and it looks like it should. Also likely fixed by prior work.

**Comment by jadudm** [comment]
This is now ready for pickup and reply to the user.
