### ISSUE TITLE
[HD]: Getting stuck on pre screener

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2391]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/165

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

"Hello - when i put in the UEI, fiscal start/end date for step [#2](https://fac-gov.zendesk.com/agent/tickets/2) to submit an audit, when i click continue i do not progress to step [#3](https://fac-gov.zendesk.com/agent/tickets/3). The UEI is deemed valid however it wont let me progress in the submission process. Please let me know how to proceed."

"We are trying to submit a school audit and after entering the auditee information and selecting continue it brings us back to the auditee information screen."

There are other tickets, and people have reported this bug on almost all internet browsers. 
https://fac-gov.zendesk.com/agent/tickets/165

https://fac-gov.zendesk.com/agent/tickets/149

**Comment by danswick** [comment]
This should be resolved.
