### ISSUE TITLE
Processing of column `P` in federal awards is wrong

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2398]
A workbook came in with the following values in column `P`:

https://drive.google.com/drive/folders/12HzBfBj9cGh8keFdxWszHCMX1m0BHm12

Some of them were integers. Excel cast them as ints. As a result, our code to process these as strings (and split on `|`) breaks badly.

```
backend-web-1            | ERROR Internal Server Error: /audit/excel/federal-awards-expended/2023-09-GSAFAC-0000000005
backend-web-1            | Traceback (most recent call last):
backend-web-1            |   File "/src/audit/excel.py", line 477, in _extract_data
backend-web-1            |     _extract_column_data(workbook, result, params)
backend-web-1            |   File "/src/audit/excel.py", line 499, in _extract_column_data
backend-web-1            |     set_fn(result, f"{parent_target}[{index}].{field_target}", value)
backend-web-1            |   File "/src/audit/excel.py", line 67, in _set_pass_through_entity_id
backend-web-1            |     for index, v in enumerate(value.split("|")):
backend-web-1            | AttributeError: 'int' object has no attribute 'split'
backend-web-1            | 
```

This breaks an unknown number of Federal Awards workbooks being submitted.

**Comment by jadudm** [comment]
This is also a content error, @lauraherring .

Our documentation does not reflect the fact that column P can have a `|` to separate multiple values. And, it would appear that the number of `|`-delimited values in column `P` must match the number in column `O`, or else we get weird errors.

I am uncertain how we can catch this error better at the moment. We end up with objects that look like this:

```
'direct_or_indirect_award': {'is_direct': 'N', 'entities': [{'passthrough_name': 'University of Pennsylvania',
'passthrough_identifying_number': '57681/00 '}, {'passthrough_identifying_number': ' 10080210'}]}
```

when the "lists" of `|`-delimited values are of different lengths. As a result, we get the error:

|  |  |  |
---- | ---- | ----
O49 | If no [Direct Award], Name of Passthrough Entity | Only plain text is allowed, no emoji, formatting, or other special additions.


because we have unbalanced/incorrect objects in the JSON.

Either way, we need to make our documentation match what was reality for the previous workbooks (as well as ours), and we need to figure out if we can catch this error and do better by the users.

Lines 64 and 69 of audit/excel.py are where we probably have to look... but the two functions don't know what the values are for *both* columns. They only know one column at a time.

Maybe we can do something in `extract_federal_awards` around line 569? I don't know yet.

We have to find these unbalanced objects and pass back an error that makes sense to the user. The error, as given, is "correct," but it won't be obvious.

**Comment by jadudm** [comment]
This is 

https://fac-gov.zendesk.com/agent/tickets/178

in ZD.

**Comment by lauraherring** [comment]
@jadudm If I'm understanding this ticket correctly, we want to let users know that they can list multiple identifying numbers in column P, so long as they are separated by `|`, correct? If so, is this wording now accurate?

> If the award did not come directly from a Federal awarding agency,  enter the identifying number assigned by the pass-through entity. Separate multiple numbers using "|". If there is not an identifying number assigned by the pass-through entity, enter "N/A" in this field.

**Comment by jadudm** [comment]
We've resolved this in documentation and code.
