### ISSUE TITLE
[HD]: Updating PDF page numbers does not work

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2399]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/177

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

I am trying to update the PDF page numbers for 2 areas.  When I try to update it, the page numbers do not save. What am I doing wrong?  Or is it possible to change the page numbers?

**Comment by danswick** [comment]
Needs to be replicated before moving to available.

**Comment by danswick** [comment]
This is no longer replicable. Looks like we're resolved here.
