### ISSUE TITLE
[HD]: Instructions for workbooks 3, 4, 5 are still wrong in the app

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2404]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/60

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

The instructions on the workbook submission pages for 3, 4, and 5 are still wrong. I believe the text in question in is `submission_progress_view.py`, and needs to be fixed and pushed to `production`.

From the user:

> This is the wording taken from the website instructions for Workbooks 3, 4, and 5.  It states that “If there are no audit findings listed in Workbook 1:  Federal Awards, only enter the auditee EIN in this workbook and upload”.
> Upload Workbook 3: Federal Awards Audit Findings
Complete this workbook using the Summary Schedule of Prior Audit Findings and the information in the financial statement audit. If there are no audit findings listed in Workbook 1: Federal Awards, only enter the auditee EIN in this workbook and upload.
> Upload Workbook 4: Federal Awards Audit Findings Text
Enter the full text of the audit finding, listing each finding only once, even if they relate to more than one program. Include the audit finding reference number for each. If there are no audit findings listed in Workbook 1: Federal Awards, only enter the auditee EIN in this workbook and upload.
> Upload Workbook 5: Corrective Action Plan
> This information should match the data you entered in the Findings Text workbook. You only need to enter plans for findings once if they relate to more than one program. If there are no audit findings listed in Workbook 1: Federal Awards, only enter the auditee EIN in this workbook and upload.
> I had completed Workbook 1:  Federal Awards and there are no audit findings, but per the instructions on the website, I have been working tirelessly to complete 3-5. 
> Since you are now telling me that workbooks 3-5 are only necessary if there are findings, then this website needs to have the instructions corrected.  Because this is very misleading.

**Comment by lauraherring** [comment]
@jperson1 Here's new copy:

3. This workbook is only necessary if there are findings listed in Workbook 1: Federal Awards. Complete this workbook using the Summary Schedule of Prior Audit Findings and the information in the financial statement audit. If there are no audit findings, you do not need to complete this workbook.
4. This workbook is only necessary if there are findings listed in Workbook 1: Federal Awards. Enter the full text of the audit finding, listing the finding reference number for each. Do not include charts, tables, or footnotes. If there are no audit findings, you do not need to complete this workbook.
5. This workbook is only necessary if there are findings listed in Workbook 1: Federal Awards. Information in this workbook should match the data you entered in Workbook 1. You only need to enter plans for findings once if they relate to more than one program. If there are no audit findings, you do not need to complete this workbook.

**Comment by jadudm** [comment]
@lauraherring @jperson1 did this close?

**Comment by lauraherring** [comment]
@jadudm @jperson1 Sounds like this was just on the checklist instructions, correct? James, maybe we can sync on this today.

**Comment by jperson1** [comment]
@jadudm @lauraherring Hello! This has been completed and can be closed, via https://github.com/GSA-TTS/FAC/pull/2416.
