### ISSUE TITLE
[HD]: Notes to SEFA error 

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2413]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/126

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

"I am getting this error message upon submission of the SEFA. Clearly, cell O2 contains text and this error is not valid."

**Comment by jadudm** [comment]
This is addressed in #2440 .

**Comment by danswick** [comment]
Tested this workbook with the new validations and it is reporting the correct error messages now:

<img width="681" alt="image" src="https://github.com/GSA-TTS/FAC/assets/2365503/daa4eb6e-238c-4165-892d-6c28ef2f6aae">
