### ISSUE TITLE
[HD]: Another Cluster Names Validation Issue

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2417]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/194

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Microsoft Edge

### Gdrive link

https://drive.google.com/drive/u/2/folders/1WuiE5NttTXdGKPr8p80r4e-abtiqbpCN

### What happened?

From user: 
"When attempting to submit the completed Federal Awards workbook, I get validation errors on the cluster name files for all awards.  I have used the cluster names from the dropdown list in the workbook and made no changes to the cluster names.  Please advise on why this is occurring and how to resolve it."

Seems like this may be the same issue as ticket 2338: https://github.com/GSA-TTS/FAC/issues/2338

**Comment by jadudm** [comment]
This is addressed by https://github.com/GSA-TTS/FAC/pull/2440.
