### ISSUE TITLE
Implement server side Search Form validation

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#2432]
Add per-field and cross-field validation to `SearchForm`

- [ ] start date must be before end date
- [ ] UEI format validation
- [ ] EIN format validation
- [ ] enforce maximums on fields that accept multiple entires (e.g. uei/ein)

**Comment by danswick** [comment]
Combining from https://github.com/GSA-TTS/FAC/issues/2434:

Update `dissemination/templates/search.html` to display form validation errors from the django template context

**Comment by jadudm** [comment]
The epic was closed. Closing this as well. We'll be coming around to search on other fronts, and this has not been an issue to-date.
