### ISSUE TITLE
[HD]: Error during submission

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2435]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/238

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/folders/1QEFZuh7ej4VHyF8m9nyueOubj1oIA_B-

### What happened?

Should the Pre-submission validation have a green check mark like everything else.

see attachment 1

We have done the Pre-submission valadation with no errors and then it goes to Certification.

When we click certification button, it gives us an error. 

see attachment 2

**Comment by jadudm** [comment]
@danswick , this appears to be an error of some sort late in the process.

How, exactly, we debug this in `prod` is a question.

**Comment by jadudm** [comment]
Files requested via ZD.

**Comment by danswick** [comment]
Needs to be replicated before moving to `Available`.

**Comment by danswick** [comment]
It looks like this issue was resolved. Let's reopen if it resurfaces.
