### ISSUE TITLE
[HD]: Error: Use Approved Cluster Names

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2436]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/239

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Microsoft Edge

### Gdrive link

https://drive.google.com/drive/u/2/folders/1rxMv5_-FtChW7JfqjT93a8jcdqpKQe_H

### What happened?

I am unable to upload my federal awards work book template which we completed due to an error message stating to use approved cluster names, but the names enter in the cells noting an error are approved and were input straight from the work books own drop box. Is this a glitch?

**Comment by jadudm** [comment]
New checks that address this workbook have been added as part of #2440.
