### ISSUE TITLE
FAC - Bug: transition submitted-but-not-disseminated to disseminated

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2438]
follow-up from: https://github.com/GSA-TTS/FAC/pull/2437

### Describe the bug

At some point in the past, we were only marking disseminated audits as "submitted." That problem has been fixed for incoming audits, but previously-submitted ones will only be disseminated with a "submitted" status.

We will need to go through those prior entries and walk them through the full transition process from `submitted` -> `disseminated`. This will likely involve grabbing the event info from `submitted` and applying it to a new `disseminated` event/status update. 

### Steps to reproduce the bug

1. Fetch some early reports form the dissemination API.
2. Verify that their status is still "submitted." 

### Expected Behavior

All disseminated audits should have a status of `disseminated`. 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by tadhg-ohiggins** [comment]
## Outline

1.  Look up how many `SingleAuditChecklist` records have a status of `submitted`.
2.  For each of them check to see whether or not a corresponding record exists in the dissemination `General` table. (Our expectation is that exactly the same amount should be present; if not, stop here and determine what’s going on.)
3.  For each of them with a corresponding dissemination-side record:
    *   Call the `.transition_to_disseminated` method.
    *   Find the submitted event in the `SubmissionEvent` table and get the user associated with it.
    *   Call the `.save` method with an `event_type` of `SubmissionEvent.EventType.DISSEMINATED` and an `event_user` of the user we grabbed from the submitted event.
4.  We check that there are now zero SACs with a status of `submitted`.

We did this and tested it in dev and staging environments before doing it in production.

## Production command log

```sh
cf target -s production
cf allow-space-ssh production
cf ssh gsa-fac
/tmp/lifecycle/shell
python manage.py shell
```

```python
from audit.models import SingleAuditChecklist, SubmissionEvent
from dissemination.models import General
sbmts = SingleAuditChecklist.objects.filter(submission_status='submitted')
rids = [sbmt.report_id for sbmt in sbmts]
gen_count = len(General.objects.all())
print(gen_count)
# 400
disms = General.objects.filter(report_id__in=rids)
assert len(sbmts) == len(disms) > 0
print(len(sbmts), len(disms))
# 91 91
def sacupdater(sac):
    sbev = SubmissionEvent.objects.get(sac=sac, event=SubmissionEvent.EventType.SUBMITTED)
    sac.transition_to_disseminated()
    sac.save(event_type=SubmissionEvent.EventType.DISSEMINATED, event_user=sbev.user)
    sac.refresh_from_db()
    assert sac.submission_status == SingleAuditChecklist.STATUS.DISSEMINATED
    dsev = SubmissionEvent.objects.get(sac=sac, event=SubmissionEvent.EventType.DISSEMINATED)
    return sac.report_id

updated = [sacupdater(sb) for sb in sbmts]
assert len(sbmts) == len(updated)
sacafter = SingleAuditChecklist.objects.filter(submission_status='submitted')
assert len(sacafter) == 0
print(len(sacafter))
# 0 
gen_count_post = len(General.objects.all())
assert gen_count == gen_count_post
exit()
```


```sh
exit
exit
cf disallow-space-ssh production
# Disabling ssh support for space production...
# OK
```
