### ISSUE TITLE
Settle on `N/A` or `blank` for state cluster/other cluster

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2450]
The instructions make clear that these columns should be blank (unless they are a state cluster, etc.). 

However, we have an `N/A` as an option in the cluster name column. This naturally implies that the other columns should be N/A.

The engineering and content teams need to decide on how we will address this.

Do we always expect:

* Blank where no value is desired, or 
* N/A where no value is desired.

The latter is explicit, and requires action on the part of the user. The former leads to invisible errors.

The product recommendation is that **a consistent submission experience would be better**. The fact that some columns *must* have `N/A`, and some *must* be blank is confusing.

**Comment by lauraherring** [comment]
@jadudm Do we want to keep this ticket open to have a future discussion on the consistency? Or are we good with the instruction updates we made last week where we were explicit in each cell whether it should be left blank or not?
