### ISSUE TITLE
[HD]: Notes to SEFA validation issue

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2451]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/187

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/folders/1cUOPXSqLycgiF_cRO3noHx92lvSEUqYX

### What happened?

It appears that a blank notes to SEFA is failing. No clear/obvious indication as to why.

**Comment by danswick** [comment]
Needs to be replicated before moving into `Available`.

cc @sambodeme

**Comment by danswick** [comment]
It looks like this issue was resolved via ZD.
