### ISSUE TITLE
Epic: Align instructions and validations

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2452]
[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I'm an auditor trying to complete an audit.

**Given**   An error
**when**  I read the instructions
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [ ] https://github.com/GSA-TTS/FAC/issues/2453
- [ ] https://github.com/GSA-TTS/FAC/issues/2455
```

**Comment by jadudm** [comment]
This is largely picked up by #2441 and other ongoing work. Closing this high-level epic in favor of the fixes being applied in more specific tickets and epics.

**Comment by Carley-Jackson** [comment]
Closing ticket
