### ISSUE TITLE
[HD]: Notes to SEFA improvements

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2464]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/213

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/folders/1MV3XiFNxK-rWAjS5fOI2AYSyZfhnMoJa

### What happened?

1. There are blank cells. We can provide better error messages using the new framework.
2. Our instructions do not cover the coversheet cells. They need to. And, there is UG about what should go into those cells. 

So, this is both an "add new checks in the new validation framework" ticket and "fix our docs" ticket.

**Comment by lauraherring** [comment]
Updates to the Notes to SEFA instructions went live on 10/23, this ticket is done.
