### ISSUE TITLE
Add DUP_REPORTS to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2467]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

`is_aicpa_audit_guide_included` is already a part of the `General` model, so just add `gen.is_aicpa_audit_guide_included` to the `general` view.

**Comment by eazapata23** [comment]
This has been added/closed with #2525
