### ISSUE TITLE
Add TYPEREPORT_FS to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2468]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

This value is the same as `dissemination_general.gaap_results` and is returned in the `general` view. Is there any work to be done here?

**Comment by eazapata23** [comment]
This has been added/closed with #2525
