### ISSUE TITLE
Add COG_OVER to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2469]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

FAC Determined Cognizant and Oversight: https://docs.google.com/document/d/1_8xB7JG-Yk7HDx12NSHCpO_GmbZMs07IslRl6m9u-5A/edit

According to https://facdissem.census.gov/Documents/DataDownloadKey.xlsx, this is `Single letter with either value 'C' or 'O' representing cognizance or oversight`

Possibly derived from general.cognizant_agency and general.oversight_agency, depending on which field is populated.

**Comment by jadudm** [comment]
Done.
