### ISSUE TITLE
Add MATERIALWEAKNESS_MP to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2470]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

<img width="1247" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/3b7e83c6-a3c5-4501-9e9d-0b7df3d3e91f">
<img width="1284" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/06dc8f5b-adac-44ab-8b04-7d6b934fc721">

**Comment by jadudm** [comment]
Documented as rollups. Not adding.
