### ISSUE TITLE
Add CYFINDINGS to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2471]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

<img width="981" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/2e118d13-62ae-4218-993f-87fc657d549b">
<img width="1246" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/dec5649d-fe98-48b1-aad9-62ac5af6ec93">

Old ticket: https://github.com/GSA-TTS/FAC/issues/2306

**Comment by jadudm** [comment]
Documented as rollups. Not adding.
