### ISSUE TITLE
Add PYSCHEDULE to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2472]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

<img width="1284" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/bf5c1f1c-7657-43e0-98ef-ebe041f0a0eb">

<img width="1227" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/1e083f21-e918-406a-bbbe-d2828939f7d7">

Page number collected here:
![image](https://github.com/GSA-TTS/FAC/assets/142051477/94e6b532-dc92-4e7a-b490-8d1142817804)

**Comment by jadudm** [comment]
Documented as rollups. Not adding.
