### ISSUE TITLE
Add TYPEREPORT_MP to API response

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2474]
Missing API fields research doc: https://docs.google.com/document/d/1JF113c52Ywx0BK4vZQN9xKmW22hpuqJQ4PqdCunBLac/edit

<img width="1269" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/01fa61a5-1bfa-4c53-b5dd-3de7035429b4">
<img width="1288" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/97f885f2-9780-4e62-b3ea-5752fdb2e238">

Old ticket: https://github.com/GSA-TTS/FAC/issues/2307 - The conditional described here is possibly wrong if `U` must be excluded if any others appear in the list.

**Comment by jadudm** [comment]
Documented as rollups. Not adding.
