### ISSUE TITLE
Research spike for matching entity names

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#2479]
https://docs.google.com/document/d/11NTzxa3Hbi0pGncuDFsBz-Ph1JbX4SbBiQcJs8MXDJc/edit#heading=h.gfw9xrh3rx22

**Comment by gsa-suk** [comment]
Edit distances and / or similarity metrics can be used for matching text strings.
Examples for edit distances:  Levenshtein distance, Hamming distance
Examples for similarity metrics: Cosine similarity, Jaccard similarity

**Comment by danswick** [comment]
This isn't a required part of the data migration work. Removing from the migration Epic and putting in backlog for later.

**Comment by danswick** [comment]
Let's close this for now and come back to it later if needed.
