### ISSUE TITLE
[INTAKE]: Unique check on passthroguh name/id number

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2505]
For all direct awards that are `N`, we need to check that the set of passthrough names and award IDs are unique. E.g.

| is_direct? | name | id |
|---|---|---|
| N | bob | 1 |
| N | bob | 2 |
| N | alice | 1 |
| N | bob | 2 |

is invalid.

**Comment by jadudm** [comment]
The federal program name (as a source of dollars) may be an important part of this set.

That is, perhaps you should only have the passthrough name appear once *per federal program name*.

**Comment by danswick** [comment]
This is getting pretty stale. It looks like @sambodeme is waiting on feedback so I'm moving to "Blocked."
