### ISSUE TITLE
[CROSS-VAL] or [INTAKE]: Validating MP and findings

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2508]
Looking at the instructions for MP (Federal Awards column S), type of audit report (FA column T), and number of findings (column U), we may have some additional cross-validations that we need.

For example, are there audit report types that require a number of findings to be present?

I only have questions here, but I have enough of a question that we need to investigate this further. It might be able to be implemented as `[INTAKE]` if it only has to do with the Federal Awards form.

**Comment by danswick** [comment]
Several of these have come up as a matter of course ([for example](https://github.com/GSA-TTS/FAC/pull/3587)). I don't think there's a way to know for sure if we're missing more of these without spending a lot of time cross-referencing the UG, which is _kind of_ captured elsewhere on the board.
