### ISSUE TITLE
Determine whether we should let users submit/certify without valid EIN

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#251]
Background from chat with @MelissaBraxton and @heymatthenry :
- Need to decide whether user's can submit/certify  in SAC flow without a valid UEI
- Current FAC experience: No UEI. They can submit/certify without valid EIN, does not check against any authoritative EIN source. 
- Currently we validate UEI's via SAM.gov, but there may be a more authoritative source 

Acceptance criteria:
- [ ] We've evaluated the comparative risks of each approach (allow submit/certify, block on validation)
- [ ] We've better understood our options for UEI validation

**Comment by MelissaBraxton** [comment]
Possible action items from our conversation:

- [ ] Document our contingency plan and/or back up plan for:
  - [ ] people experiencing UEI issues
  - [ ] If we get to August and there’ still a big backlog of folks experiencing UEI issues
- [ ] Get service level agreement from SAM.gov re: our API as far as availability including at least a point of contact that we can reference for cases like this.

**Comment by MelissaBraxton** [comment]
@petermarks-gsa  - Do you think we can archive this?
