### ISSUE TITLE
In-progress overview page for certifying officials

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2510]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."
[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** be certain of what I am certifying 
**as a** auditor or certifying official
**I want** to be able to see what was submitted.

This story involves being able to see the same summary view we present in search results during the submission process. That is, it should be possible for anyone in an audit submission to click on a "Summary" link, and see a rendered result of the audit up to that point.

Auditors expect to be able to 

1. Review what was submitted, and then
2. Lock for certification

before signing off. They should be able to review after locking as well, but it is the pre-lock review that is of particular interest/concern.

**Comment by lauraherring** [comment]
@Leighdiddy, @jperson1 and I met on this page and planned a path forward. James has the new copy and the rough page design.
