### ISSUE TITLE
[HD]: PDF audit won't upload and points to a browser issue

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2521]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/444

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

https://drive.google.com/drive/folders/1KKw3OaxvjkEWiH9TMgzP1vBprfZNmaeN

### What happened?

User is unable to upload the attached audit report to submission. They are getting an error that reads “your browser is not working properly - please try to refresh this screen”. If they refresh the screen, the same error appears again. They have tried to upload this file on three different computers and three different web browsers, and it hasn't worked on any of them.

**Comment by danswick** [comment]
I successfully replicated this error and am seeing some `TimeoutError: The read operation timed out` logs, possibly originating during the file scan. @asteel-gsa, I might need some backup on confirming whether or not the scanner is finding an issue.

**Comment by jadudm** [comment]
We addressed this by trimming our validation process. We're going to have to change that a bit, but for all intents and purposes, this particular issue was solved/closed.
