### ISSUE TITLE
[HD]: Cant get past UEI validation stage

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2535]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/497

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

I have validated the UEI and entered the beginning and ending fiscal year ending.  When I click “OK” it refreshes the page and will not go to the next step.  Am I doing something incorrect?  How do I get to the next step?  The fiscal year for the audit I am submitting is 7/1/22-6/30/23.  Thank you.  Robyn

**Comment by danswick** [comment]
I believe this was part of the duplicate-account issue that has since been fixed!
