### ISSUE TITLE
Improve ALN updates and validation

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2559]
This issue has morphed since it was opened. There isn't an immediate action, but it should stay in the backlog as we go into quarterly planning. Updating and validation ALNs is a much larger scope of work that needs some dedicated planning.

Original description:

---

### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/521

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

On our sefa we show the Federal Perkins Loans outstanding at the end of the fiscal year. When I entered this on the federal awards spreadsheet the Federal Program Name did not appear when I used the ALN 84.038, so I typed in the name.  When uploading my file it failed validation.  I removed the Federal Perkins Loans outstanding from the file and my file then passed validation and uploaded.  The issue is now the total on the spreadsheet does not match the total in our audited financial statements and our auditors will not certify.  

Can someone please advise how we should report the Federal Perkins Loans outstanding on the federal awards spreadsheet?

**Comment by danswick** [comment]
It's not immediately clear whether 84.038 should be added to the template. Per chat with @timoballard, the source of truth for this sam.gov.

**Comment by danswick** [comment]
I looked through sam.gov's ALN data from 2024, 2023, and 2022 and didn't see `84.038` listed in any of the "Program Number" columns. It is referenced as a related program ("Federal Perkins Loan Program_Federal Capital Contributions"), but it's not clear whether this is actually a valid ALN.

**Comment by jadudm** [comment]
![image](https://github.com/GSA-TTS/FAC/assets/38290/8fd41a3c-f222-4676-b53a-957e3d246cbf)

https://www.singleaudit.org/program/?id=84.038

This *appears* to be part of the pain that is ALNs. They are not globally unique identifiers over time. 

I even (early days) wrote about this in a ticket: https://github.com/GSA-TTS/FAC/issues/1555

They get created/decomissioned/reused. Although singleaudit.org seems to claim it was expired in 2010, there are Education supplements that refer to it all the way until 2020/2021?

This doesn't help, per se; my Googling just shows that this ALN did exist at some point, and it is unclear how we should handle ALNs now. This conversation has come up with OMB in larger contexts, and a short answer for the public ticket might be "this is much more complex than it appears."

I do not have a conclusive answer at the moment as to the best course of action.

**Comment by Leighdiddy** [comment]
Closing due to unclear goal/outcome, updating ALN validation master list is currently scheduled for FY25 Q2.
