### ISSUE TITLE
[HD]: Certifying officials cannot view audit even after redoing submission

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2566]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/538

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

I have re-entered the entire form, definitely included the auditee certifying official (as I am sure I did the first time) and she still does not have any access to the form created.

 

Is there a way to get more specific help on this particular submission?

 

Thank you

**Comment by jadudm** [comment]
We're going to accelerate fixing access to this. I can try and look at the backend for this, though, and see if we can figure out what is going on.
