### ISSUE TITLE
Create a zip file suitable for use in a local environment

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2575]
The following source tables are the tables of interest for GSAFAC, based on FILE_DOWNLOAD_HEADERS_PIPE_DATA in https://docs.google.com/spreadsheets/d/1NG_WK6RLIspdYfXBcFE9WyQWY6cvml43/edit#gid=376377861:
  
ELECAUDITHEADER, ELECAUDITS, ELECEINS, ELECDUNS, ELECPAS, ELECAUDITFINDINGS, ELECPASSTHROUGH, ELECNOTES, ELECFINDINGSTEXT, ELECCAPTEXT, ELECUEIS

The data suitable for use in any local environment will have:
ELECAUDITHEADER -> SUPPRESSION_CODE  = Null
ELECAUDITHEADER -> ENTITY_TYPE  = [Non profit, Local government, State, Institution of Higher Education]

Subset ELECAUDITHEADER for 2016 through 2022 using the above SUPPRESSION_CODE and ENTITY_TYPE and obtain random sample of 1000 for each ENTITY_TYPE.  Use the AUDITYEAR & DBKEY & EIN from this subset to obtain data from the other tables.

Generate zip file with all these tables and place in GDrive https://drive.google.com/drive/folders/1fQydz5dKOoPn8yRN8uBoaytFnf6N4ApT.

**Comment by JeanMarie-TTS** [comment]
- Design option: Place the zip file for non-prod in ghcr. We can include code in run.sh to download it and load it into the S3 bucket.
- We should get a matching subset of pdf files, zip them and handle the zip archive like the ones for the data.

**Comment by jadudm** [comment]
Once we have the data, I can help create an image/process that mirrors the other data we're using, if that helps. Sadly, I didn't think we would be duplicating that, so there is not as much documentation as we'd like. But, there's some in the repo for the data image we're currently using.

Dropping that here so that, if we want a data-load-image for this, I can provide some support.

**Comment by JeanMarie-TTS** [comment]
@gsa-suk 

- Does 1000 per entity type refer to submissions per year? I think a total of 1000 should suffice - like 200 per year.
- Will the zip file contain a folder for each audit year? Or will there be one zip file per audit year?
- What about the pdf files? We need to get the ones corresponding to the subset.
- Will we be able to access the Google drive from the `dev` space in cloud.gov? If not, we need to put the files in a place that can be accessed both locally and in the `dev` space.

**Comment by gsa-suk** [comment]
@JeanMarie-TTS 

- Ok.  Will pull 200 submissions per year.  

I was planning on making 11 csv files, one per table (ELECAUDITHEADER, ELECAUDITS, ELECEINS, ELECDUNS, ELECPAS, ELECAUDITFINDINGS, ELECPASSTHROUGH, ELECNOTES, ELECFINDINGSTEXT, ELECCAPTEXT, ELECUEIS) per year.  

This will result in one zip file per year.  Each zip file will have 11 csv files.

- @jadudm Do we have any pdf file from Census?
- Once the team is happy with the zip files in GDrive, we can probably load them into the container for access in local and dev.

**Comment by jadudm** [comment]
We have no PDF files that I'd feel comfortable using at this time. If we knew what they were supposed to be called, we could create mock PDFs with the filenames we're looking for. But, I'm not confident of that at this time. FWIW, I'm trying to keep PDF handling separate in my head/in our process for the moment, so we can proceed with data with velocity.

However, @JeanMarie-TTS may have thoughts there. If we can easily mock them up, we can/should. But, I wouldn't let PDFs be a blocker at this moment. If we have to rework something a bit later to accommodate them, then we can.
