### ISSUE TITLE
Implement an orchestrator to run end to end with parallelism and restartability

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2582]

**Comment by danswick** [comment]
Add some detail here about generating exceptions, logging them, moving to next record

**Comment by danswick** [comment]
The GitHub action tracked elsewhere handles orchestration. Kicking off multiple GitHub actions at once could achieve the kind of parallelism we need. In preview, need to test if multiple actions can reliably interact with shared S3/RDS.
