### ISSUE TITLE
Create and test code that populates the raw PG models from zip to S3 to PG

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#2588]
```[tasklist]
### Tasks
```

**Comment by gsa-suk** [comment]
https://github.com/GSA-TTS/FAC/issues/2718 is related to this ticket.  
The fac_s3 and csv_to_postgres django commands have been tested and merged with main.

The fac_s3 django command transfers all csv files from a local folder to minio S3 bucket.
The cvs_to_postgres django command loads all csv files from minio S3 bucket, one file at a time, in chunks into postgres database. 

Census csv files from July 2023 containing ~17.8 million rows of data load into postgres db on my GFE using the csv_to_postgres django command in ~ 1 hr 45 mins.
