### ISSUE TITLE
[HD]: Workbook Additional Award Identification error

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2598]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/551

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Firefox

### Gdrive link

https://drive.google.com/drive/folders/1FtQg0X7rakEg7Ch1OKqsgkTYFRuaeLUE?usp=share_link

### What happened?

User recieves "Additional Award Identification" errors in the workbook and a message text to contact support. They attempted using multiple browsers but the errors still appear.

**Comment by danswick** [comment]
This should have been resolved with the new validations.
