### ISSUE TITLE
[HD]: Cant make it past step 2 

### ISSUE THREAD

**Issue by LeoFotovich** [GSA-TTS/FAC#2601]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/581

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

"ON the checklist everything shows complete down to workbook 2, but I can't enter anything in after that."

**Comment by danswick** [comment]
Looks like this was resolved.
