### ISSUE TITLE
FAC - Possible bug: faulty gaap_results information through /general

### ISSUE THREAD

**Issue by stucka** [GSA-TTS/FAC#2608]
### Describe the bug

I'm not an accountant, but I seem to be seeing that there are several distinct categories for opinions reflected in `gaap_results`. The system is combining some.

non-GAAP seems to be an additional flag to the categories, so I can see that co-existing. But I'm not sure what a unmodified, adverse opinion would be; from what I can tell, that's a contradiction in terms. From a recent pull of `/general`:

- 'unmodified_opinion': 1128
- 'not_gaap': 52
- 'qualified_opinion': 3
- 'adverse_opinion, not_gaap': 17
- **'unmodified_opinion, qualified_opinion'**: 8
- 'unmodified_opinion, not_gaap': 2
- **'unmodified_opinion, adverse_opinion'**: 1
- 'adverse_opinion': 1

I see no data for `disclaimer_of_opinion` entries to evaluate whether they're suffering from any overlap problems.

I don't know that "unmodified opinion" can co-exist with "not_gaap".

### Steps to reproduce the bug

Where the environment contains an API key in FED_API_KEY:
```
import requests
import os
fedapikey = os.environ['FED_API_KEY']
requestheaders = {"X-Api-Key": fedapikey}
r = requests.get(f"https://api.fac.gov/general", headers=requestheaders)
resultsdict = {}
for entry in r.json():
    results = entry['gaap_results']
    if results not in resultsdict:
        resultsdict[results] = 0
    resultsdict[results] += 1
print(resultsdict)
```

### Expected Behavior

https://www.ecfr.gov/current/title-2/subtitle-A/chapter-II/part-200/subpart-F/subject-group-ECFRea73e47c9a286e6/section-200.515

200.515(d)(1)(i) seems to suggest that unmodified, qualified, adverse and disclaimer opinions are exclusive categories within the GAAP-compliant audits.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by cephillips** [comment]
Hmm, I don't actually recall an unmodified opinion being part of it. I thought it was Unqualified Opinion, Qualified Opinion, Adverse Opinion, Disclaimer of Opinion. Unqualified being fine and Disclaimer being so bad that the auditor couldn't even make an opinion.

**Comment by jadudm** [comment]
I missed this bug ticket. We need to discuss it, and potentially bring it forward soon.

**Comment by danswick** [comment]
Quick follow-up here: we've learned that some submitters have been reusing the same finding reference numbers for multiple distinct findings. We think this is either a hold-over practice from Census or reflects a difference between Census' and GSA's data models. We would like to explore stricter validations for these cases soon.

**Comment by sambodeme** [comment]
> Quick follow-up here: we've learned that some submitters have been reusing the same finding reference numbers for multiple distinct findings. We think this is either a hold-over practice from Census or reflects a difference between Census' and GSA's data models. We would like to explore stricter validations for these cases soon.

@danswick This [validation ](https://github.com/GSA-TTS/FAC/pull/4283) has been merged

**Comment by danswick** [comment]
We implemented this validation and then very quickly learned from the auditor community that our validation was too aggressive and was blocking some valid findings combinations. More detail [here](https://github.com/GSA-TTS/FAC/issues/4385), but the issue in this ticket has been both resolved and subsequently reverted.
