### ISSUE TITLE
[debt] Explore modularizing dockerfile and docker compose files

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2632]
Building on comments from @JeanMarie-TTS, @gsa-suk, and @tadhg-ohiggins in Slack, we can improve our Dockerfiles and Docker compose files to:

* Reduce duplication (DRY)
* Reduce the number of layers / steps in the build process
* Better support multiple architectures (especially for dev machines with Apple silicon)
* Possibly make builds/tests run faster

Related:

* https://github.com/GSA-TTS/FAC/issues/1523
* Possibly lots of tickets related to workflows/GH actions

**Comment by jadudm** [comment]
Some of this was done. Closing. We can re-ticket if we want to.
