### ISSUE TITLE
Front end - "You are now leaving FAC" modal

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#267]
Breakout issue of #135 

**Background**

- As a user, I need to know that I need to login to the system to access secure information
- As a user, I need to consent to the redirect and understand the implications of falsifying information on a government site
- As a system, authentication is done through login.gov which requires a redirect to a login.gov sign-in/sign-up page.

**Acceptance Criteria**

- [x] Click "sign in" button in navigation header
- [x] See "Submitting information to the Federal Audit Clearinghouse requires authentication" modal ([design link](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3136%3A18521))
- [x] Click "Authenticate with Login.gov" to move to Login.gov screen
- [x] Click "Go back" to dismiss modal

**Comment by austinhernandez** [comment]
I just wanted to flag that the designs are old, but functionality shouldn't change much. updated designs will be on #290 and are based off latest research findings.

**Comment by petermarks-gsa** [comment]
Verified this is done!
