### ISSUE TITLE
E2E refactor: demonstrate execution of code via GH Action

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2671]
There is a nascent GH Action for the workbook generation code. It is intended to be manually triggered. This is OK.

Update the action and demonstrate that it can be used in `preview`, `dev`, and `staging` to generate workbooks from the existing historical data.

The existing workbook generation code, and action, should allow for generating 3 submissions by default. This is adequate.

**Comment by phildominguez-gsa** [comment]
This can be run [here](https://github.com/GSA-TTS/FAC/actions/workflows/historic-data-migrator.yml) but I am reopening this ticket because it produces errors
