### ISSUE TITLE
FAC-D-2023-005 - NR

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2690]
https://docs.google.com/spreadsheets/d/1SYLLqrstW3kpR3skRoXrm8tSa6jQF1NvBsR3i37GvsU/edit#gid=565013969

```[tasklist]
### Tasks
- [x] Automate shipping of logs to NR
- [x] Configure alerts for suspicious activities
```

**Comment by danswick** [comment]
* Need clarification on what GSA considers suspicious
  * Check in during weekly ATO meeting
* Review which of those activities apply to the FAC app and how/whether to add or configure instrumentation to capture them

**Comment by danswick** [comment]
This has been marked as completed.
