### ISSUE TITLE
FAC-D-2023-006 - SOP

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2691]
https://docs.google.com/spreadsheets/d/1SYLLqrstW3kpR3skRoXrm8tSa6jQF1NvBsR3i37GvsU/edit#gid=565013969

SIEM/Cont Mon SOP updates (possibly)

**Comment by jadudm** [comment]
Awaiting response from assessment team.

**Comment by danswick** [comment]
Marked as completed in the tracker.
