### ISSUE TITLE
FAC-D-2023-013 - package-update

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2697]
Resolved.

**Comment by jadudm** [comment]
https://github.com/GSA-TTS/FAC/security/code-scanning/524

**Comment by danswick** [comment]
@asteel-gsa - it's not clear to me where this alert originates. Is it coming from the trivy workflow?

**Comment by asteel-gsa** [comment]
Yes, this comes from Github security tab, from the trivy scans. @danswick

**Comment by danswick** [comment]
Marked as completed in the tracker.
