### ISSUE TITLE
E2E refactor: Clone tests `all_should_pass` and `all_should_fail`, plus workbooks

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2727]
This ticket is to replicate specific tests and their associated workbooks from the `audit` module to the `census_historic_migration` module, ensuring they function correctly in the new module.

Tasks to be completed:

1. Clone the following test files from the `audit` module:
   - `test_workbooks_should_pass.py`
   - `test_workbooks_should_fail.py`

2. Relocate the workbooks located in the `audit` module from:
   - `audit/fixtures/workbooks/should_fail`
   - `audit/fixtures/workbooks/should_pass`
   to a more centralized location that other modules can access. The chosen destination directories are:
   - `data_fixtures/audit/workbooks/should_fail`
   - `data_fixtures/audit/workbooks/should_pass`

3. Modify the existing code within the `audit` module to ensure it references the workbooks in their new locations and continues to function properly.

4. Adjust the newly cloned tests in the `census_historic_migration` module to correctly interact with the workbooks in their updated file paths.

**Comment by phildominguez-gsa** [comment]
Determined newly generated workbooks can be placed in the existing test dir (`FAC/backend/audit/fixtures/workbooks/should_*`) and without having to move/modify the testing scripts
