### ISSUE TITLE
[ADR]: Approach to deleting entries, with `Access` as the first instance

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2739]
## Areas of impact

- [ ]   Compliance
- [ ]   Content
- [ ]   CX
- [ ]   Design
- [x]   Engineering
- [ ]   Policy
- [ ]   Product
- [ ]   Process
- [ ]   UX

## Related resources

*   [Epic: Modify user roles after audit creation](https://github.com/GSA-TTS/FAC/issues/2654).
*   Many ZenDesk tickets from users who want to change the auditee and/or auditor certifying officials for a submission.
*   [The code for the `Access` class](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/models.py#L623).
*   [Expanded user role management ADR](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0031-user-access-management.md).

## Context

As outlined in the [expanded user role management ADR](https://github.com/GSA-TTS/FAC/blob/main/docs/architecture/decisions/0031-user-access-management.md), we need to delete `Access` entries. It’s also quite likely that we might need to delete a variety of other objects, in particular `User` entries, in the future.

Here “deletion” means “remove from the code paths that deal with active elements of our application” and not “scour from the earth and from history”.

For record-keeping purposes, we should not destroy the information that was in these entries, but store it for potential future investigation.

In the case of `Access` entries, if we were to delete the entires without doing anything else, we could run into this scenario:

1.  User A adds User C as a auditee certifying official
2.  User C makes some of the changes to the submission.
3.  User A realizes that the auditee certifying official should actually be User Z.
4.  User C’s `Access` entry is deleted and a new one is created for User Z.
5.  Some time later, there are questions about who did the edits in step 2.

Since the `Access` object active at the time is now gone, figuring out that link would require more work than seems ideal.

## Decision

*   Create a new `DeletedAccess` class that would be created whenever the application deletes an `Access` object.
*   This would have all of the fields in `Access`[^1] plus:
    *   `removed_at` (UTC timestamp)
    *   `removed_by_user` (reference to a user object)
    *   `removed_by_email_address` (email address of removing user) (these last two are not actually redundant).
    *   `removal_event` (this would mostly be something like `access-change`, but could theoretically in future include things like `account-inactivity`, `security-incident`, `data-correction`, etc.)

This approach has the advantage of not touching any of the existing `Access` code or related code paths, lowering the likelihood of breaking existing features; the same would apply to `User`, etc.

This would also be the path to follow for future entries of other kinds that we might might need to remove—if we need to remove `User` entries, we would put them in a `DeletedUser` table with the same four additional fields.

[^1]: `sac`, `role`, `fullname`, `email`, and `user`.

**Comment by timoballard** [comment]
Should we account for `Access` objects that are deleted through Django admin?

**Comment by tadhg-ohiggins** [comment]
Probably.

Also, I think that if this approach is approved, I might expand the ADR to cover what we're likely to do as the most basic support for `Access` changes.

**Comment by timoballard** [comment]
yeah, I think it's probably worth covering both the web and django-admin entrypoints in one go. Beyond that I think this approach looks good

**Comment by jadudm** [comment]
Without understanding some of what's in the weeds...

Is it enough to log the event to the table where we (waives hands) log events? Do we need to add the tracking machinery to the `Access` class, or could we just put it in the same table where we log other significant events?

**Comment by timoballard** [comment]
> Without understanding some of what's in the weeds...
> 
> Is it enough to log the event to the table where we (waives hands) log events? Do we need to add the tracking machinery to the `Access` class, or could we just put it in the same table where we log other significant events?

as it stands, the [submission event log](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/modellib/submission_event.py) tracks the type of event and who initiated it, but does not include any metadata about what specifically happened. So in this case, we'd be able to see that bob@example.com revoked _someone's_ access, but we wouldn't be able to see who that someone is

**Comment by tadhg-ohiggins** [comment]
@jadudm @timoballard I changed this to remove things covered in the user management ADR and to make it clearer that while we're starting with `Access`, this is probably a reasonable path to follow for future similar needs.

@jadudm I'm assuming that Tim's comment above makes apparent the need to create a new table for this kind of thing? Unless you think that instead of this approach we should expand the scope of [submission events](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/models/submission_event.py) to be able to track everything we'd need here?

**Comment by jadudm** [comment]
Ah. My apologies. I was operating from the assumption that the events table has a text field somewhere.

I'll defer. I think that when we give users the ability to view the event log, these are events that will *also* need to be user-visible. So, whether that means:

1. A rendering of events includes two tables, or 
2. We expand the scope of the events table

is up to the two of you. However, in our not-quite-yet feature roadmap is going to be providing users the ability to see the actions taken on their audit, and this will definitely be something that they will need to be able to see as part of that record trail.

**Comment by tadhg-ohiggins** [comment]
We'll have to do some amount of shaping work to present the data to the users in that future “actions take on my audit” view, and I think that checking for related entries in a `DeletedAccess` table won't add much friction there.

**Comment by tadhg-ohiggins** [comment]
Closed via #2822
