### ISSUE TITLE
Create documentation for modifying user role

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2743]
```[tasklist]
### Tasks
- [x] Modify user role KB article in ZenDesk
- [x] Modify user role docs on static site
```

**Comment by lauraherring** [comment]
The [page on the static site](https://www.fac.gov/resources/instructions/user-access/) is published and ready to be incorporated into a ZD article, @James-Paul-Mason.

**Comment by James-Paul-Mason** [comment]
@lauraherring ZD article written and published. https://support.fac.gov/hc/en-us/articles/22964442877709-How-can-I-change-user-access-or-modify-user-roles-for-my-audit-
