### ISSUE TITLE
Update URLs that change and add redirects where URLs cannot be changed

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#2746]

**Comment by danswick** [comment]
Some questions:
1. How long will we maintain redirects?
2. How can we get GA online?
3. Should we handle redirects at the cgov pages level or 11ty?

**Comment by lauraherring** [comment]
Hey @jperson1, [here's a spreadsheet](https://docs.google.com/spreadsheets/d/1wdCfGcv_s6LLAGSI9Ib65kLTNAWJl2_jduvO0d9dBBY/edit#gid=1182383919) with the old and new URLs. Let me know if this works/if you have questions.

**Comment by jadudm** [comment]
Why did we decide on 

`fac.gov/search-resources`

and 

`fac.gov/audit-resources`

as opposed to what feels like a more natural

`fac.gov/resources/audit`

and 

`fac.gov/resources/search`

?

**Comment by jperson1** [comment]
Completed by https://github.com/GSA-TTS/FAC-transition-site/pull/91.

Redirects are visible at file [src/redirects.md](https://github.com/GSA-TTS/FAC-transition-site/blob/main/src/redirects.md?plain=1)
