### ISSUE TITLE
[bug] Log out action redirects to the previous page instead of a general landing page, causing an unexpected 500

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2780]
There are two related issues here:

1. Sometimes, when users log out, they'll be redirected to a page that would otherwise require authentication. We should instead redirect them to fac.gov or some other general page that doesn't expect authentication.
2. When the above occurs, users are seeing a `500` page. While we shouldn't be directing them to these pages in the first place, a `500` is probably not the right status to report and implies we're not correctly handling authentication issues gracefully in these cases.

cc @timoballard @tadhg-ohiggins @asteel-gsa

**Comment by jadudm** [comment]
@timoballard , was this picked up? If so, is it merged? In which case, I think we can close it.

**Comment by timoballard** [comment]
yes, there were some recent bugfixes (#3393 #3404) that cleaned up some logout issues, and users are now redirected to the home page after logout
