### ISSUE TITLE
[bug] If a user deletes and recreates their login.gov account, we do not reassign Access objects to the new FAC user

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2782]
🎫 Related HD ticket: https://fac-gov.zendesk.com/agent/tickets/902

This requires some investigation, but users have reported unexpected `500`s that may be caused by the following scenario:

* User logs in to login.gov and creates some audits.
* Something happens and the user needs to delete and recreate their login.gov account **using the same email address**.
* User logs in to new login.gov account expecting to find their previously-created, in-progress audits. Instead, they see an empty list of audits. 
* User starts a new audit. After submitting the Access form, they get a `500` status page.

A possible explanation:
1. When the user submits the access form, the app creates an `Access` object for the first `User` that matches the logged-in user's email address.
2. The first `User` that matches the logged-in account's email address is actually associated with the previously-deleted login.gov account and we inadvertently use it to create a new `Access`.
3. When the general form loads, it checks whether the currently logged-in `User` is in the list of allowed accounts. 
4. The currently logged-in user is not actually allowed because we created the wrong `Access` in step 2. 
5. The user lands on a `500` page.

**Comment by tadhg-ohiggins** [comment]
#2783 addressed this, right? Now whenever someone logs in, we look at their email addresses and associate all `Access` objects with that email address to that user: https://github.com/GSA-TTS/FAC/blob/main/backend/users/auth.py#L14

**Comment by danswick** [comment]
> #2783 addressed this, right? Now whenever someone logs in, we look at their email addresses and associate all `Access` objects with that email address to that user: https://github.com/GSA-TTS/FAC/blob/main/backend/users/auth.py#L14

right you are!
