### ISSUE TITLE
Implement navigation updates

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#280]
### Background
Information architecture was refined in #371 and we need to update nav styles as a result, as well as a breadcrumb system

### Rough task list
- [ ] Update nav styles, including sign in / sign out state
- [ ] Implement breadcrumb system / UI

### To define
- What is the breadcrumb system? How does it relate to URLs? 

### Designs

[Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4828%3A21660)
![image](https://user-images.githubusercontent.com/2846578/191850261-460f315b-170a-4684-8959-2b7151057458.png)

For reference: Broke implementation out as follows.

```[tasklist]
### Implementation
- [ ] #912 
- [ ] #653 
```

**Comment by mogul** [comment]
Will hold off for now and re-review for consistency during Milestone 7.

**Comment by mogul** [comment]
@melchoyce can you create a new issue that breaks out the breadcrumb implementation?

**Comment by mogul** [comment]
For reference: Broke this out for implementation as follows.
```[tasklist]
- [ ] #547 
- [ ] #653 
```
