### ISSUE TITLE
[HD]: Update Workbook 1 Instructions Column O and P

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2810]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/884

https://fac-gov.zendesk.com/agent/tickets/1493

https://fac-gov.zendesk.com/agent/tickets/1598

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

In reviewing the Workbook 1 instructions we noticed an error in the instructions. If you mark in column N: Direct Award “Y" that the award is a direct award from a federal entity, then in column O you should leave this cell blank (because there is no passthrough entity to identify). However, in the instructions in column O, it states in the last line that “This field cannot be left blank if Direct Award (column N) is ”Y"). This should be revised.

This is incorrect: This field cannot be left blank if Direct Award (column N) is “Y".

Workbook 1 Instructions require an update under Column O and Column P's instructions:
https://www.fac.gov/resources/workbooks/federal-awards/

**Column O: If no (Direct Award), Name of Passthrough Entity**
If the award did not come directly from a Federal awarding agency, enter the name of the pass-through entity.

This field cannot be left blank if Direct Award (column N) is “N”.

**Column P: If no (Direct Award), Identifying Number Assigned by the Pass-through Entity, if assigned**
If the award did not come directly from a Federal awarding agency, enter the identifying number assigned by the pass-through entity.

If there is not an identifying number assigned by the pass-through entity, leave this field blank.

This field cannot be blank if Direct Award (column N) is “N”.

**Comment by lauraherring** [comment]
@alyssamwong I made these changes and published them this morning so this is taken care of.
