### ISSUE TITLE
Disseminate auditor certification

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2824]
[This line in intake_to_dissemination.py](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intake_to_dissemination.py#L275) has been commented-out for quite some time; I think it was originally introduced when the auditor certification page wasn’t implemented.

We need to either decide we’re not publishing this info, or make sure that the publication chain includes it, it’s covered by tests, etc.

**Comment by tadhg-ohiggins** [comment]
This may require a follow-on change to the API to pick up this info once it's being disseminated.

**Comment by danswick** [comment]
Done!
