### ISSUE TITLE
E2E improve: Create Transformation Utils for Common Transformations

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2833]
## Description
The goal of this ticket is to develop a transformation (xform) utility that can handle and standardize foundational Python types like strings, booleans. This utility will centralize the transformation logic for these types, ensuring consistency in our codebase.

### Task
Create a function named `string_to_string` (or similar) that will:

- Perform error checking (e.g., check for non-string types) and normalization (e.g., trimming whitespace) on string inputs.
- Throw an exception under specified conditions (e.g., if the input is not a string).
- Return the transformed string.

Create a function named `string_to_bool` (or similar) that will:

- Convert a string input to a boolean.
- Perform error checking.
- Throw an exception under specified conditions (e.g., if the input string does not represent a boolean value).
- Return the transformed boolean.

**Comment by danswick** [comment]
I think this is done. Feel free to reopen if i'm mistaken, @sambodeme!
