### ISSUE TITLE
Record Successful and Failed Migration Attempts (Logic)

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2841]
Update code to record the DB key and year of both successful and failed migration attempts.

**Comment by gsa-suk** [comment]
When a migration completes successfully, 

1. ReportMigrationStatus table will be updated with migration_status = 'SUCCESS', audit_year, dbkey, run_datetime. 
2. MigrationChangeRecord table will be updated with information about the transformations performed.

When a migration fails,

1. ReportMigrationStatus table will be updated with migration_status = 'FAILURE', audit_year, dbkey, run_datetime. 
2. MigrationErrorDetail table will be updated with error details and foreign key to the ReportMigrationStatus table.
