### ISSUE TITLE
Implement Django Model for Tracking Migration Attempts

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2843]
Add a Django model with the fields DB key, year, and status to record both successful and failed migration attempts.

**Comment by gsa-suk** [comment]
How is this table different from the 'ReportMigrationStatus' table defined in https://github.com/GSA-TTS/FAC/issues/2848 ?

**Comment by sambodeme** [comment]
There is no difference. This ticket was created to track the model's creation and should have been closed once the task is done.

**Comment by sambodeme** [comment]
Closed by #2845
