### ISSUE TITLE
🅜 Front End - Create new submission without valid UEI

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#285]
Breakout of https://github.com/GSA-TTS/FAC/issues/278

See above for acceptance criteria and designs. 

This issue covers new styling, new copy, modal (Assumption SAM.gov provides appropriate response for no results)

Still to be done:
- [x] Wiring up buttons inside modal
- [x] Handle error states - close it and try again or move forward without valid UEI
- [x] Tests for ^^

**Comment by sreuber** [comment]
@heymatthenry Heads up, new copy in the artboard: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3390%3A15694

This is just to be specific to an unrecognized UEI, not a general outage error (similar to the way the old artboard was written).

**Comment by heymatthenry** [comment]
Currently blocked by #376.

**Comment by petermarks-gsa** [comment]
@heymatthenry This is no longer blocked as #376 was resolved, right?

**Comment by heymatthenry** [comment]
That's right. Just moved it back to `in progress.`

**Comment by heymatthenry** [comment]
@petermarks-gsa I moved this straight into `Done` since we walked through the AC yesterday, but please feel free to move it back to review if necessary.
