### ISSUE TITLE
Add `state` filter to search

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2851]
Per conversations in Design/Dev huddle.

In coordination with @Leighdiddy and @James-Paul-Mason , we've identified that search by state is something users definitely need.

The filter should search by `auditee-state` (or whatever the field name is). We capture this as part of the `general` form. 

The state is a controlled vocab, so we're looking at matching `ME` with `ME`. A straight equality match.

To begin, we'll do this as a single select. We can iterate later if multi-select or other is deemed valuable. (If @Leighdiddy suggests something else, we should follow her guidance.)

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given** that I'm a resolution official trying to track down a passthrough   
**when**  I want to limit my search to a given state
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] I can select the state from a drop down
- [ ] Only results where the auditee's address reside in that state come back.
```  

There are no known security concerns from this work.

**Comment by timoballard** [comment]
to be clear (@Leighdiddy) - this should only search on auditee state, not the auditor state, correct?
