### ISSUE TITLE
Add Y/N columns for findings

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#2852]
# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given**   that I am a resolution official or IG
**when**  I want to find audits that are potentially problematic
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] I want to know which audits have findings regardless of ALN
- [ ] I want to know which audits have findings on ALNs that I have searched for
- [ ] I want to be able to sort (bring to the top) audits that fit in either (but not both) of these categories.
``` 

Per conversation, we're going to add two columns to the search results rather than add filters (at this time). The first column will tell the user if there are any findings on the record. The second will tell the user if there are any findings on any of the ALNs in the search.

## Any findings

This column always contains a `Y` or `N`. 

If, on any federal award, there is a findings count greater than 0, then this column is `Y`.

If all of the federal awards associated with this record have a findings count of 0, then this column is `N`. 

## Findings on a provided ALN

This column may contain a `Y`, an `N`, or a `-`. 

```
SELECT FROM federal_awards WHERE aln IN (list of provided_alns) AND count > 0
```

Note that the ALN will need to be broken up into a agency number and program number.

If the query returns non-empty, then that result row in the table should contain a `Y`. 

If the ALNs are present and all have a findings count of 0, then the table should contain a `N`.

It is possible a user does a search that does not involve ALNs. They may search only by state, for example. In that case, we have no ALNs to perform this query. The column should contain a `-`.

**Comment by timoballard** [comment]
This can be closed, yes @jperson1 ?

**Comment by jperson1** [comment]
Yes!
