### ISSUE TITLE
Update CSV to Postgres Logic to Prevent Empty Values Turning Into nan

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#2874]
We have identified an issue in the current implementation of our CSV to PostgreSQL import process. When importing CSV files into our PostgreSQL database, we're encountering a situation where empty string values in the CSV are being converted to the string 'nan' in the database.

**Comment by gsa-suk** [comment]
When the CSV file is retrieved from S3, empty strings are showing as 'NaN's.
