### ISSUE TITLE
Generate gaap_results from TYPEREPORT_FS in ELECAUDITHEADER

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#2903]
Create a functions to populate gaap_results in backend/census_historical_migration/sac_general_lib/audit_information.py using data in TYPEREPORT_FS in ELECAUDITHEADER.

Reference: https://github.com/GSA-TTS/FAC/issues/2832

**Comment by gsa-suk** [comment]
Some of the values in TYPEREPORT_FS, SP_FRAMEWORK, SP_FRAMEWORK_REQUIRED, TYPEREPORT_SP_FRAMEWORK columns:
<img width="841" alt="Screenshot 2023-11-30 at 1 13 40 PM" src="https://github.com/GSA-TTS/FAC/assets/135276194/63ac3280-52b1-433f-8347-a8ee427ec9dd">

**Comment by gsa-suk** [comment]
def _get_gaap_results(dbkey):
    elecauditheader = ELECAUDITHEADER.select().where(ELECAUDITHEADER.dbkey == dbkey).first()
    gaap_results = {
        "typereport_fs": elecauditheader.TYPEREPORT_FS,
        "sp_framework_basis": elecauditheader.SP_FRAMEWORK,
        "is_special_framework_required": elecauditheader.SP_FRAMEWORK_REQUIRED,
        "sp_framework_opinions": elecauditheader.TYPEREPORT_SP_FRAMEWORK
    }
    return gaap_results

**Comment by sambodeme** [comment]
We have a match for `CASH` and `OTHER` [here](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/base/GAAP.libsonnet#L23) but we don't have a clear match for `REGULATORY`. This will question will be discussed as part of #2912

**Comment by sambodeme** [comment]
Implementation is here https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/sac_general_lib/audit_information.py#L106
