### ISSUE TITLE
🅜 Record user in SAC form submission

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#291]
**Background**: Now that we are passing auth bearer tokens with our form submissions, we need to make sure we are recording user data for the submission and are limiting a submissions access to a given user. 

**Acceptance Criteria**:
* Login with login.gov
* Create a new audit by filling out forms
* Data for the audit including the user is visible is django admin

**Comment by timoballard** [comment]
@petermarks-gsa - the backend support for this appears to already be in place. When I manually trigger the eligibility/auditee/access endpoints (the last of which actually creates the SAC record on the backend), the resulting SAC in the database is tied to my user record (via the `submitted_by` field). This linkage is verifiable from the django admin panel: 

![image](https://user-images.githubusercontent.com/1425377/176716812-8910b931-eb0a-4795-87e0-871126c6bbce.png)
