### ISSUE TITLE
Add the single-report downloads to the search summary template.

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#2923]
For each report entry in the search results table, we should enable the user to download a summary spreadsheet containing the disseminated report data.

**Comment by timoballard** [comment]
Closed by #2987

**Comment by Leighdiddy** [comment]
_Feature notes:_ https://docs.google.com/document/d/1HcFogdV_JmcUnS6arHiuWK90P3tYyldcBUydyZqelqo/edit?usp=sharing
