### ISSUE TITLE
[HD]: Workbook 1 Cluster Total Errors

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2947]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/690

https://fac-gov.zendesk.com/agent/tickets/1309

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### Gdrive link

690 and 1309: https://drive.google.com/drive/folders/1FUXKQmpDqsJQfO6mmc0epih8fPoSC0c4?usp=drive_link

### What happened?

Per ticket 690 comments: Negative expenditures located in the Amount Expended column F is mapping out the R&D clusters, when the clustors totals are calculated based on absolute value - which is why the spreadsheet is over by $151,219. I think the $151,219 delta is what his negative expenditures balances out to. This is possibly what is causing errors on upon upload.  

Ticket 1309: K5, K6, K7 errors: 
This cluster total is 482299, but should be 0.

**Comment by danswick** [comment]
Some breadcrumbs we could follow in the future:

1. Some users have worked around negative values by putting them inside parentheses. 
2. We could ask which workbook version they are working with.
