### ISSUE TITLE
[HD]: Submitted/Accepted report not showing in search

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2952]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1287

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

I could not locate this report in Search.
**From user:**
The UEI is K4ZDA84UXNN5.
I was informed the audit was submitted on November 17, 2023.
One recipient notified us that its 2021 audit was accepted by the FAC and provided a screenshot of its accepted status from this new FAC site. When I search (both when logged out and logged in) no records appear. I've tried the search by UEI, EIN, Name, and with/without the audit year selected. I have also tried this in both Chrome and Edge. Please assist.

**Comment by danswick** [comment]
Needs follow up and/or replicate. @tadhg-ohiggins and @James-Paul-Mason.

**Comment by jadudm** [comment]
This is a tribal audit. Answering in ZD. It was accepted correctly.
