### ISSUE TITLE
[HD]: Content Issue with Auditor Certification Language

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2957]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1089

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/u/2/folders/1vYwKPtXugG_5q9eJ3qrqqpf97xuEyIO8

### What happened?

**BLUF: 
The text of item #2 on the auditor checklist must be changed:**

"The auditee completed the Federal Awards workbook using the audit reporting package as required by the Uniform Guidance."

**Must be changed to...**

"The information in Part II of this Form SF-SAC is the responsibility of the auditee and is based on information included in the reporting package required by the Uniform Guidance"
--
As per @Carley-Jackson the auditor certification language must be changed back to the original certification language (for checkbox 2, see screenshot in Google Drive).  
 
Please refer to part 5, item 2, checkbox 2 on the PDF in G-Drive for the correct language (or see BLUF above). @lauraherring @Leighdiddy @Jamesper

**Comment by lauraherring** [comment]
If I'm reading this ticket right, this is an exact text swap out in the app so it should be something that @jperson1 can knock out without further input from content.

**Comment by lauraherring** [comment]
I've picked this up and created [a new branch](https://github.com/GSA-TTS/FAC/blob/lh/fixing-2957/backend/audit/templates/audit/auditor-certification-step-1.html) to make this change.

**Comment by jperson1** [comment]
Completed as by https://github.com/GSA-TTS/FAC/pull/3017, and is active in the production environment.
