### ISSUE TITLE
Add "locked" helper text to cover sheet of generated workbook

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#2964]
Add helper text to generate workbook coversheet noting that it is locked and can't be edited / won't affect the corresponding audit. 
```[tasklist]
### Tasks
- [x] Draft text
- [ ] Add helper text logic to openpixel workbook generation
```

**Comment by lauraherring** [comment]
Here's the text for coversheet, based on the language we're also putting on the certification page.

> This file is for review only. It is locked for certification and can't be edited.

**Comment by jadudm** [comment]
This text suggests that this file was actually part of the certification process. It is not "locked _for_ certification."

"This file is locked and for review only." may be more accurate?

**Comment by lauraherring** [comment]
If that's the case, then we should make the copy:

> This file is for review only and can't be edited.

**Comment by jadudm** [comment]
Implemented. Will merge as part of... https://github.com/GSA-TTS/FAC/pull/2987
