### ISSUE TITLE
[HD]: Audit Report PDF not uploading

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#2974]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/773

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [X] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Microsoft Edge

### Gdrive link

https://drive.google.com/drive/folders/1_BRunCTeQ8jJMt7GGLDZKGS8JmAcH5M0?usp=drive_link

### What happened?

User's audit report PDF meets system requirements, but still fails to upload. Staging displays a 400 error.

**Comment by danswick** [comment]
ZD ticket marked as resolved.
