### ISSUE TITLE
Determine tags to be used for the table and document

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#2978]
As mentioned [here](https://github.com/GSA-TTS/FAC/issues/2977), the `migrationerrordetail` table will have a `tag` column that will be used to generally categorize errors. They will be restricted to short, snake_case descriptions, such as `bad_zipcode`. For this ticket, start compiling tags we'll want to use.

**Comment by gsa-suk** [comment]
There are 4 types of errors that could occur in census_historic_migration.
1.  DataMigrationError
2. ValidationError
3. Exception
4. CrossValidationError

**Comment by phildominguez-gsa** [comment]
- `ValidationError`: `validation`
- `CrossValidationError`: `cross_validation`
- `Exception`: `exception` ? `unknown`?
- `ValueError`: `value`
- `DataMigrationError`
  - [Skipping ACE audit](https://github.com/GSA-TTS/FAC/blob/c2c2ba9fafdc852b080daacb05b6344d8fb9f3a0/backend/census_historical_migration/workbooklib/end_to_end_core.py#L204): `skip_ace_audit`
  - [UEI value is missing or invalid](https://github.com/GSA-TTS/FAC/blob/a10d74f55810db71675c35c88b1f710bdce81b3f/backend/census_historical_migration/workbooklib/excel_creation_utils.py#L130): `invalid_uei`
  - [No audit header record found](https://github.com/GSA-TTS/FAC/blob/a10d74f55810db71675c35c88b1f710bdce81b3f/backend/census_historical_migration/workbooklib/excel_creation_utils.py#L139): `missing_audit_header`
  - [Invalid mappings](https://github.com/GSA-TTS/FAC/commit/b2ae52ec0557526b5c82ecfb187af70217951b37#diff-eae075bf6e57d4c88fcec4401de5304a3013148a8a386af8c219aee997fac79bR165): `invalid_mappings`
  - [Zip code is malformed](https://github.com/GSA-TTS/FAC/commit/b2ae52ec0557526b5c82ecfb187af70217951b37#diff-eae075bf6e57d4c88fcec4401de5304a3013148a8a386af8c219aee997fac79bR238): `invalid_zip`
  - [Unable to determine if the de minimis rate was used](https://github.com/GSA-TTS/FAC/blob/f698ca833e35173b28fb3e4e32850508427f39ec/backend/census_historical_migration/workbooklib/notes_to_sefa.py#L76): `invalid_de_minimis_rate`

**Comment by phildominguez-gsa** [comment]
Closing for now and will update as needed
