### ISSUE TITLE
[HD]: EINs can have leading 0s

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#2985]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/905

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

User summarizes the issue comprehensively: 

Hello, I work for an auditor and have run into an issue with the additional EINs workbook. I have an additional EIN number to enter that begins with a zero, which the character count is not recognizing as part of the full EIN number (9 character requirement). I received a stop error message stating that there needs to be 9 characters in that cell in order to proceed/save the workbook. I have tried to unprotect the sheet, format the individual cell as custom so that the zero will appear in the cell, and change the settings under data validation from a stop error message to a warning error message in order to save the workbook. However, when I try to upload the workbook, I receive the following error message, which doesn't appear to relate to the workbook I am trying to upload at all, since it references UEI and 12 characters in the error message instead of EIN and 9 characters. I'm hoping someone can walk me through how to enter/upload an additional EIN number workbook that has an EIN beginning with zero.

“UEIs are 12 characters long and match rules as given by SAM.gov.”

**Comment by danswick** [comment]
Needs to be replicated. @tadhg-ohiggins, @James-Paul-Mason and I will add to the replication backlog.

**Comment by danswick** [comment]
User was using an old version of the workbook and has since resolved their issue.
