### ISSUE TITLE
Investigate submissions that are missing mandatory roles

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#2992]
We’ve seen submissions in production that don’t seem to have the full set of `Access` entries—that is, either `Access` entries with the `certifying_auditee_contact` role, or the `certifying_auditor_contact` role, or both, are not listed as associated with the submission. It’s required that users supply information for these roles when creating the submission, and it’s not clear how these submissions could have been created without them.

No code for deleting these `Access` entries was live before we saw these cases, and in addition the `Access` deletion code specifically requires that new certifying roles must be created, so the new user management code is not the explanation for this problem.

This problem would result in users having to start the submission over—there’s no user-accessible way to add these roles if they don’t already exist, and it would require superuser authorization to do this in the database.

Some examples of this happening are in Slack [here](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1701979816466359) and [here](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1702061131354569).

Since it’s not clear what’s going on, this issue doesn’t have tasks beyond trying to figure out what’s causing this.

**Comment by danswick** [comment]
tagging @James-Paul-Mason for visibility.

**Comment by James-Paul-Mason** [comment]
I am recording the ZD ticket numbers of the affected users so I can easily find/reply to them when we have an answer.
https://fac-gov.zendesk.com/agent/tickets/1242
https://fac-gov.zendesk.com/agent/tickets/1334
https://fac-gov.zendesk.com/agent/tickets/1425

**Comment by tadhg-ohiggins** [comment]
My best current guess is that this is the result of [Bug: Users with non-unique emails unable to create submissions](https://github.com/GSA-TTS/FAC/issues/3067), and that when users created submissions triggering the problems from #3067 it resulted in submissions being created but failures when attempting to create the `Access` entries in question.

How plausible does that sound? @timoballard ?

**Comment by tadhg-ohiggins** [comment]
If the hypothesis from my above comment is correct, then this will have been fixed via:

*   [Bug: Users with non-unique emails unable to create submissions](https://github.com/GSA-TTS/FAC/issues/3067) and 
*   [Manage issues around Access and missing certifier roles](https://github.com/GSA-TTS/FAC/pull/3072)

That would mean no future occurrences of this issue, and existing problems could be addressed via the access management features.

**Comment by timoballard** [comment]
We [independently arrived at the same hypothesis](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1703187710320919?thread_ts=1703187284.507809&cid=C03QCP4FSN8), so I think that makes it quite plausible 😄

**Comment by tadhg-ohiggins** [comment]
We're pretty sure this was closed by:

*   [Allow Access creation for non-unique emails](https://github.com/GSA-TTS/FAC/pull/3068)
*   [Manage issues around Access and missing certifier roles](https://github.com/GSA-TTS/FAC/pull/3072)
