### ISSUE TITLE
[HD]: Workbook 1 Upload Timeout Error Message

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#3005]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1443

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/folders/1yUo_8RBTpbqK6224y03Qvy1QwndLOTBM?usp=drive_link

### What happened?

User experiencing a timeout message when they upload their workbook1. It's likely due to their workbook file size, as the info filled in go up to row 4000s.

**Comment by danswick** [comment]
We need to investigate increasing the timeout. cc @sambodeme
