### ISSUE TITLE
Content and visual design for editor role addition.

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3006]
We need a place on the access management page to put a link to the add editor page; unlike with the certifying roles, we can't just put it next to rows in the table, since it's for adding a new person, not editing a current person.

**Comment by Leighdiddy** [comment]
<img width="533" alt="Screenshot 2023-12-19 at 3 58 21 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/0759c447-6856-413e-86a6-cc7f2af50f6e">

**Comment by lauraherring** [comment]
@Leighdiddy @jperson1 New copy is in the Google doc for this project.

**Comment by lauraherring** [comment]
Here's the link to the doc with the copy for this update: https://docs.google.com/document/d/1TqYN_F0wMzy02YqHwOGj6rpTdiaVRc5v5z-ypmt_nl0/edit
