### ISSUE TITLE
Discuss potential refactor of section completion info

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3011]
Follow up on feedback for PR #2910:

> How difficult would it be to move a lot of this into sac_validation_shape() instead? That function already takes a SingleAuditChecklist instance as an argument, and we could put the per-section information into the sf_sac_meta field in the dictionary it returns, instead of altering the other functions to also require taking a SingleAuditChecklist argument.

https://github.com/GSA-TTS/FAC/pull/2910#issuecomment-1836373162

**Comment by danswick** [comment]
This doesn't look like a priority for now, but we can always come back to it later.
