### ISSUE TITLE
[Epic] Unlock from "auditor_certified" and "auditee_certified" 

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3012]
Following the work done in https://github.com/GSA-TTS/FAC/issues/2355, which enabled users to unlock an audit after moving into "ready for certification" state, users would also like the ability to unlock after moving an audit into `auditor_certified` and `auditee_certified` states. **Note**: _the app should never allow unlock after an audit has reached `submitted` or `disseminated` states_. 

Task list to be fleshed out whenever this ticket is ready to be prioritized.

**Comment by jadudm** [comment]
Complete. Closing this ticket/epic.
