### ISSUE TITLE
[HD]: Auditee cannot certify, receives 500 error

### ISSUE THREAD

**Issue by alyssamwong** [GSA-TTS/FAC#3027]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1423

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

User is experiencing issues accessing auditee certification. They should be able to certify the record. 2023-06-GSAFAC-0000003319

**Comment by danswick** [comment]
@alyssamwong did this issue get resolved?
