### ISSUE TITLE
Spike: Generate a large amount of dissemination data for non-production environments

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3028]
The comparatively small amounts of data in our non-production environments mean we don’t see some problem that are evident in production.

We could pull some amount of the production dissemination data and put it in the other environments (including making it available for local development).

Any issues with collisions? We pull dissemination data and then somehow have the same `report_id` in a lower environment and break things when we push? Do something to `report_id` values as part of migration? Changing the source—that is, changing the `GSAFAC` string in the `report_id` to something like `FRMPRD`—might work, but could potentially cause other issues.

We would not pull tribal reports down, but we should probably tweak some of the data we grab so that they’re switched to tribal, so that we have test data to work with.

This spike will be done when we have the following:

- [ ]   A decision on how many records to pull from the dissemination tables in production.
- [ ]   A reasonable idea of the practical approach (do it in a GitHub action/ do it locally and push to environments/etc.) to copying the data.
- [ ]   A description of the transformations (if any) to apply after getting the data from production before loading it into the target environment.

**Comment by jadudm** [comment]
We're finishing up the historic migration now, and should be able to pull a subset into staging pretty easily.

That said, we're going to want to have a way to reliably/repeatably load it in. 

Which... you said. I got this far repeating what you said, so I'm committed to finishing the comment regardless...

**Comment by danswick** [comment]
Noting that we did run into a collision issue between dissemination and submission data in staging just yesterday!

**Comment by danswick** [comment]
This is done.
