### ISSUE TITLE
Spike: Generate a large amount of submission data for non-production environments

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3029]
The comparatively small amounts of data in our non-production environments mean we don’t see some problem that are evident in production.

We could pull some amount of the production submission data and put it in the other environments (including making it available for local development).

We would not pull tribal reports down, but we should probably tweak some of the data we grab so that they’re switched to tribal, so that we have test data to work with.

We would probably need to also pull `Access` entries from that are associated with the submissions, but then change the email/user data in those submissions so that the actual users of the lower environments would have access to the submissions. This would also need to be done in such a way that wouldn’t disrupt current workflows (like Cypress tests)

This spike will be done when we have the following:

- [ ]   A decision on how many records to pull from the dissemination tables in production.
- [ ]   A reasonable idea of the practical approach (do it in a GitHub action/ do it locally and push to environments/etc.) to copying the data.
- [ ]   A description of how to make the submissions useful to users in the lower environments without breaking current workflows.
- [ ]   A description of the transformations (if any) to apply after getting the data from production before loading it into the target environment.

**Comment by danswick** [comment]
I think this is mostly satisfied by @gsa-suk's work on dissemination data. We don't have a system for intake data, accesses, etc, but it doesn't seem like a priority right now. Feel free to reopen if this is something we want to pursue.
