### ISSUE TITLE
design "Audit Start Page" page for implementation based on sprint 6 research insights

### ISSUE THREAD

**Issue by austinhernandez** [GSA-TTS/FAC#303]
Breakout issue of #274 

**Background**
[Sprint 6 research -  observations/refinements by page](https://docs.google.com/document/d/1Y8g7HEd6eysBQjg3x_-K3nzk9M9xBCp5w8eZXql_8xQ/edit#heading=h.ycduc4d91ltn)

**Observation(s)**
- Most users identified that they could edit the UEI beginning here and recognized this element on the subsequent SF-SAC pages.
- One user completely missed the ability to update the invalid UEI at any step in this process and assumed it needed to be done in the SF-SAC General Info page.
- Several users appreciated that they could update the entity type here.
- Multiple users didn’t feel that completion date/time/by columns would be all that useful.
- Version number field again was pointed out as confusing.
- The View/Print Form SF-SAC link was appreciated by several users.
- Numbering on tasks confused at least one user, particularly around the certification buttons (they thought it was a typo that there were two 3’s).
- A couple of users in this research spike as well as users from the first round suggested that some indicator of when the auditee had submitted could be helpful to the auditor.

**MVP recommendation(s)**
- Remove version number.
- Removing task numbers on the CTAs may be fine here (alphanumeric callouts for different sections in the form were removed and perhaps these no longer need to exist here either).

**Future improvements**
- Would “Last updated date/time” and “Last updated by” be more useful? 
- Investigating a way to enter when the auditee submitted their info to the auditor agency could be helpful, and then referencing that with some indicator on this page. They have frequently spoken to better understand the risk when they are in that 30 day timeline.

**Tasks**
- [x] Review sprint 6 research analysis
- [x] Create checklists for refinement needed to each page
- [x] Update #274 with the checklist of refinements needed
- [ ] Make refinements
- [ ] Peer review

**Definition of done**
**Acceptance Criteria (We'll know we're done when...)**
- [ ] Screens in Figma are ready to be handed off to front end
- [x]  All text has a contrast ratio of 4.5:1 with the background
- [ ]  Interaction are documented if they deviate from USWDS components
- [ ]  The needs of someone navigating the site with the use of a screenreader or keyboard has been considered and documented 
- [ ] There is an option for multilingual support
- [ ] There is supporting documentation for alt text, labels for links (anchor + target), error text in forms, and what assistive technologies should announce (if applicable)

**Comment by MelissaBraxton** [comment]
@sreuber I think you have some thoughts on this already? With @austin out, would you be able to drive this forward and loop in @melchoyce?

**Comment by sreuber** [comment]
Open to peer review! Check the comments please. @MelissaBraxton @melchoyce @austinhernandez 
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3407%3A15718

**Comment by sreuber** [comment]
@MelissaBraxton @melchoyce @austinhernandez 
Further refinements here, open to peer review:
[Start Page (standard)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3407%3A15718)
[Start Page (invalid UEI)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3458%3A16797) 
[Start Page modal (edit entity type)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3457%3A16114)
[Start Page modal (edit UEI initial)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3457%3A16257) 
[Start Page modal (edit UEI, new unconfirmed)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3458%3A16405)
[Start Page modal (edit UEI, new confirmed)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3458%3A16573)
[Start Page modal (unlock)](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground-(Copy)?node-id=3457%3A16400)

**Comment by melchoyce** [comment]
Looking good! Left a few minor comments in Figma.

**Comment by MelissaBraxton** [comment]
Looks good to me too, @sreuber  - With the accessibility fix that Mel called out, I think we can move this to "in review"?
