### ISSUE TITLE
Explain that results are limited to 1000

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3035]
We're currently planning to limit bulk export to 1000 results. During initial testing, larger batches loaded slowly and 1,000 seemed to be a reasonable place to limit, but it may be revised up or down later.

Some options:

* Put disclaimer in coversheet
* Add some helper text to the summary UI explaining limit
* Add helper text encouraging users to limit results to 1000

cc @lauraherring @jperson1 @timoballard

**Comment by lauraherring** [comment]
@jperson1, @Leighdiddy and I settled on a 3-prong approach to this one:

- Added helper text to the page making it clear bulk download is only for 1,000 results at a time and users who want bigger should refine search parameters to download in batches. This text also points to the API documentation page.
- Added similar copy to the cover sheet of the downloaded results worksheet
- Made it so the bulk download button only appears for results less than 1,000

These changes are in PR #3025
