### ISSUE TITLE
No easy way to `GSA_MIGRATE` flag `dollar_threshold`.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3036]
https://github.com/GSA-TTS/FAC/pull/3008/files#diff-68efbab2880ab0b6eb95a0faebc61ae0d3d818df7ed8914c354c3a2e0f66f7efL17

The dissemination tables have this as an `INTEGER`, so we cannot put `GSA_MIGRATE` in this field without updating the dissemination tables and the API. 

To be discussed and... something.

**Comment by jadudm** [comment]
Initial conversation suggests that @gsa-suk will look at what these values look like in the historic data, and we may go with a sentinal value (like `-999999`) where nothing is present.

**Comment by gsa-suk** [comment]
There are no negative values for DOLLARTHRESHOLD in census historic data.  Here is a summary of all values present:
dollarthreshold.csv in https://drive.google.com/drive/folders/1fQydz5dKOoPn8yRN8uBoaytFnf6N4ApT

**Comment by tadhg-ohiggins** [comment]
@jadudm during dev huddle today it sounded like we already have the negative sentinel in our code, is this still an open issue?

**Comment by jadudm** [comment]
It probably wanted to be tracked by one of the migration tickets. However, it was answered/addressed. Closing.
