### ISSUE TITLE
[HD]: review certification resulting in error 500

### ISSUE THREAD

**Issue by Carley-Jackson** [GSA-TTS/FAC#3039]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1532

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

Chrome

### What happened?

Error 500 when looking to review the draft submission prior to certification steps.

**Comment by tadhg-ohiggins** [comment]
The 500 error is at `/audit/summary-report/xlsx/<report_id>`. The logs include lines similar to this:
```
/home/vcap/app/dissemination/summary_reports.py\", line 469, in generate_presubmission_report\n    data = gather_report_data_pre_certification(i2d_data)\n  File \"/home/vcap/app/dissemination/summary_reports.py\", line 381, in gather_report_data_pre_certification\n    for obj in dissemination_data[model_name]:\nTypeError: 'NoneType' object is not iterable"
```

**Comment by tadhg-ohiggins** [comment]
Almost definitely addressed by https://github.com/GSA-TTS/FAC/pull/3041

**Comment by tadhg-ohiggins** [comment]
The SAC in question has been disseminated, so this was solved. Closing.
