### ISSUE TITLE
List all transformations in census_historic_migration

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3040]
Make a list of all transformations in census_historic_migration.

**Comment by gsa-suk** [comment]
The transformation functions:
xform_add_hyphen_to_zip
string_to_string
string_to_bool
string_to_int
xform_census_date_to_datetime
xform_entity_type
xform_country
xform_auditee_fiscal_period_end
xform_auditee_fiscal_period_start
xform_audit_period_covered
xform_audit_type
xform_apply_default_thresholds
xform_framework_basis
xform_census_keys_to_fac_options
xform_build_sp_framework_gaap_results
_xform_agencies
_xform_set_certification_date
xform_dbkey_to_report_id
xform_remove_trailing_decimal_zero
_xform_populate_default_passthrough_values
_xform_populate_default_loan_balance
_xform_populate_default_award_identification_values
xform_prior_year_findings
xform_cleanup_string
xform_is_minimis_rate_used

**Comment by gsa-suk** [comment]
Question:  string_to_string is only removing leading and trailing white spaces.  Should this be included in the transformations list ?

**Comment by phildominguez-gsa** [comment]
Some further research for being able to create `MigrationChangeRecord`s within xform methods

- Everything but xform_dbkey_to_report_id would need report_id to be passed in
- Everything has access to original and new values, though sometimes not 1:1
- What should be used for `transformation_function` besides the method name? Commit hash, in case it changes?

Only in mappings 
- Used here https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/sac_general_lib/utils.py#L15
- xform_remove_hyphen_and_pad_zip
- xform_entity_type
- xform_apply_default_thresholds
- xform_remove_trailing_decimal_zero
- xform_prior_year_findings
- Need: Audit year and DB key (from audit_header)

Nested
- xform_census_date_to_datetime
	- Within xform_dbkey_to_report_id, xform_auditee_fiscal_period_end, xform_auditee_fiscal_period_start
	- Have: Audit year and DB key (from audit_header)
- xform_framework_basis
- xform_census_keys_to_fac_options
	- Within xform_build_sp_framework_gaap_results
	- Need: Audit year and DB key (audit_header in calling func)

In general_information 
- xform_auditee_fiscal_period_start
- xform_auditee_fiscal_period_end
- xform_country
- xform_audit_period_covered
- xform_audit_type
- Need: Audit year and DB key (audit_header in calling func)

In audit_information
- xform_framework_basis
- xform_census_keys_to_fac_options
	- Need: Audit year and DB key (audit_header in calling func)
- xform_build_sp_framework_gaap_results
	- Have: Audit year and DB key (from audit_header)

In auditee_certification and auditor_certification 
- _xform_set_certification_date
- Need: Audit year and DB key (audit_header in calling func)

In setup_sac and generate_dissemination_test_table
- xform_dbkey_to_report_id
- Have: Everything

In generate_federal_awards
- xform_populate_default_passthrough_values
- xform_populate_default_loan_balance
- xform_populate_default_award_identification_values
- Need: Audit year and DB key (audit_header in calling func)

In generate_notes_to_sefa
- xform_is_minimis_rate_used
- Need: Audit year and DB key (audit_header in calling func)

Included?
- string_to_string
- string_to_bool
- string_to_int

Not used
- xform_cleanup_string
