### ISSUE TITLE
[HD]: Auditee cannot certify: 500 error despite correct emails for certifying officials

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3069]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1575

### FAC components involved

- [X] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

2023-06-GSAFAC-0000005261
Auditee certifying official continues to receive 500 error when attempting to certify. All the emails in the Report ID are correct and the report is Auditor certified.

**Comment by tadhg-ohiggins** [comment]
@James-Paul-Mason I can't see any issues with the submission, and the only errors I see associated with the `report_id` are 403 errors, not 500s. Is the user definitely getting 500s and not 403s?

The `Access` entries look correct to me and I'm not sure why they'd be getting 500s _or_ 403s, but being sure about which would make troubleshooting easier.

**Comment by collins050199** [comment]
I am the auditee certifying official and have tried both Google Chrome and Microsoft Edge and receive the same error in both browsers.  The error message is 500 Error: Internal Server Error; Something went wrong. Try refreshing the page, or come back later.

**Comment by collins050199** [comment]
I understand from our auditor that our single audit submission is due today! Can you help me troubleshoot and resolve the issue?

**Comment by collins050199** [comment]
Hallelujah!  I was able to successfully submit the single audit this afternoon!  Many thanks to those involved in the troubleshooting!  This case can be closed.  Thank you!
