### ISSUE TITLE
PRD - PDF Validation

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#307]
Background: When audit PDF's are uploaded to the current Census FAC, they are validated for being text, searchable and unlocked. This is important because before they had these checks, they'd get scanned PDFs and auditors could not search for specific text. Also sometimes get locked files where they can’t take pages out or can’t even open it. Users tell us we need these documents to be workable. It's also possible that some or none of these validations are viable for MVP. It's possible that without this

Acceptance Criteria:
- [ ] Compared a few libraries and considered security/compliance considerations. 
- [ ] Estimate effort of  text, searchable and unlocked validations
- [ ] Compare estimates with user needs and make a decision for MVP

**Comment by jadudm** [comment]
As a note, it is possible the repository that had the Excel validation has a demo of some PDF validation as well. Or, I might have that code local, and in need of push. It would be front/client-side only. Just noting so it doesn't get lost.
