### ISSUE TITLE
🅢 Update SF-SAC pages to remove web form data entry

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#313]
Breakout issue of #274

**Background**
For the MVP, we've decided to allow data input via Excel only. We need to update the mocks for a few pages that still have both an Excel and and a web form data entry option. This applies to the **Secondary auditors** page and the **additional UEIs** pages. 

**Acceptance Criteria (We'll know we're done when...)**
- [ ] None of the mocked SF-SAC form pages have both Excel and webform options for data input. 

**Tasks**
- [ ] Refine mocks
- [ ] Add implementation notes

**Comment by MelissaBraxton** [comment]
Moving to blocked until design/eng discussion of dynamic Excel templates on Wed. 7/6.

**Comment by MelissaBraxton** [comment]
The key places where Excel data impacts how other data collections forms/screens work: 

Places where answers on some form pages **unlock** other parts of the data collection form.

 - Answers on the SEFA form lock/unlock: Award findings, findings text, and CAP text pages

Places where data from one part of the form appears on templates for other parts of the form:

 - The list of federal awards entered on the SEFA form appear on the award findings template.

**Comment by MelissaBraxton** [comment]
This is currently blocked by #324.

**Comment by melchoyce** [comment]
Blocked by https://github.com/GSA-TTS/FAC/issues/328

**Comment by petermarks-gsa** [comment]
Per discussion with @melchoyce, this is essentially done. Per #447, we are exploring putting it back in.
