### ISSUE TITLE
Observability

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3132]
## High level goals:

1. Improved internal log capture. For example, better error traces, which might require more app instrumentation beyond the basic `new_relic.initialize()`. 
3. Generate a list of alert conditions. For example: rate of 500s, app response time, etc. Note: GSA IT will provide some guidance around SOPs for suspicious behavior, etc. 

## Open questions:

1. What would it take to set up/configure a browser agent?
2. What kinds of built-in functionality can we just turn on? DDoS alerts, etc.
3. Would it be possible to track issues during build and deploy?
4. How are we currently logging issues with invalid auth tokens (login JWTs, API tokens, etc)?

```[tasklist]
### Tasks
- [ ] Identify three questions we want to answer with observability (discuss at various huddles)
```

**Comment by jadudm** [comment]
This epic is not well scoped. I feel like we've done a number of things around observability, and now discussed some next steps. I'd like to either close this epic (and write a more focused set of tasks), or rescope this and put a timeline on it. I'm cool with either. I feel like observability should be worked into other epics, just like testing: as we are doing feature work, we should be asking *how can we see this*? That might be a better way to shape the work going forward.

**Comment by jadudm** [comment]
This is neither an epic nor actionable. I'm closing this ticket.

We want observability to be part of all work going forward. It should be front-and-center, just like testing. "Is this new feature *observable*" is a question we should be asking
