### ISSUE TITLE
Spike: Submission guide

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3140]
We have limited documentation for submission. There is nothing that guides a user through a submission from start to finish, in terms of what must be done, when it must be done, and what resources need to be in place in order to be successful.  We might use [the login.gov documentation](https://www.login.gov/help/get-started/create-your-account/) as a model: it is thorough and keeps the user oriented throughout a fundamentally complex process.

[An exploration of what this might look like](https://docs.google.com/document/d/1AChebztxadEZ2C4PHZbG_12deWxHuqMZK0mocNNQ0zE/edit#heading=h.oxv0mrsc5o9u) is in GDrive.

For this spike, we should:

1. Discuss what a submission guide might look like
2. What resources we want to make sure we include
3. Bounce the outline past a few auditors/auditing orgs for quick feedback

Having a guide in place by mid-February (approx. 4 weeks) would be a massive boon to our users. It can then be iterated on/improved through March.

**Comment by lauraherring** [comment]
Hey @jadudm, looking at the Login example and the doc you've started, it seems to me like we can work on adding to [our existing walkthrough page on FAC.gov](https://www.fac.gov/resources/instructions/) for this instead of creating something brand-new. Does this approach work for you?

**Comment by jadudm** [comment]
Oh, absolutely. The point of the spike is for us to riff/discuss. I banged some text out so I could even wrap my head around it. 100%, I think we already have a lot of pieces, between what's on the site and the HD content, etc.

We might also decide we need something else. But, I'd at least like us to engage with it.
