### ISSUE TITLE
Spike/Exploration: Visual indicators for tribal audits

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3141]
## User story

**As a federal user with permission to view suppressed tribal audits, after I've logged in I want confirmation that suppressed tribal audits are being included with my search results.** 

Currently: Suppressed audits will appear in search results for users with permission once they're logged in, but there is nothing to indicate which audits are suppressed in the results table. 

## Questions

1. Once a user logs in how do they know that they have suppressed tribal audit access? Should we visually indicate this somewhere in addition to the search results table?

2. Would a visual indicator of which audits are suppressed in the search results table itself be useful?

3. Should we duplicate the workflow from Census? _A logged in user knows that they have access to suppressed audits because their results table view is different depending on whether or not they're logged in. Census assumed this was an adequate indicator, to the best of our knowledge it was not tested/confirmed with users._

4. All users are routed to the audit submission home page upon logging in. Should we update this page design/copy to acknowledge both parties (submission and search)?

**Comment by Leighdiddy** [comment]
notes doc: https://docs.google.com/document/d/11IICFm42Mde5GnW8AVF9LJKhoGq7-sd3LYr8FoaywTc/edit?usp=sharing

**Comment by Leighdiddy** [comment]
Pending convo re: best approach

**Comment by danswick** [comment]
The above convo happened and it sounds like there were no clear next actions / priorities. Closing here.
