### ISSUE TITLE
Revise/collapse checklist

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3161]
1. We think the checklist can collapse after lock for certification.
2. We think the SF-SAC and report download can appear in the checklist at that point.
3. It should be possible to lock/unlock from the same place.

**Comment by Leighdiddy** [comment]
Proposed solution: Once the validation step is complete, the submission checklist loads partially collapsed with updated text in the info box explaining how to review for certification and lock/unlock + reupload as needed:

![Image](https://github.com/GSA-TTS/FAC/assets/119363060/b050ef40-e77d-4320-bcc1-8293edbe24f0)

**Comment by Leighdiddy** [comment]
For content - Revise copy and location of user warning re: locking (currently shown at validation step), new infobox copy

**Comment by lauraherring** [comment]
@jperson1 Sorry, one last bullet to be added re. notifications:

- **The FAC doesn't send email notifications.** You may want to notify certifying officials the submission is ready for their review.
