### ISSUE TITLE
🅢 Ensure data submitted on frontend makes it to the backend

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#317]
Breakout of https://github.com/GSA-TTS/FAC/issues/128

This is integration work between front end and backend long the lines of what @jasnakai did in #226 and #228

**Comment by jasnakai** [comment]
Adding FE task to append an incrementer to the end of the added Auditor and Auditee Contacts on the Audit submission access form. 
![Screen Shot 2022-07-22 at 2 07 50 PM](https://user-images.githubusercontent.com/106776019/180520394-66045fe1-4d2f-4253-8a77-10525176ff16.png)

**Comment by petermarks-gsa** [comment]
Per comments in https://github.com/GSA-TTS/FAC-Frontend/pull/34, we can consider this done.
