### ISSUE TITLE
Instructions Error: Type of Compliance Requirements and their definitions

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3176]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/1754

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

The static site has incorrect information for types of compliance requirements. In the list copied below, "Other" is currently listed as "O" but it should be listed as "P"
 
A: Activities allowed or unallowed
B. Allowable costs/cost principles
C. Cash management
D. Reserved
E. Eligibility
F. Equipment and real property management
G. Matching, level of effort, earmarking
H. Period of performance (or availability) of Federal funds
I. Procurement and suspension and debarment
J. Program Income
K. Reserved
L. Reporting
M. Subrecipient monitoring
N. Special tests and provisions
**P. Other**

**Comment by lauraherring** [comment]
@Carley-Jackson I'd like your input on this. I copied this list from the 2022 Census instructions and O is listed as other. If we change it to this, then our list will skip the letter O entirely and go from N to P.
