### ISSUE TITLE
FAC - Feature: use a second ClamAV instance for redundancy

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3195]
### Is your feature request related to a problem? Please describe.

On 1/11, we experienced a brief uploads outage following a cloud.gov-wide VM update (more details below). I'm still not entirely clear what the failure mechanism was, but cloud.gov support told us we could avoid this issue in the future by using multiple instances of the ClamAV app.

### Describe the solution you'd like

I'm not sure exactly how we'd do this. We configure 2 instances of the fac app [in a manifest](https://github.com/GSA-TTS/FAC/blob/main/backend/manifests/vars/vars-production.yml#L7), but I think all of the ClamAV configuration happens in terraform files.

### Describe alternatives you've considered

Possibly just configuring better alarms and managing incidents on a one-off basis?

### Additional context

More details about the uploads outage:

* We noticed while tailing app logs for a completely unrelated reason and noticed a suspicious volume of 500 errors for uploads.
* I poked around our cloud.gov event logs and noticed a "cell evacuation" message for ClamAV.
* I started tailing the ClamAV logs and noticed that it was only loading "started scanning file..." messages. It stopped logging scan results or the "finished scanning..." message two hours prior to us realizing there was an issue.
* We rebooted the ClamAV instance, which immediate resolved the issue. 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Feature+Request%22) for duplicate feature requests.

**Comment by timoballard** [comment]
Closed by https://github.com/GSA-TTS/FAC/pull/3459
