### ISSUE TITLE
Add Index to Historical Database Tables to Mitigate Queries Performance Issues

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#3206]
In an attempt to speed up the data migration process, we launched multiple data migration tasks in parallel but realized that only a few processes were actually running in parallel. 
After investigation, it turned out that the database was hitting its max CPU limit, causing a bottleneck and preventing all the processes from running as expected. 
This ticket is to add an index to the historical database tables to mitigate the database bottleneck issue.

**Comment by gsa-suk** [comment]
The following commands were used to create index for census_historical_migration tables in Preview via DBeaver:

create index dbkey_index on census_historical_migration_elecauditheader("DBKEY");
create index dbkey_year_index on census_historical_migration_elecauditheader("DBKEY") include ("AUDITYEAR");
create index dbkey_year_findings_index on census_historical_migration_elecauditfindings("DBKEY") include ("AUDITYEAR");
create index dbkey_year_audits_index on census_historical_migration_elecaudits("DBKEY") include ("AUDITYEAR");
create index dbkey_year_captext_index on census_historical_migration_eleccaptext("DBKEY") include ("AUDITYEAR");
create index dbkey_year_cpas_index on census_historical_migration_eleccpas("DBKEY") include ("AUDITYEAR");
create index dbkey_year_eins_index on census_historical_migration_eleceins("DBKEY") include ("AUDITYEAR");
create index dbkey_year_findingstext_index on census_historical_migration_elecfindingstext("DBKEY") include ("AUDITYEAR");
create index dbkey_year_notes_index on census_historical_migration_elecnotes("DBKEY") include ("AUDITYEAR");
create index dbkey_year_passthrough_index on census_historical_migration_elecpassthrough("DBKEY") include ("AUDITYEAR");
create index dbkey_year_ueis_index on census_historical_migration_elecueis("DBKEY") include ("AUDITYEAR");
