### ISSUE TITLE
Clean up inconsistent section naming

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3213]
We have some lingering inconsistencies with our naming of workbook sections across the app.

Areas to cleanup:
- `audit.urls.py` makes use of `FORM_SECTIONS` to build the `View` name patterns for workbook uploads & download: [here](https://github.com/GSA-TTS/FAC/blob/be95d5a4776bc02190b65a58aa1bbb4f5ab36362/backend/audit/urls.py#L125)
- `report_submission/views.py` makes use of `naming.py` to build context data for the workbook upload page, included the upload and download URLs. The `camel_case` naming in `naming.py` does not fully align with `FORM_SECTIONS` (specifically, `FederalAwards`, `AdditionalUEIs`, and `AdditionalEINs`

**Comment by danswick** [comment]
Would it be worth it to expand this ticket to cover field names as well? Referencing a somewhat subtle section naming bug: https://github.com/GSA-TTS/FAC-transition-site/pull/80
