### ISSUE TITLE
Add "accepted date" to audit summary page

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3214]
On the audit summary page (navigated to by clicking an "eye" eyecon. See what I did there?), we present the "submitted date," but not the "accepted date."

We must present the accepted date somewhere; I think adding it under the submitted date makes sense.

Agencies need this, as they need to know the date that their MDL process kicks off. (Arguably, the date in the search results would tell them, but lets add it to the audit summary page, too.)

**Comment by jadudm** [comment]
Note that the wording should be consistent with the audit overview page that submitters see; perhaps that should be "completed date."

**Comment by jadudm** [comment]
I think I confused myself during a webinar that this was the "Start date" vs. "Submitted date."

It was inspired by a Federal user trying to figure out where the MDL start date was. So, we may want to think about clarification. I'm going to bump it back to "Triage" for a moment, and it may end up being closed.

**Comment by danswick** [comment]
Closing in favor of https://github.com/GSA-TTS/FAC/issues/3260
