### ISSUE TITLE
January: Initial conversations to frame research questions

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3217]
We want to learn more about how resubmission of revised single audits affects Audit Resolution Officials and IG's work with data from the FAC. We're conducting this research to: 1. Identify problem areas to further investigate, and 2. Explore initial light-lift solutions to implement and help support our agency users in this space. We aim to interview 6-8 users by mid-February. 

- What are some potential questions to ask?
- Who do we want to speak with? 
- Who from the FAC team should be included on interviews?

**Comment by Leighdiddy** [comment]
I met with @Carley-Jackson to discuss questions and start pulling resources for this upcoming round of interviews. Progress has been shared with @jadudm, Notes are [here](https://docs.google.com/document/d/1C39V007jwGMzISXkAyNZvhc8FUHp4R4MILpS_ga8xGk/edit).

**Comment by jadudm** [comment]
Initial convos complete. We can close this ticket.
