### ISSUE TITLE
🅢 Verify authentication between steps 1-2 of pre-SAC flow

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#322]
Breakout task of https://github.com/GSA-TTS/FAC/issues/226 and https://github.com/GSA-TTS/FAC/issues/228

**Comment by jasnakai** [comment]
Hey, @petermarks-gsa. I believe this issue is completed. PR#26 has been approved and merged. The forms now use the login.gov sandbox authentication. Is there anything else needed for this?
