### ISSUE TITLE
Ensure Correct Display of UEI and EIN on Audit Report Search Page

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#3225]
As part of data migration, we realized some audit reports do not have a UEI associated but only an EIN. In these cases, the data migration process replaced the missing UEI with the placeholder keyword GSA_MIGRATION to allow those reports to pass validations. This ticket is to ensure that the search page result only shows GSA_MIGRATION in the 'UEI or EIN' column when both UEI and EIN are missing. That is, if UEI is missing and replaced by GSA_MIGRATION but EIN exists, then EIN should be shown instead. GSA_MIGRATION will only be shown if both UEI and EIN are missing.

![image](https://github.com/GSA-TTS/FAC/assets/26260777/b8212c32-cf5a-4b06-bd2d-bc64b1857deb)

**Comment by sambodeme** [comment]
@jadudm I believe this is duplicated now.

**Comment by jadudm** [comment]
And, I think it is fixed. 

https://github.com/GSA-TTS/FAC/pull/3363
