### ISSUE TITLE
Workbooks can be downloaded irrespective of submission status

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3235]
#3212 brought in the ability to download previously uploaded workbooks for an in-progress submission. The [view](https://github.com/GSA-TTS/FAC/blob/ae178dad8851c0aa9fe3204eb013714833b8275b/backend/audit/views/views.py#L213) for downloading workbooks does not currently look at the submission status before providing a download URL. This means that if a user can navigate to the relevant download URL, they will be able grab the original workbooks for their submission even after it is certified and submitted. This may or may not be something we want to change.

**Comment by danswick** [comment]
The impact here seems pretty limited, so I'm going to close this as unplanned for now. We can re-open later if it becomes a priority!
