### ISSUE TITLE
Increase threshold on PDF checks to 3 pages of text

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3237]
## Background

https://app.fac.gov/dissemination/summary/2022-09-GSAFAC-0000003118

That PDF is one page; it's some notes.

At one point, we were reading the entire PDF into a string, and asking if it was non-empty. Then, we made the check faster.

## Proposal

We should read the first 8 pages of the PDF, and ask if there are at least (5 * 200), or 1000 words in the document. A double-spaced document will have around 250 words per page. We can lower that threshold by 20% to 200 words/page (to account for cover pages, etc), and then increase the number of pages to 8 (so we have roughly 50% more pages to read).

## Test

1. Script the download of 500 PDFs in our repo
2. Run this algo/check against those PDFs. 
3. If none fail, push it.

Someone will complain if this is too high a threshold.

**Comment by jperson1** [comment]
A 6000 character threshold was determined in cowork to be an appropriate limit. 6000 characters is roughly comparable to 1000 words, and is a smaller overall change to our initial implementation.
