### ISSUE TITLE
RESEARCH SPIKE: De-risk Excel template approach

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#324]
Breakout issue of <story>

### Background
We need to understand whether we can support the dynamic Excel to JSON translation in both directions (read/write). If we can't we need to decide what the Excel experience will be. 

### Acceptance Criteria (We'll know we're done when...)
- [ ] We have a PDR on our definitive approach on the level of Excel data entry experience we will support as part of the MVP. 

### Tasks

- [ ] 
- [ ]

**Comment by melchoyce** [comment]
Is this covered by #328?
