### ISSUE TITLE
[ADR] Documenting changes in living data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3240]
## Areas of impact

- [ ]   Compliance
- [ ]   Content
- [ ]   CX
- [ ]   Design
- [x]   Engineering
- [ ]   Policy
- [ ]   Product
- [x]   Process
- [ ]   UX

## Context

In discussing a recent concern in the data intake regarding passthrough names and IDs ([Slack](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1705681582775559)), we became concerned that we were incorrectly collecting this data. Specifically:

1. If `is_direct` is `N`
2. Then there **must** be a `passthrough_name`

We originally interpreted guidance to imply that there **must** also be a `passthrough_identifying_number`. In PR 1817, in August of 23, we decided this was *not* the case.

https://github.com/GSA-TTS/FAC/pull/1909/files#diff-d945a3ba53f41bc54fcf627acb28b478e17ce2c9d2412a7a33be0c36cf81891cL17

In revisiting the language of 2022:

> (l) If not Direct, list Name of Pass-through Entity - If “N” was marked for direct award, enter the name of the pass-through entity as required by 2 CFR 200.510(b)(2). If a program has multiple pass-through entities, multiple award lines should be entered, with each award line entered having a unique pass- through entity name.
> (m) If not Direct, list Identifying Number Assigned by the Pass-through Entity, if assigned - If “N” was marked for direct award, enter the identifying number assigned by the pass- through entity, if assigned, as required by 2 CFR 200.510(b)(2). If a program has multiple pass-through identifying numbers, the data collection form will accept multiple identifying numbers assigned by each pass-through entity. If there is not an identifying number assigned by the pass-through entity, enter “N/A” in this field.

Census recommended that an `N/A` be used if there is no identifying number. However, we find that (in the historical data) this is often left *empty*, and an `N/A` is not enforced. 

The 2023 collection is allowing the `passthrough_identifying_number` to be blank as well.

## Decision Sketch

We are in the middle of a data migration from Census. We are tracking changes to the data through an `InspectionRecord`. 

https://github.com/GSA-TTS/FAC/blob/f7360cfb4c6894adb5d2355471c2cc449beedcf3/backend/census_historical_migration/change_record.py#L5

This tracks changes made through our data migration process.

Given that 

1. Our historical data <strike>almost</strike> certainly leaves this blank, and 
2. Some of our 2023 data leaves this blank.

we will want to patch or fix both historical and current data.

In this regard, we are going to want to have a few things in place.

1. We need a section of the fac.gov website *about the data*. We will want this anyway, because we need to document the historical migration and all of the things that we did there.
2. We will want an SOP about how/why we might update/patch/"fix" data that we have collected. 
3. We will want to log/create `InspectionRecords` for any changes we make.

That is a high-level (to-be-fleshed-out-further) realization from the work of today. Our data is not *static*. Our data is a *living thing*, and we *curate it over time*. The question is, to a large degree, how do we decide when to do that curation, and how do we document and communicate that curation.

If there is a decision here, it is that we need to develop and document our SOP, comms, and processes regarding this data. The purpose of the decision sketch is to capture the learning from today to inform next steps.

## Consequences

There are consequences, but those will be documented further as we develop a more concrete decision pathway.

**Comment by danswick** [comment]
I think this is captured in other data curation tickets. The concept of the work has changed pretty substantially since then. 

Feel free to re-open or edit if you disagree!
