### ISSUE TITLE
Update ClamAV image

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3246]
Per

https://github.com/GSA-TTS/FAC/security/code-scanning/1125

it looks like an update to our ClamAV image should resovle a libcrypto3 update issue. We want to go from `-r1` to `-r4`.

**Comment by asteel-gsa** [comment]
Part of golang:alpine-3.18 
https://hub.docker.com/layers/library/golang/alpine3.18/images/sha256-6c3594a637fd59b8646e120c30465cbdc7b2b95567a80e777539578e8bada43d?context=explore

Also in https://hub.docker.com/layers/library/golang/alpine3.19/images/sha256-0f7e0b1413ed81da9abecb9a397c3cc12d7f078fb39086399cb0e324e0b86297?context=explore

[`apk upgrade libssl3 libcrypto3`](https://github.com/alpinelinux/docker-alpine/issues/296) _should_ fix.

**Comment by asteel-gsa** [comment]
@jadudm PR available for your review

**Comment by asteel-gsa** [comment]
This has been resolved.
