### ISSUE TITLE
Unencrypted PDF not uploading

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3276]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/2023

### FAC components involved

- [X] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/u/2/folders/1QIqF4PNFNytu2rm9iiVDOqdM1rBfo1u9

### What happened?

User's PDF does not appear to be encrypted; however, it is not uploading for them (or in dev for me).

**Comment by jadudm** [comment]
![image](https://github.com/GSA-TTS/FAC/assets/38290/624daa1a-bb3b-4e39-a73c-da7a1862fcae)

I'm pretty sure that a screenshot of the PDF upload page from them would show that they're being told their PDF is encrypted. Which...

```
Encrypted:       yes (print:yes copy:no change:no addNotes:yes algorithm:AES-256)
```

it is.

**Comment by jadudm** [comment]
The PDF was actually encrypted to some degree. Closing.
