### ISSUE TITLE
Update dictionaries per API mailing list request

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3284]
## Background

From 01/25 on the Federal API mailing list:

> Thanks Mat, I was able to map all roll up fields and all the fields that you provided mappings on the differences page except the Unknown/Unavailable fields.
> 
> And the tool is ready to import GSA data to *********.
> 
> I have noticed some extra fields in GSA data below which are not present in *********. (I have asked ********* if they were to be added in *********)
> 
> General End Point:
> 
> Type_Audit_Code
> Is_Public
> Ready_For_Certification_Date
> Agencies_With_Prior_Findings
> Data_Source
> Is_AICPA_Audit_Guide_Included
> Is_Additional_UEIs
> Additional UEIs
> Additional EINs
> Is_Secondary_Auditors
> 
> Notes End Point:
> 
> Accounting_Policies 
> Is_Minimis_Rate_Used 
> Rate_Explained
> Contains_Chart_Or_Table 

```[tasklist]
### Tasks
- [ ] Update `dictionaries` branch on fac.gov
- [ ] Publish all of the API docs improvements to the static site.
```

**Comment by jadudm** [comment]
The dictionaries need a comprehensive walk as part of documentation review/update. I'm going to move this to available, and think this is an excellent ticket for a member of the content team to cut their teeth on some technical docs.

**Comment by danswick** [comment]
This is done.
