### ISSUE TITLE
PDR - Audit processing

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#329]
**Background:** We talked with Census processors and learned about their work and role in processing FAC submissions. GSA will need to determine how we handle processing as we go forward. Considerations and recommendations are[ here](https://docs.google.com/document/d/1ApHaC5_daADSJzrUnWk4P6Oe-OYmJd6570ZmBiJWCk4/edit#).

  * Option 1: "Process" audits in the new FAC, send them to "dissemination pipeline" of Census FAC
  * Option 2: "Process" audits in the old FAC, send them to "processing pipeline" of Census FAC
    * Will there actually be anyone around to "process" when we launch this? 

**Acceptance Criteria**: ADR/PDR outlining our decision here

**Comment by MelissaBraxton** [comment]
Heads up, @petermarks-gsa Some notes on this are linked to in #219.

**Comment by petermarks-gsa** [comment]
@MelissaBraxton Ah, thank you. Maybe we should combine these?
