### ISSUE TITLE
[HD]: Invalid Integer Error on Federal Awards Workbook

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3297]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/2084

### FAC components involved

- [ ] submission system (app.fac.gov)
- [X] workbooks
- [ ] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### Gdrive link

https://drive.google.com/drive/u/2/folders/10uMV5odzKu7n9p19vKTLGgFXLuamichi

### What happened?

User is receiving an error message regarding "not a valid integer" for two cells in the workbook. See supporting files for the workbook and a screenshot of the error generated in dev (with problem cells indicated).

**Comment by danswick** [comment]
This is old and I have a very old draft branch. I need to see if this was handled elsewhere. If not, I will get the PR ready for review.

**Comment by danswick** [comment]
I don't think we've seen any other instances of this, so let's close for now rather than disturb the schemas right now.

I'll close my PR as well.
