### ISSUE TITLE
Search - Rework the logs to be more concise

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#3299]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** effectively track search times
**as a** developer
**I want** the logs for searches to be concise enough to understand at a glance. 

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

**Given**  a search has been made
**when** any user submits the form on via `/dissemination/search`
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] The logs for search should be cleaned up to be more concise. Timing and total results count are useful things to keep.
```

**Comment by danswick** [comment]
I think this was covered here: https://github.com/GSA-TTS/FAC/pull/3883
