### ISSUE TITLE
Missing information in `fac-summary-report`

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3303]
From an auditor:

> I have reviewed the new fac-summary-report available and it is very nice!  I have one question - should the information input in the notes-to-sefa workbook first tab (for the description of the significant accounting policies, and the yes/no question for the 10% IDC rate and related explanation) be in the new summary report?  I can't find it, so should that information also be input on the second tab of the notes-to-sefa workbook?

It feels very likely that we are missing this from the report, because of how the report is generated.

```[tasklist]
### Tasks
- [x] Review the summary report generation code.
- [ ] Confirm whether this, and other "singleton" values are missing from the report
- [ ] Add them
```

It is likely that these should all be added on the coversheet page. No concrete recommendation as to where they should be added at this time... but, they should not be added to a sheet that is a "many-rows" output. They should be on their own as singleton values (much like they are input as singletons on the coversheet in the workbook).

**Comment by sambodeme** [comment]
The values are not missing. There are in the `note` sheet. I moved them to a separate sheet `note_coversheet`

**Comment by jadudm** [comment]
Groovy. I probably wrote the code that duplicated the values, and then promptly forgot when I wrote this ticket. Thank you.
