### ISSUE TITLE
Bug: Entries to search fields are not fully clean, drop results

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3306]
## To reproduce

Copy-paste a UEI or two from the search results. You'll get one that has a tab or group of spaces after it.

Run the search on 3-4 UEIs. One won't appear.

The spaces get sent back, so clean up the search list.

Now, all of them arrive.

## To fix

We should split/cleanup the text better.

**Comment by jperson1** [comment]
The UEI, name, and ALN fields all received better cleaning functionality with https://github.com/GSA-TTS/FAC/pull/3440. Closing this as complete.
