### ISSUE TITLE
More granular error messaging around UEI validation

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3327]
[Related slack thread](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1706295078256479)

On Jan 26 we saw an extended outage at api.sam.gov which prevented all users from performing UEI verifications / starting new submissions. The error message displayed to the user in this case did not make it clear that UEI validation was failing because of a service outage, so we received a large number of help desk issues from users who were unsure why verification was failing and how they should proceed.

We should make a distinction between service-level errors/outages at sam.gov and actual UEI verification failures, and make that clear to the users so they better understand what their next steps should be.

Tagging design/content ( @Leighdiddy @lauraherring )

**Comment by jadudm** [comment]
This moved to "In progress" a month ago, but there has been no action on it?

I'm moving this to "Blocked." As we move forward, I'd like the "In progress" column to mean "I'm working on it, and intend to have it done within a week." Nothing should be, as a single ticket in this board, bigger than that. 

If we need to reticket this to make it more actionable, we should.
