### ISSUE TITLE
Proper dissemination of Tribal FAC data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3331]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** find all audits
**as a** member of the public or a resolution official
**I want** non-suppressed Tribal data to appear in search results.

This spreadsheet, which was originally to help track transformations on migration data, has an added column to indicate which columns should be public and which suppressed.

https://docs.google.com/spreadsheets/d/1iS2B35gWE6j2EzmD2OfSEVU6y8xlQb5EL_ezNLzYzXo/edit#gid=159822551

We will be able to do this table-by-table, which will make implementation easier.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: 

**Given**  that I am a Tribal auditee
**when**  I suppress some data
...

```[tasklist]
### Before any implementation begins...
- [x] The team has walked and documented every field in the `dissemination_*` tables and confirmed, field-by-field, what **must** be made public, and what **must** be suppressed.
```

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [ ] https://github.com/GSA-TTS/FAC/issues/3450
- [ ] https://github.com/GSA-TTS/FAC/issues/3441
- [ ] https://github.com/GSA-TTS/FAC/issues/3449
- [ ] Documentation is updated regarding Tribal audit access
- [ ] Optional bonus: Visual indicator of suppressed status is present in the dashboard
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

This is the last step in correctly disseminating data and meeting our obligations as the FAC. Now that we hold all of the data from Census, this is *more* important than ever, because we are the only place the data can be accessed.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no specific *compliance* requirements, but mishandling this data will constitute a data leak incident. Therefore, the testing and controls around this are critical.

**Comment by timoballard** [comment]
I walked all of the models/fields in `dissemination` and cross checked them with the [spreadsheet in the issue description](https://docs.google.com/spreadsheets/d/1iS2B35gWE6j2EzmD2OfSEVU6y8xlQb5EL_ezNLzYzXo/edit#gid=159822551)

Confirmed that visibility (as of now) aligns with table boundaries, so we won't need to do field-by-field filtering. There are a handful of fields in the `dissemination` models that had no match in the above spreadsheet. Can @Carley-Jackson or @jadudm fill in the visibility for those fields in [this spreadsheet](https://docs.google.com/spreadsheets/d/1DXkWcu3kuAOeQh4B3YrdiiHnIIc04QdLyzJwDLyjneg/edit#gid=0) (they're highlighted yellow)

**Comment by jadudm** [comment]
It looks like `data_source` is the only question.

We populate this field. It is either `GSA_FAC` or `CENSUS`. It can/should be public.
