### ISSUE TITLE
Duplicate dissemination race condition

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3347]
Last week, a user alerted us to an issue where some disseminated records appeared to be duplicated. Specifically, some audits had multiple copies of everything except the general table. During he intake-to-dissemination step, it is possible for multiple app instances to run the same dissemination operation if the DB is too slow to respond to the initial request. While we enforce uniqueness on the general table, we do not for any of the others, allowing the app to create and save that data multiple times without error. 

@jadudm, @timoballard, and @jperson1 were able to confirm that the race condition occurs here in `audit/views.py`: https://github.com/GSA-TTS/FAC/blob/main/backend/audit/views/views.py#L719-L720. Two requests are able to transition to `submitted` because the first request is not yet persisted to the database by the time the second request arrives.

## Impact

Dissemination data consumers are getting confusing and incorrect data for affected audits. This makes it difficult to do oversight, generate useful reports, etc.

## Possible triage steps

There are a couple of paths we can consider right now. This is a rough list and will change as we work on the problem.

1. Client-side: for now, only allow a single copy of data to be returned to end users. Search results, generated spreadsheets, and API results would need to pass through this uniqueness step before they make it to a user. 
2. Client-side: display an error of some kind during submission?
3. Backend: make state transitions more atomic during intake-to-dissem.
5. Comms: add macros to HD (cc @James-Paul-Mason) 

## Possible longer-term fixes

The above options should be treated as a path to triage. Once we have triaged, we will need to fix the underlying issue AND rebuild the dissemination data. Again, this is a rough list and will change as we work on the problem.

1. Client-side: robust error messaging for users attempted to create a duplicate submission.
2. Backend: make state transitions more atomic during intake-to-dissem.
3. Database: for SAC objects with multiple `submitted` events, remove extras.
3. Database: re-disseminate audits with duplicate data.
4. Database: enforce uniqueness at the table level (not possible until the broken data is re-disseminated)

**Comment by jadudm** [comment]
Fixed and in production.
