### ISSUE TITLE
ADR/spike - Email sending

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#335]
Breakout of https://github.com/GSA-TTS/FAC/issues/319

**Background**: we have a few use cases for sending emails, including invite emails and status update notification emails. At some point, we're surely going to want to be able to send emails. 

**Acceptance Criteria**: 
* Approved ADR on how to send emails. 
* Dev spike illustrating how to send emails

**Conversations**:
* Ryan Palmer, who will be approving our ATO: "Easiest option in [cloud.gov](http://cloud.gov/) is to use the GSA enterprise email servers (if mail isn't bulk). Otherwise, you can use SES on AWS but will need to cover that in your ATO. You should be able to use the following mail relay from [cloud.gov](http://cloud.gov/)  [smtp-relay.gmail.com](http://smtp-relay.gmail.com/). Note you will be limited to sending from an @[gsa.gov](http://gsa.gov/) address. You can also reach out to the Challenge.gov teams or IDVA Teams (Garrett Folks) on slack, as they are using these relays from [cloud.gov](http://cloud.gov/)."
* Mark Headd, SYR Cloud.gov: Some good info that might be helpful in [this thread](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1631199542012400). And a knowledge base article [here](https://cloud.gov/knowledge-base/2021-09-21-sending-emails-from-clouddotgov/). Feel free to drop into [#cg-support](https://gsa.enterprise.slack.com/archives/C09CR1Q9Z) with questions or if you want to dive deeper on sending emails from apps running in [cloud.gov](http://cloud.gov/).

**Comment by JeanMarie-TTS** [comment]
@mogul , @jadudm and I discussed this topic. For the MVP, we will use GSA SMTP service.
We should do a quick spike to  send a formatted email from our django app using this service. We need to connect to their non-prod environment from our non-prod environment.

**Comment by danswick** [comment]
consolidating to https://github.com/GSA-TTS/FAC/issues/1401
