### ISSUE TITLE
Improve application performance, experience for March

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3358]
# Story

March is a significant submission deadline. Our goal, through the month of February and March, is to be ready for the heavy season at the end of the month.

What follows are ideas we might develop into tickets to tackle on short(er) order. Some might be too large to undertake. Some might want to be thrown out, or rewritten. This ticket wants to be discussed and shaped before breaking out any individual tasks. The spirit here is "we need the FAC to be performant before March 15th."

```[tasklist]
### Ideas
- [ ] Rotate everyone on the team through the helpdesk
- [ ] Update cluster names and ALN lists/program names to be current/correct
- [ ] Fix the broken workflow where auditees certify but do not submit
- [ ] Review, improve documentation for everything users encounter difficulty with.
- [ ] Load test the FAC in a performance-like condition (e.g. multiple instances in `staging`)
- [ ] Normalize our DB, application infrastructure across all environments
- [ ] Provide standard (large) data testing sets for developers to use locally
- [ ] Automate data loading into dev, staging for performance testing
- [ ] Make observability part of all critical paths, verify common user stories/problems can be seen in NR
```

```[tasklist]
### Possibly related tickets
- [ ] https://github.com/GSA-TTS/FAC/issues/3014
- [ ] #2814
- [ ] #2813
- [ ] #2780
- [ ] #2756
- [ ] #2229
- [ ] #2505
- [ ] https://github.com/GSA-TTS/FAC/issues/3195
- [ ] https://github.com/GSA-TTS/FAC/issues/3455
- [ ] https://github.com/GSA-TTS/FAC/issues/3456
```

**Comment by danswick** [comment]
This epic has become entangled with https://github.com/GSA-TTS/FAC/issues/3388.

**Comment by danswick** [comment]
March has come and gone. The straggling tickets here are still on the primary board, but we don't need to track this epic anymore.
