### ISSUE TITLE
Document Tribal API, publish API docs

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3369]
# Story

The Tribal API is now complete. It is not documented. This means users do not know how to use it.

```[tasklist]
### Tasks
- [ ] Add an article to the API documentation about the Tribal API to the branch `jadudm/dictionaries`
- [ ] Merge the branch to the public site.
```  

There are several months worth of improvements to the API documentation that have never been published. They have been shared, in a non-published branch, with API users for months. Whether a thorough review takes place or not, the branch must be published with this documentation.

**Comment by jadudm** [comment]
@purvinptl , is this done? Is it drafted in Gdocs for review, perhaps?

**Comment by lauraherring** [comment]
The page is built and ready to go in the same static site branch as the updated nav changes. It should go live today or tomorrow.
