### ISSUE TITLE
Benchmark ClamAV

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3432]
We're expecting a significant load increase in March. We currently see on the order of 200 file uploads per hour during the busiest part of the day, and it's reasonable to expect that to increase to something like 1000 uploads per hour next month.

At this time, we do not have a good sense of how well a single ClamAV instance will cope with that increased load. We should do some local benchmarking of ClamAV by pushing many concurrent scan requests to it and gather some throughput & latency metrics so that we can make a more informed decision about whether or not to stand up additional instances in production.

When benchmarking ClamAV we should:
- use representative files that lean toward a worst case scenario (e.g. large Excel files)
- understand whether or not ClamAV does any internal caching that might skew the performance metrics (if you tell ClamAV to scan the exact same file multiple times in rapid succession, does it redo the scan or briefly cache the results of the previous scan?)

**Comment by phildominguez-gsa** [comment]
@timoballard I've pushed a new command to `pd/3432-clamav-bench` to help with benchmarking (stealing a bunch from the scan_bucket command).

To run it:
`docker compose run --rm web python manage.py collect_scan_metrics --path 'audit/fixtures/federal-awards-workbook-181744-7mb.xlsx' --num_to_scan 5`

Findings so far:
- With the 15 second timeout we use, I can only get xlsx files of about 7mb through, so I increased it for my command. Possibly this needs to be increased in `validators.py` to handle 20mb+ files?
- I do think some caching is going on. The first run for a file will take some number of seconds, but subsequent requests for the same file only take about tenth of a second.
  - <img width="487" alt="image" src="https://github.com/GSA-TTS/FAC/assets/142051477/8304ec74-03c3-4adc-b686-19ff6fd4e75e">


Files of various sizes I've been testing with:
[federal-awards-workbook-181744-5mb.xlsx](https://github.com/GSA-TTS/FAC/files/14350694/federal-awards-workbook-181744-5mb.xlsx)
[federal-awards-workbook-181744-7mb.xlsx](https://github.com/GSA-TTS/FAC/files/14350696/federal-awards-workbook-181744-7mb.xlsx)
[federal-awards-workbook-181744-10mb.xlsx](https://github.com/GSA-TTS/FAC/files/14350697/federal-awards-workbook-181744-10mb.xlsx)
[federal-awards-workbook-181744-16mb.xlsx](https://github.com/GSA-TTS/FAC/files/14350698/federal-awards-workbook-181744-16mb.xlsx)
[federal-awards-workbook-181744-23mb.xlsx](https://github.com/GSA-TTS/FAC/files/14350699/federal-awards-workbook-181744-23mb.xlsx)

**Comment by timoballard** [comment]
nice @phildominguez-gsa! Good catch on the caching, that's good to know

Is there a way to use this command to send multiple scanning requests to clam AV simultaneously (either internally in the command or by invoking the command several times all at once)? I don't think we have a good sense of whether or how well ClamAV is able to parallelize scans

Ultimately, we'd like to surface some high level benchmarks that will help us decide whether the single ClamAV instance we have is likely to be able to handle a significantly increased load, and I think a big part of that is understanding how much the response time degrades as the number of concurrent scanning requests increases. Maybe as a next step we could try to generate some data around questions like "what's  the average & max scan times if I send [2, 3, 4, 5, n...] requests all at once?

**Comment by phildominguez-gsa** [comment]
@timoballard I've created a second command, `generate_xlsx_files`, to create the files we can use for testing.

To run it: `docker compose run --rm web python manage.py generate_xlsx_files --base_xlsx 'output/181744-22/federal-awards-workbook-181744.xlsx' --num_files 100`

I've modified the `collect_scan_metrics` command to perform parallel scan requests. There's a new `num_workers` flag, so it can now be run like this:

`docker compose run --rm web python manage.py collect_scan_metrics --path 'audit/fixtures/federal-awards-workbook-181744-7mb.xlsx' --num_to_scan 100 --num_workers 5`

Generating and scanning tons of large files will take a while, so I'm starting small. For now I've been using 100 files of ~1.5mb each, with 2-5 workers. Here are the results of those runs:
```
INFO Num files: 100
INFO Num workers: 1
INFO Total time: 199.2062036395073 seconds
INFO Max time: 2.5281508730258793 seconds
INFO Avg time: 1.992062036395073 seconds

INFO Num files: 100
INFO Num workers: 2
INFO Total time: 245.6247690229211 seconds
INFO Max time: 3.2871659391094 seconds
INFO Avg time: 2.456247690229211 seconds

INFO Num files: 100
INFO Num workers: 3
INFO Total time: 291.0432849936187 seconds
INFO Max time: 3.9531039888970554 seconds
INFO Avg time: 2.9104328499361873 seconds

INFO Num files: 100
INFO Num workers: 4
INFO Total time: 349.8778303170111 seconds
INFO Max time: 4.355165403103456 seconds
INFO Avg time: 3.498778303170111 seconds

INFO Num files: 100
INFO Num workers: 5
INFO Total time: 410.09031212469563 seconds
INFO Max time: 5.129633011994883 seconds
INFO Avg time: 4.100903121246956 seconds
```

If I'm on the right track I'll move on to running bigger tests 😃

**Comment by timoballard** [comment]
this is great @phildominguez-gsa, exactly the type of info we're looking for

at a glance, looks like it can definitely deal with concurrent requests, since the processing time increases as you add workers, but it doesn't increase linearly, so that's a good sign

so, yes, I think this is definitely the right track and that it would make sense to really hammer it and try to see if there's a point at which the concurrency breaks down and the processing time per file spikes up

**Comment by phildominguez-gsa** [comment]
@timoballard @danswick @asteel-gsa @jadudm Summarizing my ClamAV benchmark findings here!

I ended up making [two scripts](https://github.com/GSA-TTS/FAC/pull/3453) to help with this task. The primary script that performs the benchmarking is `tools/collect_scan_metrics.py`. The number of workers you want to be making requests to ClamAV at one time can be configured via argument, to help simulate higher load.

One hurdle we ran into is that ClamAV uses file caching, which means we can't just send the same file to it over and over. This can theoretically be disabled, but Tim/Alex/I were stumped after a while and figured it would be easier to just write a script that generates unique files, hence `tools/generate_xlsx_files.py`. We determined the average file size was a bit under 2mb, and that XLSX files took a lot longer than PDFs for whatever reason, so that's what we stuck with. ClamAV still has to be restarted after each benchmark to clear the cache, though.

Here are the results, all using 1000 files, and using 1, 2, 5, 10, and 20 workers making ClamAV requests:
```
INFO Num files: 1000
INFO Num workers: 1
INFO Real time: 44.048857286999315 minutes
INFO Total time: 43.54090271275491 minutes
INFO Max time: 3.29536947212182 seconds
INFO Avg time: 2.612454162765294 seconds

INFO Num files: 1000
INFO Num workers: 2
INFO Real time: 27.18959363916656 minutes
INFO Total time: 53.78730716404195 minutes
INFO Max time: 4.295284790918231 seconds
INFO Avg time: 3.227238429842517 seconds

INFO Num files: 1000
INFO Num workers: 5
INFO Real time: 18.90642105715039 minutes
INFO Total time: 93.58303841039306 minutes
INFO Max time: 9.238254899159074 seconds
INFO Avg time: 5.614982304623584 seconds

INFO Num files: 1000
INFO Num workers: 10
INFO Real time: 23.547397279017606 minutes
INFO Total time: 234.363432602953 minutes
INFO Max time: 236.71336735785007 seconds
INFO Avg time: 14.06180595617718 seconds

INFO Num files: 1000
INFO Num workers: 20
INFO Real time: 18.584111564583147 minutes
INFO Total time: 368.6542559894655 minutes
INFO Max time: 28.03001002781093 seconds
INFO Avg time: 22.119255359367934 seconds
```
Note: "Total" time is a summation of the individual workers' time waiting for their responses, not to be confused with "real" time, which is basically how long the benchmark took overall.

While the benchmark finishes more quickly as we add more workers, the average response time from ClamAV grows to over 20 seconds when 20 workers are used. Let me know if there are any questions, or other test scenarios you'd like me to try out!
