### ISSUE TITLE
PDR/ADR - File Upload storage

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#344]
We need to come up with a solution to store Uploaded PDFs.

**Comment by timoballard** [comment]
@petermarks-gsa @tadhg-ohiggins 

As a conversation starter: the [Civil Rights Portal](https://github.com/usdoj-crt/crt-portal) for USDOJ has the same backend stack that we do (Django backend on Cloud.gov). We built a file upload/storage solution there which includes validations around file size, supported file types, and virus scanning. Files are stored in S3 (via [cloud.gov's managed services](https://cloud.gov/docs/services/s3/)).

Seems like at a minimum, we could use this as a reference model for our solution

**Comment by jadudm** [comment]
Part of the answer to this might be informed by some conversation with Federal users. I don't *think* it will radically shift storage choices, but knowing how people want/need to access the data may help inform the design. In particular, I'm thinking about questions around persistent links, bulk access, and so on that have surfaced in piecemeal ways over the past few months... I don't know if we have any dedicated UX conversations around this?
