### ISSUE TITLE
Web search should properly disseminate Tribal data

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3441]
Epic: #3331 

### Background
Because [only some](https://docs.google.com/document/d/1RNMOLAcgXk9NGX_05GMElqVR0-2c5HS4DPMKALlUB6I/edit) of the SF-SAC fields should be hidden from public view, we should be displaying tribal/private submissions in the web search results, even when the user is not authenticated or otherwise lacking permission to access Tribal data.

All of the tabular data in the search results is public, so nothing needs to be omitted there.

The summary view for a submission ([example](https://app.fac.gov/dissemination/summary/2023-09-GSAFAC-0000024841)) does contain protected data which will need to be omitted when accessed by unpermissioned users.

The PDF report is also restricted, so the download link should only be available for permissioned users.

### We're done when
- [ ] Tribal submissions appear in search results for all users
- [ ] PDF downloads work for users with the `read-tribal` permission
- [ ] PDF downloads do not work for users without the `read-tribal` permission
- [ ] Summary workbook downloads work, and are unabridged, for users with the `read-tribal` permission, and the workbook includes a disclaimer on the cover page
- [ ] Summary workbook downloads work, and omit [all protected fields](https://docs.google.com/spreadsheets/d/1DXkWcu3kuAOeQh4B3YrdiiHnIIc04QdLyzJwDLyjneg/edit#gid=0), for users without the `read-tribal` permission
- [ ] We have tests verifying all of the above

### Design considerations (@Leighdiddy):
- ~~How should we omit the PDF download link in cases where the user does not have tribal access permissions? Should we omit the link altogether, keep it there but present an access forbidden error if clicked, etc~~
  - Per @Leighdiddy's [comment](https://github.com/GSA-TTS/FAC/issues/3441#issuecomment-1965380828), we'll omit the link from the search results table

### Content considerations (@lauraherring):
- How should we word the disclaimer that we'll insert into the cover sheet of the unabridged summary workbook for permissioned users?

**Comment by Leighdiddy** [comment]
@timoballard I think it would be best to fully omit the PDF download button from the summary view for users that don't have permission to access it, because showing it but then throwing an error message could confuse users. I could also see this (showing it but using an error message) resulting in more helpdesk tickets vs. not showing it. I'd like to make the difference as clear as possible for showing restricted data vs. regular public view data, which is tricky with using the same page layout so anything we can do to help visually differentiate between the two is a win.

**Comment by Leighdiddy** [comment]
@Carley-Jackson did the census include any kind of disclaimer/legalese for the user on restricted tribal audits when they were downloaded? Or do you know of anything we are legally required to state or include with downloaded restricted tribal audits?

**Comment by lauraherring** [comment]
@timoballard I've written disclaimers for both permissioned and public users, just to cover all our bases. 

Public user:
> This document is for a Tribal entity that has chosen to keep their data private. It doesn't include their audit findings text, corrective action plan, or notes to SEFA.

Permissioned user:
> This document is for a Tribal entity that has chosen to keep their data private. Because your account has access to these submissions, this document includes their audit findings text, corrective action plan, and notes to SEFA. **Don't share this data outside your agency.**

**Comment by jadudm** [comment]
This is a good example of a space where we should/must always reference back to the law and UG, even if we are in a plain language mode.

The front of the Tribal API attestation has some citations that could serve. 

https://docs.google.com/document/d/17v9sIykHLDV51KOG5q_vQYIjkkKmTorngBmt_fS2UBY/edit#heading=h.7cthuokdptqx

"This document is for a Tribal entity that has chosen to suppress portions of their audit per 2 CFR 200.512(b)(2)."

with a relevant hyperlink wherever/whenever possible. 

Much like we as "how can we test this?," or "how can we make this observable in NR?," we should be asking ourselves when working on the app/content/site "should this cite Uniform Guidance?"

**Comment by lauraherring** [comment]
Hey @phildominguez-gsa, just to make sure I'm understanding correctly: the same message will be used on the coversheet of the downloaded summary report spreadsheet regardless of whether it's the summary for a single audit submission or the combined summary download for multiple submissions included in a search? For example, all the reports submitted for HHS on a particular date vs just the summary report for Acme Auditee?

**Comment by lauraherring** [comment]
Thanks for the clarification, @phildominguez-gsa. Let's go with this language instead. (@jadudm, also good call on including the UG citation, I've added that as well)

Public user:

> This document includes one or more Tribal entities that have chosen to keep their data private per 2 CFR 200.512(b)(2). It doesn't include their audit findings text, corrective action plan, or notes to SEFA.

Permissioned user:

> This document includes one or more Tribal entities that have chosen to keep their data private per 2 CFR 200.512(b)(2). Because your account has access to these submissions, this document includes their audit findings text, corrective action plan, and notes to SEFA. Don't share this data outside your agency.

**Comment by jadudm** [comment]
Could we please update "Don't share this data outside your agency" to "This document should only be stored on Government-issued equipment or on systems rated FISMA Moderate or higher."
