### ISSUE TITLE
API should properly disseminate Tribal data

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3449]
Epic: #3331 

### Background
Because [only some](https://docs.google.com/document/d/1RNMOLAcgXk9NGX_05GMElqVR0-2c5HS4DPMKALlUB6I/edit) of the SF-SAC fields should be hidden from public view, we should be returning tribal/private submissions from the API endpoints, even when the API key is lacking Tribal access permissions.

### We're done when
- [x] `/additional_eins` includes Tribal data for all users
- [x] `/additional_ueis` includes Tribal data for all users
- [x] `/findings` includes Tribal data for all users
- [x] `/federal_awards` includes Tribal data for all users
- [x] `/passthrough` includes Tribal data for all users
- [x] `/general` includes Tribal data for all users
- [x] `/secondary_auditors` includes Tribal data for all users
- [x] `/findings_text` does **_NOT_** include Tribal data for users lacking Tribal access permissions
- [x] `/findings_text` includes Tribal data for users holding Tribal access permissions
- [x] `/corrective_action_plans` does **_NOT_** include Tribal data for users lacking Tribal access permissions
- [x] `/corrective_action_plans` includes Tribal data for users holding Tribal access permissions
- [x] `/notes_to_sefa` does **_NOT_** include Tribal data for users lacking Tribal access permissions
- [x] `/notes_to_sefa` includes Tribal data for users holding Tribal access permissions
- [x] We have full test coverage on the above scenarios

### Testing
At this time, we do not have a general purpose testing framework for our PostgREST API. For the purposes of this ticket, we should extend our Cypress full-submission tests to cover the above scenarios. [These tests currently only check the `/general` endpoint, but we can extend this to also check the other endpoints](https://github.com/GSA-TTS/FAC/blob/641b879c8b503fec303210f653a8d576b49188cf/backend/cypress/support/dissemination-table.js#L67-L135) and assert the appropriate response for each test permutation (public/private, permissioned/unpermissioned).

**Comment by danswick** [comment]
Sounds like this is close but will wait until after the submission deadline.

**Comment by timoballard** [comment]
completed by https://github.com/GSA-TTS/FAC/pull/3508, but holding off on closing this until deploys are unblocked
