### ISSUE TITLE
Revisit statuses in light of user research developments

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#345]
### Background

The current statuses as listed in https://github.com/GSA-TTS/FAC/blob/main/docs/product/decisions/0005-P-submission-statuses.md don't cover everything we need, including:

*   Workflow doesn't distinguish *who* has certified.
*   Break out `In progress`, `Certifiable` `Partly certified` and `Certified` into statuses that show which “tasks” have been completed.
    *   Enter and finalize SF-SAC.
    *   Upload and finalize audit report.
        *   Note that we don't have a concept of `finalize` at the moment.
    *   Auditor certification.
    *   Auditee certification.
    *   Submit to FAC.

In addition we need to:

*   Map the relationship between the statuses and the states of the above tasks.
*   Map out the state machine that governs status changes.

This will need refinement into smaller stories.

Based on 2022-07-12 discussion between @tadhg-ohigggins and @MelissaBraxton.

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by melchoyce** [comment]
@tadhg-ohiggins What kind of priority is this? Should it remain in the backlog?

**Comment by tadhg-ohiggins** [comment]
Following some further discussion, I need to write a new PDR to update https://github.com/GSA-TTS/FAC/blob/main/docs/product/decisions/0005-P-submission-statuses.md to reflect that discussion.

**Comment by melchoyce** [comment]
@tadhg-ohiggins Milestoned this but please move if I'm wrong!

**Comment by jadudm** [comment]
We've picked this up. Closing.
