### ISSUE TITLE
Update to the instructions on the static site

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3460]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/2431

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

User discovered the following issue with static site instructions for the Federal awards workbook: 

The instructions for “Column N: Direct Award” state to select “Y” if the award came directly from a Federal awarding agency. Continuing to “Column O”, the instructions state “If column N is ”Y". […] You must enter the name of your pass-through entity.". If I selected “Y” in “Column N” indicated that the award came directly from a federal awarding agency, why am I required to enter the name of a pass-through entity? Column O appears backwards.

**Comment by James-Paul-Mason** [comment]
@lauraherring Looks like another ticket just came in regarding this same issue. They provided some thoughtful/helpful commentary: https://fac-gov.zendesk.com/agent/tickets/2442

**Comment by lauraherring** [comment]
This has been fixed by [PR #89](https://github.com/GSA-TTS/FAC-transition-site/pull/89).
