### ISSUE TITLE
Validate federal award reference on upload

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3465]
Related ticket: https://fac-gov.zendesk.com/agent/tickets/2465

While troubleshooting an issue with @James-Paul-Mason, we discovered that it's possible to upload a workbook with invalid award references and pass validation with what is effectively an empty list of awards. To replicate the issue, you need to unlock the workbook template, delete the formulas in the first column, and substitute your own award reference values. While unlikely, this has happened and implies to the user that they've uploaded a perfectly valid workbook. In these cases, the audit summary page does not update to display a ✅ next to the awards section and the audit would presumably fail cross-validation.

**Comment by sambodeme** [comment]
I investigated this issue and was unable to replicate. It is more likely that the issue was resolved by one of the mutiple PRs around validation improvement. Closing this ticket.
