### ISSUE TITLE
Typo Static Site: SF-SAC Section 3: Federal awards audit findings

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#3469]
### Zendesk link

https://fac-gov.zendesk.com/agent/tickets/2470

### FAC components involved

- [ ] submission system (app.fac.gov)
- [ ] workbooks
- [X] static site (fac.gov)
- [ ] The helpdesk (zendesk)
- [ ] API (api.fac.gov)
- [ ] other

### What browser did the user report as using?

None

### What happened?

@Lau User noticed a typo (F-SAC vs. SF-SAC). Please see attached.
<img width="1007" alt="F-SAC typo" src="https://github.com/GSA-TTS/FAC/assets/141076251/e197a44e-ed0f-4da8-b338-b5c8357cb7ed">

**Comment by lauraherring** [comment]
This has been resolved by the merge of [PR #89](https://github.com/GSA-TTS/FAC-transition-site/pull/89)
