### ISSUE TITLE
Add FMCSA as valid cluster name

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3490]
### Background
[A couple of our users](https://fac-gov.zendesk.com/agent/tickets/2562) have pointed out that `Federal Motor Carrier Safety Assistance (FMCSA)` is a [valid cluster name](https://www.whitehouse.gov/wp-content/uploads/2023/05/2023-Compliance-Supplement-%E2%80%93-2-CFR-Part-200-Appendix-XI.pdf) and that our Federal Awards workbook validations should reflect that.

### We're done when
- [ ] We've added `Federal Motor Carrier Safety Assistance (FMCSA)` as a valid cluster name in our [workbook validations](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/base/ClusterNames.json)
- [ ] We've notified @James-Paul-Mason that this work is completed so that they can followup with our blocked users

**Comment by jperson1** [comment]
This awaits bugfix https://github.com/GSA-TTS/FAC/pull/3513. After which the static site workbooks can be updated and this can be considered done.
