### ISSUE TITLE
Fix Fiscal Period Start

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#3506]
### Description:
The function [`xform_auditee_fiscal_period_start`](https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/sac_general_lib/general_information.py#L232) aims to calculate the start date of an auditee's fiscal period based on the provided end date within the `general_information` dictionary. However, the current implementation assumes a fixed 365-day fiscal year, which does not account for leap years. This can lead to incorrect fiscal period start dates, especially around leap years.

#### Problematic Code:
```python
fiscal_start_date = xform_census_date_to_datetime(
    general_information.get("auditee_fiscal_period_end")
) - timedelta(days=365)
```

#### Suggested Fix:
Modify the function to check if the year of the fiscal period end date is a leap year and adjust the calculation accordingly. Here's a proposed adjustment:

```python
# Determine if the fiscal_end_date's year is a leap year
if isleap(fiscal_end_date.year):
    days_to_subtract = 366
else:
    days_to_subtract = 365

# Adjusted calculation for the fiscal start date
fiscal_start_date = fiscal_end_date - timedelta(days=days_to_subtract) + timedelta(days=1)
```

**Comment by danswick** [comment]
We'll tackle this as part of the next batch of curation work.
