### ISSUE TITLE
Investigate deploy timeouts

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3507]
## Background

Starting yesterday, production deploys starting failing with a timeout message ([example](https://github.com/GSA-TTS/FAC/actions/runs/8251902649/job/22575575803#step:13:359)). We tried [increasing the CF app timeout](https://github.com/GSA-TTS/FAC/pull/3502), but were already hitting the hardcoded maximum for that value. 

Today, @timoballard and @asteel-gsa, following a theory about our organization's app memory quota, attempted to deploy again, this time reducing the number of instances. The deploy failed in the same way, but @asteel-gsa was able to scale the app manually via the CF CLI. At this point, we started a cloud.gov support thread to get some guidance from the CG team.

While troubleshooting with CG support, it looked like our woes were specifically with instance 0 of the application. Further, @asteel-gsa noticed a number of error messages indicating issues with, apparently, gunicorn worker timeouts:

> 2024-03-12T13:58:34.47-0400 [APP/PROC/WEB/2] ERR [2024-03-12 17:58:34 +0000] [7] [CRITICAL] WORKER TIMEOUT (pid:245)

CG support noted that these logs have been present for many weeks, but have only recently started spiking. 

## Theories

While doing some Googling around the issues we were seeing, a few theories emerged that will need further investigation/to be ruled out:

1. About a month ago, we [set the gunicorn worker timeout to 120s](https://github.com/GSA-TTS/FAC/pull/3426). Could a worker be blocking the instance from restarting until its pending request is resolved? If so, this timeout could be consuming 120 seconds out of our 180 second timeout period during deploy.
  a. To rule this out, we could try _lowering_ the timeout and observing the deploy process.
  b. We could also evaluate some other gunicorn strategies (see below).
2. CF health checks are doing _something unexpected_ related to timeouts or possibly sending SIGKILLs to gunicorn workers (I'm not as clear on this theory). The default [`health-check-timeout`](https://docs.cloudfoundry.org/devguide/deploy-apps/healthchecks.html#health_check_timeout) is _shorter_ than the timeout we've configured for gunicorn. There is at least one [SO thread](https://stackoverflow.com/questions/43104913/why-are-my-gunicorn-python-flask-workers-exiting-from-signal-term/73993486#73993486) describing a situation where a Kubernetes health check would sometimes get stuck in a queue behind a long-running request and, if it had to wait too long, would interpret the non-response as an unresponsive worker, sending it a SIGKILL signal.
  a. We could rule this out by tinkering with the CF health check timeout value, though there isn't a great way to guarantee we could get the app into a state that replicates the current issue. 
3. Tying all of the above together: while we've increased the number of gunicorn workers configured in the app, we're still using [sync gunicorn workers](https://docs.gunicorn.org/en/stable/design.html#sync-workers). This is interesting for two reasons: a) sync workers don't support persistent connections and b) sync workers waiting on long blocking calls could result in more timeouts and could possibly block the CF health check requests, causing the issue theorized in item 2 above. 
  a. We could rule this out by configuring gunicorn to use async, threaded workers and attempting another deploy. This probably requires the most testing before it's ready to deploy.

**Comment by asteel-gsa** [comment]
[Slack Message for script](https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1710341734605689?thread_ts=1710278180.834459&cid=C03QCP4FSN8)

Test #1 - Run this while an active deploy occurs.
Results:
130 counts of `[CRITICAL] WORKER TIMEOUT`
Mutiple instance 0 terminated processes
Multiple reboots of instance 0 New Relic agent
Multiple instances of `[ERROR] Worker (pid:273) was sent SIGKILL! Perhaps out of memory?`
*Instance 0 was successfully able to boot, though it did appear to follow the behavior of production*

**Comment by asteel-gsa** [comment]
We believe this to be relatively resolved. Closing.
