### ISSUE TITLE
Load Prod Data into Preview

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3524]
Load Prod data into Preview.

1.  Alex downloaded Prod DB backup into Preview.
2.  cf login -a [api.fr.cloud.gov](http://api.fr.cloud.gov/) --sso
Select Preview

cf connect-to-service -no-client gsa-fac fac-db
Use the credentials to connect to Preview DB via DBeaver.
Truncate dissemination tables.

pg_restore -d $DATABASE_URL --table=dissemination_general production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_federalaward production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_migrationinspectionrecord production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_additionalein production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_additionaluei production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_captext production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_finding production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_findingtext production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_note production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore -d $DATABASE_URL --table=dissemination_passthrough production-db-backup-2024-03-15-1820.psql.bin --data-only
pg_restore: error: COPY failed for table "dissemination_passthrough": ERROR:  could not extend file "base/16399/11178612": No space left on device
HINT:  Check free disk space.
CONTEXT:  COPY dissemination_passthrough, line 292159
pg_restore: warning: errors ignored on restore: 1

**Comment by gsa-suk** [comment]
Disk space needs to be increased to be able to load the two remaining tables - passthrough and secondaryauditor.

**Comment by asteel-gsa** [comment]
@gsa-suk 
[Optional Paramaters](https://cloud.gov/docs/services/relational-database/#setting-optional-parameters-1)
`cf update-service fac-db -c '{"storage": 50}'`

**Comment by gsa-suk** [comment]
- Separated public data from the prod backup and stored in GDrive. https://github.com/GSA-TTS/FAC/issues/3528

- Truncated the following tables in Preview:

dissemination_additionalein
dissemination_additionaluei
dissemination_captext
dissemination_federalaward
dissemination_finding
dissemination_findingtext
dissemination_general
dissemination_migrationinspectionrecord
dissemination_note
dissemination_passthrough
dissemination_secondaryauditor

- Loaded the above tables as follows:

```

- In Terminal 1:

cf login -a [api.fr.cloud.gov](http://api.fr.cloud.gov/) --sso
Select Preview
cf ssh gsa-fac
export PATH=/home/vcap/deps/0/apt/usr/lib/postgresql/15/bin:$PATH
export PATH=/home/vcap/app/bin:$PATH

export db_name=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.name')
export username=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.username')
export host=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.host')
export port=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.port')
export password=$(echo $VCAP_SERVICES | jq -r '.["aws-rds"][] | select(.name=="fac-db") | .credentials.password')
export PGPASSWORD=$password
echo $PGPASSWORD

- For each file in the public dataset, 
In Terminal 2 
cat ./file.sql | cf ssh gsa-fac -c "cat > ./file.sql

In Terminal 1
psql  -h $host -p $port -U $username -d $db_name   -f file.sql
rm file.sql
```
