### ISSUE TITLE
Reset storages and DBs in lower environments

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3525]
Now that the data migration work is largely complete, we need to reset our non-production environments' databases and S3 storages. The lower environments have all drifted over time, causing some unexpected test failures and undesirable behavior. We don't need to retain any of this test data, so it will be much more straightforward to reset the environments and load fresh data in place.

There are three main phases here: clear DBs/S3s to remove test data, generate a small set of _fake_ non-public data, then load the _real, public_ data and the _fake, non-public_ data into the reset environments. @gsa-suk has already begun some of this work (see https://github.com/GSA-TTS/FAC/issues/3524, for example), but we'll still need to do a full reset on all non-prod environments and ensure we load data into all of them afterward.

**Comment by asteel-gsa** [comment]
@danswick 
Storage increase PR: #3527

**Comment by gsa-suk** [comment]
If the public Prod data is stored in S3 and the loading process outlined in https://github.com/GSA-TTS/FAC/issues/3524 is automated, all Devs can use load data into any of the lower environments.

**Comment by gsa-suk** [comment]
Preview, Staging and Dev are now loaded with public Prod data.
https://github.com/GSA-TTS/FAC/issues/3524
https://github.com/GSA-TTS/FAC/issues/3544
https://github.com/GSA-TTS/FAC/issues/3545
https://github.com/GSA-TTS/FAC/issues/3546
