### ISSUE TITLE
Data related helpdesk support

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3539]
3/18/24 - Check award count for UEI given by Dan.
3/19/24, 3/20/24 - Check award counts for some of the failed migrations with criteria from Laura (fiscal year end = 6/30/2022, audit_year = 2022).
3/27/24, 3/28/24 - Details of audits that failed migrations.  
https://drive.google.com/drive/folders/1iPyAnXnQyo6Zaxx42kyOddFX93_9j7p_?usp=drive_link

**Comment by danswick** [comment]
@gsa-suk can you add a little more detail here? What will be the outcome of this work?

**Comment by gsa-suk** [comment]
For the first 2 items, the findings were shared in the slack channel.
For the last item, the results are stored in GDrive.
