### ISSUE TITLE
Public API for accessing general SF-SAC Data

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#355]
## Background

Eventually, we will have a public API capable to disseminate information to the general public and to agencies. Per our [migration plan](https://github.com/GSA-TTS/FAC/blob/main/docs/product/decisions/0004-P-migration-plan.md), our near term goal is to provide a public API capable disseminating data to the Census FAC. Given that there are over 100 fields to transfer, the goal is to implement the API section by section as we build out the intake forms as a means of getting faster feedback and de-risking the project. The first section we're taking on is the general information section. While we will not be taking time to "shape" the data in any way for Census' needs, we will take stock of the fields we're exposing and start a conversation with them about how the data is looking at a high level. 

## Technical overview

This approach will not break the SF-SAC into sections, but will move forward with a monolithic data model since that's what we currently have. Future iterations may make it possible to access specific sections. For now, the API endpoint for accessing general SF-SAC data will be the same endpoint for accessing all SF-SAC data.

This endpoint has an inherent “filter” in that it only deals with `SingleAuditChecklist` instances with a `status` of `submitted`.

This endpoint will be unauthenticated; all `submitted` audits are assumed to be public.

Given this, the initial path for this will be `/public/api/sac/`. (If there's some technical reason why this needs to be elsewhere, it can go elsewhere; this specific path is not a requirement, just a suggestion.)

This initial version will have no sorting/paginating/filtering. A `GET` request to `/public/api/sac/` will return all `SingleAuditChecklist` instances in the system.

We will create an endpoint along the lines of `/public/api/sac/<report_id>/` for information about a specific SAC as part of this ticket.

## Acceptance criteria

- [x]   `GET` endpoint, `/public/api/sac/<report_id>/`, that returns the `SingleAuditChecklist` with the corresponding `report_id` (assuming its `status` is `submitted`).
- [x]   `GET` endpoint, `/public/api/sac`, that returns all `SingleAuditChecklist` instances with statuses of `submitted`.
- [ ]   ~~Updated the "migration plan" column in our [rosetta stone document](https://docs.google.com/spreadsheets/d/1e-NQPeXk9pcQhA9PEbywkfoJa1bcTunKsVsBjqFYVK4/edit#gid=2083425063) to start a conversation with census about whether they need remaining data~~

## Not in scope
* Filters to query API data - Presumably this include the filter criteria on the front end of the current Census FAC, but potentially more filters will be needed. 
* https://github.com/GSA-TTS/FAC/issues/157
*   Support for the following filtering / sorting options:
    *   Some way to sort/filter by "last modified" date.
    *   Pagination.
*   Support for querying specific SF-SAC sections, such as `/public/api/sac/<report_id>/<section>`.
*   A read-only API; the uses for SACs in progress and SACs with a status of `submitted` are very different. This should be its own issue or set of issues.

    Some filters the read-only API might support:

    *   Year (fiscal year covered by audit. I think.)
    *   Reviewing agency. (Note that right now I don't know how we associate a given SAC with a reviewing agency…)
    *   Submitting auditee? (By UEI, presumably…)
    *   By organization type?
    *   By presence/absence of findings in the audit?

    We need user research to determine other filters.

    What about returning things other than lists of SACs? What about returning individual data points from SACs? What about “how many SACs from a given year for this reviewing agency had findings?”

    We also need user research in order to know what similar queries might be expected/necessary.

**Comment by tadhg-ohiggins** [comment]
Are the API operations for in-progress SAC submissions and the API operations for `submitted` SACs as distinct as they appear to me right now? If so, we should probably consider them as two separate applications.

**Comment by tadhg-ohiggins** [comment]
## `submitted` only, read-only API thoughts

Possible filters here:

1.  Year (fiscal year covered by audit. I think.)
1.  Reviewing agency. (Note that right now I don't know how we associate a given SAC with a reviewing agency…)
1.  Submitting auditee? (By UEI, presumably…)
1.  By organization type?
1.  By presence/absence of findings in the audit?

We need user research to determine other filters.

What about returning things other than lists of SACs? What about returning individual data points from SACs? What about “how many SACs from a given year for this reviewing agency had findings?”

We also need user research in order to know what similar queries might be expected/necessary.

**Comment by geekygirlsarah** [comment]
> ## `submitted` only, read-only API thoughts
> Possible filters here:
> 
> 1. Year (fiscal year covered by audit. I think.)
> 2. Reviewing agency. (Note that right now I don't know how we associate a given SAC with a reviewing agency…)
> 3. Submitting auditee? (By UEI, presumably…)
> 4. By organization type?
> 5. By presence/absence of findings in the audit?

Maybe certified/not certified?

> Are the API operations for in-progress SAC submissions and the API operations for `submitted` SACs as distinct as they appear to me right now? If so, we should probably consider them as two separate applications.

> What about returning things other than lists of SACs? What about returning individual data points from SACs? What about “how many SACs from a given year for this reviewing agency had findings?”
> 

I could also see a difference between what someone would be trying to get for the dashboard upon logging in vs. just general queries for public data. I can imagine the same endpoint could be used for both, but one might just want like in progress vs completed SACs for what the user is involved with (through the website) vs filtering on criteria to see SACs publicly. Probably just a matter of either adding in the right criteria or adding in an auth token to get stuff not publicly searchable yet.

**Comment by petermarks-gsa** [comment]
@geekygirlsarah @tadhg-ohiggins Thanks for putting some thought on this. I've added some background in the description and a pass at scoping this issue. I'm thinking we can keep this story fairly lean at this point. In response to a few specific points raised:

> Possible filters
For now, I think we can go without anything other than what Census might find useful for data ingestion (I just reached out to them), which I imagine is not much. 

> We need user research to determine other filters.
There has been some user research on [APIs](https://docs.google.com/document/d/1L6XkC0xzqDGE8F9rE-u6hK6QRGE1dulzSj9ouHmbrd8/edit#heading=h.7dd22xlunw9w). I asked, but people we talked to didn't have specific concerns about filters. Presumably this include the filter criteria on the front end of the current Census FAC and if those are relatively straightforward, we could implement those as part of this story. However, I don't see a need to research and implement an exhaustive list of filters right now. 

> What about returning things other than lists of SACs?
We will need to surface other data points like findings at some point, which I understand are attached to SACs. I figure we can hold off on exact approach of those APIs until we start planning / implementing the fields for those?

> What about “how many SACs from a given year for this reviewing agency had findings?”
This sort of question/query could be useful for data analysis users and I love the idea of making our data more transparent and queryable. I'm not familiar with REST patterns that make these kinds of queries extensible. However, I've seen GraphQL be extended to accommodate these kind of queries. Not sure if that's something we can or would consider as I'm not aware of any GraphQL APIs in the federal government, but thought I'd float it out there.

**Comment by geekygirlsarah** [comment]
@beechnut has done some work with graph databases, but I'm not sure if that's here at TTS or outside of that. He gave a tech talk on it back in December '21.

**Comment by petermarks-gsa** [comment]
@geekygirlsarah @tadhg-ohiggins Please let me know if this is now defined enough to scope/estimate. Otherwise, I suggest we make time to meet and discuss.

**Comment by tadhg-ohiggins** [comment]
I have rewritten the ticket and trimmed it as much as possible; we can consider potential enhancements at a future time.

**Comment by timoballard** [comment]
@tadhg-ohiggins - are you able to pair with me on the third AC (updating migration plan)? Not familiar with this document so I could use some help in making the necessary updates.
