### ISSUE TITLE
[Production ssh access]: move “stuck” submission to `disseminated`

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3568]
### Start (UTC)

2024-03-27 18:15

### End (UTC)

2024-03-27 18:31

### Explanation

On Monday 2024-03-25 a completed submission was submitted but the dissemination process did not successfully complete. We think that this was due to heavy database load at same moment this SAC was submitted. Only one recent SAC is in this state.

This issue logs the steps taken to disseminate the SAC in question.

Enable production `ssh`, connect to the production environment, and access the Django shell:

```sh
cf target -s production
cf allow-space-ssh production
echo $(date -u +"%Y-%m-%d %H:%M") UTC
# 2024-03-27 18:15 UTC
cf ssh gsa-fac
/tmp/lifecycle/shell
python manage.py shell
```

Retrieve the relevant SAC:

```python
from audit.models import SingleAuditChecklist, SubmissionEvent
SingleAuditChecklist.objects.filter(submission_status="submitted")
xx = SingleAuditChecklist.objects.get(report_id="2023-06-GSAFAC-0000031022")

```

The operation that failed on 2024-03-25 is the following Python code, excerpted from https://github.com/GSA-TTS/FAC/blob/main/backend/audit/views/views.py :

```python
            with transaction.atomic():
                disseminated = sac.disseminate()

            # disseminated is None if there were no errors.
            if disseminated is None:
                sac.transition_to_disseminated()
                sac.save(
                    event_user=request.user,
                    event_type=SubmissionEvent.EventType.DISSEMINATED,
                )
```

We need to synthesize `request.user` here. We use the same user that did the transition to `submitted` for this SAC; in other words, this will reflect what would have happened if the original attempt to submit had not encountered problems.

```python
from django.contrib.auth import get_user_model
User = get_user_model()
yy = User.objects.get(username="[REDACTED]")
result = xx.disseminate()
assert result is None
xx.transition_to_disseminated()
xx.save(event_user=yy, event_type=SubmissionEvent.EventType.DISSEMINATED)
exit()
```

We confirmed that the SAC is now disseminated and is available at https://app.fac.gov/dissemination/summary/2023-06-GSAFAC-0000031022

Exit the production environment and disable `ssh`:

```sh
exit
exit
cf disallow-space-ssh production
echo $(date -u +"%Y-%m-%d %H:%M") UTC
# 2024-03-27 18:31 UTC
```

**Comment by tadhg-ohiggins** [comment]
@timoballard  found this entry in the log, which is very close in time to the submission event timestamp:
```
Dissemination errors: {'errors': [OperationalError('could not extend file "base/16399/16710": No space left on device\nHINT:  Check free disk space.\n')]}, report_id: 2023-06-GSAFAC-0000031022
```

**Comment by tadhg-ohiggins** [comment]
A graph of free space in the RDS instance, supplied by cloud.gov support, also shows zero disk space at that time.

Our current best guess is that a DB backup overlapped with some other PostgreSQL operation such that it was attempting to copy a larger-than-usual amount of data and thus ran out of space.

We plan to increase the RDS space to 100GB to attempt to avoid this happening in future; we also need some way to observe the free disk space so that we'll know in future if we're approaching the 100GB limit.

**Comment by jadudm** [comment]
@jadudm double-checking to make sure nothing was left hanging from this work.

**Comment by danswick** [comment]
I don't think there's any reason to believe anything was left hanging here. I'm not sure why I moved it out of "Done," either.
