### ISSUE TITLE
Homepage copy updates

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#358]
**Design**: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4148%3A19746

**Implementation notes:**

"Find older audit information" will link to https://facdissem.census.gov/
The copy on this page still needs to get usability tested and is subject to change
Navigation is not final

**Comment by erinzstrenio** [comment]
Related ticket: #380 
@melchoyce created updated Figma mocks based up updated content I provided
