### ISSUE TITLE
Develop DB restore workflow

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3595]
We're currently backing up the databases on a regular cadence. We haven't needed to restore yet, but should have tooling and a plan in place for that eventuality. 

This ticket captures some prior thinking in one place.

1. Test backup integrity: https://github.com/GSA-TTS/FAC/issues/2215
2. Test restore integrity: https://github.com/GSA-TTS/FAC/issues/2218 
3. Collect metrics about restore activity: https://github.com/GSA-TTS/FAC/issues/2219
4. Create tooling for doing a restore: https://github.com/GSA-TTS/FAC/issues/2217

**Comment by asteel-gsa** [comment]
Outdated. Backup Utility does this, however, we opted for a manual approach for restores.
