### ISSUE TITLE
"Single audit reporting package upload" page

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#360]
**Background:** This issue covers the initial design of the interface for where auditors will upload a pdf audit report. You can find it in the story map [here](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1647627056111). 

**Design**: [Figma](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3653%3A17527), [Design Ticket](https://github.com/GSA-TTS/FAC/issues/338)

**Stories covered in this issue:**

0. As an auditor, I need to be able to upload my audit report as a pdf so that I can complete my audit.
1. As an auditor I need to check that all audit report components are included in my audit report so that I can submit a complete audit that will be accepted.
3. As an auditor, I need to upload a CAP as a separate document so that my submission meets uniform guidance.
3. As an auditor, i need to ensure that my audit report contains no PII before I submit.  
4. As an auditor, I need to be sure the audit report I upload is for the entity UEI for which I created the audit submission.  

**Not in scope for this issue:**

- The back end pdf validation work that will be needed to implement this (needs issue)
- Error messages in the event there's an issue with uploading their pdf (needs issue)

**Acceptance Criteria:** TBD, this needs more definition and scoping. Should possibly be broken up.

**Comment by danswick** [comment]
I believe this is closed by https://github.com/GSA-TTS/FAC/pull/1389.
