### ISSUE TITLE
FAC - Bug: Missing Data

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#3611]
### Describe the bug

Per [helpdesk ticket #3060](https://fac-gov.zendesk.com/agent/tickets/3060):

It appears that Montana State University has no data in our system. It doesn't come up in any kind of search of our live data, of our known failed migrated data, or the missing PDFs. It's possible it is a subrecpient of the State of Montana, which did fail migration.

We need to confirm if it was a subrecipient of the state and that's why it's not available, or confirm that somehow this data is missing.

### Steps to reproduce the bug

If you search by the entity UEI, EJ3UF7TK8RT5, it doesn't come up in any of our systems. Neither does it come up by a name search of our system.

### Expected Behavior

We expect to find the missing data.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
This was missing due to data migration; the State of Montana is now in the house.
