### ISSUE TITLE
Migration follow-up: clean up temp tables in Preview

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3613]
There are a few migration tables left in the Preview environment that need some spring cleaning:

- **Census tables**: these are already backed up elsewhere (right, @gsa-suk?) and can be dropped from Preview.
- **Migration records**: need to confirm these are backed up in an accessible place. Once they're safely backed up, they can be dropped from Preview. 
- **Documentation**: we need some internal documentation describing where these tables are backed up and how to access them.

**Comment by gsa-suk** [comment]
These tables in Preview are needed for migrating the remaining 2% of historical data that failed migration.

**Comment by gsa-suk** [comment]
@danswick Please review https://docs.google.com/document/d/1lP2tgo4s-MWhXe9gqWqeFJC0QgYxRzfpVaTSAGoREbQ/edit.

**Comment by gsa-suk** [comment]
Team decided to keep census tables in Preview until completion of the remaining migration work.

**Comment by gsa-suk** [comment]
Preview database has been purged - https://gsa-tts.slack.com/archives/C03QCP4FSN8/p1721668675008799.
Closing this ticket.
