### ISSUE TITLE
Move request_file_access function to dissemination API

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3625]
### Background
The [request_file_access](https://github.com/GSA-TTS/FAC/blob/00846cb662fa4832dcdfe0dfe668456e951f2f97/backend/support/api/admin_api_v1_1_0/create_functions.sql#L387-L432) API endpoint lives in the admin API. This endpoint is used by external users to generate file download URLs, and so it should probably be part of the dissemination API and not the admin API.

### Tasks

```[tasklist]
- [ ] Duplicate the `request_file_access` function in `dissemination/api`
- [ ] Create a ticket to deprecate the existing `request_file_access` function in `support/api`
```

**Comment by sambodeme** [comment]
Here is the process.
https://www.fac.gov/api/tribal/
