### ISSUE TITLE
FAC - Bug: "Type requirement" should be "Compliance requirements" on our search pages.

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3664]
### Describe the bug

We're using the wrong language here.

### Steps to reproduce the bug

It's on the site.

### Expected Behavior

We should use the right words.

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by jadudm** [comment]
@lauraherring , before we assign this to anyone, would you double-check me that we want "compliance requirements" as the heading for that part of search? Once we get your go-ahead, I imagine it can be moved to "available," as this is a really light fix.

**Comment by lauraherring** [comment]
@jadudm I'm actually just reading through the new OMB memo now and I think we might have gotten slightly ahead of ourselves with this ticket/want to discuss further because I don't think this list is quite as straight forward as we (or at least I) thought even earlier this afternoon.

**Comment by lauraherring** [comment]
...disregard my previous comment, that was for a different ticket.

**Comment by jadudm** [comment]
Although this isn't the original source, I'm thinking about this matrix:

https://us.aicpa.org/content/dam/aicpa/interestareas/governmentalauditquality/resources/singleaudit/uniformguidanceforfederalrewards/downloadabledocuments/2020-omb-comp-supp/2020cspart2.pdf

Yep. And, understood on the disregard. 

Does it want to be "Type of compliance requirement?"
