### ISSUE TITLE
Check GH alerts and update requirements accordingly

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3667]

**Comment by jperson1** [comment]
Alerts marked "Critical" that landed in the AM of 4/17/24 were all Cypress dependencies. These alerts have been closed as they are all for tests. and do not affect production security. 

![image](https://github.com/GSA-TTS/FAC/assets/91098850/229f41f3-b8d8-4759-9414-44db7f20ff54)

**Comment by danswick** [comment]
Quick sweep of critical alerts. I can take a crack at addressing the one non-Cypress dependency next week:


1.`minimist`: The alert is for the Cypress dependency, but we have another offending version as a descendant of `stylelint`, which is getting pretty stale anyway. 
3. `underscore`: dismissed as Cypress-only.
4. `flat`: dismissed as Cypress-only. 
5. `loader-utils`: dismissed as Cypress-only.

**Comment by jadudm** [comment]
This has been added to our dev huddles as a check we need to do. Going ahead and closing this issue.
