### ISSUE TITLE
Top navigation update (static + app): Adding "Submission home" under "Audit submission"

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3669]
**As an auditor who is submitting a SAR to the FAC, I need to be able to find the _Submission home_ screen to review the status of all reports associated with my login.** 

Currently, once a user logs in they are automatically taken to the _Submission home_ screen. Once you have selected an in-progress SAR, you are taken to that reports _Submission checklist_ screen. To get back to _Submission home_ from _Submission checklist_ you can select the FAC logo in the upper left hand corner. We have received consistent user feedback that this route is unclear, and users are instead fully logging out and back in again to return to _Submission home_. 

We would like to add a new, clearer route through top navigation: _Audit submission> Submission home._ **Selecting _Submission home_ will have two actions:** If you are already logged in, it takes you to the _Submission home_ screen. If you are not logged in, it takes you to login.gov, and then the _Submission home_ screen. This should work the same in the static site and the app for consistency. 

### Tasks

```[tasklist]
- [x] Add new "Submission home" option to Audit Submission dropdown in top nav on static site, following behaviors as noted above.
- [ ] Add new "Submission home" option to Audit Submission dropdown in top nav on the app, following behaviors as noted above.
```

**Comment by lauraherring** [comment]
Hey @jperson1, I've already got this staged on the static site. Here's a [link to that branch](https://federalist-35af9df5-a894-4ae9-aa3d-f6d95427c7bc.sites.pages.cloud.gov/preview/gsa-tts/fac-transition-site/lh/nav-testing/) if you want to copy that. These changes should go live on the static site and app at the same time if possible.

**Comment by jperson1** [comment]
Fantastic! The above is the PR for the app side change. We can point the static site link at https://app.fac.gov/audit/. If a user isn't logged in, they'll be redirected to do so. If they're already logged in, it will take them there directly without being redirected through the login step.

**Comment by lauraherring** [comment]
@jperson1 Great! I just commented on it that it looks good to me superficially, but I'll leave the actual approval to an engineer.

**Comment by jperson1** [comment]
Completed by https://github.com/GSA-TTS/FAC/pull/3672 and https://github.com/GSA-TTS/FAC-transition-site/pull/119
