### ISSUE TITLE
04.24 Product update for static site

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3670]
**As a federal stakeholder for the FAC, I need access to regular updates on the evolution of the product so I can adjust my workflows and communications accordingly.** 

### Tasks

```[tasklist]
- [x] Draft a product update for April '24 based upon information covered in this month's Office Hours federal stakeholder call
- [x] Post the update to Updates & News> FAC updates on the static site
```

**Comment by Leighdiddy** [comment]
@lauraherring please let me know if this needs more context or links!

**Comment by lauraherring** [comment]
@Leighdiddy This looks good, thanks! I'll get started on this today/tomorrow as meetings allow.

**Comment by lauraherring** [comment]
I've staged these changes and opened [a PR](https://github.com/GSA-TTS/FAC-transition-site/pull/118) with @jadudm and @James-Paul-Mason tagged for review. Moving this one over to the review column.

**Comment by lauraherring** [comment]
PR is merged so moving this ticket to done.
