### ISSUE TITLE
Address historical audit error "' should be non-empty"

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#3699]
This ticket is to fix the data migration failure related to the `should be non-empty` error message.
After investigating the issue, it turns out that the issue is caused by missing auditee contact name.
The solution was to replace the missing value with GSA_MIGRATION
- Error message: `' should be non-empty`
- Example: 38560, 2018
- Explanation: TBD

**Comment by sambodeme** [comment]
This audit no data in any other Census tables except elecauditheader table (similar to #3712).
