### ISSUE TITLE
Address error "Skipping ACE audit"

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3700]
- Skipping ACE audit
- Example: 204066, 2022
- [AUDITTYPE in ELECAUDITHEADER](https://drive.google.com/file/d/1s8aFZ3kOrzX7jirUY9QGZ3Is6bRqi4pp/view?usp=drive_link)

**Comment by phildominguez-gsa** [comment]
Closing, as we don't plan on processing ACE audits in the near future.
