### ISSUE TITLE
Note title is blank

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#3703]
- Error: `Missing note title`
- Example (dbkey, audit_year) with this error: 118366, 2019
- Explanation: TBD
- Proposed solution: Use the GSA-MIGRATION keyword.

**Comment by gsa-suk** [comment]
Based on team discussions, note_title, note_content and contains_chart_or_tables are handled as follows:

- When note_title is blank, and note content is present, set note_title and contains_chart_or_tables to GSA_MIGRATION.
- When note_content is blank and note_title is present, set note_content and contains_chart_or_tables to GSA_MIGRATION.
- When note_title is blank and note_content is blank, set contains_chart_or_tables to blank.
