### ISSUE TITLE
Address historical audits with missing auditor EINs

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3704]
This ticket addresses the issue related to invalid EINs. Some historical records are either missing the auditor EIN, or contain an auditor EIN value that will fail validation against the application's EIN schema with the error message 'does not match '^[0-9]{9}$''. The team-approved solution is to replace the missing or invalid value with 'GSA_MIGRATION', which is what this ticket will implement.
Changes will include:
- Update the schema to allow 'GSA_MIGRATION' in EIN fields.
- Update logic to only allow 'GSA_MIGRATION' in EIN fields when the migration flag is present.
- Error message: `'auditor_ein' is a required property`
- Example: 257745, 2022

**Comment by sambodeme** [comment]
Close by #3726
