### ISSUE TITLE
Address historical audits with empty audit types

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#3712]
- Error message: `Audit type is empty`
- Example: 904650, 2021
- Related section: Gen info
- Related validation: [xform_audit_type](https://github.com/GSA-TTS/FAC/blob/main/backend/census_historical_migration/sac_general_lib/general_information.py#L268)
- Explanation: Requires further investigation
- Investigation result: This audit 
Has blank AUDITTYPE in Census elecauditheader table.  
No data in any other Census tables.
pdf report is not present.
- Proposed solution: TBD

**Comment by gsa-suk** [comment]
This audit has some data in the Census elecauditheader table with AUDITTYPE set to blank.  There is no data in any other Census tables.  Also, pdf report is not present.  This audit cannot be migrated.

Closing this ticket based on team decision.
