### ISSUE TITLE
Address historical federal awards with invalid non-empty passthrough numbers

### ISSUE THREAD

**Issue by phildominguez-gsa** [GSA-TTS/FAC#3717]
- Error message: `When the award is direct, passthrough number must be empty`
- Example: 166851, 2018
- Related section: Federal awards
- Related validation: [passthrough_name_when_no_direct](https://github.com/GSA-TTS/FAC/blob/main/backend/audit/intakelib/checks/check_passthrough_name_when_no_direct.py#L12)
- Explanation:
  - Investigate the failures further to determine what values they have instead of being empty (N/A?)
  - Phils research: Most I've what I'm seeing are actual values, as opposed to something like "N/A". There is only one dbkey where "NOT AVAILABLE" is being used: 158396, 2021.
- Proposed solution: TBD

**Comment by sambodeme** [comment]
This ticket is resolved by #3705 and #3811. 
For context, one of the current validation rules for federal awards stipulates that when an award is categorized as a direct award (i.e., when the is_direct flag is set to Y), then the passthrough entity fields (name and ID) must be blank. Conversely, when an award is categorized as an indirect award (is_direct flag set to N), the passthrough entity name must be provided. Some historical reports have awards categorized as direct, but the passthrough entity fields associated with these reports are not blank, which causes them to fail validation. The agreed-upon fix is to replace the is_direct flag with GSA_MIGRATION to indicate that the provided value is incorrect.
