### ISSUE TITLE
FAC - Bug: Invalid date formats in search create 500 errors

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3734]
### Describe the bug

When providing search start or end dates from the search page, if either is in an incorrect format (e.g. `YYYY-MM-DD` instead of `MM/DD/YYYY`), the backend returns a `500` error response [such as this one](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MzkxOTA3NnxBUE18QVBQTElDQVRJT058MTA1ODE5MzE4Ng?account=3919076&duration=1800000&state=85b0e73b-fd72-f944-af1a-8b266de872ce)

### Steps to reproduce the bug

1. Go to `/dissemination/search`
2. Under FAC Acceptance date -> Start date, enter "2024-04-01"
3. Click Search
4. See error response

### Expected Behavior

In these cases, we should use Django form cleaning/validation to check for the appropriate date format, and, if it is invalid, return a descriptive error message that is displayed near the form field in question

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by sambodeme** [comment]
Closing this as unplanned. I was unable to replicate the issue in production, staging, or local environments. The issue may have been resolved by one of the improvement PRs related to the search module that was merged some time ago.
