### ISSUE TITLE
Add Cypress test for "Reset Search" functionality

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3749]
[We recently saw a regression in the "Reset Search" functionality](url). We should add a Cypress test that covers this to prevent future regressions.

### Tasks

```[tasklist]
- [ ] The "Reset Search" functionality is covered by a Cypress test.
```

**Comment by phildominguez-gsa** [comment]
This was completed [here](https://github.com/GSA-TTS/FAC/pull/3867), closing
