### ISSUE TITLE
Create a barebones flask application in the periodic scanner repository

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3759]
Create an empty Flask application and any CF artifacts (e.g. `Procfile`) needed to run the application on cloud.gov

**Comment by asteel-gsa** [comment]
This uses a very lightweight [flask app](https://github.com/GSA-TTS/fac-periodic-scanner/blob/main/app.py) to spin up a hello world on 8080, allowing the `python_buildpack` to do a port check and ensure its running. This should make development of the v1 easier, but something we will need to change later. Ideally to a `process` or `http endpoint`.
