### ISSUE TITLE
Setup deployment pipelines for the periodic scanner application

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#3760]
Make the necessary updates to Terraform and/or GHA workflows to facilitate deploying the [periodic scanner application](https://github.com/GSA-TTS/fac-periodic-scanner) to our cloud.gov spaces.

**Comment by asteel-gsa** [comment]
No workflows are necessary at this time, just to [deploy to preview](https://github.com/GSA-TTS/FAC/actions/runs/8836060461/job/24261739121) with branch = `scanning-app`. The terraform will create all necessary application specific requirements.

- `fac-file-scanner` application
- `fac-db` service binding
- `fac-private-s3` service binding
- `clam` user provided service to store the `AV_SCAN_URL` in `$VCAP_SERVICES`
- Network policies to allow communications on `61443` between:
  - `fac-file-scanner` & `fac-av-$env`
  - `fac-file-scanner` & `https-proxy`
