### ISSUE TITLE
Cross-validation should fail for submissions with 0 federal awards

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3769]
While working on [stuck submissions](https://github.com/GSA-TTS/FAC/issues/3764), @tadhg-ohiggins discovered that it's possible to submit an audit with 0 federal awards. To the intake side of the application, this is a valid thing to do (though it shouldn't be). The dissemination side, however, has no way to handle a submission with no awards data and fails silently, leaving the submission stuck in a "submitted" state, but never reaching a "dissemination" state.

**Comment by danswick** [comment]
We're still not entirely sure if there's a legitimate scenario for submitting a report with zero federal awards. However, given that we've only seen a handful of these submissions and have confirmed that at least some portion were accidental, I'd advocate for adding this validation now. Later, if we learn that we need to accept reports with zero federal awards, we could create a pathway to do so.

**Comment by jadudm** [comment]
100% concur. I think, by definition, you cannot spend Federal money without describing an award. Therefore, I think a submission *must* have at least one award.
