### ISSUE TITLE
🅢 Backend implementation of logging out

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#379]
Breakout issue of #359 

### Background
When a user logs out from the FAC-Frontend, the backend should be notified so that it can delete the auth token associated with that user. This will prevent the token from being reused and force the user to re-authenticate with their Login.gov token before continuing to use the rest of the API.

### Acceptance Criteria (We'll know we're done when...)

- [ ] An authenticated `DELETE` request can be sent to `/auth/token`
- [ ] After sending a `DELETE` request to `/auth/token`, the previously issued FAC token can no longer be used for API requests

### Tasks

- [ ] 
- [ ]

**Comment by petermarks-gsa** [comment]
@timoballard I see https://github.com/GSA-TTS/FAC/pull/393 got merged. Are we good to close this?

**Comment by timoballard** [comment]
@petermarks-gsa yep!
