### ISSUE TITLE
Contact relevant individuals re: stuck SACs

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3790]
We need to contact folks involved with [the stuck SACs](https://github.com/GSA-TTS/FAC/issues/3764) in production.

The contact information and other details are [in this Google doc](https://docs.google.com/document/d/1LESt7tTLWPSr-raMgIe_mbJwboS7YdvghyHr6bGgxPw/edit#heading=h.ici413wi5sbt), which can be used for coordination/drafting emails/etc.

I’m available to provide any information that’s needed past the context in the doc/parent issue.

**Comment by lauraherring** [comment]
Hey @tadhg-ohiggins, quick gut check on this one: if these users did mean to include federal awards in their submissions, because they have gone through the certification and submission steps, they're only option is to resubmit, correct? At this stage, they can't unlock the ones that stalled out, right?

**Comment by tadhg-ohiggins** [comment]
@lauraherring yes, although you could argue that it's not technically “resubmission” in the way that we’ve been using the term; no public record of their submission has been created. Practically, yes, the UI doesn’t allow them to proceed from here without starting over.

My suspicion is that they didn’t mean to do that, and one of the things we need to find out is why they think they should submit a SAC if they don’t have any federal awards.

**Comment by lauraherring** [comment]
I've drafted some email copy and added it to the GDoc linked above. If that sounds good to you, @tadhg-ohiggins and @jadudm, I can send that to the individuals using the fac@gsa.gov email.

**Comment by lauraherring** [comment]
I emailed these people this morning from the FAC team email so we should all see when/if they reply.
