### ISSUE TITLE
Error message content refinements 

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#381]
Breakout issue of #367 and #337 

This issue covers the design of the error messages throughout the FAC.

### Background

Drafted content in [Google doc](https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#heading=h.qxh1fnjvsw9m)
Errors .txt file [here](https://github.com/GSA-TTS/FAC/files/9132950/Errors_939014.txt)

### Acceptance criteria (We'll know we're done when...)

- [x]  Updated content has been reviewed and is ready for dev
   
### Tasks

- [x] Draft updated content for the list of error messages
- [x] Peer review

**Comment by erinzstrenio** [comment]
Ready for peer review! https://docs.google.com/document/d/1rCdqfW5XSVBp3a768Z6Ql4a-g9s0EfxGKyH-4uD1SYc/edit#
cc @melchoyce @austinhernandez

**Comment by melchoyce** [comment]
@petermarks-gsa Do we need to do anything additional with these completed copy tickets?

**Comment by petermarks-gsa** [comment]
@melchoyce I'm creating implementation tickets for them. Just created this: 

https://github.com/GSA-TTS/FAC/issues/412
