### ISSUE TITLE
Crosswalk table? (How do users go from DBKEY/AY to Report ID?) (Computed view in API?) Migration status may serve in this regard?

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3831]
The census_historical_migration_reportmigrationstatus  table holds the DBKEY, YEAR and migration status of all census audits that went through the migration process to GSA FAC.  Provide users a translation of DBKEY/AY to Report ID.

Proposed solution:  Create a Materialized view mapping dbkey, audit_year, report id, UEI, ein

**Comment by Leighdiddy** [comment]
@gsa-suk please revise to include description of action items, desired outcomes

**Comment by jadudm** [comment]
This is probably an old low-content ticket I created w/ Sudha. I'll circle up with @gsa-suk to see what we can do here.

**Comment by gsa-suk** [comment]
I just picked up the ticket and wanted to chat with @jadudm .
