### ISSUE TITLE
FAC PenTest Account Creation_May 2024

### ISSUE THREAD

**Issue by ChrisB-16** [GSA-TTS/FAC#3838]
### Tasks
@JeanMarie-PM @timoballard @jadudm 

GSA Pen Test team has made an request for account creation- test accounts. Need task completed before 5/17/2024
Assign FAC DevOps team to create unique account type

1. Provide a test account for the FAC non-prod environment (the most common account/role that has write permissions).
2. Provide a test account for the FAC prod environment (the most common account/role that has write permissions).

**Comment by timoballard** [comment]
@ChrisB-16 - I'm assuming that by "write permissions" they just mean the ability to submit audits, i.e. a "public" user from our perspective, as opposed to a backend, admin user?

If so, I can create one for them, or we can just clarify that any account freely created at https://idp.int.identitysandbox.gov/ will have the ability to submit audits. If they want us to create, do you know how they'd like us to send them the credentials?

**Comment by jadudm** [comment]
In the last round, it was a standard user account.

**Comment by timoballard** [comment]
Accounts created and ready to share, asked pen test team for a list of emails to share the doc with

**Comment by danswick** [comment]
Looks like Tim wrapped this up this morning!
