### ISSUE TITLE
Add cross-validation for `total_amount_expended` < limit

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#3869]
Following from #3769, we may also need to catch the case where `total_award_expended` is some invalid amount.

We've primarily seen this in cases where there were no federal awards and `total_award_expended` is zero, but should we just reject if the total is below some limit, and should that limit be the same as the limit we ask submitters about in the initial steps? (Currently this is $750,000.)

**Comment by jadudm** [comment]
I believe this is safe.

There is ambiguous policy floating around the world that suggests that, for some entities, they can/must submit at a lower threshold. This has never been resolved. Therefore, we will disregard it as an "unknown/unknown."

I think it is safe to set this to the threshold. If someone thinks they *should* be able to submit with a spend below the SA threshold, and we prevent them... they will reach out to us.

**Comment by jperson1** [comment]
Moving this to "Blocked" for now. See the relevant Slack thread for why, but TL;DR:

Expenditures and reimbursements count against each other. If that brings the record below the threshold, we don't want to block it. How can we detect that, and is it our place to block a submission when the user has attested early in the process that they are above the threshold?
