### ISSUE TITLE
Certification and certification screen tracking issue

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#387]
### Background
Certification requires role-based checks, validation of the entire submission, and a set of attestations about it that certifiers must submit (possibly in the form of a series of checkboxes). This should be its own issue or set of issues, which this is the starting point for.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins I'm going to put this in the backlog until we refine, scope and assign a milestone to it.

**Comment by melchoyce** [comment]
Removing the design label since design of these screens is ready for the MVP: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A25417&t=ZtSXqJAaDEZOlmbU-4
