### ISSUE TITLE
Data reliability documentation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3871]
**Squad**: TBD
**Timeframe**: Must ship to GSA leadership for review by end of 6/24
**Timeframe**: Due to GAO by end of 9/24

The FAC has [known issues with data](https://docs.google.com/document/d/123IpqJBj2Oyd911G9uO8aI_DiQmQ-Iq34De6WHvMZCQ/edit#heading=h.p1pa5x5yrwn2) that are not documented publicly. GAO has recommended:

> GAO recommends the Administrator of GSA should develop a process to regularly identify, analyze, and respond to FAC data reliability issues that may affect federal oversight, such as establishing edit checks to mitigate issues related to data accuracy, consistency, and completeness.

We have committed to GAO to documenting this publicly on fac.gov.

## What problems are we trying to solve

1. Users of the FAC data have no way of knowing what errors currently exist in the data, and therefore their work may be negatively impacted by our (incorrect, misleading) data.
2. We have no way of publicly documenting new issues as they are discovered.

## What can we do today

We can begin by documenting the known data issues, and ticketing the work to resolve those issues. The documentation **informs** the Federal (and public) user communities of the FAC regarding known problems in the data. The tickets allow us to **prioritize** the work with Federal partners, as some issues are more disruptive to oversight and analysis than others.

We will need to first [load the migration tables](https://docs.google.com/document/d/123IpqJBj2Oyd911G9uO8aI_DiQmQ-Iq34De6WHvMZCQ/edit#bookmark=id.8strvntkrs9j) and [historic data](https://docs.google.com/document/d/123IpqJBj2Oyd911G9uO8aI_DiQmQ-Iq34De6WHvMZCQ/edit#bookmark=id.tv8tq8mey4ze) into `production` in order to do any remediation of data.

## Context and further reading

The GAO report [Single Audits: Improving Federal Audit Clearinghouse Information and Usability Could Strengthen Federal Award Oversight](https://www.gao.gov/products/gao-24-106173).

```[tasklist]
### Requirements
- [ ] Establish a `data-resources` hub on fac.gov (https://github.com/GSA-TTS/FAC/issues/3786).
- [ ] Provide a consistent set of elements for each data integrity report (a "template") for ease of authoring and use.
- [ ] Iterate with GSA leadership early and often for approval
```

```[tasklist]
### Known data issues
- [ ] Replicated federal awards rows
- [ ] Submitted (accepted) date in migrated data off-by-one
- [ ] Fiscal year end-dates off-by-one
- [ ] Removal/permanent suppression of incorrect audits
- [ ] Delete internal XLSX docs for complete audits
- [ ] Clean up partial submissions
- [ ] Fixing incorrect audit identifiers
```

**Comment by danswick** [comment]
Rolled up into #4465
