### ISSUE TITLE
Add GSA privacy policy link to page footers

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#3877]
As part of our ongoing compliance work, we learned we're not meeting the "system use notification" requirement. Per a [🔒 recent announcement](https://gsa-tts.slack.com/archives/C048FRTFULB/p1715949727758569), we _should_ be able to satisfy the requirement by linking to GSA's [website privacy policy](https://www.gsa.gov/website-information/website-policies#privacy) page. 

```[tasklist]
### Tasks
- [x] Add privacy policy link to FAC app footer.
- [x] Add privacy policy link to FAC static site footer.
```

As a reminder, this cannot be published to the static site or app until the code freeze is over.

**Comment by Leighdiddy** [comment]
[new guidance on website warning banners.pdf](https://github.com/GSA-TTS/FAC/files/15489059/new.guidance.on.website.warning.banners.pdf)

Here is some extra context from a recent GSA-wide email!

**Comment by phildominguez-gsa** [comment]
This was completed for the app [here](https://github.com/GSA-TTS/FAC/pull/4006), which closed [this ticket](https://github.com/GSA-TTS/FAC/issues/3973)
