### ISSUE TITLE
FAC - Bug: FAC acceptance date search field accepts non-chronological dates

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3891]
### Describe the bug

The FAC acceptance date range search field will accept dates in non-chronological order, for example this start date is later than the end date:

<img width="269" alt="Screenshot 2024-05-28 at 4 44 49 PM" src="https://github.com/GSA-TTS/FAC/assets/119363060/e3f56752-c87e-448e-87c8-91fc8b081c94">

We need to correct the field so that it will not accept a start date that occurs after an end date. 

### Steps to reproduce the bug

See above

### Expected Behavior

See above 

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by sambodeme** [comment]
Closing this ticket as the change has already been impleted by another PR.
