### ISSUE TITLE
Update user workflow from SAR submission screen

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3894]
**As a user who has just submitted a single audit report, I want to see the status of that report after selecting "submit", so that I can confirm that the report has been submitted.** 

Currently: After a user completes all required steps and selects "Submit single audit package," they are taken back to the submission checklist. This can be confusing because it appears that you're being directed back to further steps to complete a submission. 

We would like to update this so that when a user selects "Submit single audit package," they are taken to their audit submission home screen and can now see that their in-progress audit has moved to the "Completed audits" table. 

### Tasks

```[tasklist]
- [ ] Implement revised user workflow to take user to their audit submission home screen after selecting "Submit single audit package" and successfully submitting 
```

**Comment by phildominguez-gsa** [comment]
Confirmed this was already implemented [here](https://github.com/GSA-TTS/FAC/pull/1881).
