### ISSUE TITLE
Update headers in data dictionary to match up w terms used in SF-SAC

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#3895]
Currently: The FAC data dictionary uses terms that do not match up/map to their corresponding fields in the SF-SAC. We want to update the terms used in the data dictionary to match the SF-SAC for user reference, and share definitions for each term.

**Comment by Leighdiddy** [comment]
@jadudm Tagging you here for any addtl explanation or ref materials, I don't have access to the current data dictionary.

**Comment by Leighdiddy** [comment]
@jadudm are we talking about the API data dictionary? https://www.fac.gov/api/dictionary/ I'm reviewing this ticket with dev and the ask is unclear, my notes are also unclear on this :/

**Comment by danswick** [comment]
Rolled into https://github.com/GSA-TTS/FAC/issues/4465
