### ISSUE TITLE
May Invicti findings

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#3902]
See [here](https://drive.google.com/file/d/1ZDzyrfjscJ0LBMTP-auVAtZWapEZbk1l/view?usp=drive_link).

Due 120 days after report was issued (05/24/2024).

Rounds up https://github.com/GSA-TTS/FAC/issues/3900 and https://github.com/GSA-TTS/FAC/issues/3899.

```[tasklist]
### Findings
- [ ] Nosniff header. Possible false positive (see below).
- [ ] Cookie settings. Confirmed [false positive](https://cloud.gov/docs/technology/platform-protections/#vulnerability-scans--challenge-responses)
- [ ] Origin header. Should be resolved by https://github.com/GSA-TTS/FAC/pull/4115. @asteel-gsa to confirm post-deploy.
- [ ] Tab navigation. Should be addressed in the app by https://github.com/GSA-TTS/FAC/pull/4007. PR for static site https://github.com/GSA-TTS/FAC-transition-site/pull/138
```

Assigning @ChrisB-16 to shepherd our responses through to the assessment team. Let's check these off when we confirm that the assessors have acknowledged.

**Comment by danswick** [comment]
Re: the `nosniff` header, I checked manually and it appears to be present on our pages and is a [cloud.gov default](https://cloud.gov/docs/management/headers/). I'm not sure why the Invicti scan isn't seeing it.

**Comment by danswick** [comment]
@ChrisB-16 will compare against the August findings and scan results to determine if we can close here. We may need to compare the test date to the most recent deploy. Some of the above findings may not have existed in prod by the scan day.

**Comment by danswick** [comment]
@ChrisB-16 to summarize current findings here.

**Comment by ChrisB-16** [comment]
This May Invicti VM scan review can be closed. There was no Criticals/ Highs/ Medium findings. The Low findings are being tracked and will be addressed during future patch release for supporting IT software. The ongoing FAC ATO continuous monitoring efforts will track updates and if any new applicable VM finding is discovered.

**Comment by ChrisB-16** [comment]
This May Invicti VM scan review can be closed. There was no Criticals/ Highs/ Medium findings. The Low findings are being tracked and will be addressed during future patch release for supporting IT software. The ongoing FAC ATO continuous monitoring efforts will track updates and if any new applicable VM finding is discovered.
