### ISSUE TITLE
Address historical audits with blank SP_FRAMEWORK

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#3927]
Some historical audits have blank values for SP_FRAMEWORK when TYPEREPORT_FS is set to 'S'.
Example: dbkey = 199903, audit_year = 2016
Proposed solution: Replace blank value with GSA_MIGRATION

**Comment by danswick** [comment]
Need to confirm, but will likely close without merging the related PR.

**Comment by gsa-suk** [comment]
https://github.com/GSA-TTS/FAC/pull/3931 is the associated PR for this.  This PR handles the issue of blank SP_FRAMEWORK present in the Census data in Preview.  

sk/3927_blank_sp_framework is the branch containing the fix for this issue.   

Since the issue is not present in the Census data in S3, closed the PR without merge.
