### ISSUE TITLE
Date fields on Auditee Info screen should be marked required

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#400]
**Background**: "auditee fiscal period start/end" date fields are required. However, our [designs](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3257%3A15230) (current as far as I know) do not have "required" next to these date fields like we do for other required fields on this screen. 

<img width="465" alt="Screen Shot 2022-07-27 at 1 49 01 PM" src="https://user-images.githubusercontent.com/100610443/181370473-987c2428-e30c-44c3-865a-aac40854c8e0.png">

**Proposed solution**: Mark these fields as required to reflect that they are indeed required.

**Comment by melchoyce** [comment]
I think that might be a design oversight, it looks like [this mockup on that page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3004%3A14713) does include the asterisks. @austinhernandez please let me know if I'm wrong!

**Comment by petermarks-gsa** [comment]
@austinhernandez Can you confirm we should have asterisks next to the date fields here as they're required?

**Comment by melchoyce** [comment]
This is what it looks like on the "General Information" form page:

![Screen Shot 2022-07-28 at 4 20 56 PM](https://user-images.githubusercontent.com/2846578/181630089-c0efbd62-72d0-4084-b3ed-a738ff48bf65.png)
