### ISSUE TITLE
Update CFDA Lookup CSV

### ISSUE THREAD

**Issue by jperson1** [GSA-TTS/FAC#4003]
# Update CFDA Lookup CSV

The [CFDA](https://sam.gov/content/assistance-listings) changes. Programs are added, programs are removed, and programs are changed in place. Thus, we have to occasionally make updates to our cfda-lookup file to ensure new programs are valid in our system. [One user](https://fac-gov.zendesk.com/agent/tickets/3832) is requesting a specific program be included. We should unblock this user now, and look to better ALN support in the future. For more info on that, check out https://github.com/GSA-TTS/FAC/issues/1555.

We use [cfda-lookup-20230626.csv](https://github.com/GSA-TTS/FAC/blob/main/backend/schemas/source/data/cfda-lookup-20230626.csv) to track what ALNs are valid in our workbook templates. The columns within are brought into `FederalProgramNames.json` by way of a short script. After changing the cfda-lookup CSV, workbook templates can be regenerated with a `make all` in the `schemas` directory.

```[tasklist]
- [x] Add to/regenerate the cfda-lookup CSV, to include the program the user is having trouble with.
- [x] Regenerate the workbooks.
- [x] Ensure the updated workbooks are included in the static site repository as well as the app.
```

**Comment by phildominguez-gsa** [comment]
Templates need to be updated on the static site after the next release

**Comment by phildominguez-gsa** [comment]
Static site templates updated here https://github.com/GSA-TTS/FAC-transition-site/pull/149
