### ISSUE TITLE
🅛 Front end - implement access denial

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#401]
Breakout issue of #332

## Background

Currently any user can visit any URL in the app, irrespective of whether they are logged in (though any interactions that involve hitting the API do require login)

## Technological overview

Eleventy doesn't have any built-in authentication, and because we're just dealing with static HTML, there's no server to handle auth and everything needs to happen on the client side. The general strategy is:

* Is there a user object? If not, redirect to home page. 
  * This redirection will be to a URL that has a query parameter to the effect of “user wasn't logged in” and that will inform the alter/flash on the home page.
  * If there is a user object, check that they have access to this submission:
    * XHR `GET` to API's `/sac/edit/[report_id]` and then base our client-side redirection off of what we get back.
    * If the XHR fails, redirection will be to a URL that has a query parameter (`?auth=not-authorized`) to the effect of “user didn't have access to that submission” and that will inform the alter/flash on the home page.
    * **Note:** the frontend will only get the data about this specific SAC submission from that XHR, so if it fails, no data is transmitted, regardless of what the client-side JS does.
* Add a `no-JS` class to hide all content in case there's no user object and the user has disabled JS.

## Acceptance Criteria

- [x] A logged-in user can visit a page to which they have access
- [x] A logged out user attempting to visit any page past `home` will be redirected to `home` and see an alert to the effect that they aren't authorized to go to that page
- [x] Similarly, a logged-in user attempting to visit an audit to which they do not have access will also be redirected to `home`
- [x] User with JS disabled is unable to view content on any page besides `home`

**Comment by heymatthenry** [comment]
Made some progress this, but am now blocked until (at least the authentication piece of) #398 lands.

**Comment by petermarks-gsa** [comment]
Blocked by https://github.com/GSA-TTS/FAC/issues/438

**Comment by heymatthenry** [comment]
@petermarks-gsa Some notes on testing in the implementation PR: GSA-TTS/FAC-Frontend#37

**Comment by petermarks-gsa** [comment]
@heymatthenry As mentioned in PR, looks good! Closing.
