### ISSUE TITLE
SF-SAC revision research

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#4013]
# What problem are we trying to solve?

The FAC submission includes two pieces: the Single Audit Report (SAR, the PDF) and the data collection form (the SF-SAC, or "workbooks").  **There is data duplicated between these two documents, and it is not always in sync.**

We do not want the same data to be collected in two different ways in our collection. It increases burden on the user, and makes oversight more difficult.

# Goals

This work has four overarching goals. These goals will be refined as we dig deeper into our work.

1. **Improve the quality of the SF-SAC data collection**. This is in keeping with the [GAO report](https://www.gao.gov/products/gao-24-106173#:~:text=The%20Administrator%20of%20GSA%20should%20develop%20a%20process%20to%20regularly%20identify%2C%20analyze%2C%20and%20respond%20to%20FAC%20data%20reliability%20issues%20that%20may%20affect%20federal%20oversight%2C%20such%20as%20establishing%20edit%20checks%20to%20mitigate%20issues%20related%20to%20data%20accuracy%2C%20consistency%2C%20and%20completeness.%20(Recommendation%201)). It is not possible to collect quality data when it is collected twice, once in a machine-verifiable form, and a second time in a form that is not verifiable.
2. **Reduce burden for the public**. We believe we can reduce burden by collecting data once, with validations, in a manner that is appropriate to the data in question.
3. **Align the collection with oversight**. The SF-SAC has evolved over 20+ years. We want to understand the data needs of government, and align the data collected (and its shape) with the needs of oversight.
4. **Prepare the collection for the GREAT Act**. We want the collection to move, incrementally, to a form that can be completed using open tools and open data formats.

# What can we do now?

Our first step is to engage in research with IGs, agencies, auditors, and grantees to understand the collection from each of their perspectives. In conjunction with OMB, our advisory committee, and Federal colleagues, we can then work to align the collection with those needs. 

Each step of the way, it is our intent to engage in *data pilots* that test possible improvements to the SF-SAC with users. This will allow us to better estimate the burden impact, as well as validate assumptions about data quality. We have already identified, with Federal partners, problems with the collection of information about *findings*. We _may_ pilot a pilot  using _findings_ as our example, so that all involved understand what a data pilot is and the potential value they represent.

```[tasklist]
### Tasks
- [ ] Develop initial research plan
- [ ] Pilot alternative findings collection mechanism.
```

**Comment by Leighdiddy** [comment]
Closing due to unclear scope, work is scheduled to continue in FY25 Q2
