### ISSUE TITLE
Display relevant UEI options for submissions with and without valid UEI

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#402]
Breakout of https://github.com/GSA-TTS/FAC/issues/185

### User stories: 
- As a user who has started submission *with* a valid UEI, the state of related fields on the general information page should reflect my options. 
- As a user who has started submission *without* a valid UEI, the state of related fields on the general information page should reflect my options. 

### Acceptance criteria: ###

**Test Case 1: MATCHING UEI FROM SAM.GOV**
 - name is auto-populated in the (uneditable) auditee name field on the auditee info page and is carried forward to the general info page where it is not editable.
 - UEI is carried forward from the auditee info page to the general info page where it is not editable.
 - address is auto-populated from sam.gov on the general info page where it is not editable if it is not blank. 
 
**Test Case 2: NO MATCHING UEI**
  - Users will **manually enter** Auditee name on the auditee info page. Auditee name is carried forward to the general info page where it is not editable.
  - Whatever UEI they searched on the auditee info page will be carried over to populate  UEI field on the general info page where it is not editable.
  - Bar users from entering entity name and address info on the general info page, and let them know it will be added/overwritten by sam.gov when a valid UEI is added. 
    - We may consider editing user-supplied data as an enhancement at a later time, we may have to provide a path to enter address at some point.

### Technical discussion notes
- Per @tadhg-ohiggins, this thinking is we'll have separate fields for user-submitted auditee info and SAM.gov submitted auditee info. 
- We do not yet know if we need to accept audits without a valid UEI, so defer decision submit user-submitted auditee info

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Flagging that we don't have someone assigned to scope this breakout story.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins Following up on estimation meeting today, flagging that the goal is to estimate this before sprint planning tomorrow.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins I'm suggesting this issue as an item for backlog refinement tomorrow. This needs to be both scoped and to take into account user research in https://github.com/GSA-TTS/FAC/issues/304

**Comment by petermarks-gsa** [comment]
Per discussion with @tadhg-ohiggins and @melchoyce, we're considering this blocked pending further design research and response from Census. We'll revisit the decision to move forward without a valid UEI after that.

**Comment by petermarks-gsa** [comment]
Blocked #446.

**Comment by petermarks-gsa** [comment]
@tadhg-ohiggins to discuss with @heymatthenry

**Comment by tadhg-ohiggins** [comment]
This needs to be rewritten to reflect the recent UEI PDR. Will assign to myself and then assign back to Matt.

**Comment by mogul** [comment]
@tadhg-ohiggins to revisit

**Comment by tadhg-ohiggins** [comment]
@tadhg-ohiggins to pick up the task of revising this from Available.

**Comment by mogul** [comment]
Moving out of `Available` because we don't intend to tackle this until we merge the FE/BE repositories.
