### ISSUE TITLE
Single audit reporting package upload

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#404]
## User stories
1. As an auditor I need to check that all audit report components are included in my audit report so that I can submit a complete audit that will be accepted.
3. As an auditor, I need to upload a CAP as a separate document so that my submission meets uniform guidance.
3. As an auditor, i need to ensure that my audit report contains no PII before I submit.  
4. As an auditor, I need to be sure the audit report I upload is for the entity UEI for which I created the audit submission.  

## Design: 
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3653%3A17360

## Implementation Notes
The requirement for the required fields are in the helper text: "Enter the starting PDF page number for each of the components listed below. Each required component on the checklist must have a numeric page number, unless otherwise noted below."

## Not in scope
- Erin is working on content so final navigation is pending IA/tree testing and error text will come after
- A PDF has to pass a validator check, what that entails is TBD

**Comment by danswick** [comment]
I believe this has been completed with https://github.com/GSA-TTS/FAC/pull/1272
