### ISSUE TITLE
[Production ssh access]: Loading 3K dissemination records

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#4055]
### Start (UTC)

2024-07-03 16:22

### End (UTC)

2024-07-03 19:15

### Explanation

Loaded data into production.

Full log of actions attached to the "Loading data" tracking issue: https://github.com/GSA-TTS/FAC/issues/3994#issuecomment-2207021282

**Comment by gsa-suk** [comment]
Paired on this data load.
