### ISSUE TITLE
Launch Qualtrics survey on fac.gov static site

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#4129]
As a Federal agency, we want to collect user feedback from our static site so that we can optimize our services for our users.

The FAC must incorporate the approved Qualtrics survey into the static site. The survey button should be included on every page of the static site, following the standard set by regulations.gov. 

### Tasks

```[tasklist]
- [ ] Review article/instructions on Qualtrics survey integration: https://www.qualtrics.com/support/website-app-feedback/getting-started-with-website-app-feedback/step-2-creating-a-website-feedback-project/
- [ ] add the survey to the footer so that it will appear on all current and future site pages
```
<img width="1400" alt="regulations feedback button style" src="https://github.com/user-attachments/assets/7ab59bdf-c782-419e-8d79-8535edba99b5">

**Comment by James-Paul-Mason** [comment]
This is a draft, please ignore until the ticket has been finalized.

**Comment by lauraherring** [comment]
@James-Paul-Mason This ticket looks good to me, great job!

**Comment by James-Paul-Mason** [comment]
@jperson1 We talked to eRegs who have already done this. They said you won't need Qualtrics access. They described this process: Create new modal for survey, create new button for survey, embed within footer. Reach out to me if this doesn't make sense; we can consult with the developer from eRegs who performed this over at their site.

**Comment by James-Paul-Mason** [comment]
Blocked while we confirm code.

**Comment by Leighdiddy** [comment]
@jperson1 WE DID IT WE GOT THE CODE!!! Here you go:



<script type='text/javascript'>

(function(){var g=function(e,h,f,g){

this.get=function(a){for(var a=a+"=",c=document.cookie.split(";"),b=0,e=c.length;b<e;b++){for(var d=c[b];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return null};

this.set=function(a,c){var b="",b=new Date;b.setTime(b.getTime()+6048E5);b="; expires="+b.toGMTString();document.cookie=a+"="+c+b+"; path=/; "};

this.check=function(){var a=this.get(f);if(a)a=a.split(":");else if(100!=e)"v"==h&&(e=Math.random()>=e/100?0:100),a=[h,e,0],this.set(f,a.join(":"));else return!0;var c=a[1];if(100==c)return!0;switch(a[0]){case "v":return!1;case "r":return c=a[2]%Math.floor(100/c),a[2]++,this.set(f,a.join(":")),!c}return!0};

this.go=function(){if(this.check()){var a=document.createElement("script");a.type="text/javascript";a.src=g;document.body&&document.body.appendChild(a)}};

this.start=function(){var t=this;"complete"!==document.readyState?window.addEventListener?window.addEventListener("load",function(){t.go()},!1):window.attachEvent&&window.attachEvent("onload",function(){t.go()}):t.go()};};

try{(new g(100,"r","QSI_S_ZN_cN4gyJuBGhPsmcx","https://zncn4gyjubghpsmcx-cemgsa.gov1.siteintercept.qualtrics.com/SIE/?Q_ZID=ZN_cN4gyJuBGhPsmcx")).start()}catch(i){}})();

</script><div id='ZN_cN4gyJuBGhPsmcx'></div>

**Comment by jperson1** [comment]
Closing this ticket as completed by the above PR. Remaining tasks are tracked by https://github.com/GSA-TTS/FAC/issues/3841!
