### ISSUE TITLE
Make frontend Login.gov settings configurable by environment

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#416]
### Background
The Login.gov settings (e.g. login.gov issuer URL) are currently hardcoded in `auth.js` to point to the Login.gov sandbox environment. This should be updated so that the appropriate settings are used based on the deployment environment.

### Acceptance Criteria (We'll know we're done when...)

- [ ] When running the FAC frontend locally, the login.gov sandbox configuration is automatically activated
- [ ] When running the FAC frontend federalist preview site, the login.gov sandbox configuration is automatically activated
- [ ] When running the FAC frontend federalist production site, the login.gov production configuration is automatically activated

**Comment by jadudm** [comment]
Also flagging @timoballard , @asteel-gsa ... I think we can close this?
