### ISSUE TITLE
Change `Access` data model

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#418]
Breakout issue of [#410](https://github.com/GSA-TTS/FAC/issues/410) covering rewriting the `Access` data model.

### Background
We need to make sure the process for lookup up `User` to `SingleAuditChecklist` relationships is a straightforward one. Our older approach was to have multiple fields in the `SingleAuditChecklist`:
*   `certifying_auditee_contact`
*   `certifying_auditor_contact`
*   `auditee_contacts`
*   `auditor_contacts`

Each had a different specific role, and the first two them were limited to one entry and the other two could have any number of entries. This is cumbersome to make queries against and isn't particularly extensible.

We will remove these fields from `SingleAuditChecklist` and change the relationship such that many `Access` instances can point to the same `SingleAuditChecklist`. Each `Access` has only one role and only one related `SingleAuditChecklist`. If a user has multiple roles, we will create a separate `Access` for each role.

In order to limit the `certifying_auditee_contact` and `certifying_auditor_contact` roles to one per `SingleAuditChecklist`, we will investigate Django's model constraints feature, and use that if possible, otherwise we will write that restriction into the code where we create `Access` instances.

### Acceptance Criteria (We'll know we're done when...)

- [x]   Those fields are no longer in the `SingleAuditChecklist` model.
- [x]   The existing functionality is now achieved by the `Access` approach outlined above.
- [x]   The existing tests pass.
- [x]   We have tests for multiple entries for `auditee_contacts` and `auditor_contacts`.
- [x]   We have tests for `certifying_auditee_contact` and `certifying_auditor_contact` (and `creator`!) that ensure there can only be one user with each of those roles associated with any `SingleAuditChecklist`.
- [x]   The tests pass.

**Comment by geekygirlsarah** [comment]
Good luck, @timoballard.  [salute]
