### ISSUE TITLE
Redesign: Updates section fac.gov

### ISSUE THREAD

**Issue by James-Paul-Mason** [GSA-TTS/FAC#4204]
As user of fac.gov, I want a more useful Updates page so that I can stay current on the topics that matter to me and my work. 

### Links

- PR: https://github.com/GSA-TTS/FAC-transition-site/pull/164
- [FAC Design Review QA](https://docs.google.com/spreadsheets/d/1FAbgvIyTE9AXYIVFfAT5jk4FABaCBlgKs1FGfHMm1vI/edit?gid=457631214#gid=457631214)

### Design
```[tasklist]
- [x] During next Design sync, discuss new design for our Updates section--roughly based on modular design of [USAGov Blog](https://blog.usa.gov/)
- [x] Mockup in Figma
- [x] Review mockups together
- [x] Sync with @jperson1 to get feedback on page and start talking about how we want to do dev handoff
- [x] Update listing page based on design and dev feedback
- [x] Create mockup for detail page
- [x] Create ticket for dev and hand off
```

### Development
```[tasklist]
- [x] Migrate updates to their own files - no visible changes
- [x] Build barebones update pages
- [x] Breadcrumbs - ideally a site-wide solution
- [x] Side bars - notifications, subscribe, etc.
- [x] "Recent updates" component at the bottom of the individual pages
- [x] Final design checks - include images, color/font/spacing changes
- [ ] Searchable updates in the main page
- [ ] !?!? Streamline adding new updates
```

### QA - Things to Check Over
```[tasklist]
- [x] New "Updates from the FAC" page (`/updates/`)
- [x] New individual update pages (`/updates/file-name/`)
- [x] Card components (on the sides of both pages), with email links
- [x] Pagination component for accessing older updates
- [x] Breadcrumbs for the updates pages, navigating to "Home" works
```

**Comment by analynd** [comment]
Thanks for adding me to this ticket @James-Paul-Mason! I'd love it if you could link me any of the content strategy work you've been reviewing with Dan. 

Also, do you think we would be sharing these updates on social media? I'm sure the reason why USA.gov blog has photos for each article is to optimize for social sharing. I'm wondering if we'd need to have photos for the FAC, and if so we'd probably need some type of style guide to maintain consistency 👀  (and make sure it doesn't become a burden for us to pull photos/graphics). Thank youu!

**Comment by James-Paul-Mason** [comment]
Hi @analynd! Excellent questions. In terms of the content strategy work around updates, the main work that has been done is a proposal for what we want to share in the Updates section. There are no specific tickets related to this work, but I will send you the proposal in terms of where we want to take the content of these updates. 

I don't think we would be sharing on the socials--that's a great question though. @Leighdiddy any thoughts on Analyn's question about social media as well as photo/graphic use?

**Comment by analynd** [comment]
Updating ticket with link to draft of mockup: https://www.figma.com/design/GE9iGBal6TGUzObB1tme8o/%234204-Updates-Page-Redesign?node-id=3694-3759&t=IIg4z51dV2lviBUg-1 
cc: @Leighdiddy @James-Paul-Mason 

I added comments in the figma file. Please lmk of any feedback, thanks!

**Comment by analynd** [comment]
Synced with Leigh, James M, and Cordelia on 9/9/24 to get feedback on design and content
- Specific edits to incorporate into next draft are [documented as comments in Figma](https://www.figma.com/design/GE9iGBal6TGUzObB1tme8o/%234204-Updates-Page-Redesign?node-id=3694-3759&t=XklQGlBdOB8fwWln-1)

### Next Steps
- Sync with @jperson1 to get feedback on page and start talking about how we want to do dev handoff (note: can potentially use this as an opportunity to improve/standardize design-dev handoff process for team)
- Update listing page based on design and dev feedback
- Create mockup for detail page

**Comment by analynd** [comment]
@jperson1 Desktop and mobile designs are ready for dev tickets! Here are some links:

- [Figma designs and annotations](https://www.figma.com/design/GE9iGBal6TGUzObB1tme8o/%234204-Updates-Page-Redesign?node-id=3798-3168&m=dev&t=3Gch5qRXdCG3PPtE-1)
- [Prototypes ](https://www.figma.com/proto/GE9iGBal6TGUzObB1tme8o/%234204-Updates-Page-Redesign?page-id=3798%3A3165&node-id=3762-579&node-type=frame&viewport=-1788%2C1384%2C0.28&t=hDTsrXcTF9TyFagD-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=3762%3A579&show-proto-sidebar=1)
  - Both the desktop and mobile prototypes can be accessed via that link

Btw, do yall have access to Figma Dev Mode / can yall see details like spacing, font sizes, colors, etc? Hoping yes so that'll save us a bunch of time on annotations! But lmk if not. 

Lmk if you have any questions or issues, thanks! 
Analyn

**Comment by jperson1** [comment]
> Btw, do yall have access to Figma Dev Mode / can yall see details like spacing, font sizes, colors, etc? Hoping yes so that'll save us a bunch of time on annotations! But lmk if not.

Yes, we do! All good on that front. Thanks!

**Comment by Leighdiddy** [comment]
@jperson1 Can you please confirm here once this work has been pushed? We'll close the ticket once it's live :)

**Comment by jperson1** [comment]
@Leighdiddy Can do! I have a list of tasks to break the implementation into pieces. Would it make more sense to add them on here, or to create a follow-up ticket?

**Comment by analynd** [comment]
Analyn is QA'ing (refer to "Things to Check Over" list)

**Comment by analynd** [comment]
@jperson1 **Amazing job!!!** 🙌  I reviewed your list of things to check and found just a few items that I documented in this spreadsheet tracker here: **https://docs.google.com/spreadsheets/d/1FAbgvIyTE9AXYIVFfAT5jk4FABaCBlgKs1FGfHMm1vI/edit?usp=sharing**

**_Assigning this back to you to implement edits._**  Lmk if you have any questions!

------

Also, anyone on this ticket please feel free to lmk if yall prefer to track this type of feedback some other way. I was thinking it could be a part of this [overall design-dev process here](https://app.mural.co/t/gsa6/m/gsa6/1722886279227/f37ed4340028b99fcfe4659f39562d5b92da7d76?sender=u657059c7ef2d757db0e10088):
 ![Image](https://github.com/user-attachments/assets/d81d7cf1-d6e8-4022-9b79-6b300f8d7a0a)
