### ISSUE TITLE
My audit submissions page - start new submission

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#424]
Related to / breakout of https://github.com/GSA-TTS/FAC/issues/391

**Design**: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3341%3A15489

**Acceptance Criteria:**
- [x] Should see "start a new submission" header, the terms checkbox unchecked and the "start a new submission" button greyed out. 
- [x] When I check the checkbox, the "start a new submission" button should be active. When I click it, I should be on the "Submission criteria check" page. 
- [x] When I click the "terms and conditions" link, I should see the "Accept and start a new submission" in modal, I should be able to dismiss the modal or continue to the "Submission criteria check" page.

**Comment by petermarks-gsa** [comment]
@jasnakai @tadhg-ohiggins Jason feels like this is doable for this sprint. Can we scope and estimate?

**Comment by melchoyce** [comment]
Designs have been updated in Figma, starting on this page design:

![image](https://user-images.githubusercontent.com/2846578/206574740-ad7598ff-2bf8-40ac-8204-f29462b167b2.png)

**[Figma mockups start here](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A23015&t=cUukfvlHay8NGXsw-4)**

Related but currently undesigned: #497
