### ISSUE TITLE
Fix postCSS glitch running on localhost

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#426]
When the site first reloads after a change to the CSS, some of the asset links don't work correctly:
![image](https://user-images.githubusercontent.com/6290/183702740-54132c09-c41b-4b88-82d3-9f4aefdd8687.png)

This is because of a quirk in how PostCSS is invoked in the build process. The PostCSS autoprefixer has to add the `-webkit` prefix to the `mask` property in order for it to work in Chrome.
![image](https://user-images.githubusercontent.com/6290/183702881-7912bbb2-02f8-4531-bc0b-79c19c96b1c9.png)
☝🏻 Is this correct behavior. In the broken case, you'll only see the unprefixed version.

A manual refresh will fix it. This is obviously not a big deal as it's only a dev problem, and it's easily worked around. Nonetheless, it's annoying and the extra refresh is distracting.

**Comment by jadudm** [comment]
@heymatthenry , just doing some board cleanup. Feel free to close this if it is no longer an issue. I feel like this was resolved.
