### ISSUE TITLE
 Convert the application to be Terraform exclusive

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#4265]
### Overview
As part of ongoing discussions, this ticket is detailing the work that would go into making the FAC application available to be brought up in the personal cloud.gov sandbox environments. Part of that work would be removing the deployment from manifest files, and handling the application deployment through terraform.

### Supporting Services

```[tasklist]
- [x] Deploy the fac-db to the sandbox environment
- [x] Deploy the fac-snapshot-db to the sandbox environment
- [x] Deploy the fac-public-s3 to the sandbox environment
- [x] Deploy the fac-private-s3 to the sandbox environment
- [x] Setup the necessary domains
- [x] Setup any necessary routing
- [ ] ....
```

### Core Services

```[tasklist]
- [x] Deploy Postgrest instance to the sandbox environment
- [x] Deploy the gsa-fac app to the sandbox environment
- [x] Deploy the proxies to the sandbox environment
- [ ] Deploy clamav to the sandbox environment
```
**We are ommitting the logshipper and anything to do with new relic, as we do not want to be sending sandbox logs to be captured with new relic**

### Debugging Tasks
```[tasklist]
- [x] Figure out why the terraform to deploy the proxy isn't working
- [x] Figure out how to pull the application out of the manifest and deploy with terraform, using the same methodology we use for other services
- [x] Figure out how to handle the <space>-egress configurations (i.e can the proxy work on internal domain, in the same space as the app)
```

### Closeout Tasks
```[tasklist]
- [x] Create a readme for how to deploy
```

**Comment by danswick** [comment]
The terraform-exclusive configuration is only for Sandbox at this stage.

Next steps: setup WSL for testing on Windows machines (Hassan, Bobby, Alex). README needs to be updated and reviewed. Testing right now is primarily individual workstations.

Possibly blocked by or needs to be coordinated with Matt's API work.

We'll know this phase is done when:
 
1. @asteel-gsa, are @sambodeme are set up on Windows
2. Update the README and onboarding docs
3. @rnovak338 runs through setup on his own using onboarding docs and asks for help when he gets stuck.
4. Iterate the docs and onboard someone else with the new version.
