### ISSUE TITLE
M1: Minor Design Updates

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#429]
Breakout issue of #395

-----

### Asterisk can break onto a new line

![Screen Shot 2022-08-09 at 11 48 23 AM](https://user-images.githubusercontent.com/2846578/183769938-beb48f8f-9bab-4adc-9d9e-8f0ac508209e.png)

- [x] Can we add non-breaking spaces between required form labels and the * so the * doesn't get bumped to a new line?

-----

### Too much space between form fields

![Screen Shot 2022-08-09 at 11 49 12 AM](https://user-images.githubusercontent.com/2846578/183770063-60cfb0b5-a2f1-4822-a74c-2b6b498ce2e6.png)

- [x] Decrease space between form fields (1.5rem instead of 3rem)

-----

### Too much padding inside UEI Info container

![Screen Shot 2022-08-09 at 1 08 14 PM](https://user-images.githubusercontent.com/2846578/183775440-2b8acfaf-5c30-4839-833b-7c9f83fd419c.png)

- [] Update the left/right padding in `.ueid-explanation` to 0.

-----

### UEI search field too small, button too compact

![Screen Shot 2022-08-09 at 11 50 05 AM](https://user-images.githubusercontent.com/2846578/183770172-87dbd2d6-8ad2-44f5-8d94-c69481c4d61b.png)

- [x] Height should match other form fields (40px tall)
- [x] 8px of space between search icon and "search" label inside button
- [x] ~20px of left and right padding inside the button. `1.5rem` should work okay. Trying to match the left/right padding of https://designsystem.digital.gov/components/button/.

-----

### Uneven spacing above/below UEI search field

![Screen Shot 2022-08-09 at 11 50 05 AM](https://user-images.githubusercontent.com/2846578/183771465-c28e0903-7795-4bbd-afbe-10c0289d896b.png)

- [x] Make same amount of space above and below UEI search field (`1em` or equivalent rem here)

-----

### Summary box lists inherit unnecessary padding

![Screen Shot 2022-08-09 at 11 56 03 AM](https://user-images.githubusercontent.com/2846578/183770810-d592c459-ebc2-4d32-ab46-520c9d55b5a8.png)

- [x] Remove right margin on the list items inside of summary boxes

-----

### Email address: "can't be null" error needs copy update.

![Screen Shot 2022-08-09 at 12 01 52 PM](https://user-images.githubusercontent.com/2846578/183771860-d548e3d4-5f8a-411f-830d-b345734b94ff.png)

- [x] "Please enter a valid email address" maybe? @erinzstrenio what are your thoughts here?

-----

### Permissions screen has uneven spacing

![Screen Shot 2022-08-09 at 11 56 43 AM](https://user-images.githubusercontent.com/2846578/183771982-aa86ae97-dd20-4041-870c-67083fb198bd.png)

I notice the mockup for this one had some inconsistent spacing as well, so I took it out into its own page and made some minor adjustments. In addition, I added horizontal rules between the sections to help clarify what text belongs with which section.

Figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4430%3A25503

- [x] Make spacing consistent
- [x] Add `hr`s

-----

### Error icon pushes over form field

![Screen Shot 2022-08-09 at 11 57 06 AM](https://user-images.githubusercontent.com/2846578/183774993-4e1fec97-138f-45b7-87a2-fd807065b9e3.png)

Any way to keep the form fields aligned along the same vertical axis, and push the warning icon to the right?

![image](https://user-images.githubusercontent.com/2846578/183775274-50062dbb-42b5-44b5-87bc-b8889fddb7c2.png)

- [x] Align form fields

**Comment by petermarks-gsa** [comment]
@heymatthenry Looks like this is done as the PR got merged? Closing this out but LMK if it should be reopened.
