### ISSUE TITLE
Update python to 3.12.x

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4300]
Python 3.12 has been out for a while now and has had a few patch releases. 3.10, our currently-spec'ed version, has started to cause some [dependency cruft](https://github.com/GSA-TTS/FAC/pull/4297).

**Comment by phildominguez-gsa** [comment]
Just noting here, we [had to pin django-storages](https://github.com/GSA-TTS/FAC/pull/4333) in order to get this working correctly.
