### ISSUE TITLE
Publish Data Reliability summary page

### ISSUE THREAD

**Issue by Leighdiddy** [GSA-TTS/FAC#4316]
**As a user of data from The FAC, I want to understand how the data is being collected and validated, so that I know I'm using accurate, complete data that will produce reliable and reproducible results.** 

The FAC's GAO report has asked that we publish a plain language explanation of our data reliability practices. We will create a new section under our existing top navigation categories for this content, **Audit search > Data reliability** 

[Copy for data reliability page 
](https://docs.google.com/document/d/1InXtHjJJmD-km6OH_dKi2vNt9XYQbjSNrv3wGjG-9L4/edit?usp=sharing)

### Tasks

```[tasklist]
- [x] Update top navigation to include **Data reliability** section under **Audit search** (use URL https://www.fac.gov/data-reliability/)
- [x] Publish Data reliability info page. Page is copy only with UI applied at your discretion using markdown. Please use [this copy ](https://docs.google.com/document/d/1InXtHjJJmD-km6OH_dKi2vNt9XYQbjSNrv3wGjG-9L4/edit?usp=sharing)
```

**Comment by rnovak338** [comment]
@Leighdiddy - it looks like the spending threshold $ is not consistent in the draft document:

<img width="387" alt="image" src="https://github.com/user-attachments/assets/2351a98d-3c65-4cfe-976a-d15630da305d">

<img width="404" alt="image" src="https://github.com/user-attachments/assets/91097988-bf93-4b0b-8497-3d517ad9a745">

Should we go with `$1,000,000` or `$750,000` at this time?
