### ISSUE TITLE
M1: Add navigation links to step indicator 

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#432]
Breakout issue of #395

Can we add links to the [step indicator](https://designsystem.digital.gov/components/step-indicator/) to navigate forward/back between sections in the "create new audit" flow? There doesn't seem to be a clear way back, since I expect "cancel" to literally cancel the entire submission process.

I'll add some hover/focus states to this ticket.

**Comment by melchoyce** [comment]
**Default:**
![image](https://user-images.githubusercontent.com/2846578/187521211-799eb09f-0907-409e-af2f-6243050f8d9c.png)

**Hover:**
![image](https://user-images.githubusercontent.com/2846578/187521236-c8fce7a0-0996-4a50-9d1e-50863d935166.png)

**Focus/Active:**
![image](https://user-images.githubusercontent.com/2846578/187521265-e9de3938-a5d4-4936-b10f-64c0f209a0cb.png)

@austinhernandez Do these interaction states make sense? Trying to mimic what USWDS does with links.

**Comment by petermarks-gsa** [comment]
@melchoyce I started creating an implementation issue for this in https://github.com/GSA-TTS/FAC/issues/496. Do you have a figma link or any implementation notes?

**Comment by melchoyce** [comment]
Figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4609%3A21144

**Implementation notes:**
- When you hover over a previous step, an underline appears under the label.
- On focus, a solid outline appears around the entire step.
- Incomplete steps are not linked.

**Comment by petermarks-gsa** [comment]
@melchoyce Awesome, thanks. I created an implementation ticket for this enhancement and put it in the triage column: https://github.com/GSA-TTS/FAC/issues/496 Closing this design issue as done. cc @tadhg-ohiggins @mogul
