### ISSUE TITLE
Prevent report creation during SAC data load

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#4320]
## Description

As part of loading historical SAC records into the production database, we need to ensure the sequential order of the IDs in the singleauditchecklist table.

This ticket is to implement a safeguard that prevents users from creating new reports while the data load into the SAC table is in progress. This will ensure data integrity and avoid conflicts during the loading process.

**Possible solutions** include:
The team has agreed to implement a kill switch mechanism that will temporarily disable specific application functionality during the data load. The following approach will be taken:

1. Kill Switch via ENV Variable:  We will introduce an environment variable in the settings that acts as a kill switch to control access to critical features during the data load process.

2. Management Command: A Django management command will be created to flip the kill switch. This command will be used to enable or disable the safeguard as needed.

3. Middleware Implementation: Middleware will be added to intercept user requests and display a “Please Hold” page when the kill switch is active. This page will inform users that the system is temporarily unavailable due to maintenance

**Comment by rnovak338** [comment]
@danswick @sambodeme Can we mark this completed with the maintenance mode implementation?

**Comment by sambodeme** [comment]
Done @rnovak338
