### ISSUE TITLE
Automate Conversion of Workbooks to IR JSON and Update Test Logic

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#4326]
### Description:
Currently, the FAC application uses a set of workbooks for testing, which are stored in various locations:
- Under the `audit` app
- Under the `historical_migration` app
- Inside folders named `should_pass` and `should_fail`.

The test logic reads each workbook file and converts it into a JSON format called the IR model, which is then used for validation checks and other test-related processes.

### Task:
This task is to implement the following enhancements:

1. **Automate Workbook-to-IR Conversion:**
   - Update the logic to build fixture workbooks or IR JSON files as needed, instead of only building workbooks.
   - Store the converted IR JSON files instead of the original workbook files.

2. **Update Test Logic:**
   - Modify the current test logic to consume the pre-converted IR JSON files rather than converting the workbooks into IR during each test run.
   - Ensure the test logic processes the IR JSON files for validation checks and other related tasks.

**Comment by danswick** [comment]
> Modify the current test logic to consume the pre-converted IR JSON files rather than converting the workbooks into IR during each test run.

What do you think about moving this change to the validation step? If validation could (optionally) consume IR and skip the workbook parsing process entirely, that could open up pathways for consuming non-workbook data. I'm thinking of things like revising and re-disseminating reports (resubmission-ish), interactively editing workbook data (far future), and possibly even merging duplicate reports. 

If something like this makes sense, the tests could specify either the IR pathway or the full workbook pathway depending on what we want to test.

**Comment by jadudm** [comment]
FWIW, the Python validations only operate on the IR. 

We convert the workbook to the IR, and that is the last time we look at the workbook. We apply a few cleanup transformations to the IR (in some cases), and then we do all of our validations on the IR. At the end, we convert the IR to the internal JSON object notation only because we wanted to keep the JSON Schema validation as a backstop.

But, I might not understand the question. We don't currently *store* the IR, which might stand in the way of some things.

**Comment by danswick** [comment]
>We convert the workbook to the IR, and that is the last time we look at the workbook.

Ah, ok that makes sense! To make my earlier comment more concise: what if, instead of tweaking the _test_ logic to accept IR, we tweaked the _intake_ logic to accept either a workbook or IR?
