### ISSUE TITLE
Improve FAC Data Dictionary

### ISSUE THREAD

**Issue by analynd** [GSA-TTS/FAC#4352]
We received feedback from Marcel Lorincz from HUD during Advisory Committee meeting on 10/01/24 to make improvements [the FAC Data Dictionary](https://www.fac.gov/api/dictionary/). 

### Tasks

```[tasklist]
- [ ] Follow up with Marcel to gain more insights pain points
```

**Comment by danswick** [comment]
Rolled into https://github.com/GSA-TTS/FAC/issues/4465
