### ISSUE TITLE
Design FAC transition site

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#441]
## Background from Census: 
We’re in the process of updating our sites to accept Fy22 audits, UIE, etc, and was wondering if GSA has a landing page yet that we can link to, from our announcements/FAQs? To provide customers a place to go for updates about the FAC transition?

I realize you may not have much/anything posted to that location yet, but it would still be useful to have the link already available on our site, so once you do have information on it, we don’t have to scramble and do another site update at that time. If it helps, we won’t post our system updates with this link until late Sept, so none of our customers would be able to access it until then.

**Comment by petermarks-gsa** [comment]
cc @melchoyce @tadhg-ohiggins

**Comment by melchoyce** [comment]
We've launched a fac.gov transition page: https://www.fac.gov/

Is there any other information we want to include, or do we think this is good-to-go? @pkigongo @JeanMarie-TTS @tadhg-ohiggins

**Comment by melchoyce** [comment]
We decided in Design/Engineering sync today to close this issue, and open new issues for any updates in the future.
