### ISSUE TITLE
[FAC threshold] Follow up with an auditor about the notion of the threshold

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4415]
(e.g. what if they spend 800K and reimburse 200K? Is that over 750K?)

**Comment by Leighdiddy** [comment]
@danswick this feels out of scope for the FAC, would this be a question for grantees cog/over?

**Comment by danswick** [comment]
Good call, Leigh. Looking at UG, I don't see anything about reimbursements. I think it's pretty solidly based on _expenditures_ only, regardless of any reimbursement activity, but they should talk to their cog/over to be sure.
