### ISSUE TITLE
Bug: conflict between award reference number formats

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4451]
We recently learned that differences in award reference numbers (four-digit vs five-digit) are causing problems in the materialized view creation process. We've begun exploring some temporary fixes, primarily via the SQL that creates the MV. Longer  term, we'll need to fix the underlying data and undo the SQL workaround.

More details as we test solutions.

**Comment by jperson1** [comment]
Looks like the SQL change fixed the issue. This maps findings with five digit reference numbers to awards with four digits when the MV is stood up. 

Long term, curation will set all the references to five digit values. Then, this change can be removed.
