### ISSUE TITLE
Update Terraform modules for the production environment

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4453]
Follow up from: https://github.com/GSA-TTS/FAC/pull/4446. These changes need to be rolled out to production as well.

**Comment by asteel-gsa** [comment]
Per the latest [release](https://github.com/GSA-TTS/FAC/actions/runs/11823764130/job/32944341207#step:4:319) terraform provider is now on `0.53.1` and necessary modules are on the correct release version of `v1.1.0`
