### ISSUE TITLE
[bug] Duplicate entries in baseline cog table

### ISSUE THREAD

**Issue by danswick** [GSA-TTS/FAC#4459]
While researching some issues with Cognizant / Oversight assignment, @gsa-suk discovered that a lot of historical Census records are duplicated in the `baseline` table. Some appear to be "real" and others possibly the result of some internal testing that got overlooked. For example:

| report_ID | source | date_added |
| ---            | ------- | -----------  |
| 001           | Census | 2023-10-11 |
| 002           | CENSUS | 2021-03-04 |

In the example above, it appears that _all_ entries with `source=Census` (initial cap) have the same date of `2023-10-11`, suggesting they were all created or at least updated at the same time as part of some batch operation. Entries with `source=CENSUS` (all cap) appear to have unique dates.

As far as we can tell, this doesn't impact functionality, but it is confusing and could cause problems in the future if the cog assignment and calculation logic changes.

**Comment by gsa-suk** [comment]
Closing this ticket, since https://github.com/GSA-TTS/FAC/issues/4510 removes CognizantBaseline table.
