### ISSUE TITLE
Advanced Search page is not displaying Cognizant only assignments for a given audit year 

### ISSUE THREAD

**Issue by gsa-suk** [GSA-TTS/FAC#4480]
### Describe the bug

For a given year, when 'Cognizant' is selected without any agency in the Advanced Search page, the result shows both cognizant and oversight for the given year.  The expected result is cognizant assignments only.

### Steps to reproduce the bug

1.  Go to 'Advanced Search' on fac.gov
2. Select 2024
3. Select Cognizant
<img width="344" alt="Screenshot 2024-11-25 at 12 38 47 PM" src="https://github.com/user-attachments/assets/d14a1026-d6b5-4e81-9b43-15521d581124">
4. Select Search

### Expected Behavior

The search result should only display all cognizant assignments for the selected year.

### Screenshots

<img width="1512" alt="Screenshot 2024-11-25 at 2 26 35 PM" src="https://github.com/user-attachments/assets/a2fb6fa4-188e-4797-97ff-aec6482cbc04">
<img width="1512" alt="Screenshot 2024-11-25 at 2 26 50 PM" src="https://github.com/user-attachments/assets/10429ef6-8da3-4ddb-b8b6-1b0c9f576fa7">
<img width="1512" alt="Screenshot 2024-11-25 at 2 27 11 PM" src="https://github.com/user-attachments/assets/8c58c40a-a412-4ec0-81cd-f5f7cd40cd61">

### Code of Conduct

- [X] I agree to abide by the [Digital.gov Community Guidelines](https://digital.gov/communities/community-guidelines/) and the [TTS Code of Conduct](https://handbook.tts.gsa.gov/code-of-conduct/). Respect your peers, use plain language, and be patient.
- [X] I checked the [current issues](https://github.com/GSA-TTS/FAC/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by Leighdiddy** [comment]
Closing for work covered in #4528

**Comment by phildominguez-gsa** [comment]
> Closing for work covered in #4528

@Leighdiddy I don't think this should be closed yet, the PR you linked hasn't been reviewed or merged.

**Comment by Leighdiddy** [comment]
@phildominguez-gsa thank you for catching this, I got a little close-happy cleaning tickets this morning lol
