### ISSUE TITLE
[Production ssh access]: investigate CENSUS pdfs in database

### ISSUE THREAD

**Issue by asteel-gsa** [GSA-TTS/FAC#4537]
### Start (UTC)

2024-12-12 16:15

### End (UTC)

2024-12-12 16:33

### Explanation

This is a non-issue and requires no code changes. We are getting caught in this try/catch where when attempting to do the `if settings.CENSUS_DATA_SOURCE in report_id:` conditional, it fails, as we have not finished the data loading operation necessary to ensure that the `report_id`'s with `CENSUS` properly utilize this logic, and those reports are currently getting caught in this logic. Those pdfs for census reports do not exist in the `audit_singleauditreportfile` table, so it returns a 404.
```py
            if sac:
                file_obj = SingleAuditReportFile.objects.filter(sac=sac).latest(
                    "date_created"
                )
                return f"singleauditreport/{file_obj.filename}"
```

`backend/dissemination/file_downloads.py`
```py
def get_filename(report_id, file_type):
    # .first() returns None if nothing is there.
    sac = SingleAuditChecklist.objects.filter(report_id=report_id).first()
    if file_type == "report":
        try:
            if sac:
                file_obj = SingleAuditReportFile.objects.filter(sac=sac).latest(
                    "date_created"
                )
                return f"singleauditreport/{file_obj.filename}"
            else:
                if settings.CENSUS_DATA_SOURCE in report_id:
                    return f"singleauditreport/{report_id}.pdf"
                else:
                    raise Http404()
        except SingleAuditReportFile.DoesNotExist:
            raise Http404()
```

**Comment by danswick** [comment]
acknowledged, thanks!
