### ISSUE TITLE
Future-proofing the data model

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#455]
## The problem

The SF-SAC has changed over time, and will change again in future. Sometimes questions are added, sometimes questions are removed, and sometimes questions or their validation rules are changed.

Currently our approach, one monolithic data model that will contain all fields, is not amenable to operating on more than one version of the SF-SAC.

For example, in the past, organization name was entered by the submitter. Now we're going to pull it from SAM.gov if possible. For \[reasons\] we will have two fields in this year's form version: one for SAM.gov-supplied UEI, and one for user-entered UEI. But in the future we have to support form versions from the past, such as someone showing up late to enter their 2016 information.

We need to determine a reasonable approach to handling multiple versions of the form.

Any solution needs to be searchable across form versions. Search users will definitely need to find results spanning different years and thus potentially different versions of the form.

One of the current FAC developers says:

> Currently people filing late/starting early mean we need to support multiple years on the input side, with different questions or alternative specific wording being required depending on the audit year.
>
> Different people in different years working on these changes have addressed the issue in different ways, so it has become quite a chore to update changes for new requirements for a specific year without breaking specifics for prior years.

------------------------------------------------------------------------

We're going to have to accommodate different data models for different form years; sometimes this is validation changes, sometimes entirely different questions.

Note that while new questions could be handled by just adding new fields to the data model, validation changes can't work this way. Field `x` has to have one set of validation rules in e.g. Django (unless we write custom functions for all of the validation here, but that would also mean losing some of the database-level constraints).

-   It's going to be necessary to add a `form_year` or `form_version` field to the model so that each report's form version is known.
-   We could have metadata somewhere that lists the fields corresponding to each form version, and possibly also validation rules corresponding to each version, while still keeping all fields in the same model and just adding to it over time.
-   We want to use a single model, rather than having a separate model per year, because we need to be able to search across form versions; searching only within a given form version isn't a restriction we can get away with.
    -   Alternatively, we could use something like Elastic Search to remove this restriction, but that means we would have to use that service and could not rely on Postgres for searching across versions. Also see <https://github.com/etianen/django-watson>. Any of those options, while workable, do add complexity and dependencies, and also add to the skills required by whoever gets to maintain this in the long run.
-   Does it makes sense to keep going with a monolithic data model where we just put all fields in the same model, or should we consider having separate models per section of the form?
-   For example, there is a list of acceptable agency codes that users can enter to indicate the source of their award(s). This list changes over time. The naive approach here is to simply add it as a `ChoiceField` in the model. However, agencies created in 2023 should not be valid options for users submitting audits for 2015, so the list of agency codes would need to be different for each year. This means we probably have to write custom validation functions that look up the applicable list of agency codes for a given form version.
-   If the Django validation rules are implemented with custom functions, it's not really possible to generate code from the Django model; for example, we couldn't generate a JSON Schema version of the validation from a bunch of arbitrary Python functions.
-   How do we handle wording changes? These are currently not stored in the database (or anywhere outside the frontend at all) but apparently do change and may need to be tied to specific form versions.
-   Developer consensus is that solving the data model considerations comes first, and solving search considerations comes later, so, for example, we might end up with a different Django model for each form version.

Current approach: focus on implementing a workable Django (plus JSON schema) data model for a single SF-SAC version (that is, for one year, 2023) and on being able to easily create JSON Schema schemas from the Django models. This implementation must store question copy somewhere that the frontend reads from, as that is too fundamental to be left as-is when we know the question wording changes over time.

### Acceptance Criteria (We'll know we're done when...)

We'll be done when we have a viable approach to storing questions, fields, and validation rules that change over time.

### Tasks

- [ ] Write ADR for how to handle storing question copy as well as validation rules and answers in some viable data structure. #456 
- [ ] Implement a viable data structure for 2023's version that includes storing question copy and validation rules somewhere, and proceed with the knowledge gained by having doing that.

**Comment by tadhg-ohiggins** [comment]
This is blocked because we want to revisit it once we have a viable data structure for the entire 2023 SF-SAC.

**Comment by petermarks-gsa** [comment]
We want to get #456 done and get familiar using this for FY23 before tackling this.

**Comment by timoballard** [comment]
Preserving some notes that came out of the work on #456:




## Notes
- We can use separate models for the `SingleAuditChecklist` and the `SingleAuditChecklistReport` (submitted SACs)
- When a `SingleAuditChecklist` is submitted, it is translated into a `SingleAuditChecklistReport`
- The `SingleAuditChecklistReport` model does not vary by fiscal year - it is the same across all years to facilitate consisent search and presentation of completed audits
- `SingleAuditChecklists` are validated against a JSON Schema for that fiscal year
- Question and validation error copy for a given year will be stored as part of the `SingleAuditChecklist` JSON Schema


## Questions
- If we use JSON Schema to store the question copy and validation rules for a given form-year, is there a reason to have a database model for `SingleAuditCheclist` data, or should we just store it as JSON?
  - Downsides to maintaining a database model alongside a JSON Schema:
    - Each time a new JSON Schema is created for a new fiscal year, a new database model will also need to created, leading to a continually growing collection of models/database tables (e.g., `SingleAuditChecklist_2019`, `SingleAuditChecklit_2020`, `SingleAuditChecklist_2021`, etc)
    - Maintaining field/validation parity between the JSON Schema and database model for each year will be difficult and tedious to manage without introducing bugs
- What does the `SingleAuditChecklistReport` model look like initially? Do we base it on the current `SingleAuditChecklist`? Do we do user research to determine what the public access needs are?


## Proposal

Refactor the `SingleAuditChecklist` model so that SAC metadata (e.g. `report_id`, `fiscal_period_start/end`, `ein`, etc) are part of the model, and all remaining data (i.e. the fields that are more likely change over time) is stored as a JSON blob:

### `SingleAuditChecklist`
| id | fiscal_year | report_id | ein | data (JSON) |
| -- | ----------- | --------- | --- | ---- |
| 1 | 2021 | 202100001 | ABC123XYZ | { ... } |
| 2 | 2022 | 202200002 | DEF456XYZ | { ... } |

Create a new model `SingleAuditChecklistTemplate` to hold the JSON Schema for each fiscal year, against which incoming submissions will be validated. The template can also hold the question copy for each field:

### `SingleAuditChecklistTemplate`
| id | fiscal_year | template (JSON Schema) |
| -- | ----------- | -------- |
| 1 | 2021 | { ... } |
| 2 | 2022 | { ... } |

Create new model `SingleAuditChecklistReport` to hold the normalized data for each submitted `SingleAuditChecklist`:

### `SingleAuditChecklistReport`
| id | fiscal_year | report_id | ein | met_spending_threshold | etc |
| -- | ----------- | --------- | --- | ---------------------- | --- |
| 1 | 2021 | 202100001 | ABC123XYZ | true | ... |
| 2 | 2022 | 202200001 | DEF456XYZ | true | ... |

For each fiscal year, create a translator to convert the validated form JSON into an instance of `SingleAuditChecklistReport`.

**Comment by timoballard** [comment]
@tadhg-ohiggins - possible candidates for SAC metadata (stable fields that will be part of the `SingleAuditChecklist` model, as opposed to being part of the JSON schema:
```
- form_version
- fy_start
- fy_end
- audit_period_covered
- audit_type
- submission_status
- submitted_by
- date_created
```

Questions:
- Why `fy_start` and `fy_end` instead of a single `fiscal_year`?

**Comment by tadhg-ohiggins** [comment]
# 2022-09-20 Data Structure Discussion

Participants: @timoballard @geekygirlsarah @tadhg-ohiggins 

## FAC-specific metadata

Data that the organization does not gather or produce, but is purely related to the submission process.

### Form version

Form version can theoretically change within a year, so we need to support that, but can also remain the same in successive years. This should start with the first fiscal year of use and then double-digit versions, so:

    *   `2022.00`
    *   `2022.01`
    
    Etc.

### Form fiscal year

The FAC fiscal year that the organization is submitting for. Four-digit year.

### Audit type

*   Single audit
*   Program specific
*   The alternative version that was created to allow organizations that received pandemic money to avoid the full audit process they might not be set up for.

### Submission status

FAC’s notion of what the current status of the submission is.

### User access data

Who the users associated with the submission are. Not stored in the main data model per se, but also not stored in the JSON.

### Submission creation timestamp

The timestamp for the initial creation of the submission.

### Organization type

-   State
-   Local Government
-   Indian Tribe or Tribal Organization
-   Institution of higher education (IHE)
-   Non-profit
-   Unknown
-   None of these (for example, for-profit)

### Report ID

The system identifier for the submission. Used in URLs and for customer support purposes.

### Is USA-based

Boolean; if the answer is no, we don’t let them proceed.

### Met spending threshold

Boolean; met the threshold required to make a single audit submission. If the answer is no, we don’t let them proceed.

-----

Fields that are metadata that will go in the model:

*   `form_version`
*   `form_fiscal_year`
*   `audit_type`
*   `submission_status`
*   `submission_creation_timestamp`
*   `organization_type`
*   `report_id`
*   `is_usa_based`
*   `met_spending_threshold`

Data that’s not in the JSON or the model, but in `Access` objects:

*   creator
*   auditors
*   auditees
*   certifiers

-----

## Changes from the current model

Only the above fields will be at the Django model level. All of the other fields currently in the model will move to sections in the JSON structure.

## What should the JSON top-level structure look like?

It should be by section of the form (with minor exceptions for things like `is_usa_based` being in the Django model).

For anything submitted via Excel, every field must be in the JSON, because we need the JSON in the database and the Excel JSON to both correspond to the JSON Schema we are building to rule all the things.

### JSON top-level sections

#### General information
*   Auditee fiscal period start (matches current question 1).
*   Auditee fiscal period end (matches current question 1).
*   Auditee identification tokens and related metadata (matches current question 4). 
*   Auditee info (name, address, etc.) (matches current question 5).
*   Primary auditor info (name, address, etc.) (matches current question 6).

#### Federal awards data

Structure TBD.

#### Audit information

Structure TBD; see https://github.com/GSA-TTS/FAC/issues/214.

#### Award findings

Structure TBD; see https://github.com/GSA-TTS/FAC/issues/215.

#### Findings text

We don’t know much about this section yet.

#### CAP text

We don’t know much about this section yet.

#### Additional EINs

We don’t know much about this section yet.

#### Secondary auditors

We don’t know much about this section yet.

**Comment by jadudm** [comment]
I think much of this was picked up through implementation. Further, much changed between September and Feb/Mar of '23. That is, the team grew, work took off, and we have SMEs working in this space as well. I'm closing this ticket as we have a model working for us, in staging/production, that was informed/developed from this conversation. Calling this work/debt closed.
