### ISSUE TITLE
ADR for how to handle storing question copy as well as validation rules and answers in some viable data structure

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#456]
Breakout issue of #455 

### Background

Question copy and validation rules change over time, so we need a structure to store those. Currently we're “storing” question copy only in the frontend, and we know that won't be sufficient for handling more than one year of the SF-SAC, which we will have to do.

### Acceptance Criteria (We'll know we're done when...)

We know our technical approach to:

- [ ] Questions are stored somewhere and read (possibly at build time, *not* necessarily at page load time) by the frontend.
- [ ] Validation rules are also stored somewhere and read—there is potential overlap between this and the JSON Schema work.

**Comment by petermarks-gsa** [comment]
@timoballard Chatted with @tadhg-ohiggins about this. Can you provide a beverage size estimate for this?

**Comment by timoballard** [comment]
@petermarks-gsa I think this is an `L`
