### ISSUE TITLE
M1: Add icons in place of bullets on "Auditee information" page

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#459]
Breakout issue of #429. We can maybe do this one when doing copy updates to the page?

![image](https://user-images.githubusercontent.com/2846578/188199673-1e1afe45-3a55-4cd4-8c44-4a2d490ab3fa.png)
[Figma](https://www.figma.com/file/8REinLFKSMj7pwQ7JIEHGW/FAC-Sprint-11-prototype?node-id=2%3A3398)

### Tasks

- [ ] Add Spellcheck icon to first list item 
- [ ] Add Verified icon to second list item 

@austinhernandez This could probably also use peer review before going to dev.

**Comment by heymatthenry** [comment]
@erinzstrenio To @melchoyce's point above, is the copy in Figma up-to-date?

**Comment by jadudm** [comment]
We've picked this up/it's done.
