### ISSUE TITLE
Front end for federal awards screen

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#462]
This issue is just frontend layout implementation. Functionality is defined in other stories in Milestone 3. 

![image](https://user-images.githubusercontent.com/2846578/189215083-e34f955c-edb1-4b10-bd55-5befbaf032d6.png)
[Figma mockups](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4647%3A21220)

## Implementation Notes
- When a user downloads the worksheet:
  - The heading and button copy updates from “download” to “re-download”
  - The step counter is changed from a number to a checkmark.
- When you upload an incorrectly formatted, empty, or incorrect worksheet, the upload is rejected and you are given error messages as to why the file was rejected.
- When a user uploads a completed, correct worksheet:
  - The “re-download” button changes to some small explanation text with a download link.
  - The second step is also checked off as completed.
  - The filename is displayed alongside a “download file” action.

## Questions
- Is the excel file processed upon upload, or when a user clicks "save and continue?"

**Comment by petermarks-gsa** [comment]
@heymatthenry @jasnakai Assigning to you two to scope this.

**Comment by melchoyce** [comment]
Most recent designs: https://github.com/GSA-TTS/FAC/issues/449#issuecomment-1241182797

**Comment by heymatthenry** [comment]
Calling this a `M`, with the understanding that all of the interactivity is covered elsewhere, such as: #443, #449, #450

**Comment by heymatthenry** [comment]
Hanging onto this one since it's related to #479 and removing @jasnakai.

**Comment by geekygirlsarah** [comment]
@heymatthenry Is this still lingering because of #479 or is this done? (Wondering about closing this as it's "ready for review")

**Comment by heymatthenry** [comment]
@geekygirlsarah It's "done" in that it's implemented in the old front-end. Idk if the issue should be closed since it needs to be reimplemented, but either way I took it off the board so it's not cluttering up the review column.

**Comment by mogul** [comment]
Given that we're now in the state where the MVP will just be submitting an Excel file for the whole submission, should we be deferring this epic? (It's listed as "active" now.)

**Comment by thebestsophist** [comment]
Noting that we've decided to rewrite this issue

**Comment by jadudm** [comment]
Replaced by #945.

Closing as being subsumed. Will reference back to this ticket from 945.
