### ISSUE TITLE
Copy for federal awards error messages

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#463]
Breakout of https://github.com/GSA-TTS/FAC/issues/450

See [Census document](https://docs.google.com/document/d/1ZTkGARo5gZMN2oLmsOrxfILg7kPagFLz/edit)

**Comment by pkigongo** [comment]
We need a content designer.

**Comment by pkigongo** [comment]
Check in on [link above](https://docs.google.com/spreadsheets/d/1e-NQPeXk)
404 Message

**Comment by lauraherring** [comment]
Need to check w/Erin to see what's going on with broken spreadsheet. Once have that figured out, need to sync w/Dev on the validation behind error message triggering.
