### ISSUE TITLE
Update design of template Excel

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#480]
Breakout issue of #443 

### Background

The FAC has to provide an Excel template file for the user to download to fill in with their submission data.

### Acceptance Criteria (We'll know we're done when...)

- [x]   We have an Excel file that contains fields for all of the required information.
- [ ]   We have a fully-defined mapping from those fields to our own models/schemas.
- [x]   We have the appropriate restrictions on answers for things like dropdowns. This does _not_ include validation, which is a separate consideration.
- [x]   The Excel template does not use awkward cell constructs for things like yes/no.
- [ ]   Design has approved the Excel file.
- [ ]   Content has approved the Excel file.

**Comment by geekygirlsarah** [comment]
#478 is closed so this is unblocked.

**Comment by tadhg-ohiggins** [comment]
While we deprioritized #479 to focus on Excel ingestion, we do still need to make sure our API has an endpoint that shows the current state of a submission, and that's essentially what this covers, so  it stays in Available for now.

**Comment by pkigongo** [comment]
We will still be generating an Excel file for users to fill out. Are we going to use what Census is using now OR adjust that file. Open Q: How important is this?

**Comment by mogul** [comment]
We made [a tab in the sf-sax.xlsx sheet](https://docs.google.com/spreadsheets/d/1KS26gDZDn0z3uMsq11AtfFrx2DNdH_y1/edit#gid=349821800) that shows the kind of formula shenanigans necessary to make usable, simple, importable data out of the current sheet layout. Where possible, we want to adjust the form such that users are entering data in a form that doesn't require much if any interpretation before we do simple ingestion from a particular cell.

**Comment by melchoyce** [comment]
Just to clarify:
- Engineering will recreate the excel templates to better work with our system
- As they're doing this, Engineering will also update parts of the template UI to streamline the data entry experience
- After this:
  - Content will perform a plain language review on the forms, and potentially run those changes by an SME for accuracy
  - Design will review the form for further usability improvements, and make those as suggestions to Engineering
  - Design will also style the Excel templates to improve readability and match the new FAC.gov branding

Does this sound accurate?

**Comment by timoballard** [comment]
This makes sense to me. So the ball is first in eng's court to fix the technical issues (e.g. replace checkboxes with dropdowns, remove merged cells, etc), without spending much time/attention on how things are laid out and worded. Once that's done, the content/design adjustments shouldn't have much if any affect on the technical side, as we'd just need to update the cell mappings once things are buttoned up.

**Comment by mogul** [comment]
Tim is picking up work on this today.

**Comment by timoballard** [comment]
Working file is stored here: https://docs.google.com/spreadsheets/d/1cVU-vMmtOwxKdndSanW9SIorKA2dfkP2/edit?usp=share_link&ouid=103707674943747480280&rtpof=true&sd=true

**Comment by melchoyce** [comment]
Related: https://github.com/GSA-TTS/FAC/issues/528
