### ISSUE TITLE
Display errors from API calls in frontend

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#484]
Ideally, the frontend should catch almost everything that might cause the API to throw an error through client-side validation. However, there are some server errors that are unavoidable, and the frontend needs to be robust to these errors and provide appropriate guidance to users. In particular, the main types of errors a user is likely to encounter are:

* `401`s if their Login.gov session has expired
* `500`-series errors if the API is unavailable or experiencing some internal error

The frontend needs to be able to recover from these and let the user what to do next

**Comment by jadudm** [comment]
Closing as very old, and the architecture changed substantially since it was written.
