### ISSUE TITLE
Figure out what to do about fiscal year dates on the SF-SAC and whether users will be able to change the year later in the form

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#491]
### Background

This question came up as a result of the [FAQs content audit](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) — see row 18.

**Comment by mogul** [comment]
The form the user is presented to fill out is dependent on the year they've selected. They wouldn't be able to change the year without potentially getting a completely different form. This will impact design; converting the issue to reflect that!
