### ISSUE TITLE
"As a FAC user uploading the Federal Awards Worksheet, I need an error message telling me that the file is in the wrong format, corrupt, or otherwise unreadable."

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#493]
Breakout issue of #450 

### Background

This question came up as a result of the [FAQs content audit](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) — see row 22.

**Comment by pkigongo** [comment]
Need error messages for when user uploads a file, the file has problems.

**Comment by lauraherring** [comment]
Need to collaborate w/Dev on this. How many possible errors are there, what exactly triggers an error, etc. Could dovetail with federal rewards work they're doing.

**Comment by jadudm** [comment]
#1285 actually works on generating corrupt workbooks; once we have the data, and can address whether we handle the errors and pass anything back to the user that makes sense. Linking to #493 from there for reference; closing this ticket.
