### ISSUE TITLE
Figure out how to handle error messages that depend on different worksheets or sections

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#494]
Breakout issue of #450 

### Background

This question came up as a result of the [FAQs content audit](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) — see row 23.

"We probably need an issue around handling errors that depend on , as I think this one does.
This can't be inline (I think) because it needs to check information that's non-local in order to make sure the different counts of federal award findings match."

**Comment by danswick** [comment]
We have cross-validations now!
