### ISSUE TITLE
Turn Census PDF into a web page on fac.gov and edit/simplify content

### ISSUE THREAD

**Issue by erinzstrenio** [GSA-TTS/FAC#495]
### Background

This question came up as a result of the [FAQs content audit](https://docs.google.com/spreadsheets/d/171VkiF0iPEo2xAVAfJDxdt1_B8VM_olhPvn-v5jrwsE/edit#gid=0) — see row 30.

"I cannot upload my audit. It tells me it did not pass the criteria, or was not the correct file type."

The answer for this FAQ currently links to the instructions for [Creating a Compliant PDF Single Audit Report](https://facides.census.gov/docs/create_pdf.pdf), which is a PDF, but we want to turn it into a web page so it's more accessible for users. 

The content can also be edited/simplified down to make it easier to read and scan.

**Comment by pkigongo** [comment]
Previously blocked for Content.
There's a few places where there's an FAQ. 
Open questions: 

- What info is relevant, 
- which info is policy, 
- which info is part of a "How to use website."

**Comment by lauraherring** [comment]
This is creating a new resource page, need to hold until Census team is moved to OROS and won't be a priority until the audit upload is complete as that's a dependency for what info this page will need.

**Comment by jadudm** [comment]
We are now tracking all content work, and have a roadmap for our runway to go-live. Closing as "not planned," but it is being tracked elsewhere.
