### ISSUE TITLE
M1 Enhancement: Add navigation links to pre-SAC step indicator

### ISSUE THREAD

**Issue by petermarks-gsa** [GSA-TTS/FAC#496]
Implementation issue for https://github.com/GSA-TTS/FAC/issues/432

### Background
There doesn't seem to be a clear way back, since I expect "cancel" to literally cancel the entire submission process.

### Design
https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4609%3A21144

### Implementation notes
- When you hover over a previous step, an underline appears under the label.
- On focus, a solid outline appears around the entire step.
- Incomplete steps are not linked.

**Comment by mogul** [comment]
Will revisit during a consistency pass around Milestone 7.
