### ISSUE TITLE
[Placeholder] Helper text for tribal organizations on certification page(s)

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#504]
### Background
For tribal organizations, the audit PDF is not to be publicly available, but data from the SF-SAC is still publicly available, and this needs to be reflected in the logic, but also in the relevant helper text, including on the relevant certification pages. We should show this information only when submissions have selected `Indian Tribe or Tribal Organization` as their organization type.

This is a reminder issue for something we haven’t tackled yet and will probably need to be broken into a set of smaller issues.

**Comment by melchoyce** [comment]
Mocked up here: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A31505&t=ZtSXqJAaDEZOlmbU-4

**Comment by lauraherring** [comment]
May need to confirm the policy implications of this selection.
