### ISSUE TITLE
Explore the possibility of adding helper text to Excel worksheets

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#506]
Breakout issue of #457 

### Background

While reviewing the existing Census FAC FAQ, @erinzstrenio, @tadhg-ohiggins and I audited this question:

> **How do I report a finding not related to an award or CFDA number (e.g. financial statement finding) on the data collection form?**
> "Only findings related to a Federal Award are to be listed on the data collection form. If the finding is not related to an award (i.e. on the financial statements, auditee was late filing in the prior year, etc.), verify the answers to the questions on the Audit Info tab and make sure the finding information is in the audit report that you will be uploading into the system. For additional guidance, please contact the Federal Cognizant or Oversight Agency."

We felt this information would be most helpful inline while someone was filling out the form, ideally in the relevant Excel worksheet, but we were unsure if adding helper text in a worksheet was even feasible. Can we explore this possibility?

### Acceptance Criteria (We'll know we're done when...)

- [ ] We know whether or not helper text can be added to Excel worksheets

**Comment by jadudm** [comment]
Not going to happen anytime soon/might not be necessary.
