### ISSUE TITLE
How do users delete a submitted report?

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#507]
Breakout issue of #457 

### Background

While reviewing the Census FAC FAQ, @erinzstrenio, @tadhg-ohiggins, and I came on this question:

> **How do I delete a report, or a draft?**
> "If you would like to delete a report, please e-mail a request with the report ID and a brief reason, along with your full name, position, and relationship to the report to the Federal Audit Clearinghouse."

We'll need to determine how users will be able to delete reports in our system as well.

We don't know yet from both a technical and policy perspective if anyone will be allowed to delete submitted reports.

### Acceptance Criteria (We'll know we're done when...)

- [ ] We'll know if people will be allowed to delete submitted reports.

I've added a question about the current process to our next Census call.

**Comment by mogul** [comment]
@melchoyce will split this into two issues to cover the policy issue for submitted audits vs deleting your draft pre-submission.

**Comment by melchoyce** [comment]
Created https://github.com/GSA-TTS/FAC/issues/510.

**Comment by danswick** [comment]
Cross-linking to https://github.com/GSA-TTS/FAC/issues/2301 and closing here.
