### ISSUE TITLE
Milestone 2 review

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#509]
In order to ensure we have consistency with the intended design and functionality, the team should review the results of Milestone 2 and do end-to-end testing.

**Acceptance Criteria**

- [ ] We have a list of issues covering any needed remediations identified

**Comment by mogul** [comment]
Delaying this until the eng-side transition to a monorepo/Django app is complete.

**Comment by jadudm** [comment]
Not relevant to current state/process.
