### ISSUE TITLE
How do users delete a draft audit submission?

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#510]
Breakout issue of #457 

### Background

While reviewing the Census FAC FAQ, @erinzstrenio, @tadhg-ohiggins, and I came on this question:

> **How do I delete a report, or a draft?**
> "If you would like to delete a report, please e-mail a request with the report ID and a brief reason, along with your full name, position, and relationship to the report to the Federal Audit Clearinghouse."

We'll need to determine how users will be able to delete drafts in our system as well.

We don't know from a technical and product perspective what is required yet. For example, who's allowed to delete a draft?

### Acceptance Criteria (We'll know we're done when...)

- [ ] We'll know who is allowed to delete drafts.

I've added a question about the current process to our next Census call.

**Comment by mogul** [comment]
@tadhg-ohiggins will check if we have notes on the answer to this question from our last meeting with Census folks.

**Comment by mogul** [comment]
Based on discussion, we'll icebox this for now.

**Comment by tadhg-ohiggins** [comment]
From [2022-10-06 Census call](https://docs.google.com/document/d/1DxuyVOusBIIRrXCaOmmzQp-Q54bthuSirmwR4j4jTbc/edit#heading=h.84wds37cgwsu):

*   Who is currently allowed to delete drafts, using the manual email process?
    *   Mark: There's an internal FAC Manager 2.0 application; that allows deletion of in-progress submissions. Right now only supervisors can delete; there's an approval process.
    -   Mark: User would call/email customer support, goes to National Processing Center, at which point it goes into FAC Manager 2.0.
*   Is this policy?
    *   Unclear. 18F team should probably not prioritize this.

**Comment by jadudm** [comment]
This is will be picked up here

https://github.com/GSA-TTS/FAC/issues/2354

Closing.
