### ISSUE TITLE
Federal Awards submission data structure

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#515]
### Background

We need a data structure for Federal Awards, both the overall section and the individual award entries it contains.

We are using [JSON Schema](https://json-schema.org/) as our definition vocabulary for this, as part of trying to maintain a single source of truth that can be used by the Django backend, the web frontend, and the Excel frontend.

### Acceptance Criteria (We'll know we're done when...)

- [ ] #519
- [ ] #520
- [ ] #521
- [ ] #522
- [ ] #523

**Comment by timoballard** [comment]
Closing after splitting this issue into separate, smaller issues
