### ISSUE TITLE
Extra-schema activities

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#518]
## Acceptance criteria

- [ ]   We have an outline for how to handle data required for UI purposes that may not be strictly part of the schema—such as, potentially, program name, which is displayed to users once they enter valid program numbers but which they’re not supposed to enter directly.

## Tasks
- [ ]   Create the outline for handling related data that’s not necessarily part of the schema.

**Comment by timoballard** [comment]
@tadhg-ohiggins - One option is, for things like `ProgramNumber`, to move away from using `enums` and use `anyOf` instead, which would allow for an accompanying description with each entry:

```
"ProgramNumber": {
  "description": "program number",
  "anyOf": [
    { "const": "10.001", "description": "Program A" },
    { "const": "10.002", "description": "Program B" },
    ...
  ]
},
```

**Comment by timoballard** [comment]
The work outlined here was superseded by #633
