### ISSUE TITLE
Processes for ingesting dynamic validation data

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#522]
## Acceptance Criteria
- [ ] We have dynamic processes for individual Federal Award entries that works for cases where the program numbers, names, etc. change.
- [ ] We have dynamic processes for the overall Federal Award section that works for cases where the program numbers, names, etc. change.

**Comment by tadhg-ohiggins** [comment]
We can develop the processes for inserting some of the dynamic data without having that data, but this may become blocked later if we can't get access the data we're trying to get in #523.

**Comment by tadhg-ohiggins** [comment]
We cannot actually validate against a strict list of program numbers, because that changes too often and has many exceptions, so we're using an approach based on regular expressions instead, making this issue obsolete.
