### ISSUE TITLE
Process for sourcing dynamic validation data

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#523]
## Acceptance Criteria

- [ ] We know what all of the regularly-changing information is.
- [ ] We know how to get the changing information from SAM.gov automatically.
        The current source for the program names and numbers is at https://sam.gov/data-services/Assistance%20Listings/datagov?privacy=Public but the `AssistanceListings_DataGov_PUBLIC_CURRENT.csv` file is behind a license agreement click-through UI.

**Comment by tadhg-ohiggins** [comment]
We cannot actually validate against a strict list of program numbers, because that changes too often and has many exceptions, so we're using an approach based on regular expressions instead, making this issue obsolete.
