### ISSUE TITLE
Update inventory of user stories

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#527]
Breakout issue of <story>

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by mogul** [comment]
The issue didn't get groomed, but this happened... Entries were made on both the [Story Map](https://app.mural.co/t/gsa6/m/gsa6/1647625636085/7825fa5ead63ebb1b65eefab5ea20d24a8ab7c59?wid=0-1648510258303&sender=bretmogilefsky1415) and in linked GitHub issues.
