### ISSUE TITLE
Meta-issue for additional validation rules

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#531]
### Background

There are certain validation rules that we can’t express in JSON Schema, such as amount passed to subrecipients not exceeding the total amount expended for a federal award entry.

Creating a system for a single source of truth for all of these rules that can be used by all of the validation clients is sufficiently complicated as to be out of scope for MVP. For the moment, we will focus on catching those validation errors at the backend only.

This means that after the backend does JSON Schema validation for a submission, it must then apply these additional rules, and supply error messages etc. to the user.

This issues is a meta-issue to hold the individual extra validation rules we want to keep track of.

### Additional validation rules

- [ ]    https://github.com/GSA-TTS/FAC/issues/532

**Comment by danswick** [comment]
@jadudm made a new fancy validation compiler system to do this!
