### ISSUE TITLE
Implement breadcrumb navigation

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#547]
Breakout issue of #280

### Background

Information architecture was refined in https://github.com/GSA-TTS/FAC/issues/371. Breadcrumb navigation was added, and needs to be implemented.

### Acceptance Criteria (We'll know we're done when...)

- [ ] Breadcrumb navigation is implemented

### Tasks

- [ ] Tasks to be broken down by a dev

**Comment by jadudm** [comment]
Closing as not planned.
