### ISSUE TITLE
Draft agenda in prep for auditor/agency user feedback on data collection

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#548]
### Background
We want to be well prepared to attend an upcoming mtg w/ auditors and agency users. We are planning to prep for this meeting in collaboration w/ our Census colleagues. This issue covers drafting an agenda for the mtg w/ Census but also how we'll recommend  framing the convo w/ auditors and agency folks. 

### Acceptance Criteria (We'll know we're done when...)

- [x] We have a document that outlines main points we want to cover 

### Tasks

- [x] Draft agenda

**Comment by pkigongo** [comment]
Presentation Deck: https://docs.google.com/presentation/d/1ghCceTnZ09VX8UcZB8O_cNI7Bj1mlVzp/edit#slide=id.p1

**Comment by melchoyce** [comment]
Video of the prototype demo: https://www.youtube.com/watch?v=ibedbs5Ysqo
