### ISSUE TITLE
Plan for Census DB key -> UEI mapping

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#554]
### Background

Agency users rely on the current Census DB key (which identifies submitting entities) to query reports by specific organizations. The switch to UEI as the identifier for organizations means that agency users won’t have a single identifier for an organization that covers both pre-GSA and post-GSA versions.

In the 2022-10-27 Census call Mark Dixon brought this up as a concern stakeholders expressed for the FAC transition.

To support agency use cases, we need a way to map DB key to UEI.

Some options include:

*   Hiring a vendor to manually do it.
*   Asking Census to make the mapping part of their current process—we know that they currently have a manual step for DB key assignment, and that this year they’re also requesting UEI, so it’s possible it might not be much effort for them to make the connection.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We have either a plan or a set of GitHub issues covering this need.

### Tasks

- [ ]   Ask Census whether or not it would be viable for them to track this mapping as part of their manual process for this year.

**Comment by pkigongo** [comment]
@tadhg-ohiggins  - Is this ticket currently in progress?

**Comment by tadhg-ohiggins** [comment]
It is not.
