### ISSUE TITLE
Start documenting APIs in an easily consumed way

### ISSUE THREAD

**Issue by mogul** [GSA-TTS/FAC#562]
In order to make it easy for stakeholders to keep up with API changes, we want to document our APIs in a form that is amenable to consumption by people and tools.

### Acceptance criteria (We'll know we're done when...)

- [ ] We know where to document, how to document, and have one of our APIs documented using [OpenAPI](https://www.openapis.org/).
  
### Tasks

- [ ] TBD

### Definition of Done

- [ ] Meets acceptance criteria

**Comment by pkigongo** [comment]
Context: To note that we want to have useful specs as early as possible

**Comment by danswick** [comment]
@jadudm started and documented this work: https://github.com/GSA-TTS/FAC-transition-site/tree/main/tools/openapi2uswds. The process can be improved, but we should ticket that separately.
