### ISSUE TITLE
18F delivers training on manual accessibility testing to OROS and vendor teams

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#576]
Breakout issue of <story>

### Background
Ensuring that new vendors who are onboarded adhere to 18F's accessibility standards

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by pkigongo** [comment]
This will probably end up being a cross engineering and design presentation

**Comment by melchoyce** [comment]
Existing documentation: https://accessibility.18f.gov/
