### ISSUE TITLE
Add FAC logo files to Google Drive

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#586]
### Tasks

- [x] FAC logo files (just mark, and mark with type) added to Google Drive in png and svg formats

**Comment by austinhernandez** [comment]
on drive: https://drive.google.com/drive/folders/1NCM9knTx-nwyAPEfb9S8cfWQK-D12KCG?usp=share_link
on figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5341%3A33528

**Comment by melchoyce** [comment]
Looks good! Mind if I move the logo page on Figma to under Resources?
