### ISSUE TITLE
Prioritizing and maintaining a product backlog

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#595]
Breakout issue of

### Background
Based on discussion from 11/17, PO will need prioritization and maintenance of a product backlog in various scenarios so that they can better manage future changes/requests/workflows

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by jadudm** [comment]
Yep. Got one.
