### ISSUE TITLE
Product visioning and roadmapping

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#596]
Breakout issue of 

### Background
Based on discussion from 11/17, PO  (and other relevant FAC/ Census staff) should attend 18F product visioning and roadmapping workshops

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] Roadmapping workshop
- [ ] Product vision roadmap

**Comment by jadudm** [comment]
We do this. Right now, even.
