### ISSUE TITLE
Schedule Date for Mark to be attending Sprint Ceremonies

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#597]
Breakout issue of 

### Background
We need to schedule a date by which Mark is attending all sprint ceremonies w/the 18F team.

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by jadudm** [comment]
And this changed, so closing as not planned.
