### ISSUE TITLE
Ensure all product management documentation is up-to-date and organized

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#601]
### Background

As we're getting ready to onboard new internal and vendor staff, we'll want to update all of our product management documentation.

### Acceptance Criteria (We'll know we're done when...)

- [ ] ...

### Tasks

- [ ] ...
- [ ] Have a peer outside of the FAC review your documentation

**Comment by mogul** [comment]
Subsumed into #803
