### ISSUE TITLE
Ensure all technical documentation is up-to-date and organized

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#602]
### Background

As we're getting ready to onboard new internal and vendor staff, we'll want to update all of our technical documentation.

### Acceptance Criteria (We'll know we're done when...)

- [ ] ...

### Tasks

- [ ] ...
- [ ] Have a peer outside of the FAC review your documentation

**Comment by mogul** [comment]
Subsumed into #807
