### ISSUE TITLE
Deliver acquisition workshop / intro to modular contracting training to Product Owner

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#605]
### Background
This is a transition task focused on helping us achieve this success scenario:

_A senior stakeholder proposes adding a new feature. Before agreeing to develop the new feature, the team evaluates whether it maps to existing goals. The Product Owner prioritizes the issue appropriately, explains the rationale for prioritization to the senior stakeholder who then accepts the Product Owner's decision._

### Acceptance Criteria (We'll know we're done when...)
- [ ] We've delivered training material to PO and any other relevant staff

### Tasks
- [ ] Determine who needs to attend
- [ ] Schedule training
- [ ] Prepare deck
- [ ] Deliver training

**Comment by pkigongo** [comment]
TBD as contractors and Census team members roll on to the engagement.

**Comment by jadudm** [comment]
I have this background, so we're good.
