### ISSUE TITLE
Plan and schedule kick-off with the vendor team

### ISSUE THREAD

**Issue by MelissaBraxton** [GSA-TTS/FAC#606]
### Background
This is issue is a transition task aimed at helping us achieve the following success scenario:

_OROS onboards a new vendor in a way that is efficient and sets the team up for success. Everyone on the team is aware of their role and responsibilities, and the internal and vendor teams collaborate seamlessly._

### Acceptance Criteria (We'll know we're done when...)

- [ ] We've held all the meetings outlined in [the agenda document](https://docs.google.com/document/d/1p3Kg9KJNtaGW58K6zbn2lfvrnu826n0ECg9mWRjIT_U/edit#heading=h.l9fyoqfnoa4f)
- [ ] We've answered questions raised in those meetings to everyone's satisfaction.

```[tasklist]
### Meetings
- [x] Contract kickoff & leadership intro
- [ ] https://github.com/GSA-TTS/FAC/issues/801
- [ ] https://github.com/GSA-TTS/FAC/issues/806
- [ ] https://github.com/GSA-TTS/FAC/issues/804
- [ ] https://github.com/GSA-TTS/FAC/issues/805
- [ ] https://github.com/GSA-TTS/FAC/issues/807
- [ ] https://github.com/GSA-TTS/FAC/issues/802
- [ ] https://github.com/GSA-TTS/FAC/issues/808
- [ ] https://github.com/GSA-TTS/FAC/issues/809
- [ ] https://github.com/GSA-TTS/FAC/issues/803
- [ ] https://github.com/GSA-TTS/FAC/issues/867
```

```[tasklist]
### Onboarding progress
- [ ] #815 
- [ ] #843 
- [ ] #845 
- [ ] #853 
- [ ] #854 
- [ ] #855 
```

**Comment by MelissaBraxton** [comment]
[This template](https://docs.google.com/document/d/1IKpGoZjmpGTO4Eze-GATITJvL-pLPbSl4tVkCGmNLiQ/edit) is a great starting point!

**Comment by thebestsophist** [comment]
Waiting for more team members to join to hold more sessions

**Comment by jadudm** [comment]
Don't know why we haven't closed this; at this point, I'd say we're done. Anything else will be picked up in the natural course of team operations.
