### ISSUE TITLE
Write usage guide for Figma doc

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#609]
### Background

As we're onboarding new designers, we'll need to introduce them to our ongoing [Figma document](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3550%3A16787&t=ZtSXqJAaDEZOlmbU-1).

### Acceptance Criteria (We'll know we're done when...)

- [ ] A new designer can hop into the Figma doc and find instructions on how to use it

### Tasks

- [ ] Write documentation on how to use our Figma doc
- [ ] Peer review

**Comment by melchoyce** [comment]
@MelissaBraxton @austinhernandez Documentation ready for peer review: https://docs.google.com/document/d/1QCSs_oMHrTUAIItru_nLIGM9p6AFx9T6S4GlXtrwfkM/edit?usp=sharing

You can also see it in context in Figma: https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5244%3A31293&t=ZtSXqJAaDEZOlmbU-4

**Comment by melchoyce** [comment]
Tagging in @Leighdiddy for peer review as well!

**Comment by austinhernandez** [comment]
looks good to me!

**Comment by melchoyce** [comment]
Thanks!
