### ISSUE TITLE
Log trail for email address changes

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#612]
### Background

The login.gov authentication flow includes a step where we get the user’s email addresses from login.gov in order to associate a user with `Access` objects to grant them access to in-progress audits submissions.

We associate the login.gov user ID, _not the email address_, with `Access` objects. We store their primary email address in our `User` model, but we update this to reflect their login.gov primary email address whenever they log in.

This is appropriate since login.gov is the canonical source of our user info, and means that users can change their primary email addresses and still retain access to submissions. However, this leads to the following potential edge case:

*   User is granted access to a submission via the email address `a@a.com`.
*   User logs in with login.gov.
*   User changes their login.gov email address to `b@b.gov`.
*   User logs in again.

At this point, even though the `Access` object will show that access should be granted to `a@a.com`, a user with the email address `b@b.com` will have that access. This is not a bug, since this is what we want to happen; the issue is that there’s no log trail showing how `b@b.com` came to have access.

### Acceptance Criteria (We'll know we're done when...)

- [ ]   We have a way to log email address changes such that the above scenario has a log trail.

### Tasks

(It’s not clear yet what the tasks required to accomplish this are.)

**Comment by tadhg-ohiggins** [comment]
2023-02-21: the first decision to be made here is whether or not we want to worry about this at all for MVP, or decide that it's an edge case that, if it arises at all, can be handled via customer support.

If we decide this is a post-MVP enhancement, we should mark it as such.

If we decide we need to handle it for MVP, we would then keep this issue going and determine what our preferred approach to handling this is.

**Comment by JeanMarie-TTS** [comment]
@tadhg-ohiggins Why do we store the email address? Where and how is it actually used?

**Comment by tadhg-ohiggins** [comment]
@JeanMarie-TTS users grant access to other users (for example, to specify that Person X is the auditor who can certify the submission) by entering email addresses. We must store those in order to check whether someone has access to a particular submission.

**Comment by JeanMarie-TTS** [comment]
@tadhg-ohiggins , can the user who grants access change whom they've given access to? If so, will this capability be a solution to the problem raised in this issue?

**Comment by JeanMarie-TTS** [comment]
Yes, it does appear so.  Should these issues be moved to the backlog, or at least to triage?

**Comment by JeanMarie-TTS** [comment]
We will not implament an audit trail.
