### ISSUE TITLE
Convert Census FAC informational PDFs to static pages

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#619]
### Background

The Census FAC has a ton of PDFs that would be great to convert into pages on the site. This would likely require copy updates, as well as someone to manually migrate the content over into a django page.

### Acceptance Criteria (We'll know we're done when...)

- [ ] We've moved all relevant PDFs to the new FAC site, as pages
- [ ] The copy is up-to-date with the new FAC site

```[tasklist]
Related Issues:
- [ ] https://github.com/GSA-TTS/FAC/issues/619
- [ ] https://github.com/GSA-TTS/FAC/issues/495
- [ ] https://github.com/GSA-TTS/FAC/issues/467
```

- [ ] Locate all PDFs (started some of this in the content audit in #457) 
- [ ] Identify which PDFs are still relevant, which need updating, and which we can discard
- [ ] Identify if any of the PDF information lives on a separate website already (like OMB guidance)
- [ ] Update content
- [ ] Copy content over into new site pages
- [ ] There's probably something here about figuring out the URL structure for these one-off pages

**Comment by pkigongo** [comment]
Related Issues:
#619  
#495 
#467

**Comment by jadudm** [comment]
We are now tracking all content work, and have a roadmap for our runway to go-live. Closing as "not planned," but it is being tracked elsewhere.
