### ISSUE TITLE
Decide whether Pa11y is required along with Lighthouse

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#622]
### Background

As part of our app unification we need to move our Pa11y setup to run in Docker in our new configuration.

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] Write an ADR
- [ ]

**Comment by pkigongo** [comment]
Since we have Lighthouse, not sure if we need Pa11y

**Comment by jadudm** [comment]
Per conversation, we're going to keep both (as they are not true sub/supersets of each other for coverage), and document that in an ADR. Assigning to me.

**Comment by jadudm** [comment]
Again, I don't know if this is ADR-level. We decided to keep two different checkers, because they cover most of the same things, but each catch slightly different things in practice. If we decide we need an ADR, we can come back.
