### ISSUE TITLE
Content refinements to the report home/audit start page

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#636]
Breakout issue of #536.

The [report home page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5281%3A30976&t=cUukfvlHay8NGXsw-4) needs a content review.

### Acceptance criteria (We'll know we're done when...)

- [x] The content is updated and ready to hand off to Engineering
  
### Tasks

- [x] Review content on the report home page
- [x] Peer review

**Comment by lauraherring** [comment]
Review copy in Figma and refine as needed.

**Comment by melchoyce** [comment]
Screenshots:

![image](https://user-images.githubusercontent.com/2846578/220398457-4e173d27-998e-459b-853d-97693c89546b.png)
![image](https://user-images.githubusercontent.com/2846578/220398513-272a4a72-b135-4d70-af88-d863b68b3bfd.png)

**Comment by lauraherring** [comment]
@Leighdiddy here's the new copy for this page. Let me know if you have any questions.


Track your progress to complete a single audit submission. Some steps are locked after completion and cannot be edited once they are finalized. Once steps are unlocked, they may be completed in any order.

Create a single audit submission
Begin your single audit submission by entering basic information about the auditee organization.

Complete form SF-SAC
Provide general information on the auditee and auditor, financial statements for the auditee entity, and information on the entity's federal program compliance.

Upload the audit report PDF
Upload the single audit report package, or audit report. This should be a single, unlocked, and machine-readable PDF.

Auditee certification
The certifying auditee must attest and sign the single audit report before submission. This step is locked until after the SF-SAC and single audit report have been completed and uploaded in the previous steps.

Auditor certification
The certifying auditor must attest and sign the single audit report before submission. This step is locked until after the SF-SAC and single audit report have been completed and uploaded in the previous steps.

Submit to the FAC for processing
The certifying auditee must submit the final single audit submission to complete the audit process. Once this has been submitted, it cannot be undone.

**Comment by jadudm** [comment]
@Leighdiddy , @lauraherring , did we pick these up in the Figma? Or, did we change things, and this ticket fell behind?

If this is the current best version of the text, ping here, and we can make sure the Figma is up to date, and then I can ask an engineering colleague to make some changes.

However, if we like what is in Figma, and the app, we can close this ticket.

**Comment by Leighdiddy** [comment]
@jadudm @lauraherring The updated copy that Laura shared (in this thread) on March 9th was implemented in Figma, and can be implemented on the site as well 👍

**Comment by jadudm** [comment]
We're now picking this up in multiple places and on an ongoing basis. Closing as done, as it is now in iteration.
