### ISSUE TITLE
Review Secondary Auditors page for content updates

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#637]
Breakout issue of #571.

### Background

The [Secondary Auditors](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5200%3A30488&t=cUukfvlHay8NGXsw-4) page has changed since we last worked on the SF-SAC, and the new content needs to be edited.

### Acceptance criteria (We'll know we're done when...)

- [ ] The content is updated and ready to hand off to Engineering
  
### Tasks

- [ ] Review and edit content on the Secondary Auditors page
- [ ] Peer review

**Comment by lauraherring** [comment]
Just needs a copy review and refinement as necessary.

**Comment by melchoyce** [comment]
Screenshot: 

![image](https://user-images.githubusercontent.com/2846578/220399250-25696dcf-aaea-44ce-8596-390bb6968a39.png)

**Comment by jadudm** [comment]
Done w/ other upload pages.
