### ISSUE TITLE
Implement My Audit Submissions design updates

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#654]
Updated version of #343 and #424.

Related: #537 

## Background

Since the initial implementation of the My Audit Submissions design, we've done two rounds of usability testing that have led to both content and design updates. We'll want to update the live website with the updated design.

![image](https://user-images.githubusercontent.com/23194720/206579010-eed70312-16e0-4c5a-9a3e-139c208d4b24.png)

## Acceptance Criteria (We'll know we're done when...)

- [x] The My Audit Submissions page has been updated with the most recent design

## Tasks

- [ ] TBD

**Comment by JeanMarie-TTS** [comment]
@melchoyce ,  Should we not be designing this page for a time when Census FAC will be decommissioned? Should we be spending cycles to make sure that we link to relevant page on Census FAC?

**Comment by melchoyce** [comment]
Hey! I was under the impression that we'd get the submission flow launched before the data dissemination flow, which is why this page includes a link to https://facdissem.census.gov/—has that plan changed?

**Comment by mogul** [comment]
To demo: Link on the date rather than report ID, column order
