### ISSUE TITLE
ADR for storing SingleAuditChecklist submission data as JSON

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#669]
We need to write an ADR that documents our decision to store SingleAuditChecklist submission data in the database as JSON. This ADR should discuss the need to accommodate schema changes over time while maintaining the ability to accept submissions for prior schema versions, the desire for a single source of truth for submission validation, and the decision to split each of the top-level submissions sections into their own database column (`JSONField`), each with a corresponding JSON Schema document.

**Comment by pkigongo** [comment]
Waiting on Engineering review
