### ISSUE TITLE
Add pylint to linters

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#704]
We should probably use `pylint` in addition to `flake8`.

### Background
Just using `flake8` seems to let some unwanted things through.

### Acceptance Criteria (We'll know we're done when...)

- [ ] `pylint` is part of our linting process.

**Comment by stucka** [comment]
Linting with `black` changes just three files in the latest snapshot. 95%+ percent of the changes are moving single quotes into double-quotes.

I can submit a pull request but y'all are looking for stuff like local tests and I don't even know how these are used.

tools\generate-sqlite-files\main.py
tools\workbook-generator\data\ay22\models.py
tools\workbook-generator\main.py

**Comment by stucka** [comment]
Ah, just found the bug. Will flag that separately.

**Comment by jadudm** [comment]
Hi Mike,

Good catch. However, that code is going to get pruned in favor of workbook generation code that is more fully integrated into the system, and can be used for end-to-end testing.

**Comment by tadhg-ohiggins** [comment]
At this point it's not worth adding `pylint` to our process; we can revisit this in future if we start seeing issues that we think it would have caught. Closing.
