### ISSUE TITLE
Add HTML linter

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#715]
Breakout issue of deployment pipeline

### Background
Migrating tooling from the previous front end.

### Acceptance Criteria (We'll know we're done when...)

- [ ]  Add a linter to our Github Actions tests
- [ ]  Add documentation on how to run linter locally

**Comment by tadhg-ohiggins** [comment]
Consider using https://github.com/Riverside-Healthcare/djlint for this
