### ISSUE TITLE
Implement My Audit Submissions "Terms & Conditions" Modal

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#738]
The basic implementation of the "My Audit Submissions" page is covered in #343. This ticket breaks out an enhancement to that page. The [mockups](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=3503%3A16158&t=z5AonUjxNDcCc4hi-4) include a checkbox for the user to indicate that they agree to the site's T&C:

![Image](https://user-images.githubusercontent.com/6290/213494022-cc26ef7b-1bf3-4f6a-9764-a40b78f41087.png)

The text of the T&C is contained in a modal:
![Image](https://user-images.githubusercontent.com/6290/213494377-ee1d729f-c7dc-4ac9-be6b-1b8de662d090.png)

In the current implementation of the page, the submit button is disabled until the user checks the box, and the link/button to surface the terms & conditions is not implemented.

**Comment by heymatthenry** [comment]
@melchoyce Perfect. Thank you so much!

**Comment by pkigongo** [comment]
@jasnakai - Can you confirm if this is done?

**Comment by jasnakai** [comment]
All done!
