### ISSUE TITLE
[spike:5d] Use Arelle to convert XLSX to XBRL

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#755]
### Background

We need to better understand the effort required to integrate the [arelle python library](https://arelle.org/arelle/documentation/api/) into the FAC backend for the purposes of converting between XLSX and XBRL.

We want to spend no more than five days of developer time on this task.

### Acceptance Criteria (We'll know we're done when...)
- [ ] We've setup an endpoint that: 
    - accepts an XLSX file upload, then 
    - uses arelle to convert the XLSX to XBRL, then
    - uses arelle to convert the XBRL back into XLSX, then
    - returns the generated XLSX back to the caller as a file download

**Comment by timoballard** [comment]
[Writeup on findings](https://docs.google.com/document/d/1quaHzbHE85ZQhAWG-3XPbFJQsrlohGc5iMy6GwptLvk/edit#)

**Comment by joffemd** [comment]
It is not necessary to use Arelle to convert simple XBRL documents and using it for this purpose adds complexity. As I understand the requirement, you wish to process Schedules of Expenditures of Federal Awards (SEFAs) via XBRL or some other format based that meets GREAT Act requirements. The best practice in my opinion would be for the Clearinghouse to accept SEFAs in Inline XBRL format (HTML with XRBL tags) and then convert them to a format that is directly compatible with a relational database, such as CSV.  To help with that, I am attaching an example of an Inline HTML SEFA, conversion code, and sample csv output. I welcome the opportunity to discuss and/or iterate this code with you.


[FAC_Issue_755_External.zip](https://github.com/GSA-TTS/FAC/files/10855792/FAC_Issue_755_External.zip)

**Comment by mogul** [comment]
Thanks @joffemd! Following this spike we decided to hold off on adding XBRL import/export until after we're able to accept submissions in the Excel-based form that users of the Census FAC system are used to. We'll revisit XBRL after the GRIP taxonomy and QSMO expectations are both final and aligned.
