### ISSUE TITLE
Review OMB clearance paperwork

### ISSUE THREAD

**Issue by melchoyce** [GSA-TTS/FAC#786]
### Background

From Shelley:

> Attached please find the updated OMB PRA clearance paperwork for part 2 of our clearance request, as referenced in our meeting this afternoon.
> 
> Normally this is not something we would ask the technical team to review, but I think it's important this year because the new system is not something that the existing subject matter team knows enough about. 
> 
> The bold language in "Supporting Statement A_B" represents the OMB questions for agencies seeking data collection clearance, and the un-bolded language represents our responses that we'd like you to review. If it helps, the subject matter team made a number of notes in the margin to draw GSA's attention to specific statements.
> 
> The other document I've attached is the updated draft 2023 form SF-SAC. We want to ensure the language of the questions in the new GSA system match the question on this form exactly. (I'm not sure which form you were given to design your system. The good news is the questions have not changed really since 2019, but it does show a couple of items relating to the ACEE submissions including the type of audit report and the certification statements for ACEE - it might be good to just use this as a reference doc to double-check language?) The form instructions in the back of this document should also be reviewed because there are occasional references to edit checks within the system, so again we want to make sure those are all truthful statements. (Example: pg 2 of the instructions says "Once a form has been started within the FAC website, the four digit year of the fiscal period cannot be changed." This reflects an edit the Census system had - want to confirm GSA is building in all the same edits, or that we strip out those statements in the instructions. Please make notes in that document so I know what to update. THANK YOU!
> 
> Again, please take a look as you have time - I would say we have a few weeks to review this, if you could let me have your combined feedback by mid-February? Feb 24 latest? Please forward to others as needed! 

The files to review are located in our Drive: Updated link: https://drive.google.com/drive/folders/1fJKGdD-oZEnP6andIHg6bFyP8FohvHBK ~https://drive.google.com/drive/folders/1AU3Qq_c1ZO55ORImo2zjVr43340VFyKo~

### Acceptance Criteria (We'll know we're done when...)

- [x] @mogul has reviewed
- [ ] @Leighdiddy has reviewed
- [ ] @jadudm has reviewed/thumbs upped
- [x] @thebestsophist has reviewed/thumbs upped
- [ ] Any updates/comments have been sent to Shelley

**Comment by tadhg-ohiggins** [comment]
After discussion with @jadudm , he and I are swapping on this issue; I'm still available for questions if necessary.

**Comment by Leighdiddy** [comment]
Met with Jadud, Cordelia and Gwynne to review. Jadud will be adding notes and handing over to Gwynne today.

**Comment by jadudm** [comment]
CY and I have reviewed this with SG. Closing as done.
