### ISSUE TITLE
[DRAFT] Create Excel upload view

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#787]
Implement USWDS upload component. Design [here](https://www.figma.com/file/8REinLFKSMj7pwQ7JIEHGW/FAC-Sprint-11-prototype?node-id=14%3A5295)

**Comment by pkigongo** [comment]
Relevant work on #462

**Comment by jadudm** [comment]
We're uploading XLSX documents, so I'm going to close this as done.
