### ISSUE TITLE
Modify "My Submissions" spec to work in Django app

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#790]
The bulk of the existing specs from the FAC-Frontend app were ported over in #789. However, as noted in that issue, the implementation of this page changed enough from the old app to the new (the table was populated via JS in the FAC-Frontend app but is now a Django view, with data coming directly from the DB) that the testing/mocking strategy will need to be revised.

**Comment by heymatthenry** [comment]
This is currently blocked, arguably by #709, but if not that then by a close cousin of it.

**Comment by tadhg-ohiggins** [comment]
Closed since we're now using a vanilla USWDS table widget, and we don't need to have our own custom tests for its functionality.
