### ISSUE TITLE
How do we want to work together

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#803]
Time: TBD—One of the last meetings
Led by: @mogul  or @jadudm 
Attendees: Everyone

```[tasklist]
- [x] Ensure all product management documentation is up-to-date and organized
- [ ] [Make slides](https://docs.google.com/presentation/d/1D3WrIHXZn0m84pd4wLbhFINR-fMnfRxhSaVhC99pPzY/edit#slide=id.p)
- [x] Present (and record!)
- [ ] Make recording available
```

**Comment by mogul** [comment]
We're meeting Monday to review the documented DoD vs the current board layout and our how things work in practice, and potentially making changes.

**Comment by pkigongo** [comment]
Waiting for team members to join.

**Comment by mogul** [comment]
@tadhg-ohiggins is right, I shouldn't have moved this to the Done column yet... Instead I'll do that once the recording and transcript of the meeting we just had lands in Google Drive.

**Comment by mogul** [comment]
A recording and transcript are now [available in the FAC Google Drive](https://drive.google.com/drive/folders/1G4WrzBRrNT1TXOxndh1LcP8lnAyWUqlB).
