### ISSUE TITLE
Design—research findings

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#804]
Time: Friday—10ET
Led by: @Leighdiddy + 18F designers
Attendees: @lauraherring @melchoyce @austinhernandez @thebestsophist 

[Slides](https://docs.google.com/presentation/d/1dkAnZ7SXP-XW4ybE4Q9es_V73ZZSqbHfbBoU7i4qASM/edit#slide=id.g1f12f0f0608_0_26)

**Comment by pkigongo** [comment]
In search of the recording, might be done

**Comment by Leighdiddy** [comment]
@thebestsophist has the recording!
