### ISSUE TITLE
Design—Prototype interface walkthrough

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#805]
Time: Monday, Feb 27, 11ET/8PT
Led by: @austinhernandez 
Attendees: Designers

**Comment by melchoyce** [comment]
Moved to Thursday, March 2 at 11ET/8PT

**Comment by melchoyce** [comment]
Note: Let's put the prototype walkthrough recording in the wiki.

**Comment by melchoyce** [comment]
Because onboarding is rolling, we're going to record a prototype walkthrough we can repeat in the future.

**Comment by melchoyce** [comment]
The recording is now in our Drive: https://drive.google.com/file/d/1l8AQTa9y5Wg-fvFUwHoEYCX166ty1G-_/view?usp=share_link
