### ISSUE TITLE
[Schedule pending] Technical constraints & architectural overview

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#807]
Time: 3/31 at 2pm ET/11am PT
Led by: @jadudm  @tadhg-ohiggins 
Attendees: Engineers + @thebestsophist 

```[tasklist]
- [x] Ensure all technical documentation is up-to-date and organized
- [x] Make summary slides
- [x] Present (and record)
- [x] Make recording available
```

**Comment by mogul** [comment]
The recording and transcript are now [available in Google Drive](https://drive.google.com/drive/folders/1G4WrzBRrNT1TXOxndh1LcP8lnAyWUqlB) for those with access.
