### ISSUE TITLE
[schedule pending] QASP & Deliverables

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#809]
Time: 3/27 at 12pm ET/9am PT
Led by: @mogul 
Attendees: @JeanMarie-TTS @tadhg-ohiggins @LindsayYoung 

[Slides](https://docs.google.com/presentation/d/12JmU_a1jeed_EvVi366RZxoAcQKaOf1R1U9H6Zu01ms/edit#slide=id.g1f12f0f0608_0_26)

**Comment by mogul** [comment]
Pretty sure I'm ready... Check the slides and let me know!

**Comment by pkigongo** [comment]
Waiting for additional team members to onboard.

**Comment by mogul** [comment]
Presented, [transcript and recording are available in the shared Google Drive](https://drive.google.com/drive/folders/1G4WrzBRrNT1TXOxndh1LcP8lnAyWUqlB)
