### ISSUE TITLE
Reorganize team google drive

### ISSUE THREAD

**Issue by thebestsophist** [GSA-TTS/FAC#812]
Goals:
- Reorganizing team drive structure to make everything more findable
- Move all documents from historic 10x folders into the OROS-owned drive

**Comment by lauraherring** [comment]
Status Update: Phase 4 Drive is empty, inventory of Phase 3 10x Drive is complete. Main FAC drive is in good shape, time to move on to FAC (internal only).

**Comment by jadudm** [comment]
I've moved this to `Done` on the grounds that it sounds like we're now in the "continuous gardening" phase. Move it around the board as you see fit, though, if you disagree.
