### ISSUE TITLE
Remove Trestle

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#813]
### Background
We aren't using Trestle to create our SSPP and one of its libraries is vulnerable.

https://github.com/GSA-TTS/FAC/pull/793#issuecomment-1439017153

### Acceptance Criteria (We'll know we're done when...)
- [x] Write ADR removing Trestle
- [x] Remove `/compliance` folder from repo
- [x] Close https://github.com/GSA-TTS/FAC/pull/824
- [x] close https://github.com/GSA-TTS/FAC/pull/793

**Comment by mogul** [comment]
This is done now, right?

**Comment by tadhg-ohiggins** [comment]
@mogul closing https://github.com/GSA-TTS/FAC/pull/824 will cross off the last outstanding item for this issue.
