### ISSUE TITLE
Document show-stopper controls

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#828]
Breakout issue of #725 

### Background
Document the plan to address the  show stopper controls listed in the Lightweight SSPP document

### Acceptance Criteria (We'll know we're done when...)

- [Have the plan documented in the document ] 
- [Review the plan with the engibeering team ] 
- [Review the plan with the Security team]

### Tasks

- [ ] 
- [ ]

**Comment by ChrisB-16** [comment]
FACH SSPP updates are in progress , tracking technical implementation details from Login.gov and submitted request to gain access to Cloud. gov

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 , we need to take a closer look at access to systems outside our cloud.gov boundary, There are two in the architecture diagram - SAM,gov and SMTP.

**Comment by ChrisB-16** [comment]
Currently, the FAC SSPP showstopper controls are under preliminary review & formatting checks. The feedback from ISSO will be addressed prior to FAC SSPP draft submission.

**Comment by ChrisB-16** [comment]
As of 04/14/23 the FAC showstopper controls preliminary review with ISSO passed, all revision updates was done. Ticket can be closed.
