### ISSUE TITLE
Collect & organize Excel template files

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#833]
## Background
The Excel submission workflow involves the uploaded of several distinct worksheets. We received [many Excel templates](https://drive.google.com/drive/folders/1tyHSXxIDk6XPIJbSilRJoVCxTWcIH2O1) from Census, but it is not clear which versions are current, and how the various worksheets map onto the different upload points [on the frontend](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954%3A22829&t=5P96X3l0KZA6PhqK-0)

We should collect the current version of each worksheet, store them in a single location in our team Drive, and name the files so that there is a clear mapping between the worksheets and the frontend upload points.

**Comment by pkigongo** [comment]
Leigh and Mel to review before Mel offboards.

**Comment by melchoyce** [comment]
| Page  | Mockup | Spreadsheet |
| ------------- | ------------- | ------------- |
| **General information** | ![image](https://user-images.githubusercontent.com/2846578/222538725-64b925bc-a5b0-4138-9f5d-ba4fddec7c00.png)  | No spreadsheet |
| **Federal awards** | ![image](https://user-images.githubusercontent.com/2846578/222537746-efb651e8-2e30-45d7-adef-6c2105ed57b4.png) | LINK TO SPREADSHEET |
| **Notes to SEFA**  | ![image](https://user-images.githubusercontent.com/2846578/222538297-af9df0c5-d030-4eee-abb3-7df75d324f1c.png)  | No spreadsheet |
| **Audit Information**  | ![image](https://user-images.githubusercontent.com/2846578/222538534-2e2621ec-7769-4c21-a563-18ddb3a0411c.png) | No spreadsheet |
| **Audit findings**  | ![image](https://user-images.githubusercontent.com/2846578/222538886-a9a31e54-10a1-41d3-90d8-04bd1822e327.png)  | LINK TO SPREADSHEET |
| **Audit findings text**  | ![image](https://user-images.githubusercontent.com/2846578/222538917-177cd306-4b18-416d-8ead-a5abdc5c78c4.png)  | LINK TO SPREADSHEET |
| **Corrective Action Plan (CAP)**  | ![image](https://user-images.githubusercontent.com/2846578/222538954-dc68067d-5864-4240-a5c8-72ac09687c2e.png)  | Content Cell  |
| **Additional EINs/DUNs**  | ![image](https://user-images.githubusercontent.com/2846578/222538993-0d591a4a-e1cc-450c-b244-9f15bb076520.png)  | LINK TO SPREADSHEET |
| **Secondary auditors**  | ![image](https://user-images.githubusercontent.com/2846578/222539030-1f795df6-d9bb-40f5-b5d7-13838f9f269b.png)  | We need to create this spreadsheet  |

Getting us started, we can edit this comment with links.

**Comment by timoballard** [comment]
FYSA I'm currently working off of this sheet for federal awards: https://docs.google.com/spreadsheets/d/1utAESt6xCQRWGBjO36H5rdF3BN40EI0v/edit#gid=1202734399

**Comment by thebestsophist** [comment]
Leigh and I are realizing that the Figma screens assume that there will be excel worksheets for things that are manually entered in the Census FAC so we're gonna go through and check on those.

**Comment by jadudm** [comment]
We now have templates for many of these in Jsonnet. Closing as done.
