### ISSUE TITLE
Create Privacy Impact Assessment

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#834]
Breakout issue of <725>

### Background
A PIA form has to be populated in archer in order to obtain a LATO

### Acceptance Criteria (We'll know we're done when...)

- [Approved by the IT Sec team]

### Tasks

- [Populate the form ] 
- [Have it reviewed ]

**Comment by ChrisB-16** [comment]
FACH PIA draft is in review with Temi -ISSO, however we have few minor questions for @mogul and @jadudm ,

- Do we know who will be the Business Point of Contact?
- What legal authority and/or agreements allow GSA to collect, maintain, use, or disseminate the information? Do you have the a contract # for FACH project?
-  Has an information collection request (ICR) been submitted to or  approved by the Office of Management and Budget (OMB)?  
- Do you have a records retention template and What is the records retention schedule for the information system(s)? Explain how long and for what reason the information is kept.      

Thanks,

**Comment by JeanMarie-TTS** [comment]
@jadudm , @mogul Tagging you to see if you have answers to Chris' questions.

**Comment by mogul** [comment]
I'm going to point to [this Slack thread](https://gsa-tts.slack.com/archives/C1L58R804/p1677691756775489) which may have some of the answers you're looking for, but otherwise defer to @jadudm.

**Comment by ChrisB-16** [comment]
2nd round of feedback came from ISSO, reviewing comments, documentation review ,& drafting updates to PIA.

**Comment by JeanMarie-TTS** [comment]
@ChrisB-16 and I met with Jacqlyn Henrt, who said that a PIA is not required. This is because we only collect professional contact information.
