### ISSUE TITLE
Swagger pipeline

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#861]
### Background
We are going to provide a Swagger interface to document and explore our postgrest API

Acceptance Criteria (We'll know we're done when...)
- [ ]  Swagger is deployed to all environments as part of our pipeline
- [x]  It follows our branching strategy
- [ ]  Update architecture diagram

Tasks
- [ ]  Set up pipeline dev
- [ ]  Set up pipeline staging
- [ ]  Set up pipeline production

**Comment by jadudm** [comment]
Archiving as this work has been moved into the Terraform process, and Lindsay has rolled off. However, we have been working with it for pilot purposes, and any future work on the Swagger pipeline can be picked up in new ticket.s
