### ISSUE TITLE
Documentation Tour

### ISSUE THREAD

**Issue by pkigongo** [GSA-TTS/FAC#867]
Time: April 3rd, 2pm ET / 11am PT
Led by: @lauraherring 
Attendees: Everyone

**Comment by mogul** [comment]
@lauraherring gentle reminder here to [make the recording and transcript available in Google Drive](https://drive.google.com/drive/folders/1G4WrzBRrNT1TXOxndh1LcP8lnAyWUqlB) when you have them so that we can close this one and move it to `Done`.

**Comment by mogul** [comment]
Sounds like @jadudm already did that!

**Comment by lauraherring** [comment]
Thank you, both!

**Comment by mogul** [comment]
Actualy just double-checking... It sounds like maybe Matt added Patrick back to the `fac-team` Google Group so that he could move the recordings, not that Matt did it himself. @pkigongo can you confirm when they're moved?
