### ISSUE TITLE
Consider parallelizing unit tests for speed/optmiziation

### ISSUE THREAD

**Issue by geekygirlsarah** [GSA-TTS/FAC#887]
### Background

Running the Django unit tests (as `python manage.py test`) runs them sequentially, one-by-one. You can run them in parallel, one per CPU, by doing `python manage.py test --parallel`. It will spin up one database per thread, then split tests up across all the processors.

This doesn't work on our repo because some tests involve creating files that other tests may expect to be there but may not be. The unit tests aren't all properly independent. Unfortunately, I don't have the time to really dig in before I leave the team.

This is an optional/tech debt ticket that would suggest using the `setUp` functions on testing classes to modify any environments needed for all tests of a class so that way they can be instantiated independently for each test. If a test requires something to be run sequentially, you can add the `SerializeMixin` to the class to enforce it running that way.

While working on this, you can `pip install tblib` to enable tracebacks while running parallel tests, since Django can't really give you errors on a bunch of tests running all at once. 

When this is done, `.github/workflows/test.yml` can change the test suite runner to add `--parallel` to the `docker-compose run web bash -c 'coverage run --source="." manage.py test --parallel &&` line.

References: 
* https://docs.djangoproject.com/en/4.2/ref/django-admin/#cmdoption-test-parallel
* https://docs.djangoproject.com/en/4.2/topics/testing/advanced/#topics-testing-enforce-run-sequentially

### Acceptance Criteria (We'll know we're done when...)

- [ ] 
- [ ] 

### Tasks

- [ ] 
- [ ]

**Comment by jadudm** [comment]
Done elsewhere.
