### ISSUE TITLE
Markdown spike

### ISSUE THREAD

**Issue by JeanMarie-TTS** [GSA-TTS/FAC#891]
Breakout issue of <story>

### Background
We have a fair anoubt of static text content in the FAC web application. Currently such content is stored in django's html template files. This makes it hard for content editors to update the content without the active involvement of the engineers.
This spike is to explore a way of separting static content into markdown files. Content editors would be able to edit the markdown files in Github without the need for engineering help. They will then be able to push their changes to the dev environment on cloud,gov by creating a PR for these changes.

### Acceptance Criteria (We'll know we're done when...)

- [ Modify home page to use markdown content from a separate file] 
- [Modify MySubmissions page to use markdown content from a separate file ] 

### Tasks

- [ Identify and test a suitable python package] 
- [ Nake the necessary changes on the selected pages]
- [ Document the process that content devlopers should follow]

**Comment by JeanMarie-TTS** [comment]
Installed django-markup2,
Changed Home,html to include Hmoe.md.
Need to resolve issues with CSS cascading correctly to the <h1> element.

**Comment by mogul** [comment]
Would this option, if it works out, obviate #709, which added some content-management functionality? Or is it a complement to that?

**Comment by JeanMarie-TTS** [comment]
This is a first step to that. This spike is to make sure that we can support MD, but requires content developers to edit a file in GH and follow our CI process. #709 will allow authors to do the editing in our web app, and we will also need to address the CI issue as we will then have to move database content across environments.
I think the current spike should be good enough for the MVP.

**Comment by JeanMarie-TTS** [comment]
Workaround for the home page `h1` not showing up is to remove the usa-hero class in the section.
Implemented  md files for MySubmissions page including the Terms and Consitions modal.

**Comment by JeanMarie-TTS** [comment]
Copying comments in Slack by @heymatthenry 

The biggest thing to note is just that if we go this route we need to be very careful that we're preserving existing styles and functionality. For instance, on the homepage (and on the submissions page), [this link](https://github.com/GSA-TTS/FAC/compare/main...jm/markdown_spike#diff-3f50056bfb2e68f71bbc2184204a2730faf7cf9df992a7d951306cc996a36e4eL16-L18) is replaced with a [simple attribute-less anchor in the markdown](https://github.com/GSA-TTS/FAC/compare/main...jm/markdown_spike#diff-3791897c56726db77f703830d5b526b4f132f4cd4637d3c709ae9faa4b30c197R8), which breaks the modal that is supposed to pop up to let the user know they're going to the old FAC site. In order to keep the required aria and data attributes, the markdown author would need to write verbatim HTML that includes those attributes rather than a markdown link. This is just one example, and a dramatic one since it involves JS, but it's also true of anywhere that content needs to include, for instance, a USWDS class to match the design. So for instance, if a paragraph needed class="usa-prose", the content author/editor would need to write a literal HTML <p class="usa-prose">  rather than a simple markdown paragraph (i.e. text surrounded by line breaks). You can see this on the homepage as well where a class="intro-text" which does in fact have styling associated with it, [doesn't make it into the markdown](https://github.com/GSA-TTS/FAC/compare/main...jm/markdown_spike#diff-3f50056bfb2e68f71bbc2184204a2730faf7cf9df992a7d951306cc996a36e4eL9-L12).
The workaround here is just to make the slots in the template very granular. So to fix the issues with the homepage described above, rather than replacing the whole hero section with one big block of markdown, we'd need to have separate template slots (and so separate markdown files) for, at the very least: 1) the text of the link that needs the aria/data attributes; 2) the intro paragraph; 3) the h1 ; and 4) text between the intro and the fancy link with the data & aria attributes. Without that granularity, again, that markup would need to be recreated verbatim inside the markdown files.
So the two horns of the dilemma are: more markdown files than is likely practicable for a particular page vs. requiring content authors/editors to write verbatim HTML that doesn't break whatever styles & functionality is required for that part of a page.
A way around this might be: rather than just using markdown, using one YAML file per page, where each property in the YAML corresponds to a template slot. This is basically how the old eleventy app worked. I don't know if the markdown parser we're trying out in this spike supports that, but it seems like the best way around the dilemma just described (other than reverting to the old plan of using Django as a CMS).

Anyway I hope this is helpful, and again, if it's premature please disregard. I just wanted to get it down since we didn't get a chance to talk about it in the huddle yesterday.

**Comment by JeanMarie-TTS** [comment]
I agree with the concerns raised by @heymatthenry .
We could restrict the use of such markdown inclusiob to simple text only to aboid the styling issues. This will not resolve the issue about the proliferation of MD files when we have many such elements in a template.
I would like to understand how the YAML file approach solves the styling issue. If this issue is addressed, say, via SCCS or something similar, then we can figure out a way to deal with django's tags and variables.

**Comment by heymatthenry** [comment]
@JeanMarie-TTS To be clear, I'm not attached to YAML specifically, but it's just what we used before and it has the right kind of structure for the use case. Maybe it would be helpful to look at an example of what I mean. Here's a template from the old FAC-Frontend app and its associated data:

![image](https://user-images.githubusercontent.com/6290/228907678-d33d6f22-9e3f-41b8-96ae-6c9e07b551af.png)

So there you can see how the properties in the YAML map to specific DOM nodes in the template. So the markup (and the required classes, etc. live in the template, and just text goes in the YAML file (there is some markup in the YAML here but you could get around that either by parsing the text in each YAML node as markdown or adding more content slots).

I'm not _necessarily_ arguing for that approach but I'm just trying to better explain how it got around some of the issues described above.

**Comment by heymatthenry** [comment]
Also tagging in @thebestsophist who wanted to follow along with this convo

**Comment by JeanMarie-TTS** [comment]
This requirement actually seems easier than what I was attempting with md. Essentially, we don’t give the content author any formatting that md allows . We can  associate a json file with each template, the backend loads it into the context of the template, and the template simply dereferences the json. Will such a solution work?

**Comment by mogul** [comment]
Personally I find JSON much harder to detangle from the noise of the syntax, so I tend to select YAML for things that are very human-facing (whether for editing or for review), and then transform YAML into JSON only for those systems that can't accept YAML as-is but do accept JSON. YAML also provides additional support for humans to make the file accessible for readers, eg [multiline string operations](https://yaml-multiline.info/).

**Comment by thebestsophist** [comment]
oh goodness please not JSON. I think anything we can do to minimize the markup authors have to remember so it's more self service-able will make everyone's lives easier until we have an admin interface that folks can use.

**Comment by jadudm** [comment]
I'm moving this ticket back to the **Design Backlog**. The question of how to structure content is harder than it appears. 

* Part of the design of the site, and how it is expressed, has 508 implications.
* Authoring content is a usability concern for the content authors/managers.

If we didn't have 508, and if we were all engineers who loved brackets and quotation marks, this would be easy. I think this is less easy than we thought, and we're not going to have a quick answer. 

I am **not** shutting down the conversation. We need to answer this question. I'm just suggesting we're going to have a "worse is faster" solution whether we like it or not *initially*, and it may be worth a bit more conversation (where we ack that Laura and new colleagues coming from Census) need to have input and visibility into the convo.

But also, this conversation does not block us from 1) ATO or 2) ship, so it is worth bumping back out of the **Engineering Available** queue.

**Comment by jadudm** [comment]
We're not in a place to work on the administrative interface, and won't be until we get through our transition of historical data with Census (6mo out from now). Closing as not planned in the near agile future.
