### ISSUE TITLE
Move to cloud.gov-supported GitHub actions

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#902]
We are using the GSA fork of cg-cli-tools and pinning to the 

Fixes happened here: https://github.com/GSA-TTS/FAC/pull/901

Once the upstream issue is resolved, we may want to move to [cloud-gov/cg-cli-tools](https://github.com/cloud-gov/cg-cli-tools) or main on the GSA fork.

**Comment by mogul** [comment]
[The upstream issue is resolved!](https://github.com/cloudfoundry/cli/issues/2390#issuecomment-1487670880)

**Comment by mogul** [comment]
Unblocked, so we should stop using the temporary version we were pointing to. I'll put in a PR for that!

**Comment by mogul** [comment]
Yes, [we did this](https://github.com/GSA-TTS/FAC/blob/015f5e17e56dcf13e38b529902120a102be40926/.github/workflows/deploy-application.yml#L59).
