### ISSUE TITLE
[revisit 6/12] Load data from previous years

### ISSUE THREAD

**Issue by LindsayYoung** [GSA-TTS/FAC#913]
Breakout of epic https://github.com/GSA-TTS/FAC/issues/723

### Background
Separating ticket between code and data load

### Acceptance Criteria (We'll know we're done when...)
We have loaded all the data and documented any issues with the data.

### Tasks
Load data by year
```[tasklist]
- [x] 2022
- [x] 2021
- [x] 2020
- [ ] 2019
- [ ] 2018
- [ ] 2017
- [ ] 2016
- [ ] 2015
- [ ] 2014
- [ ] 2013
- [ ] 2012
- [ ] 2011
- [ ] 2010
- [ ] 2009
- [ ] 2008
- [ ] 2007
- [ ] 2006
- [ ] 2005
- [ ] 2004
- [ ] 2003
- [ ] 2002
- [ ] 2001
- [ ] 2000
- [ ] 1999
- [ ] 1998
- [ ] 1997
```

**Comment by mogul** [comment]
Blocked on API validation work and getting the full set of data from Census

**Comment by mogul** [comment]
@jadudm FYI

**Comment by jadudm** [comment]
I have written Census and asked for help unblocking data transfer.
