### ISSUE TITLE
Exiting audit creation

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#919]
# Exiting audit creation

When creating an audit (the Pre-SAC workflow), an auditor or auditee may decide they do not want to create an audit at this time. They should be taken back to the homepage when they decide to *cancel*. 

Breakout issue of https://github.com/GSA-TTS/FAC/issues/395

Replaces issue https://github.com/GSA-TTS/FAC/issues/430

# Acceptance Criteria

We use [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible. Try specifying them using behavior driven development."

[comment]: # "**Blurb** : **Given** **and** **when** **then**"

### Scenario: I am an auditee starting the submission process.

 **Given** that I have started the audit process, **when** I click *cancel*, ...
```[tasklist]
### then...

- [x] A modal alert is thrown indicating I will loose all progress (OK/I want to keep going)
- [x] I am returned to the "My Audit Submission Page" after I click *cancel*.
- [x] All state is cleared from the browser for the Pre-SAC workflow.
- [x] I remain logged in.
- [x] Content has revised the "cancel button" language and those changes are reflected in the implementation.
```

@jperson1 is the issue shepherd.

# Background

#430 was the less-descriptive, long-standing ticket for this work.

---

# Security Considerations ([required](https://nvd.nist.gov/800-53/Rev4/control/CM-4))

There are no security concerns to exiting the Pre-SAC workflow.

# Sketch

[Notes or a checklist reflecting our understanding of the selected approach]

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

**Comment by jperson1** [comment]
Relevant PR: https://github.com/GSA-TTS/FAC/pull/953

**Comment by lauraherring** [comment]
@jperson1 Copy on the cancel modal looks good to me, I marked off the content review task.
