### ISSUE TITLE
SF-SAC submission

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#928]
# At a glance

[comment]: # "Begin with a short summary of this ticket, so its intent can be understood at a glance."

Auditors and auditees work together to complete the SF-SAC.

# Acceptance Criteria

We use [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible. Try specifying them using behavior driven development."
[comment]: # "**Given** **when** **then**"
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

#### Key
* submitter = auditee or auditor

### Scenario: Submitters want to submit their SF-SAC and associated files.

**Given**  that a submitter is ready to start the SF-SAC
**when**  they have completed the Pre-SAC checklist
...

```[tasklist]
### then...
- [x] the submitter can complete the SF-SAC general information page
- [ ] https://github.com/GSA-TTS/FAC/issues/945
- [ ] https://github.com/GSA-TTS/FAC/issues/989
- [ ] https://github.com/GSA-TTS/FAC/issues/977
- [ ] https://github.com/GSA-TTS/FAC/issues/992
- [ ] https://github.com/GSA-TTS/FAC/issues/993
- [ ] https://github.com/GSA-TTS/FAC/issues/965
- [ ] https://github.com/GSA-TTS/FAC/issues/994
- [ ] https://github.com/GSA-TTS/FAC/issues/995
- [ ] https://github.com/GSA-TTS/FAC/issues/996
```

```[tasklist]
### E2E Testing
- [ ] https://github.com/GSA-TTS/FAC/issues/1055
- [x] Audit Findings
- [x] Audit Findings Text
- [x] CAP (Corrective Action Plan)
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The Data.gov team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.' so please don't remove this section without care."
[Any security concerns that might be implicated in the change. "None" is OK, just be explicit here!]

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: #"Notes or a checklist reflecting our understanding of the selected approach"
![image](https://user-images.githubusercontent.com/38290/229174150-2ec57160-3543-41d2-b98e-cfdaf73d9531.png)

## Links to Figma mocks for each page

- [SF-SAC general information page](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-24912&t=azeQNyHI1V1Ll58h-4).
- [federal awards information XLSX](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23338&t=azeQNyHI1V1Ll58h-4).
- [audit information XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23338&t=azeQNyHI1V1Ll58h-4)
- [upload the notes to SEFA XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23338&t=azeQNyHI1V1Ll58h-4)
- [upload the audit findings XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23910&t=azeQNyHI1V1Ll58h-4) 
- [upload the audit findings text XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23604&t=azeQNyHI1V1Ll58h-4)
- [upload the corrective action plan  XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23665&t=azeQNyHI1V1Ll58h-4)
- [upload the additional EINs XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23727&t=azeQNyHI1V1Ll58h-4)
- [upload the secondary auditors  XLSX file](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5200-30488&t=azeQNyHI1V1Ll58h-4)
- [check for errors as part of finalization](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=4954-23868&t=azeQNyHI1V1Ll58h-4)
- [lock the SF-SAC for certification](https://www.figma.com/file/1bNncVt1TcFFDhQslqFC2o/FAC-Playground?node-id=5046-30643&t=azeQNyHI1V1Ll58h-4)
- the submitter is made aware of what has happened, and what will happen next (see #550).

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
Memo to self: Integrate 

https://github.com/GSA-TTS/FAC/issues/463

with the stories around 928 re: validation error message text.

**Comment by jadudm** [comment]
Also:

https://github.com/GSA-TTS/FAC/issues/493

**Comment by mogul** [comment]
@jadudm the issue is marked down but some of the sub-issues that were broken out for individual ACs are not done. We're going to remove them from the tasklist here and assume that you will surface them in another issue later.

**Comment by mogul** [comment]
Since we demo'd this last sprint and the ACs have been broken out, we're not going to demo it again this week.
