### ISSUE TITLE
ADR for CFDA/ALN handling

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#929]
[CFDA numbers are messy](https://github.com/GSA-TTS/fac-dissemination-api-exploration/blob/main/python/examples/test_program_number_story.md). They are an uncontrolled number government wide, and many people enter incorrect CFDAs/ALNs. This leads to downstream problems in the oversight process.

Notes from conversation are pasted below. 

We need to decide how we will handle these in the MVP. Current best-case is to use a pattern that accepts the majority of prior CFDAs (that are *correct*, ideally, even if they are of the form `nn.Unnn`, indicating an unknown number...). If it rejects, we'll provide a warning along the lines of "Your ALN may be incorrect; please consult your granting agency for the correct ALN for this audit before making your final submission. An incorrect ALN can lead to resubmission and possible penalties associated with late audits."

All TBD. Once determined, we need an ADR.

**Comment by jadudm** [comment]
- people don't always know what it is
- comms about CFDAs on other sites (including [grants.gov](http://grants.gov/), [sam.gov](http://sam.gov/)) is confusing
- non-government sources say even less
- some places call them CFDAs and others call them assistance listings, not sure anyone mentions that they're the same thing
- people hit a lot of dead ends because a couple of the common links to [sam.gov](http://sam.gov/) are just dead links
- [sam.gov](http://sam.gov/)'s assistance listing search tool is hard to use/unclear/confusing

**Comment by thebestsophist** [comment]
Noting something for posterity (and newcomers to the data), improving the quality of this data (and other fields) is likely going to be a multi-year change management project purely because there are a lot of established practices within the community.

While there are a bunch of things we can do within the interface and supporting content to help grantees submit useful information, CFDA/assistance listings are **not** a tightly controlled vocabulary so the standard is pretty loose.

**Comment by jadudm** [comment]
I don't think this is going to be an ADR.

We know what the pattern for an ALN should be. We know it accommodates unknown ALNs. Therefore, it should be possible for auditees/auditors to enter an ALN that matches the pattern even if it is "unknown" or one an agency created.

We will discover new variations as we go. For now, I'm going to close this as "not planned," and we can come back to it later.
