### ISSUE TITLE
Implement frontend error handling for General Information form

### ISSUE THREAD

**Issue by timoballard** [GSA-TTS/FAC#937]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

Users deserve to know when they're wrong, politely (of course).

**In order to** complete the general information form
**as a(n)** auditee
**I want** to be warned when I incorrectly information into the General Information form.

**Clarification/update**: This ticket is about implementing error messages coming from the backend to the frontend.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I am a backend developer looking to pass a data validation error to the user.

**Given** That I am dealing with an error
**when** I want to communicate that to the user

```[tasklist]
- [ ] a JSON object structure is designed/documented for passing error messages from the backed to the frontend.
- [ ] the JSON object structure includes information about the field (in the case of a web form) or spreadsheet location (in the case of an Excel upload) so that the location of an error can be communicated clearly to the user
- [ ] error messages are broken out as strings in a central/shared location
- [ ] error messages are templated and can be parameterized where appropriate (e.g. row, column)
```

### Scenario: I am an auditee starting the Single Audit process.

**Given**   That I am starting the SA process
**when**  I enter something incorrectly into the General Information form
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then... 
- [ ] I should receive feedback that my entry does not conform to requirements
- [ ] Unit tests on the form indicate that all validations are functioning as expected
- [ ] E2E tests confirm that the GI form can be completed successfully
- [ ] E2E tests confirm that common (and uncommon) erroneous GI entries are alerted to the user
- [ ] Data is correctly stored into the backend when submitted and all entries are correct
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Design shepherd: N/A
* Engineering shepherd:  

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no particular security concerns to this work beyond our normal controls on validating submitted data.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by heymatthenry** [comment]
Couple of questions on this,.

* Is this ticket about showing users errors the server gave back after submission or augmenting the client-side validations or both?
* Related: if displaying server-side errors to the user is part of the ticket, we won't be able to test that in the e2e tests since submitting the form would require a logged-in user. As it is, we're side-stepping auth entirely in the e2e tests. Bascially, we'd need to rely on the unit tests to verify that the server-side validations work as expected, and then ensure the correctness of the client-side piece in the cypress tests, but as things currently stand, we couldn't have one test that is truly "e2e" doing both.

**Comment by jadudm** [comment]
1. Unless Tim says otherwise, lets say this ticket is *not* about _augmenting_ the client-side validations. If we need to improve the validations, that should be ticketed out separately (either as a bug or feature story). 
2. How about we focus this ticket on how we report errors to the user from the backend. If this is something we haven't tackled before, then we should probably huddle a bit on how we do it, because we're about to have the validation of XLSX documents to handle, too.
3. I feel like our E2E problems are... problems. But, lets set that aside for a moment? Or, lets talk about that at dev huddle, so I understand it, and we can better either 1) work around or 2) address or 3) punt, but do so in a recorded/principled way.

**Comment by jadudm** [comment]
In the first instance, if errors are always reported at the top or bottom of the page (in the case of web forms and spreadsheet upload), this is just fine. Or: lets not overwork the spike. We can ticket and iterate improvements.

In the case of multiple errors, I recommend we report no more than 3 at a time, and indicate how many more errors exist. Under no circumstances is reporting 37 errors (say, in a spreadsheet) useful to a user.

I'll look for some support in the literature as to how we might best report errors, and can only say that we're best served by 1) doing something straight-forward, 2) fast to implement, and 3) iterate from there in consultation with users. This is not the kind of work we will get right the first time, and it is better to have *something* in and working than to slow down the spike.

https://dl.acm.org/doi/10.1145/3411764.3445696

is some current work in the space of error messages for novices (which is adjacent to the error reporting challenge on the worksheets) from CHI'21. I know a few of the authors if we want to follow up with questions; I'll look for other relevant guides, and update the ticket with guidance as I can. For now: **simple and done**.

**Comment by neilmb** [comment]
I just ran into this when trying to fill out the general information form and entering "District of Columbia" or "DC" for the state in the auditee and auditor street addresses.

<img width="992" alt="Screenshot 2023-06-20 at 2 44 40 PM" src="https://github.com/GSA-TTS/FAC/assets/443389/86d3553f-bd8f-48ee-bc07-f3214f547ec3">

```backend-web-1          | INFO ValidationError for report ID 2023JUN0001000001: 'DC' is not one of ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']```

I expected to get an error message in the UI telling me that the state I entered was not valid and helping me figure out how to enter it right. Like moving out of DC.? Or Puerto Rico? Or Guam?

**Comment by jadudm** [comment]
We've handled what this ticket spoke to, and have other tickets related to this. Closing.
