### ISSUE TITLE
Pre-SAC progress indicator no longer works

### ISSUE THREAD

**Issue by heymatthenry** [GSA-TTS/FAC#954]
The step indicator component does not show the user how far along they are in the pre-SAC flow. For instance, 
this screen is taken from the second step in the process, so the first step should be shown as complete:

![Image](https://user-images.githubusercontent.com/6290/230203079-4f8a0171-9dcc-457b-8585-b7e149cddd53.png)

**Comment by mogul** [comment]
Images of the fix, hoisted from the PR:


![Image](https://user-images.githubusercontent.com/47762/234961263-285118c4-a2ca-4cb1-b440-7349728b4b4f.png)
![Image](https://user-images.githubusercontent.com/47762/234961305-cea27e64-8fb1-4e33-a528-90efb2d52995.png)
![Image](https://user-images.githubusercontent.com/47762/234961331-c60b9d72-3e59-42e1-a90c-94801fac7b15.png)
