### ISSUE TITLE
Storing integral data

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#983]
# At a glance

[comment]: # "Begin with a short summary so intent can be understood at a glance."

[comment]: # "In order to: some objective or value to be achieved"
[comment]: # "as a: stakeholder"
[comment]: # "I want: some new feature"

**In order to** provide oversight
**as an** audit resolution official
**I want** data with high validity and integrity.

# Acceptance Criteria

We use [DRY](https://docs.behat.org/en/latest/user_guide/writing_scenarios.html#backgrounds) [behavior-driven development](https://en.wikipedia.org/wiki/Behavior-driven_development#Behavioral_specifications) wherever possible.

[comment]: # "ACs should be clearly demoable/verifiable whenever possible."
[comment]: # "Given: the initial context at the beginning of the scenario"
[comment]: # "when: the event that triggers the scenario"
[comment]: # "then: the expected outcome(s)"
[comment]: # "Repeat scenarios as needed, or repeat behaviors and lists within a scenario as needed."

[comment]: # "The scenario should be a short, plain language description."
[comment]: # "Feeling repetative? Apply the DRY (Don't Repeat Yourself) principle!"

### Scenario: I'm  an audit resolution official trying to do my job.

**Given**  I work with the FAC data all the time
**when**  I try and review a Single Audit
...

[comment]: # "Each task should be a verifiable outcome"
```[tasklist]
### then...
- [ ] I want the CFDA/ALN to be formatted properly
- [ ] I want the Federal Program Name to follow controlled conventions
- [ ] I want the auditee name to be consistent year-to-year
- [ ] auditees should not be able to break data storage/export through the text they enter
- [ ] Covid-19 funding to be properly flagged
- [ ] findings text to be broken out (cause, criteria, condition, effect, and recommendation)
- [ ] improve/standardize capture of prior finding reference number
- [ ] CFDA "general note" is large and difficult to use/ingest
- [ ] standardize character encoding across all imports/exports
- [ ] avoid optional fields for consistency and reliability
- [ ] indicate completeness (or lack thereof) on export/download
- [ ] require fields that are unique/identifiers (do not make optional)
- [ ] avoid many-to-many relationships, or simplify for analysis purposes
- [ ] EINs are not unique identifiers, and make analysis difficult
- [ ] use the UEI as a globally unique identifier
- [x] validate the UEI against SAM.gov
- [ ] don't drop the DBKEY in historic data
- [ ] we need a way to repair/notify on data errors and corrections
```

### Shepherd

[comment]: # "@ mention shepherds as we move across the board."

* Product shepherd: @jadudm
* Design shepherd: 
* Engineering shepherd: 

# Background

[comment]: # "Any helpful contextual notes or links to artifacts/evidence, if needed"

This comes from conversation and email with HHS. 

https://docs.google.com/spreadsheets/d/1FojbfFTz4H1yoXwBihLk3FxYyvuPvZxy/

The concerns/comments are all broken out in each of the individual tickets, and included in a table here.

Census Table Name | Column name | Observed issues | Description
---|---|---|---
CFDA | CFDA | Inconsistent data formatting due to system error | Improper CFDA number formatting. The correct format is xx.xxx (Example 93.498). The issue appears when there is an additional character after or before the extension. Example of incorrect formatting 93.989.00000004, 93. NIH02XX.
CFDA | Federal Program name | Naming convention for a specific program | Auditees use different names for a specific Program (inconsistent data). This increases the number of records and potentially decreases system/tool performance due to increased amount of data. For example, 93.244 has around 14 names used by different Auditees. For example "ADVANCED NURSING EDUCATION GRANT PROGRAM", "ADVANCED NURSING EDUCATION WORKFORCE GRANT PROGRAM".
General | Auditee Name | Variations in naming convention | Auditors may enter variations of an auditee's name from year-to-year (e.g., Dept vs. Department vs. Dept.)
General | Multiple | Use of delimiters in names/titles impacts importing data. | Auditors/Auditees may use a pipe delimiter in their names, titles, etc. Since FAC uses a pipe delimiter, the data is then imported incorrectly. Suggest using tab instead of a character delimiter, and consistently use this delimiter (there are currently some instances where the data contains a tab delimiter instead of pipe delimiter).
CFDA | General Note | COVID flags not used to indicate COVID funding expended | Unlike with ARRA funding, FAC did not incorporate a flag to indicate funding expended was associated with COVID funds.  Inconsistent ways to indicate COVID funding impacts accuracy of analysis (e.g., COVID or CARES added to program name, COVID or CARES indicated in award title, grant/award number listed but not indicated that it relates to COVID).
Findings Text | Findings Text | All text is grouped together - difficult to conduct analysis | The elements of a finding are all grouped together in one findings text cell rather than separating out the elements (cause, criteria, condition, effect, recommendation). This impacts the analyst's ability to conduct analysis and identify trends in findings/deficiencies identified.
Findings | Prior Finding Reference Number | - Only most recent finding number identified<br>- Incorrect or missing finding number preventing relationship to prior finding<br>- Some findings are linked to multiple prior finding numbers (current finding combines two or more prior findings) | Listing the most recent finding reference number requires daisy chaining the data to identify the original finding and determine how many times the finding repeated. Suggest having the prior ref number be the original finding number and possible standardization.
CFDA | General Note | File difficult to use | Size of the data makes it difficult to use (causes slowness and ingest errors)
General and CFDA | All | Ingesting data inaccurately | There are different character encoding (i.e. ASCII, latin, etc) used for different FAC .txt tables.  This has resulted in some lines being dropped from the general and CFDA files.
All Tables | General Note | Data reliability/accuracy | Only some general information and completeness of the file are validated when the report is submitted.  As a result, some of the data provided is inaccurate or inconsistently reported. For example, FAC originally designated the type of entity associated with a submission, but this was later changed to a self-reported field that was optional.
All Tables | General Note | Data completeness | Would be helpful to know the row counts for the bulk data when downloading so users can confirm they received all of the data.
All Tables | General Note | Required data fields could be improved | In the original data, DUNS was an optional field whereas EIN was required.  This impacted the user's ability to link with other datasets to do in-depth analysis. Requiring fields that provide a unique identifier for entities would be helpful (believe this will be incorporated with UEI requirement).
EINs and DUNs Tables | All | Difficult to incorporate into data for analysis | When linking the EINS and DUNS tables with other FAC data it creates a many-to-many relationship, making it difficult to conduct analysis. Allowing for an easier way to incorporate/link with the EIN and DUNS data would be helpful.
EINs are not unique identifiers | General Note | Difficult to incorporate into data for analysis | One EIN may be associated with multiple auditees, which makes doing analysis on specific recipients a challenge. For example, EIN 470491233 is associated with 9 auditees. Some of the auditees are:<br>Board of Trustees of the Nebraska State colleges<br>Chadron State Colleges<br>Nebraska state colleges system<br>Peru State College
EINs | All | EIN is not validated | EIN Number is a required field in the submission of a Single Audit Report.  The EIN Number is not validated as part of the acceptance of the Single Audit Report.  An EIN Numbers can map to one, many or no DUNS, when DUNS was the government-wide single identifier.  DUNS is not a required field for Audit report submission.  Now that UEI has replaced the DUNS as the government-wide single identifier for issuing federal grants, suggest that GSA FAC uses UEI.
New | UEI | Replace DUNS and/or EIN with UEI | EINs/DUNS number on the additional EIN/DUNS page of the SAC, should be changed to UEI.  All UEIs entered on the additional UEI page should be validated against SAM.gov.
New | UEI | UEI should be a required field | UEI should be a required field for submission of a Single Audit Report in place of EIN.  The UEI should be validated against the SAM.gov database and populate the Audit Report submission with the legal name and address of the Recipient per SAM.gov.  This will ensure the Single Audit Report submission is aligned with the Recipient information included on the federal Notice of Award.
DB Key |  | Discussion of dropping the DBKEY in the new GSA FAC data | The DBKey is important to maintain the historical perspective of Single Audit data.
All Tables | General Note | Lack of communication across the government for requested data corrections | When agencies identify data errors (due to data entry or inaccuracies), they contact the auditee/auditor to correct the information.  Having better data validation to ensure data accuracy would minimize the need for requesting corrections and resubmissions. <br><br>As a note, there is no mechanism to inform the other agencies about the identified error or notify the agencies that a request was made to have the auditee/auditor resubmit the report after correcting the error. This could result in wasted resources as other agencies attempt to resolve the findings, could result in the auditee being contacted by multiple agencies to correct the error, or cause noncompliance with Uniform Guidance as the agencies do not perform audit resolution while waiting for the auditee/auditor to resubmit the report.<br><br>Better data validation might help to ensure data accuracy and minimize the time to clean and prepare the data.

# Security Considerations

Required per [CM-4](https://nvd.nist.gov/800-53/Rev4/control/CM-4).

[comment]: # "Our SSP says 'The team ensures security implications are considered as part of the agile requirements refinement process by including a section in the issue template used as a basis for new work.'"
[comment]: # "Please do not remove this section without care."
[comment]: # "Note any security concerns that might be implicated in the change. 'None' is OK, but we must be explicit here."

There are no security concerns to improving the validations we perform on our data and the integrity thereof.

---

<details>
  <summary>Process checklist</summary>
  
# Sketch

[comment]: # "Notes or a checklist reflecting our understanding of the selected approach"

- [ ] Design designs all the things
- [ ] Engineering engineers all the things

# Definition of Done

### If not likely to be important in the next quarter...
- [ ] Archived from the board

### Otherwise...

- [ ] Has a clear story statement
- [ ] Design or Engineering accepts that it belongs in their respective backlog

## Design Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Meets the design Definition of Ready [citation needed]
- [ ] A design shepherd has been identified

## Design In Progress

- [ ] Meets the design Definition of Done [citation needed]

## Design Review Needed

- [ ] Necessary outside review/sign-off was provided

## Design Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts

### If no engineering is necessary
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

## Engineering Backlog

- [ ] Has clearly stated/testable acceptance criteria
- [ ] Has a sketch or list of tasks
- [ ] Can reasonably be done in a few days (otherwise, split this up!)

## Engineering Available

- [ ] There's capacity in the `In Progress` column
- [ ] An engineering shepherd has been identified

## Engineering In Progress

- [ ] Meets acceptance criteria
- [ ] Meets [QASP conditions](https://derisking-guide.18f.gov/qasp/)

### If there's UI...
- [ ] Screen reader - Listen to the experience with a screen reader extension, ensure the information presented in order
- [ ] Keyboard navigation - Run through acceptance criteria with keyboard tabs, ensure it works. 
- [ ] Text scaling - Adjust viewport to 1280 pixels wide and zoom to 200%, ensure everything renders as expected. Document 400% zoom issues with USWDS if appropriate.

## Engineering Blocked

- [ ] Blocker removed/resolved

## Engineering Review Needed

- [ ] Outside review/sign-off was provided

## Engineering Done

- [ ] Presented in a sprint review
- [ ] Includes screenshots or references to artifacts
- [ ] Tagged with the sprint where it was finished
- [ ] Archived

</details>

**Comment by jadudm** [comment]
From ARO interviews:


> The DoE uses an alpha character on the end of their CFDA codes to differentiate between programs sharing the same code (for example: 84.215C, 84.215D, etc), they can have upwards of 15+ programs using the same code. The current FAC does not accept alpha characters for CFDA codes, so they have no way to search for individual programs if they want to look at their findings history. Since their system (AARTS) is just using data from the FAC, it doesn't capture the full codes either.

**Comment by danswick** [comment]
This is covered by extensive validation/cross-validation now.

**Comment by jadudm** [comment]
I'm flagging for revisit, and don't want to lose the overall... there's things here that have a longer arch. Agreed we've done good work on intake.
