### ISSUE TITLE
Unknown Data Type for Questioned Costs Column in Findings_Uniform_Guidance XLSX

### ISSUE THREAD

**Issue by sambodeme** [GSA-TTS/FAC#984]
### Tasks
The Questioned Costs column data type is not mentioned in the instructions sheet of Findings_Uniform_Guidance XLSX.  This could be Yes or No type or a String type. This ticket will capture effort/discussion related to finding the expected data type of the aforementioned column. 

```[tasklist]
- [ ] Identify Questioned Cost column data type
```

**Comment by jadudm** [comment]
@sambodeme , I'm tagging you on this one. I suspect it's getting picked up in the work you're currently doing.

**Comment by sambodeme** [comment]
> @sambodeme , I'm tagging you on this one. I suspect it's getting picked up in the work you're currently doing.

Not really, I have not found any clue on this field so far.

**Comment by sambodeme** [comment]
It was determined from the hidden sheets in this Excel file that Questioned Cost column is of type Yes or No
