### ISSUE TITLE
Update Audit Year copy on My Audit Submissions page

### ISSUE THREAD

**Issue by lauraherring** [GSA-TTS/FAC#988]
### Update the copy on the My Audit Submissions page to reflect accepting copy for Audit Year 2023. Related to ticket #763 

```[tasklist]
- [ ] Copy for page is written
- [ ] Page is updated with new copy
```

**Comment by jadudm** [comment]
This is picked up/done in the Figma, and will be picked up in future reviews. But, I think this is done.
