### ISSUE TITLE
SSPP and GitHub process harmonization

### ISSUE THREAD

**Issue by tadhg-ohiggins** [GSA-TTS/FAC#990]
The System Security & Privacy Plan states that the system owner must approve a “change package”. A PR is the closest GitHub object to this, so we need a PR for compliance purposes. The nearest possible PR is likely to be the `main`-to-`prod` PR; we can’t make changes to production without another PR.

The only issue with this is that ideally we would like the system owner approval to include reviewing the application _on staging_, which can only happen after the `main`-to-`prod` PR. This enhancement is something we can work into our process later; for now, requiring system owner approval as part of deployment to staging complies with the SSPP.

We need to update the documentation for deployment to staging to indicate that one of the approving reviewers must be the system owner. We should also mention this in our branching strategy documentation.

This is the relevant text from the SSPP (SI-2):

> 1) Proposed changes to FAC are documented via the FAC CM Configuration Control process. Documentation is maintained in Github with automated workflows routing documentation of work items as they proceed through work phases:
> 2) FAC Developer documents changes to the system in Github issues
> 3) FAC Developer prepares a change package via GitHub for the FAC System Owner that is tied to a FAC Release. The change package includes a security analysis, code quality analysis, impact analysis,

-----

(This came from conversation with @LindsayYoung and I'm not sure where it should, so I'm assigning it to @jadudm and handing it off.)

**Comment by JeanMarie-TTS** [comment]
@tadhg-ohiggins , I think we ought to discuss how we plan to address this requirement eventually. Thinking aloud ... can we not have deployment to staging be triggered by tagging `main`, and deployment to production be triggered by a PR to merge `ptod` from `main`?

**Comment by mogul** [comment]
What do you think about keeping our existing process and [taking advantage of GitHub's new tag protection rules](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules) to ensure only `fac-admins` can make tags that result in a release to the prod environment?

**Comment by tadhg-ohiggins** [comment]
I didn't realize GItHub could do that; that seems like the right way to do it.

To match the SSPP wording, we might need to ensure that only “system owners” can do that part; I don't know if `fac-admins` is small enough to count as only being made up of “system owners“.

**Comment by mogul** [comment]
Lindsay confirmed [we've already configured the repository to protect the prod-relevant tags](https://github.com/GSA-TTS/FAC/settings/tag_protection)... It's totally legit to say that `fac-admins` is too broad; personally I think it should only include the product lead and one backup, since the group is being applied for access control oversight.

**Comment by tadhg-ohiggins** [comment]
Sure, but there are a bunch of more minor administrative privileges that it makes sense for @danswick (and to a lesser extent me, while I'm on the project) to have, so I'm wondering if we should leave `fac-admins` as it is and create a `fac-owner` group to handle things like creating tags.

Again, regardless of how we do the groups, if we use this approach then the system owners must be the people who actually creates the release tag, which isn't how we've been handling it so far.

**Comment by mogul** [comment]
(And I agree, we should have @fac-system-owners so I'll create that.)

**Comment by mogul** [comment]
OK, well, this looks like the feature won't do what we want even if we create that special team... *Any* bypass also enables people with admin permission to bypass.

![image](https://user-images.githubusercontent.com/47762/232617918-539f13f3-081b-4efe-8b6d-836a47f62031.png)

**Comment by mogul** [comment]
> Sure, but there are a bunch of more minor administrative privileges that it makes sense for @danswick (and to a lesser extent me, while I'm on the project) to have, so I'm wondering if we should leave fac-admins as it is and create a fac-owner group to handle things like creating tags.

Note there's a separate `Maintainer` role now...
![image](https://user-images.githubusercontent.com/47762/232618459-ea0b9d42-f4fe-49a7-a745-1e5c4c05d40c.png)

Here's what it can do:
![image](https://user-images.githubusercontent.com/47762/232618747-e14bee89-099e-4e19-8416-d02f46a4d117.png)
![image](https://user-images.githubusercontent.com/47762/232618811-a63bc7eb-7f98-4e8c-9812-af9eea4c9ba6.png)
![image](https://user-images.githubusercontent.com/47762/232618856-f5ed8d71-fcb7-4738-a31e-c116b95549ef.png)

I'm thinking maybe we should add you and Dan to a `fac-maintainers` team and remove you from `fac-admins` and see what you're not able to do that you want/need to be able to do yourselves. Sound OK?

**Comment by tadhg-ohiggins** [comment]
I have definitely used the ability to bypass branch protections quite a few times. The risk of restricting that to only the True System Owners means that the True System Owners will then need to descend from their lofty perches and get into the middle of tricky build or deployment problems. We could assume/hope that those are mostly in the past.

It's probably worth it to try this and keep an eye on how often we need to pull in support from `fac-admins`, and remain open to the option of changing it back.

**Comment by danswick** [comment]
> It's probably worth it to try this and keep an eye on how often we need to pull in support from fac-admins, and remain open to the option of changing it back.

Agreed. This seems like a reasonable approach to me.

**Comment by mogul** [comment]
OK, I created [a `fac-maintainers` sub-team](https://github.com/orgs/GSA-TTS/teams/fac-team/teams) (!) in the `FAC-team` and added you two to it. Then [I gave that team the `Maintain` role in the `FAC` repository](https://github.com/GSA-TTS/FAC/settings/access):
![image](https://user-images.githubusercontent.com/47762/233193189-a1e913b6-090b-4a21-973d-b3fd53619c01.png)
Then, I removed the two of you from `fac-admins`. (I also made the `fac-admins` team a subset of FAC-team, which I didn't know I could do!)

**Comment by mogul** [comment]
With reference to [the settings described above](https://github.com/GSA-TTS/FAC/issues/990#issuecomment-1512124126): I have re-enabled the tag protection and enabled bypass by admins.

**Comment by danswick** [comment]
It's been a few months and this seems to be working well. Let's close and revisit later if needed!

**Comment by jadudm** [comment]
@danswick , do you have a specific way you want to track this, other than keeping the issue open?

**Comment by jadudm** [comment]
Having undergone review, and continued SSPP development for full ATO, our processes are in alignment/compliant, so I am  closing this as "done."
