### ISSUE TITLE
the JSON schema for the audit information page is authored/updated

### ISSUE THREAD

**Issue by jadudm** [GSA-TTS/FAC#998]

**Comment by sambodeme** [comment]
@jadudm this is most likely a duplicate ticket and I would like to close it. As per #928 we are tracking three xlsx files (#977  for FindingsUniformGuidance.xlsx, #993 for FindindsText.xlsx and #994 for CorrectiveActionPlan.xlsx). The FederalsAwards.xlsx was already done. So, I am not sure which file #989 is tracking.
